### ISSUE TITLE
[bug] When using tcp:// connection, NVM read fails with Error while calling api backupNVMRaw: The length must be between 1 and 6553

### ISSUE THREAD

**Issue by vladbabii** [zwave-js/zwave-js-ui#1800]
**Checklist:**

- [ X ] I am **not** using Home Assistant.
- [ X ] I have checked the troubleshooting section and my problem is **not** described there.
- [ X ] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [ X ] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version: 5.8.0
Z-Wave JS version: 8.4.1

### Describe the bug

Backup does not start but returns an error.

### To Reproduce

1. Go to setting -> zwave, set tcp://<ip>:<port> for ser2net server attached to a zwave stick on a network device
2. Save setting
3. Check zwave  works by turning a device/on/off
4. Go to ui in control panel -> actions -> advanced -> nvm management -> backup
6. click on backup
7. get error "Error while calling api backupNVMRaw: The length must be between 1 and 65535"

### Expected behavior

For backup to start

### Additional context

1. I don't think it matters but my network device is a vera edge with all it's vera software turned off and ser2net being started automatically
2. I am using docker image with :latest tag pulled one hour ago and i did a zwave config updates then restarted everything
[zwavejs2mqtt-store (2).zip](https://github.com/zwave-js/zwavejs2mqtt/files/7315780/zwavejs2mqtt-store.2.zip)

**Comment by AlCalzone** [comment]
I should have made a video. Of course I can't reproduce now

**Comment by robertsLando** [comment]
So what?

**Comment by AlCalzone** [comment]
Any chance there is a stack trace?

**Comment by robertsLando** [comment]
@vladbabii Please ensure you have set the zwave log level to silly level and retry to call the backupNVM
