### ISSUE TITLE
[bug] FGS221 does not report switches status

### ISSUE THREAD

**Issue by lpaso** [zwave-js/zwave-js-ui#1889]
### Version

**Checklist:**

- [ ] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [ ] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [ ] Docker
- [] PKG
- [x] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version: 5.8.0
Z-Wave JS version: 8.4.1

### Describe the bug

Switches on Fibaro FGS-211 modules with firmware 1.4 do not report changes on Z-WaveJS2MQTT and, hence, not to HA.
Neither switch 1 or switch 2 report any change.

I had to enable polling on the corresponding values.

### To Reproduce

- Include a FGS-211 module with 1.4 firmware
- connect switches on the switches input
- turn the switches on/off
- relays are switched on/off but nothing happens : status is not updated and nothing appear on the HA or Z-waveJS logs 

### Expected behavior

- Include a FGS-211 module with 1.4 firmware
- connect switches on the switches input
- turn the switches on/off
- relays are switched on/off and status is updated accordingly in HA and Zwave-JS 

### Additional context

I already saw the bug report about the exact same module, but on a newer firmware. I tried the config file provided, but it didn't work. Also tried to update the config file with the firmware version, but it does not seem to work either.

**Comment by Ascariota** [comment]
Not working for me : 

zwave-js: Current version: 0.1.45
core-2021.10.7 
supervisor-2021.10.8

**Comment by lpaso** [comment]
The same. Still does not work. No status report on any of my 5 fgs-221 on firmware 1.4.
Also, another « bug », they’re marked as dead at least once a day, and they can only be revived after a reboot (cut the power, and apply again).

**Comment by bpolanec** [comment]
@lpaso 

I have 2x FGS 221 but firmware 2.1 maybe that is the cause. 

Or that I also have manually setup group association for the module:
Endpoint 0 -> Controller updates -> (Aeotec zwave stick) Controller 

No problems with dead nodes

**Comment by lpaso** [comment]
> @lpaso
> 
> I have 2x FGS 221 but firmware 2.1 maybe that is the cause.
> 
> Or that I also have manually setup group association for the module: Endpoint 0 -> Controller updates -> (Aeotec zwave stick) Controller
> 
> No problems with dead nodes

Indeed, I got a FGS-211 with firmware 2.1 and I got no issue with it. It seems to be related to the 1.4 firmware, as the « targetvalue » seems to be not populated.

**Comment by robertsLando** [comment]
Please try disable mqtt store option in settings

**Comment by lpaso** [comment]
> Please try disable mqtt store option in settings

You mean to check the « disable MQTT gateway » option ? If so, it’s disabled since I installed ZwaveJS2MQTT 😉

**Comment by robertsLando** [comment]
Please reference to issue #1921 the fix has been made on zwave-js side and should be available on next release
