### ISSUE TITLE
[question] Issue when selecting USB port "by-id"

### ISSUE THREAD

**Issue by ScratMan** [zwave-js/zwave-js-ui#1905]
Hello,

After updating zwavejs2mqtt to 5.10.1, and rebooting my system (Raspberry Pi 4 running Raspbian Buster with Home Assistant and zwavejs2mqtt in docker containers), I faced some issues with the zwavejs2mqtt server, saying the /dev/ttyACM0 was busy. A restart of the Zwave docker container fixed the issue, but as I read in the changelog of the latest version that it was recommended to map the port by ID instead of using ttyACM0 to avoid renaming issue at soft reset, I tried to identify my Aeon Labs Z-Stick Gen5 to get its ID, and set this in zwavejs2mqtt settings.
But then, the server fails to open the serial port, with the following message in the log:

`2021-10-29 10:41:52.917 INFO ZWAVE: Controller status: Driver: Failed to open the serial port: Error: No such file or directory, cannot open /dev/serial/by-id/usb-0658_0200-if00 (ZW0100)
`

The ID of the ports looks OK, as shown below, but even when restarting zwavejs2mqtt it still fails to open the stick's port.

> n@raspberrypi:~ $ sudo udevadm info --query=all --name=ttyACM0
> P: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1.4/1-1.1.4:1.0/tty/ttyACM0
> N: ttyACM0
> L: 0
> S: serial/by-id/usb-0658_0200-if00
> S: serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1.4:1.0
> E: DEVPATH=/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1.4/1-1.1.4:1.0/tty/ttyACM0
> E: DEVNAME=/dev/ttyACM0
> E: MAJOR=166
> E: MINOR=0
> E: SUBSYSTEM=tty
> E: USEC_INITIALIZED=508946396
> E: ID_BUS=usb
> E: ID_VENDOR_ID=0658
> E: ID_MODEL_ID=0200
> E: ID_PCI_CLASS_FROM_DATABASE=Serial bus controller
> E: ID_PCI_SUBCLASS_FROM_DATABASE=USB controller
> E: ID_PCI_INTERFACE_FROM_DATABASE=XHCI
> E: ID_VENDOR_FROM_DATABASE=Sigma Designs, Inc.
> E: ID_MODEL_FROM_DATABASE=Aeotec Z-Stick Gen5 (ZW090) - UZB
> E: ID_VENDOR=0658
> E: ID_VENDOR_ENC=0658
> E: ID_MODEL=0200
> E: ID_MODEL_ENC=0200
> E: ID_REVISION=0000
> E: ID_SERIAL=0658_0200
> E: ID_TYPE=generic
> E: ID_USB_INTERFACES=:020201:0a0000:
> E: ID_USB_INTERFACE_NUM=00
> E: ID_USB_DRIVER=cdc_acm
> E: ID_USB_CLASS_FROM_DATABASE=Communications
> E: ID_PATH=platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1.4:1.0
> E: ID_PATH_TAG=platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_1_4_1_0
> E: ID_MM_CANDIDATE=1
> E: DEVLINKS=/dev/serial/by-id/usb-0658_0200-if00 /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1.4:1.0
> E: TAGS=:systemd:

If setting back the /dev/ttyACM0 path with the drop-down list, the driver immediately opens the port correctly after saving settings.

What am I doing wrong ?

**Comment by silverl** [comment]
I'm in a similar situation. A few days ago my Z-Wave network started getting hinky. I run zwavejs2mqtt inside Home Assistant as a supervisor add-on. I've always had my Aeotec Z-Stick 5 set up using `/dev/serial/by-id/usb-0658_0200-if00`.

Last few days, it runs for a while, then it seems connectivity to the stick just fails.

Switching it to `/dev/tty/ACM1` and saving will jolt it back to life. Switching back to `/dev/serial/by-id/usb-0658_0200-if00` then works. For a while.

Things were rock solid until just recently, last few days. I have everything in HA set to auto-update nightly.

I don't have enough time investigating to pinpoint what's happening, but I was glad at least to find someone else having similar problems in the last couple weeks. Haven't spotted anything in the logs yet.

I run HA in a Proxmox VM under HA OS/Supervised. I pass 2 USB devices (zigbee and zwave) into the VM.

If I learn more, I'll be back.

**Comment by robertsLando** [comment]
@silverl All this issues are caused after the new zwave-js feature called soft reset. Following zwave specs soft reset should be performed on startup on every controller stick, after introducing this we realized that some controllers just don't like that and also that this could cause some sticks changing the serial path (this is why we suggest to use the serial by id path).

This said, what I can suggest to you is to disable soft reset from settings or by using the env var if it looks unstable

**Comment by silverl** [comment]
@robertsLando Beautiful! Thank you! I'm disabling it now.

**Comment by DavidRBailey** [comment]
@robertsLando How do you "update your docker-compose or your docker command" in HASS.IO?

**Comment by robertsLando** [comment]
> How do you "update your docker-compose or your docker command" in HASS.IO?

I have no idea. BTW the easier thing is to just disable soft reset

**Comment by kan84** [comment]
I am running zwavejs2mqtt in docker container in privileged mode. I can see /dev/ttyUSB0 and /dev/ttyUSB1 etc. I am trying to use device by id and when i type the address manually I get the error Driver: Failed to open the serial port: Error: No such file or directory, cannot open dev/serial/by-id/usb-xxx. In the log i can see it keeps trying to connect but does not work.

Any reason why this might be happening? Privilleged mode allows all usb devices to pass, wonder if device by id does not get passed?

**Comment by kpine** [comment]
> Any reason why this might be happening? Privilleged mode allows all usb devices to pass, wonder if device by id does not get passed?

It doesn't include symlinks. There's no reason to use privileged mode anyways.

Just pass the symlink into the container as a device, as the [instructions](https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/quick-start?id=docker) in the [docs](https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/docker?id=installation) suggest you do.
