### ISSUE TITLE
[feat] Change project name

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js-ui#2212]
Please vote and suggest names

Steps:

- [x] Create docker repo on zwavejs org https://hub.docker.com/u/zwavejs 
- [x] Replace zwavejs2mqtt to the new name, edit workflows to allow pushing to both repos to keep back compatibility
- [ ] Rename github repo

**Comment by robertsLando** [comment]
`@zwave-js/ui`

**Comment by robertsLando** [comment]
`@zwave-js/admin`

**Comment by robertsLando** [comment]
`zwave-js-admin`

**Comment by robertsLando** [comment]
`zwave-js-ui`

**Comment by LongDono** [comment]
For whatever reason, I spent the last 30 minutes trying to come up with names and one thing that eventually came to mind with names like "UI" and "Admin" is that it gives the impression it is only the GUI and that you'd use it alongside Z-Wave JS...

Z-Wave JS GUI
Z-Wave JS Control
Z-Wave JS Console
Z-Wave JS Frontend
Z-Wave JS Dashboard
Z-Wave JS Navigator
Z-Wave JS Plus
Z-Wave JS Enhanced

I like the last one, as the interface and MQTT support are definitely big enhancements.  Plus, do you want to use Z-Wave JS or Z-Wave JS Enhanced? I know which one I'd want!

I know these can't be voted on this way but I'm not really sure this is open to everyone anyway. Hope it helps and thanks for all the work that has been done on this project.

**Comment by robertsLando** [comment]
> "UI" and "Admin" is that it gives the impression it is only the GUI and that you'd use it alongside Z-Wave JS

I know that, the reason why I decided to change repo name is because most peoples think zwavejs2mqtt is something strictly related to mqtt, mqtt is just one of the features of it (and based on stats also the less used one). For this reason thanks to what stats says I know most people that use zwavejs2mqtt is looking for an interface (ui) to manage their devices. I like your names but I think they are too generic

**Comment by LongDono** [comment]
Well, yeah, I looked at the previous names for guidance on the type of naming that was expected. :) I'm sure a good name will be selected; I know we've all seen countless conversations where someone explains that you don't need to use MQTT to take advantage of that great UI.

**Comment by zetlen** [comment]
Call it `zee`. You're *seeing* your ***z**-wave* devices (with Vue). It's exactly as corny as npm package names are expected to be. `@zwave-js/zee`

**Comment by AlexMekkering** [comment]
zwave-js-portal

**Comment by AlexMekkering** [comment]
zwave-js-manager

**Comment by austinbeam** [comment]
zwave-js-advanced

**Comment by stevebritton** [comment]
It's a well designed user interface that interfaces with...

zwave-js-interface

**Comment by rjulius23** [comment]
Are there any other projects that translate zwave to mqtt ? If not my only option is to fork ? The reason for mqtt is the inner robustness of the protocol, http inherently flakier...

**Comment by LongDono** [comment]
Not sure how you inferred that; only the name is changing.
Removing MQTT from the name != removing MQTT support, that will remain. 
It's just that this code is so much more than just MQTT support and the name should reflect that...

**Comment by rjulius23** [comment]
Ahh I misunderstood this:
The preferred method of integrating your Z-Wave components with Home Assistant is through the official Home Assistant [Z-Wave JS integration](https://www.home-assistant.io/integrations/zwave_js), this because MQTT Discovery is limited compared to a native integration and Home Assistant updates frequently break it. Based on this I would NOT RECCOMMEND using MQTT Discovery, I don't plan to keep it maintained in the future.

So this is just about the support of MQTT discovery, but if I want I can still define the sensors via yaml, or update the mqtt templates.

**Comment by LongDono** [comment]
Ah. Yes, I use Home Assistants's native Z-Wave JS integration and ZWaveJS2MQTT for the backend, without MQTT.

**Comment by j9brown** [comment]
Perhaps zwave-js-gateway.

The project currently uses “gateway” to refer to the MQTT API but the term could be generalized to encompass everything the service is doing to provide access and control over a zwave-js instance.

Other names in this vein: zwave-js-controller, zwave-js-console, zwave-js-frontend, zwave-js-manager, zwave-js-commander, zwave-js-dash…

**Comment by GitHubGoody** [comment]
Z-Wave Control

I don't think most people care about the JS part either.

**Comment by TheOriginalMrWolf** [comment]
How about: `zwave-hub`

**Comment by coltenkrauter** [comment]
What are your thoughts about going abstract?

Zorro (It has a Z)
Otto (like automation)
Mation (like automation)

Less abstract, 

ZWaveServer
ZWaveJS (pretty similar but it covers key search terms)

**Comment by robertsLando** [comment]
> Zorro

🤣

I'm still more atracted to: zwave-js-ui

**Comment by robertsLando** [comment]
PR ready guys, moving to `zwave-js-ui`
