### ISSUE TITLE
[feat] Use GMT time in logs, like zwave-js does

### ISSUE THREAD

**Issue by darkbasic** [zwave-js/zwave-js-ui#2236]
We could decide to use either local or GMT time in the logs, but I think that both zwave-js and zwavejs2mqtt should use the same timezone in order to be consistent. Right now zwavejs2mqtt uses local time while zwave-js driver log uses GMT.

**Comment by blhoward2** [comment]
I get both logs in local. Have you defined the timezone in your docker compose?

**Comment by kpine** [comment]
I still see driver logs in UTC format and zwave-js-ui logs in the host/container timezone format.

According to this comment in an open issue, https://github.com/zwave-js/node-zwave-js/issues/4088#issuecomment-1013660735, node-zwave-js is harcoded to use UTC time. I'm not sure if that comment is technically still accurate, but the logging library being used, [winston logger](https://github.com/winstonjs/winston), sets the timezone format to UTC unless configured with a custom timestamp, which node-zwave-js does not do.

**Comment by robertsLando** [comment]
I use this timestamp: https://github.com/zwave-js/zwave-js-ui/blob/master/lib/logger.ts#L71

**Comment by blhoward2** [comment]
> I still see driver logs in UTC format and zwave-js-ui logs in the host/container timezone format.
> 
> According to this comment in an open issue, [zwave-js/node-zwave-js#4088 (comment)](https://github.com/zwave-js/node-zwave-js/issues/4088#issuecomment-1013660735), node-zwave-js is harcoded to use UTC time. I'm not sure if that comment is technically still accurate, but the logging library being used, [winston logger](https://github.com/winstonjs/winston), sets the timezone format to UTC unless configured with a custom timestamp, which node-zwave-js does not do.

Not sure what to tell you. Mine are in local time. 

```08:27:11.705 SERIAL « 0x011a00498418140410015e2585598672555a735b9f6c702c2b227a99 (28 bytes)
08:27:11.712 SERIAL » [ACK] (0x06)
08:27:11.713 DRIVER « [Node 024] [REQ] [ApplicationUpdateRequest]
payload: 0x18140410015e2585598672555a735b9f6c702c2b227a
08:27:11.716 CNTRLR « [Node 024] Received updated node info
08:27:12.960 SERIAL « 0x011a00498418140410015e2585598672555a735b9f6c702c2b227a99 (28 bytes)```

**Comment by kpine** [comment]
> 
> Not sure what to tell you. Mine are in local time.
> 
> ```
> 08:27:11.712 SERIAL » [ACK] (0x06)
> 08:27:11.713 DRIVER « [Node 024] [REQ] [ApplicationUpdateRequest]
> payload: 0x18140410015e2585598672555a735b9f6c702c2b227a
> 08:27:11.716 CNTRLR « [Node 024] Received updated node info
> 08:27:12.960 SERIAL « 0x011a00498418140410015e2585598672555a735b9f6c702c2b227a99 (28 bytes)```
> ```

Any chance your timezone is set to UTC, but the clock with a local time? 😅

Using any kind of custom log transport?

The winston [default timestamp](https://github.com/winstonjs/logform#timestamp) format uses `toISOString()`, as mentioned in the above issue, which uses UTC time always. Wondering how you're getting around that. 🤔 I'd be happy to have synced local timezones, but maybe easier to switch entirely to UTC...

**Comment by blhoward2** [comment]
I’m mapping in /etc/localtime and setting my time zone in the environment variable. 

My system time is correct:

```blhoward2@server:~$ date
Mon 17 Oct 2022 10:32:31 AM EDT```

**Comment by kpine** [comment]
@blhoward2 Are you logging to the console, not a file?

In my testing, when console logging is enabled (file logging disabled) it uses "short" timestamps (no date), which happen to be in the local timezone.

Console logging (file logging off), uses the correct local timezone:

```text
22:42:48.029 SERIAL » 0x011a00a9010c0e9f034c007100fafba19ff3f6b1bf240000000000fe          (28 bytes)
```

File logging is always UTC:

```text
2022-10-18T05:39:32.271Z SERIAL « 0x011d00a92300000200ba7f7f7f7f01010300000000020100007f7f7f7f7faf    (31 bytes)
```

I just checked myself, I don't see any issue with zwave-js-ui, it respects the TZ environment variable. If you set `TZ=UTC`, whether you are using Docker or not, the zwave-js-ui log timestamps will be UTC time.

**Comment by robertsLando** [comment]
> I just checked myself, I don't see any issue with zwave-js-ui, it respects the TZ environment variable. If you set TZ=UTC, whether you are using Docker or not, the zwave-js-ui log timestamps will be UTC time.

I think we can close this issue
