### ISSUE TITLE
[feat] Rewrite Network graph

### ISSUE THREAD

**Issue by brianegge** [zwave-js/zwave-js-ui#2517]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.13.0

### ZwaveJS version

9.5.0

### Describe the bug

I've been running jwavejs2mqtt for about a month now. The nodes in my graph are not connected. My mailbox sensor seems to be missing about half the messages so I'm wondering what it's connected to. 

![image](https://user-images.githubusercontent.com/175930/177618540-2be7adef-6a49-43d9-b943-2267f3749182.png)

### To Reproduce

unknown

### Expected behavior

Connected lines between nodes

### Additional context

I'm using the Zooz 700 Series Z-Wave Plus S2 USB Stick ZST10 700 with firmware "ZW_SerialAPI_Controller_7_17_2_406_ZGM130S_REGION_US.gbl" 

Also, health checks seem to timeout.

**Comment by robertsLando** [comment]
Please do a node dump

![2022-07-07_08-33](https://user-images.githubusercontent.com/11502495/177707227-f32a6bde-bf18-4513-a30a-5e1ea376ec87.png)


cc @AlCalzone any known bug with Zooz 700?

**Comment by brianegge** [comment]
[nodes_dump.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/9062993/nodes_dump.json.zip)

**Comment by AlCalzone** [comment]
I think this is just the general incorrectness of the neighbor info used to draw the map. @robertsLando Didn't you want to implement the live network map based on statistics? 😇

**Comment by robertsLando** [comment]
>Didn't you want to implement the live network map based on statistics? innocent

Hehe I really wish to have the time, I still have to find a good package to do it

**Comment by robertsLando** [comment]
From @AlCalzone sketch 

![Route statistics](https://user-images.githubusercontent.com/11502495/212040204-13245869-146b-4ca8-b9bd-3b2a0fc71f34.svg)

**Comment by robertsLando** [comment]
Just for info I started worlking on this, follow the PR here: #3098
