### ISSUE TITLE
No way to set a battery device status to dead for removal[Bug]: 

### ISSUE THREAD

**Issue by globe-earther** [zwave-js/zwave-js-ui#2651]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.14.0

### ZwaveJS version

9.6.2

### Describe the bug

I'm trying to remove a battery powered device but can't do it by the normal exclusion process.

So I factory reset the device and removed the battery but the device never shows as dead so I can remove it that way.

Now the device is in the network but unusable and I can't remove it.

My mains powered devices show as dead if I power them down as expected but the battery powered one doesn't

How do I get a battery powered device to show as dead?

### To Reproduce

factory reset a battery powered device and remove the battery

### Expected behavior

After a time the device should show as dead so it can be forced to remove

### Additional context

[https://www.dropbox.com/s/r2ftgi3wh1uwbr9/nodes_dump.json?dl=0](url)

[https://www.dropbox.com/s/tdbbmtforekbieb/zwavejs2mqtt-store.zip?dl=0](url)

**Comment by robertsLando** [comment]
Did you try to use replace failed node against it?

**Comment by globe-earther** [comment]
No, I didn't think it would work since the device is not showing as failed.

I'll try it and see if it works.

**Comment by robertsLando** [comment]
Let me know

**Comment by globe-earther** [comment]
It didn't work. 

the device went to inclusion mode and zwavejs started the inclusion process then at about 5 seconds left in the countdown timer the system hangs and everything stops until I click the 'x' to close the inclusion pop up.

I tried it a few times and made sure to hit the zwave button to keep the device awake with the same results.

I didn't try it next to the controller tho and just tried it in it's final location.

**Comment by globe-earther** [comment]
Is there a way to manually edit a file somewhere to set the failed flag?

I figured that file would be stuck somewhere in the docker store folder but I've looked but can't find it.

**Comment by globe-earther** [comment]
Nevermind, I just found out that battery operated nodes don't need to be dead in order to remove them.

Might I suggest changing the function description to make it less confusing/vague about removing battery powered nodes, please?

Unless I missed that somewhere.

**Comment by robertsLando** [comment]
> Might I suggest changing the function description to make it less confusing/vague about removing battery powered nodes, please?

You mean the descriuption of replace failed node action?
