### ISSUE TITLE
[Bug]: ERROR: manifest for zwavejs/zwave-js-ui:latest not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by Sennevds** [zwave-js/zwave-js-ui#2663]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

7.0.0 

### ZwaveJS version

zwave-js: 10.0.3

### Describe the bug

I've updated my docker compose file to get the new tag zwavejs/zwave-js-ui:latest but get an error while running up -d

### To Reproduce

create docker compose file from here: https://github.com/zwave-js/zwave-js-ui/blob/master/docker/docker-compose.yml

### Expected behavior

New tag works :)

**Comment by robertsLando** [comment]
@Sennevds That's because there isn't a `latest` tag yet as `latest` is built when there is a new stable release. If you want to use it actually there is `master` tag available that always points to `master` branch

**Comment by Sennevds** [comment]
Aha okay maybe update the docs and the example docker compose file because this will create confusion I think :)

**Comment by robertsLando** [comment]
No need for that, I will release it today so `latest` will be always there then
