### ISSUE TITLE
[question] Web interface doesn't work.

### ISSUE THREAD

**Issue by sunbingnan** [zwave-js/zwave-js-ui#2668]
My application was running in a docker container correctly, but suddenly the web interface on port 8091 failed several months ago, while the application is still running correctly except the web interface. I found  the container is listening on the port 8091, but no response from the port. I have tried many docker images with different versions, but this issue still exists.

```
version: '3.7'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwave-js-ui:master
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Asia/Shanghai
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/ttyACM0:/dev/zwave'
    volumes:
      - zwave-config:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
```

```
2022-09-20T19:22:35.157368834Z  2022-09-21 03:22:35.155 INFO APP: Version: 7.2.0
2022-09-20T19:22:35.158002139Z  2022-09-21 03:22:35.157 INFO APP: Application path:/usr/src/app
2022-09-20T19:22:35.163135479Z
2022-09-20T19:22:35.163155412Z    ______  __          __                      _  _____     _    _ _____
2022-09-20T19:22:35.163158863Z   |___  /           / /                     | |/ ____|   | |  | |_   _|
2022-09-20T19:22:35.163161284Z      / /____   /  / /_ ___   _____         | | (___     | |  | | | |
2022-09-20T19:22:35.163163713Z     / /______ /  / / _'   / / _     _   | |___     | |  | | | |
2022-09-20T19:22:35.163166098Z    / /__        /  / (_| | V /  __/   | |__| |____) |   | |__| |_| |_
2022-09-20T19:22:35.163168448Z   /_____|      /  / __,_| _/ ___|    ____/|_____/     ____/|_____|
2022-09-20T19:22:35.163170790Z
2022-09-20T19:22:35.163173233Z
2022-09-20T19:22:35.178010942Z  2022-09-21 03:22:35.177 WARN STORE: scenes.json not found
2022-09-20T19:22:35.238913587Z  Logging to file:
2022-09-20T19:22:35.238936828Z          /usr/src/app/store/logs/zwavejs_2022-09-21.log
2022-09-20T19:22:46.538985852Z  2022-09-21 03:22:46.538 INFO Z-WAVE-SERVER: ZwaveJS server listening on 0.0.0.0:3000
2022-09-20T19:22:47.549649358Z  2022-09-21 03:22:47.548 INFO Z-WAVE-SERVER: DNS Service Discovery enabled
2022-09-20T19:24:39.215928878Z  2022-09-21 03:24:39.215 INFO Z-WAVE-SERVER: Client disconnected
```

**Comment by robertsLando** [comment]
Is your log truncated? Cannot see where it prints listening port/protocol

**Comment by sunbingnan** [comment]
> Is your log truncated? Cannot see where it prints listening port/protocol

No, the logs are all here, but I get into the container and found the port 8091 is on listening.

```
/usr/src/app # netstat -nap
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:40688        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      1/node
tcp        0      0 0.0.0.0:8091            0.0.0.0:*               LISTEN      1/node
tcp        0      0 172.19.0.2:3000         172.19.0.1:58976        ESTABLISHED 1/node
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1/node
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1/node
udp        0      0 127.0.0.11:47535        0.0.0.0:*                           -
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path
```

**Comment by robertsLando** [comment]
I have you don't have another container running on the same port? 

Try to `docker-compose down` then run `docker ps -a` to see if there are other containers running, if so kill them

**Comment by robertsLando** [comment]
It must be something strange on your setup.

Did you try to run it without compose just to test?

**Comment by sunbingnan** [comment]
> It must be something strange on your setup.
> 
> Did you try to run it without compose just to test?

Thanks for your suggestion. 

I found the issue is in the volumes folder, the web interface would run correctly, if new volumes folder mounted.

But how to fix the existing volume files for the web interface, or migrate the information of the z-wave devices to a new container, I hope it is not need to reconnect all the z-wave devices.

**Comment by mattkasa** [comment]
I think this may have just happened to me, when changing from the zwavejs2mqtt image to the zwave-js-ui image. I did so in-place, and now the UI will not connect to the websocket, it receives a 400 bad request.

**Comment by Thaui57** [comment]
I am not sure if the name change was a good idea. In a running  application (e.g. Domoticz with Auto discovery) all my devices have the prefix "zwavejs2mqtt". Also the docker container is stored in the zwavejs2mqtt directory. After changing to version 8.0 I have lost all my device information and the system is running a re-interview of all my devices followed by a re-discovering in Domoticz ending in a database mess. Is there any update instruction available?

**Comment by robertsLando** [comment]
> In a running application (e.g. Domoticz with Auto discovery) all my devices have the prefix "zwavejs2mqtt"

I didn't changed the discoovery prefix on purpose to prevent this kind of issues. From a mqtt discovery side and also others there shouldn't be any breaking change. I dunno how domoticz is handling this internally

> I found the issue is in the volumes folder, the web interface would run correctly, if new volumes folder mounted.

That's really strange, I need to investigate. Do you still have the content of the old volume?

**Comment by mcaminiti** [comment]
I had a similar issue and then the container eventually hung (UI first) and I tried to roll back to previous version but I had to shift back to the old name for the docker image as only the one tagged in dockerhub with 7.2.0.  I used my same folder and volume mount shifting from zwavejs2mqtt to zwave-js-ui but updated the name and the image pull path in my script.  I didnt see many issues published with 8.0.0 and now I see an 8.0.1 but since rolling back my entities are all stable.  I can try to upgrade again sometime but would be good to know what logs to collect if it hangs/fails again.

**Comment by robertsLando** [comment]
Driver/Application logs as described [here](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=generating-log-files)

**Comment by sunbingnan** [comment]
> That's really strange, I need to investigate. Do you still have the content of the old volume?

[zwave-config.zip](https://github.com/zwave-js/zwave-js-ui/files/9666561/zwave-config.zip)

Here is my volume.

**Comment by robertsLando** [comment]
@sunbingnan I think the problem is for some reason you have `https` enabled in settings, disabling it should do the trick. Otherwise be sure you are tring to connect to `https://localhost:8091`

**Comment by sunbingnan** [comment]
@robertsLando Thanks for your help, I've accessed to the web interface. But I've never changed the https setting.

**Comment by robertsLando** [comment]
But was that the problem so?

**Comment by sunbingnan** [comment]
> But was that the problem so?

Yes, I changed the value of `https` to `false` in settings.json, then the web interfase start work.
