### ISSUE TITLE
[feat]: Persist Rows per page on smart provisioning entities table

### ISSUE THREAD

**Issue by dimatx** [zwave-js/zwave-js-ui#2721]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Z-Wave JS UI version

8.2.0

### ZwaveJS version

10.3.0

### Describe the bug

On the /smart-start page, the "Rows per page" always reverts to '10' upon every refresh. This is unlike the persistence that is seen on other pages such as /control-panel where picking a value other than the initial one survives a page refresh.

### To Reproduce

1. Go to /smart-start page
2. Select a value other than '10' from "Rows per page"
3. Refresh page.
4. Value will be back to '10'

### Expected behavior

Chosen value for "Rows per page" should survive a page refresh.

**Comment by robertsLando** [comment]
I could not reproduce your issue. After pulling new changes did you remember to run `yarn install` `yarn build` commands?

**Comment by dimatx** [comment]
I see. OK sounds like then it's not a bug. Thanks for confirming! I guess I would consider it a feature request to persist page settings across the app for a consistent UX. Feel free to close or convert into a feature request based on your view as to whether this is desirable.

**Comment by robertsLando** [comment]
Converted to a feat request :)

**Comment by webmogul1** [comment]
+1 to the request.
