### ISSUE TITLE
[Bug]:  8.2.0 not starting on Raspberry PI buster

### ISSUE THREAD

**Issue by marcinkowalczyk** [zwave-js/zwave-js-ui#2725]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

N/a

### ZwaveJS version

8.2.0

### Describe the bug

Latest release does not start on Raspberry Pi. Docker logs dumps

```
# FailureMessage Object: 0x7eb9049c


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ed0149c


#
# Fatal error in , line 0
# unreachable code
```

### To Reproduce

docker pull zwavejs/zwavejs2mqtt:8.2.0

### Expected behavior

Zwavejs2mqtt starts

### Additional context

Works fine with zwavejs/zwavejs2mqtt:8.1.0

**Comment by robertsLando** [comment]
cc @chrisns

**Comment by robertsLando** [comment]
@marcinkowalczyk thanks for your report, we updated base docker images and I think that's the reason of that failure, let me investigate

**Comment by robertsLando** [comment]
Ok found a solution for you, please follow steps described [here](https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/guide/installation/02_docker.md#notes-for-raspberry-pi-users)

**Comment by robertsLando** [comment]
Also added to docs now: https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/app_crash?id=raspberry-pi-crash-with-820

**Comment by robertsLando** [comment]
Perfect, thanks for your feedback @janneman001 and sorry for the inconcenience

**Comment by psfales** [comment]
I'm running buster, but installing libseccomp2 from the buster-backports didn't work for me.  Is there anything else I can try?

**Comment by robertsLando** [comment]
@psfales Upgrade to bulleyes

**Comment by bushvin** [comment]
Just to chime in here... Upgrading to bullseye worked like a charm!
Thanks, @robertsLando !

**Comment by robertsLando** [comment]
Thanks for the feedback @bushvin :)

**Comment by psfales** [comment]
I was able to get it working by following the instructions at [](https://wiki.alpinelinux.org/w/index.php?title=Release_Notes_for_Alpine_3.13.0&oldid=19609#time64_requirements) to launch docker with a  modified seccomp profile.

**Comment by robertpeteuil** [comment]
Thanks for the tip @psfales!  Saved me the hassle of upgrading the OS.

**Comment by scyto** [comment]
i tested the upgrade from buster to bullseye[ using this set of instructions, ](https://linuxhint.com/upgrade-raspberry-pi-os-buster-to-bullseye/#:~:text=How%20to%20Upgrade%20Raspberry%20Pi%20OS%20from%20Buster,...%207%20Step%207%3A%20Reboot%20the%20System%20)worked perfectly.

**Comment by ktpx** [comment]
Installing the libsec2 package worked for me.  Time to switch my pi to a rolling distro, dist upgrades are not pretty.

**Comment by fuxjezz** [comment]
Besides installing the backported libsec2 package I had to add this to my docker-compose.yml in order to leviate this issue:

<pre>
version: '3'
services:
  zwave-js-ui:
    security_opt:`
      - seccomp:unconfined
</pre>

(perhaps this works just as well without installing the backported libsec2 package, haven't tested yet)

I know I should've upgraded to bullseye already, at least this workaround allows me to plan the upgrade to bullseye a little more carefully..

**Comment by dlasher** [comment]
Ran into this as well - was far faster to backup the /DATA folder - image the RPI with dietpi-buster version, then restore. Working fine now, but ugh, I would have been dead in the water if it wasn't for this bug report.
