### ISSUE TITLE
Controller CSV export [feat]

### ISSUE THREAD

**Issue by tamorgen** [zwave-js/zwave-js-ui#2736]
**Is your feature request related to a problem? Please describe.**
Not a problem per say, but I would find it useful to be able to export the table to a CSV, to more easily track and manipulate inventory of devices

**Describe the solution you'd like**
An export button allowing the contents of the device table to be exported to CSV

**Describe alternatives you've considered**
I've tried selecting all the devices, but it does not paste cleanly into Excel 

**Additional context**
N/A

**Comment by robertsLando** [comment]
@tamorgen you could download them in json format and then convert those info to excel? Just go to advanced and then debug export to export a json file array with all nodes info. 

Then you can use any online tool like json to csv to make them excel compatible: https://data.page/json/csv
