### ISSUE TITLE
[Bug]: MR40Z missing action capability

### ISSUE THREAD

**Issue by jpoeppelman1** [zwave-js/zwave-js-ui#2740]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

latest

### ZwaveJS version

latest

### Describe the bug

MR40Z button scene controller will not send the button push event to MQTT.  We have no way to trigger an automation in Home Assistant.

Here is the device:

https://www.amazon.com/dp/B09BQKD5FQ?psc=1&ref=ppx_yo2ov_dt_b_product_details

### To Reproduce

easy to produce, no action events..

### Expected behavior

should send the button push events

### Additional context

none

**Comment by robertsLando** [comment]
> should send the button push events

Do you see this events in node events tab? Did you check under basic cc? Do you have mqtt explorer?

**Comment by jpoeppelman1** [comment]
The events are not coming through.  I use Node Red and there is no entity I can listen to when triggering an automation.  All other scene controllers work fine.  Check out the screen shot below.

![image](https://user-images.githubusercontent.com/35069890/196472601-665684c8-2782-453d-9325-edbf70f743bc.png)

**Comment by robertsLando** [comment]
> The events are not coming through. I use Node Red and there is no entity I can listen to when triggering an automation. All other scene controllers work fine. Check out the screen shot below. There should be a button action entity registered in HA.

I mean in zwave-js-ui, click on a node, expand it, go to events tab and see if the event is shown on that list.

If it is there I suggest to use mqtt explorer to detect the topic where that event is published. On the HA side I cannot help so much as I don't use HA

**Comment by kpine** [comment]
It certainly sounds like you're using HA and the Z-Wave integration, based on the screen shot, not MQTT. In that case you should be consulting the [integration docs](https://www.home-assistant.io/integrations/zwave_js/). Scene controllers send [events](https://www.home-assistant.io/integrations/zwave_js/#scene-events-value-notification), they are not entities.

**Comment by jpoeppelman1** [comment]
You are correct, the events are coming through but HA is not creating an entity for the button action.  I will report this to HA team.  Thank you!  BTW, great job with this zwave software!

**Comment by kpine** [comment]
There are no entities created for the button action, it is not a bug. Use the events.

**Comment by jpoeppelman1** [comment]
In other scene controllers, there is an entity created in HA that stores the last button action.  Tuya devices are a good example of this.

**Comment by kpine** [comment]
They are different integrations. The Z-Wave integration does not create entities. Use the events as indicated in the docs.

**Comment by kpine** [comment]
You're free to submit an issue to HA as you choose, but just letting you know it probably won't go anywhere. The events are by design. It is a nuisance that integrations approach this in different ways. IMO Tuya has it wrong.
