### ISSUE TITLE
Actually refresh the groups associations, on "Refresh"

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwave-js-ui#2752]
**Is your feature request related to a problem? Please describe.**
I was on slack yesterday trying to track down an issue with lost messages or long delays. I was recommended to restore NVM backups and re-interview nodes to try to restore any past "working condition". None helped, except, the reinterview apparently refreshed the associations table where it turns out a bad node had come in.

My theory is that I didn't see this, as the bad node was a secondary controller I added for debugging, and since removed. This must have, for whatever reason, added itself to the associations for some nodes. Zwave-js-ui was then unaware of this.

I am 100% certain I checked the associations, because I've had this issue before, but the bad node did not appear, even after clicking Refresh.

![image](https://user-images.githubusercontent.com/1027111/197395255-6c65a856-c368-41b5-9d78-e7fec338a211.png)

I've since through logs found that "Refresh" does in fact _not_ refresh the actual associations, but merely updates the table visually.

**Describe the solution you'd like**
Make the "Refresh" button actually go out and query the node to get the associations.

**Describe alternatives you've considered**
I may be able to instrument the zwave-js API using "driver functions" etc., to do refreshes of just this one piece of information.

**Additional context**
Some time ago, I made a feature request on health checks. This association to a "ghost" is exactly one of the conditions I'd love to be warned about. I'm aware the zwave-js, in this instance, does not get to know anything about this association as it was added outside of its purview, but once it became aware of it (through the reinterview process), I'd _love_ to see a banner or a menu flashing red saying "oh btw, this association doesn't work". :)

Logs showing that refresh does not "refresh" (`wave-js` and `zwave-js-ui` in one). Notice that no packets are sent on the network:
```
2022-10-23 15:39:35.915 INFO Z-WAVE: Calling api getAssociations with args: [ 6, [length]: 1 ]
2022-10-23 15:39:35.928 INFO Z-WAVE: Success zwave api call getAssociations [
  { endpoint: 0, groupId: 1, nodeId: 1, targetEndpoint: 0 },
  [length]: 1
]
```

**Comment by robertsLando** [comment]
@LordMike I think the only way to do this is to do a re-interview of the node. Getassociations like other methods simply fetch informations from zwave-js cache.

@AlCalzone ?

**Comment by AlCalzone** [comment]
@robertsLando re-querying associations makes sense, especially without having to go through an entire interview. I'm not sure if refreshValues does this or if I need to add a method to the controller class

**Comment by robertsLando** [comment]
> re-querying associations makes sense

I have checked docs and cannot find a specific method to do this, maybe using refresh values but how should I call it?

**Comment by AlCalzone** [comment]
It's not high priority. Let me check when I have the time and/or add a proper solution to the driver

**Comment by LordMike** [comment]
IIRC it's something along the lines of querying each association for a list of partners.. So yea, it can potentially be very long, especially for many associations or high latency devices. At least, that's what I got from running the PC controller :)
