### ISSUE TITLE
large negative Meter Reports on NAS-WR01ZE 

### ISSUE THREAD

**Issue by TomMalfrere** [zwave-js/zwave-js-ui#2762]
Hi,
I have 7 NAS-WR01ZE devices running and I got these large negative values for the electric consumption.
I added the following function to the "Parse send"

return (((value*100)&2147483647)/100);

Now it seems like I'm getting correct values in MQTT explorer and in domoticz.

All this function does is strip of the highest bit (sign bit)

Is it an option to always apply this for this device without having to add a "Parse send" function?

**Comment by kpine** [comment]
It's a known bug with these devices. See [device DB](https://devices.zwave-js.io/?jumpTo=0x0258:0x0100:0x1027:0.0) for warning and https://github.com/zwave-js/node-zwave-js/issues/2692 for more information and solutions.

![image](https://user-images.githubusercontent.com/791794/197870616-21c0f278-4b92-42a4-95a6-b679c950de00.png)

**Comment by robertsLando** [comment]
Warnings should be shown on UI too BTW

**Comment by TomMalfrere** [comment]
Hi,

I know it is marked as a bug. Maybe it is not a bug but just strange behavior. Maybe the highest bit was reserved from day 1 and was never used in the old devices.

I'm offering you a solution for this known bug/behavior. 
If you would implement this for all devices with this ID, you could lose the warning and these devices would work just fine with your zwavejs implementation.
Just trying to add my bit here...

**Comment by kpine** [comment]
> If you would implement this for all devices with this ID, you could lose the warning and these devices would work just fine with your zwavejs implementation.

Please read through the issue I linked to, this proposal has been discussed thoroughly and rejected.

**Comment by TomMalfrere** [comment]
As an end-user it is quite confusing at first that you refuse to apply a fix for a broken device.

But after reading the thread zwave-js/node-zwave-js#2692, I better understand why and I have to admit that refusing to fix somebody else's bugs is right thing to do.
