### ISSUE TITLE
Allow to fetch pre-releases in OTA udpates

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js-ui#2768]
Add a flag to UI to include pre-releases in ota updates check

`getAvailableFirmwareUpdates` options `includePrereleases`

Ref: https://github.com/zwave-js/node-zwave-js/issues/5167

**Comment by catchthemonster** [comment]
cool thanks @robertsLando

**Comment by AlCalzone** [comment]
This should be an opt-in and beta firmwares should be easily recognizable as such.
