### ISSUE TITLE
Add node name to `StatisticsUpdated` node events

### ISSUE THREAD

**Issue by zhimsel** [zwave-js/zwave-js-ui#2789]
**Is your feature request related to a problem? Please describe.**
The way I collect RX/TX metrics (liked dropped commands, etc) is to subscribe to the `_EVENTS/<mqtt_name>/node/statistics_updated` MQTT topic. I can then parse the JSON body and insert that data into a time-series database. However, each message to that topic only includes the node ID. This is pretty hard to quickly parse when viewing the metrics in something like Grafana (i.e. seeing node numbers instead of names).

**Describe the solution you'd like**
I'd like the `Include Node Info` setting to also insert a field or something into the payload of those messages that includes the node name (in addition to the ID). Maybe just another item in the array? or a field in the `data` object?

**Additional context**
I'm referring to this API: https://zwave-js.github.io/node-zwave-js/#/api/node?id=quotstatistics-updatedquot

---

I would submit a pull request, but I'm particularly strong with JavaScript, and I don't have the spare time to fully parse the moving parts of all the different classes and code structure.

If this is something easily possible, I'd love to see it implemented.

**Comment by zhimsel** [comment]
Awesome thank you! That was quick! I'll test it out once it hits the next release and report back. Or, if I have time, build an image off this branch and test.

**Comment by robertsLando** [comment]
@zhimsel you welcome! Be aware that the PR that fixed this also aligned all node events to have the complete [zwaveNode](https://zwave-js.github.io/node-zwave-js/#/api/node?id=zwavenode-properties) object as first element in mqtt payload `data` array

**Comment by zhimsel** [comment]
Understood. I'll adjust my metrics collection accordingly. Thanks!

**Comment by robertsLando** [comment]
Release is out now
