### ISSUE TITLE
[feat] OpenWrt packaging

### ISSUE THREAD

**Issue by dwmw2** [zwave-js/zwave-js-ui#2797]
**Is your feature request related to a problem? Please describe.**
We package Domoticz for OpenWrt, and so far we have built it to use OpenZWave.

Newer versions of Domoticz have deprecated the OpenZWave support, so I'm looking at how to package zwave-js-ui for OpenWrt so that it can be part of the embedded router firmware.

I would very much appreciate some help working out how to do clean packaging from known source releases.

There are some OpenWrt node packages in https://github.com/partylover/openwrt-node-packages maintained by @partylover and I've experimented a little bit but I haven't made much progress. Packaging zwave-js itself seems like it might be a little simpler since it's in npm.

**Comment by robertsLando** [comment]
Hi David! Unfortunally I have zero experience with OpenWrt, couldn't you use a packaged version of zwave-js-ui instead? 

https://github.com/zwave-js/zwave-js-ui/releases/download/v8.4.1/zwave-js-ui-v8.4.1-linux.zip

**Comment by robertsLando** [comment]
> If I could work out how to build the packaged version from a known set of sources

My idea is not you to build it but to directly use the already builded version.

**Comment by dwmw2** [comment]
OpenWrt is an embedded distribution using musl instead of glibc; the one I run domoticz on is a MIPS CPU. There aren't prebuilt versions for those platforms — we need to work out how to build it.

**Comment by nxhack** [comment]
@dwmw2 
zwave-js is now supported. Please try it out.

https://github.com/nxhack/openwrt-node-packages/tree/master/node-zwave-js

22.03, 21.02 will be merged after build test is completed.

**Comment by dwmw2** [comment]
Thanks! I'll see if I can test it. Not quite sure how to test zwave-js on its own... the next request is to package zwave-js-ui :)

**Comment by dwmw2** [comment]
I installed it and tried putting some of the example at https://zwave-js.github.io/node-zwave-js/#/getting-started/quickstart into a `foo.js` file and running it (with a `package.json` with `type=module`. I get:
```
root@U7623:~# node foo.js 
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'zwave-js' imported from /root/foo.js
Did you mean to import zwave-js/build/index.js?

```
Sorry to be clueless... what should I do here to test it? 

FWIW if I do `npm i zwave-js` then it *does* get a little bit further... it at least opens the serial port, and then segfaults.

**Comment by dwmw2** [comment]
Thanks for the help with this, @nxhack. It would be great to be able to upgrade the OpenWrt package of Domoticz to the latest version and switch to using zwave-js-ui. 

If it's more convenient, I'm happy to let you have remote access to a test OpenWrt system with a Z-Wave dongle attached.
