### ISSUE TITLE
[bug] "Last seen" is updated on dropped message

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwave-js-ui#2800]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Z-Wave JS UI version

8.4.1.ac29618

### ZwaveJS version

10.3.0

### Describe the bug

I was looking at a node that didn't respond, and it looked like it _was_ since I had a "last seen" timestamp that was "now"..

Turns out that when a message is _not_ delivered to the node, e.g. dropped, the timestamp _also_ updates. This is misleading.

### To Reproduce

1. Have a dead node.
2. Ping it
3. Observe after a timeout, that the "last seen" updates

See gif.

### Expected behavior

Timestamps should reflect when the device was last heard from.

### Additional context

![Recording 2022-11-14 at 09 05 22](https://user-images.githubusercontent.com/1027111/201607698-66e445e0-9ab8-4fd5-98f1-2199376db08d.gif)

**Comment by robertsLando** [comment]
There is also a feature request on zwave-js side to add this lastSeen on driver to be more precise, BTW I should check on code if there is a way to fix this
