### ISSUE TITLE
Radio Thermostat Company of America (RTC) CT101 Thermostat Fan mode missing from Hass devices

### ISSUE THREAD

**Issue by cookemmm** [zwave-js/zwave-js-ui#2803]
Build/Run method:

[ X] Docker
[ ] Git Clone + yarn install + yarn run build + yarn start
[ ] Pkg

Z-Wave JS UI version: 8.4.1.ac29618
Z-Wave JS version: 10.3.0

I am moving from openzwave to zwavej22mqtt for use with domoticz which uses the Hass devices. Everything seems good except there is no Hass device to control the fan mode which there was previously in openzwave. I was trying to follow the docs to add it myself but can't seem to figure it out.

**Comment by robertsLando** [comment]
Hi @cookemmm, like I suggested in the other discussion, you should manually edit the discovery payload until you find a format that works for your thermostat, you could follow already existing examples like: https://github.com/zwave-js/zwave-js-ui/blob/master/hass/devices.ts#L28

It could be that the same template also works for your thermostat, what's the if of your device? You can find id when you click-expand a node in control panel, it's in the format `xxx-xxx-xxx`

**Comment by cookemmm** [comment]
id is 152-11-25857

I have attempted several times to add the fan modes to the json but I must be missing something because no new devices are created. 

here is what  i have after adding the fan modes.....maybe you can find my error 

{
  "type": "climate",
  "object_id": "climate",
  "discovery_payload": {
    "min_temp": 5,
    "max_temp": 40,
    "temp_step": 0.5,
    "modes": [
      "off",
      "heat",
      "cool",
      "auto"
    ],
    "fan_modes": [
      "Auto low",
      "Low"
    ],
    "mode_state_template": "{{ {0: \"off\", 1: \"heat\", 2: \"cool\", 3: \"auto\"}[value_json.value] | default('off') }}",
    "fan_mode_state_template": "{{ {0: \"Auto low\", 1: \"Low\"} [value_json.value] | default('Auto Low') }}",
    "current_temperature_topic": "zwave/17/49/1/Air_temperature",
    "current_temperature_template": "{{ value_json.value }}",
    "fan_mode_state_topic": "zwave/17/69/0/state",
    "fan_mode_command_topic": "zwave/17/68/0/mode",
    "temperature_state_topic": "zwave/17/67/1/setpoint/1",
    "temperature_state_template": "{{ value_json.value }}",
    "temperature_command_topic": "zwave/17/67/1/setpoint/1/set",
    "mode_state_topic": "zwave/17/64/1/mode",
    "mode_command_topic": "zwave/17/64/1/mode/set",
    "action_topic": "zwave/17/66/0/state",
    "action_template": "{{ {0: \"idle\", 1: \"heating\", 2: \"cooling\", 3: \"fan\", 4: \"idle\", 5: \"idle\", 6: \"fan\", 7: \"heating\", 8: \"heating\", 9: \"cooling\", 10: \"heating\", 11: \"heating\"}[value_json.value] | default('idle') }}",
    "temperature_unit": "F",
    "precision": 0.1,
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xcadd9946_node17"
      ],
      "manufacturer": "Radio Thermostat Company of America (RTC)",
      "model": "Z-Wave Thermostat (CT101)",
      "name": "nodeID_17",
      "sw_version": "9.0"
    },
    "name": "nodeID_17_climate",
    "unique_id": "zwavejs2mqtt_0xcadd9946_Node17_climate"
  },
  "values": [
    "49-1-Air temperature",
    "64-1-mode",
    "66-0-state",
    "67-1-setpoint-1",
    "67-1-setpoint-2",
    "67-1-setpoint-1",
    "69-0-state",
    "68-0-mode"
  ],
  "mode_map": {
    "off": 0,
    "heat": 1,
    "cool": 2,
    "auto": 3
  },
  "fan_mode_map": {
    "Auto low": 0,
    "Low": 1
  },
  "setpoint_topic": {
    "1": "67-1-setpoint-1",
    "2": "67-1-setpoint-2",
    "3": "67-1-setpoint-1"
  },
  "default_setpoint": "67-1-setpoint-1",
  "action_map": {
    "0": "idle",
    "1": "heating",
    "2": "cooling",
    "3": "fan",
    "4": "idle",
    "5": "idle",
    "6": "fan",
    "7": "heating",
    "8": "heating",
    "9": "cooling",
    "10": "heating",
    "11": "heating"
  },
  "discoveryTopic": "climate/nodeID_17/climate/config",
  "persistent": true,
  "ignoreDiscovery": false,
  "id": "climate_climate"
}

**Comment by robertsLando** [comment]
Does the discovery fail or simply the component doesn't work? Do you have access to domoticz logs? When the discovery payload is received from domoticz it should parse it and throw an error if something is wrong

**Comment by robertsLando** [comment]
> "fan_mode_command_topic": "zwave/17/68/0/mode",

Should be `"fan_mode_command_topic": "zwave/17/68/0/mode/set",`

**Comment by cookemmm** [comment]
no fan component is created in domoticz....a mode switch was created along with set point and temperature......I see no errors in the domoticz logs. not sure if it is a domoticz issue or the payload is wrong....i have opened an issue  on the domoticz side to see if there is some additional info I can gather

**Comment by robertsLando** [comment]
If there is no error log in domoticz means that the discovery payload is parsed correctly I think (never used domoticz so dunno for sure).

About the payload it looks good to me except the error I show you in my previous comment
