### ISSUE TITLE
Error reading settings file

### ISSUE THREAD

**Issue by TheAceMan** [zwave-js/zwave-js-ui#2805]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.4.1.ac29618

### ZwaveJS version

10.3.0

### Describe the bug

When the container is recreated (not sure if it happens on a restart but see it usually after pulling a new image and recreating the container), I will see this error in the log (The blank space after token shows as NUL character in other UI):

```
 ERROR STORE: Error reading file: settings.json /usr/src/app/store/settings.json: Unexpected token  in JSON at position 0
SyntaxError: /usr/src/app/store/settings.json: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at _readFile (/usr/src/app/node_modules/jsonfile/index.js:25:16)
    at StorageHelper._getFile (/usr/src/app/server/lib/jsonStore.js:100:20)
    at StorageHelper.init (/usr/src/app/server/lib/jsonStore.js:54:25)
```

And my setting file is lost and a new setting file with default values is created. I simply copy in the data from a backup file I have and recreate container and it works. It does not seem to happen every time the container is recreated but notice it when I cannot control my zwave devices. I used to get a similar error but it appears to have changed recently, same except the unexpected value which could just be a rending difference based on the NUL character:

```
ERROR STORE: Error reading file: settings.json /usr/src/app/store/settings.json: Unexpected token ? in JSON at position 0
SyntaxError: /usr/src/app/store/settings.json: Unexpected token ? in JSON at position 0
    at JSON.parse (<anonymous>)
    at _readFile (/usr/src/app/node_modules/jsonfile/index.js:25:16)
    at StorageHelper._getFile (/usr/src/app/server/lib/jsonStore.js:56:20)
    at StorageHelper.init (/usr/src/app/server/lib/jsonStore.js:47:25)
```

### To Reproduce

Does not happen each time and do not recreate the container often so mainly notice this after pulling a new image and recreating the container.

### Expected behavior

Existing settings file should not be reset to default values. If there is an error do not overwrite the existing file but stop the container. But since the container starts on subsequent starts it seems more like a timing issue or other error leading to a bad state.

Expect the container to recreate and use the existing settings file.

### Additional context

Is there a process on new images/versions that tries to update the settings file that is running in a different context that would not have the same access to the file?

**Comment by robertsLando** [comment]
@TheAceMan What is the content of the settings file when the parse fails? 

The setting file is only written when you press save on the UI

**Comment by robertsLando** [comment]
> Haven't found where it writes the file. Maybe only apply defaults in cases where the file is not found, but if file found and cannot read do not continue start up. This would at least prevent the file overwrite and signal something went wrong vs just clearing the settings.

I tought about this a while ago, the problem is that doing this requires user a manual edit of the file in order to fix it and that's annoying, what I could do is to rename the file instead of overwriting it?

> As mentioned this seems to happen when getting a new image, to do this I do a docker-compose pull to get the latest images and then docker-compose up -d to update containers

That's the usual steps that should be done when updating an image, seems like the file gets corrupted for some reason, maybe the stop signal sent to the container is not correct? Can I see your docker compose file? Are you using the default one?

**Comment by robertsLando** [comment]
> volume being a file share

Could you try to see if you are able to reporduce this issue with a local volume? I personally had some weird bug with docker volumes and I have a feel that's the root cause
