### ISSUE TITLE
new bug when running UI addon on Pi4.

### ISSUE THREAD

**Issue by jonny9998** [zwave-js/zwave-js-ui#2806]
Why have you removed the menu item [Disable Gateway] from the UI settings page?

The documentation still refers to this feature and indicates that you would "Enable this to use Z-Wave JS UI as only a Control Panel"

Without this option available, there seems to be an issue running both Zwave JS and Zwave JS UI, at least on a Pi4.  Specifically, the following errors are being generated by Zwave JS UI when trying to run:

![image](https://user-images.githubusercontent.com/37650010/202365175-11567f85-5132-4277-944a-359faab10ac3.png)

**Comment by robertsLando** [comment]
@jonny9998 This usually means you have 2 applications that are using the port.

Could it be you have 2 instances of zui running? Or maybe, if you are using Home Assistant, you have both the integration and zui connecting to the port?

**Comment by jonny9998** [comment]
Thanks for the reply.  You are correct, I was running both the official addon and your addon.  Once I removed the official add on, everything worked fine.
