### ISSUE TITLE
Getting error: "Too many levels of symbolic links" when attempting to install Z-Wave JS via docker.

### ISSUE THREAD

**Issue by magudelo58** [zwave-js/zwave-js-ui#2807]
I'm following the instructions from here [https://zwave-js.github.io/zwave-js-ui//#/getting-started/quick-start] specifically the section:

### As a service
wget https://raw.githubusercontent.com/zwave-js/zwave-js-ui/master/docker/docker-compose.yml
docker-compose up

This is the output for the docker-compose up command:

> Creating network "pi_zwave" with the default driver
> Creating volume "zwave-config" with default driver
> Pulling zwave-js-ui (zwavejs/zwave-js-ui:latest)...
> latest: Pulling from zwavejs/zwave-js-ui
> 9b18e9b68314: Already exists
> c36a46adb29b: Already exists
> eafd75f9515d: Extracting [==================================================>]  2.444MB/2.444MB
> b3f4a695f92c: Download complete
> 8405a88807c0: Download complete
> 7c1f7b865f6b: Download complete
> 4f4fb700ef54: Download complete
> ***ERROR***: failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/fb25fb968237f7bdccb61340ea2541f1190da849ebeab4e0383e8b2c6ff866ac/merged: too many levels of symbolic links

 
To be honest I'm new using docker, but since I have been able to install home-assistant and other containers via docker without issues, and before spending hours trying to troubleshoot this, I'm double checking with you guys to know if this have been reported before when Z-Wave JS is being installed.

My current issue is that my Z-Stick is not working anymore after getting some upgrade from HA, but this is different history...

Thanks in advance for your input.

Marco

**Comment by robertsLando** [comment]
By googling it seems it's a docker issue, someone suggests to try deleting all docker images and retry, also it could be you are running out of disk space?

**Comment by robertsLando** [comment]
You welcome. Let me know

**Comment by magudelo58** [comment]
Hi Lando

That made the trick, the Z-Wave is now up. Thanks for the suggestion.
