### ISSUE TITLE
Choose controller as default target node for Health Check

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js-ui#2842]
**Is your feature request related to a problem? Please describe.**
When doing a health check, the default target node is empty. This means you always have to go through the list and pick a node. I would argue that the most common use case for this feature is to check health against the controller node. It takes a couple extra mouse clicks to pick a target, so setting the default would be convenient.

**Describe the solution you'd like**
The controller node set as the default target node.

**Describe alternatives you've considered**
None.

**Additional context**
N/A.

**Comment by robertsLando** [comment]
Agree 👍🏼
