### ISSUE TITLE
Web interface issues when accessing via "web proxy"

### ISSUE THREAD

**Issue by juanjoSanz** [zwave-js/zwave-js-ui#2843]
Hi all,

we have identify an issue, when accessing zwavejs-ui not directly but via a proxy.  URLs for some resources were pointing wrong paths.

We tested a fix, removing the following line and for us it seems to be working. 

https://github.com/zwave-js/zwave-js-ui/blob/f033ee8724799063c3979adfa8511005cb7a8276/build/webpack.base.conf.js#L91

Do you see any problem removing that parameter?  `publicPath: '../../'`  

Thanks

**Comment by robertsLando** [comment]
Have you checked this? https://zwave-js.github.io/zwave-js-ui/#/usage/reverse-proxy?id=accessing-from-behind-a-proxy

Also  how are you running zui? Docker?

**Comment by juanjoSanz** [comment]
zui is build in a **pkg** for arm64 arch. The proxy is an app call **teleport**.
With the suggested fix, everything works fine. Do you think it will be possible to incorporate that into official build?

**Comment by robertsLando** [comment]
> With the suggested fix, everything works fine. Do you think it will be possible to incorporate that into official build?

If I do that it stops working in the other usage so nope, I'm sorry

**Comment by juanjoSanz** [comment]
I thought this would not affect other usage. Do you have any suggestion about which usage could be affected? If so, I would be able to run some test to check it.

In any case, thanks for the support and the great job with this app.

**Comment by robertsLando** [comment]
Even normal usage should stop working with that. Just try to run the server with that change

**Comment by juanjoSanz** [comment]
Actually it works fine with and without proxy, and there are no errors/warning in web browser dev console. 

Without the fix, normal web works but when using proxy some static links are wrong.

**Comment by robertsLando** [comment]
Just tested and that change breaks the logic when running application behind a proxy, I get 404 on all fonts

**Comment by juanjoSanz** [comment]
Hi again, I tested again later release, v8.9.0, and still having issues with icons when using proxy. We really tried many options using nginx and nothing worked.

So I recreated the package with the fix we suggested and for us it seems to be working fine, and seems to be the solution for our issues. I tested it with proxy and direct access, and so far I see nothing broken. 

Just in case, let me paste the suggested fix, cause maybe it was not clear enough.

<img width="857" alt="Screenshot 2023-03-03 at 09 29 24" src="https://user-images.githubusercontent.com/1581524/222671531-94583bd3-7bf5-4b1c-94a9-1d5cc9f2bea8.png">

**Comment by robertsLando** [comment]
Tried what I suggested in [above](https://github.com/zwave-js/zwave-js-ui/issues/2843#issuecomment-1377367370) comment?

**Comment by juanjoSanz** [comment]
Thanks. Unfortunately, it cannot be tested since device does not support docker, and installing docker would require a huge effort.

**Comment by robertsLando** [comment]
I don't want you to test on devices but locally on your PC to verify that it doens't work with your suggested change
