### ISSUE TITLE
Battery icon is showing level "unknown" but level is 100%

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js-ui#2845]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.6.0.01c659b

### ZwaveJS version

10.3.1

### Describe the bug

The battery icon for a node is showing "unknown", but the battery level exists at 100%. Screenshot:

![image](https://user-images.githubusercontent.com/791794/207515599-1394d436-e6a8-42fa-8d69-c48b5fbecf23.png)

### To Reproduce

Not sure, it might be specific to this device and how the interview went.

### Expected behavior

Battery icon should be correct.

### Additional context

The only interesting thing I can think of is that the initial interview failed to Get the battery level, as there was a command timeout. However, after interview a Battery Report was sent, which triggered a 'value added' event (visible in debug info). You can see this in the attached inclusion logs.

[zwavejs_current.log](https://github.com/zwave-js/zwave-js-ui/files/10224697/zwavejs_current.log)

Node Debug info:

[debug.json.txt](https://github.com/zwave-js/zwave-js-ui/files/10224737/debug.json.txt)

**Comment by robertsLando** [comment]
Let me know :)

**Comment by robertsLando** [comment]
News on this ?

**Comment by robertsLando** [comment]
I have a feel the problem is:

> Not sure, it might be specific to this device and how the interview went.

ATM I don't really like how this is handled internally, I'm going to rewrite the logic soon
