### ISSUE TITLE
Discovery devices gets mixed up !

### ISSUE THREAD

**Issue by Miesje** [zwave-js/zwave-js-ui#2846]
Hi Developer,

Almost two weeks I'm migrated to zwave-js-ui, so I'm not an expert.

I have manually transferred 71 devices to my new zwave 7 stick.
At first it seems to be correct but after a while a receive new device items.
The thing is now, that non electric devices, like a PIR motion sensoror smoke detector, are getting values from it, like 220 Volts.
For example the smoke sensor below is getting a meter v0

![image](https://user-images.githubusercontent.com/5450900/207865980-8b6e5fea-d066-4fde-b35a-014622463eb9.png)

This happens with a lot of devices.
Also other devices items are appearing where the should not.
If restart the docker then it seems to be Ok but then the devices items return.
I have all the logs ready but I will not post them in a public channel.

Thanks in advance.

With kind regards,
Mies

**Comment by Miesje** [comment]
Forget to mention my hardware situation:

I run Domoticz version 2022.2 on a PI4 with Raspbian.
Latest version zwave-js-ui runs on docker on the same PI4
Mosquito = mosquitto is an MQTT v5.0/v3.1.1/v3.1 broker.
700 Series-based Controller	ZST10-700 with 71 devices
Domoticz ->  MQTT Auto Discovery Client Gateway with LAN interface

**Comment by robertsLando** [comment]
Did you tried to re-interview devices?

**Comment by Miesje** [comment]
Dear Lando,

Thanks for your response.
Today as I got values that should not be there.
I think have tried everything, re-interview, exclude-include, delete values- refresh values, clear retain, set retain.

![image](https://user-images.githubusercontent.com/5450900/208135105-db78e8f7-a40d-48bd-8cd3-9cb3ff5131c7.png)

The ones marked in red are all non electric like a PIR, smoke detector or door contact
Three week ago I was running on zwave 500 series.
Now I'm running the 700 series from aeon, maybe they are less quality.

For example I have a outdoor sensor Philio PSP05 Motion PIR.
When I include the above one then the Qubino Flush Shutter ZMNHCD will be installed.
Also my Eurotronics Thermostatic Valve	Spirit are not functioning correct anymore.
I did not have such problems with the 500 series on USB.

Maybe it is the new zwave stick, maybe mqtt or domoticz but probably I'm doing something wrong but I don't know what.
If you need logs, please let me know, then I will send them on a private channel.

With kind regards,
Miesje

**Comment by robertsLando** [comment]
@Miesje Could you firstly ask to domoticz for support? I never used it and I have a feel the error is not on zui but there

**Comment by Miesje** [comment]
Dear Robert,

Thanks for reading the problem.
It depends on your answer if the problem should be here or somewhere else

For example: I have a wall push button with no electricity items on it: Heatit Z-Push Button 8.

See the image below.

![image](https://user-images.githubusercontent.com/5450900/209720386-9a3d9d7c-e0d8-423a-8b8c-4b4035999ea4.png)

As you can see it has a meter v0 with the value of -214...
This is a value from probably a other item:

![image](https://user-images.githubusercontent.com/5450900/209720597-082921ce-496f-4bed-9795-bc7c185dc9f3.png)

**Now is the question**: 
Is it possible that through MQTT, that it can create a new value on the object.
If that is the case, then the problem can reside in three options:

1. Zwave-JS-UI create this object and send it to mqtt
2. MQTT is mixing id's or something like that and send it to zwave-js-ui
3. Domoticz creates this object and send it back through mqtt

I would like to go to the right support but for me it looks as the zwave-js-ui creates the value.
Please let me know if mqtt can create items in zwave-js-ui ?

Thanks in advance.
Miesje

**Comment by robertsLando** [comment]
@Miesje if that device has that valueId it means it supports that CC. I have many heatit devices and almost all have Meter CC support so nothing wrong here just ignore it?

**Comment by Miesje** [comment]
Ok thanks for the explaining.
I will not delete them anymore because it will come back.
Thanks.
