### ISSUE TITLE
Eurotronics Thermostatic Valve Spirit not correct

### ISSUE THREAD

**Issue by Miesje** [zwave-js/zwave-js-ui#2849]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.6.1.7833cd8

### ZwaveJS version

10.3.1

### Describe the bug

The setpoint and Temperature ID get mixed up.

![image](https://user-images.githubusercontent.com/5450900/208289728-42be541e-aa10-4c02-b262-f94f34442d4c.png)
 

### To Reproduce

Change the SetPoint for a Eurotronic Spirit device then the temperature get altered.
This applies for all Eurotronix devices.

### Expected behavior

The setpoint should be changed and not the temperature

### Additional context

If I see the device ID from the old zwave USB plugin then there is a difference:
The red group have the same ID but the temperature is not included in the same group

![image](https://user-images.githubusercontent.com/5450900/208290411-3c91a450-d5ba-4ff0-b78b-23246c559609.png)

On zwave-js-ui it is different:
![image](https://user-images.githubusercontent.com/5450900/208290018-a7589f83-495c-4211-a225-7f315d317169.png)

**Comment by robertsLando** [comment]
@Miesje What tool is that? Domotics? Jeedom? You should ask for support on those repos before

**Comment by Miesje** [comment]
Dear Lando,

The above screenshot are indeed from domoticz. 
The id's from EuroTronic are not correct because I think that the xml template in JS-UI is not correct.
Thats why I show you the different screenshots in the old way and the JS-UI way.
Zwave-JS-UI creates the ID's and not Domoticz, so the problem should be here I think..

With kind regards,
Miesje

**Comment by robertsLando** [comment]
Did you try to manually fix the discovery template from UI? Once you get how to fix that I could check to fix code. Also what's the deviceId of your thermostat? It's the id you see in control panel when you expand a node
