### ISSUE TITLE
MCO Home MH-S412 switch max associatios

### ISSUE THREAD

**Issue by sebekhtc** [zwave-js/zwave-js-ui#2856]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.6.2

### ZwaveJS version

10.3.1

### Describe the bug

Node Group functions doesnt allow to add more than 3 nodes (indeed it's possible if they are not refreshed)  while the max nodes for group 1 and 2 is 5.

https://devices.zwave-js.io/?jumpTo=0x015f:0x4121:0x1302:0.0

### To Reproduce

try to add more then 3 nodes to group 1 or 2

### Expected behavior

to have max 5 nodes at group 1 or 2

### Additional context

it's possible to add more than 3 if group nodes are not displayed (before refreshing them)

**Comment by robertsLando** [comment]
Could you go to node debug tab and paste here the content please?

**Comment by robertsLando** [comment]
I tried to reproduce your bug without success locally, I have a feel that for some reason you may have an outdated configuration for that device, try to re-interview it please

**Comment by sebekhtc** [comment]
Still the same after re-interview. How to update config files?
![Max Associations_1](https://user-images.githubusercontent.com/5500978/209693569-3fbf3fdc-824c-463a-ab99-96f090a25e5b.png)

**Comment by robertsLando** [comment]
@sebekhtc that `max associations` comes from what I receive from zwave-js so it's not something I can fix on my side. 

If you are running the very last version it should be fixed with a re-interview. 

@blhoward2 any clue on what could be wrong here? has that config file been updated recently?

**Comment by sebekhtc** [comment]
I have the latest versions of zwavejsui and zwavejs (verified latest versions on github). I also found that on github the config file max node is set to correctly to 5. I wonder what is really in the docker.

**Comment by sebekhtc** [comment]
I did reinterview on node 150, below example of the group 1 maximum # of nodes I found in the log (part of the log file attached): 

2022-12-29T13:19:57.946Z DRIVER « [Node 150] [REQ] [ApplicationCommand]
                                  └─[MultiChannelAssociationCCReport]
                                      group id:           1
                                      maximum # of nodes: 3
                                      node ids:           1
                                      endpoints:          166:2, 174:2, 73:2
2022-12-29T13:19:57.952Z CNTRLR « [Node 150] received information for multi channel association group #1:
                                  maximum # of nodes:           3"


[zwave-js-ui-store.zip](https://github.com/zwave-js/zwave-js-ui/files/10321054/zwave-js-ui-store.zip)

**Comment by robertsLando** [comment]
Ok so that's what is reported by the node, no issue on zui...
