### ISSUE TITLE
Security : Cypher mqtt password

### ISSUE THREAD

**Issue by barrydouu** [zwave-js/zwave-js-ui#2857]
**Is your feature request related to a problem? Please describe.**
The configuration file settings.json contains mqtt password as uncypher texte. `"password":"mypasswordhere"`
With the store browsing it's really simple to get it.

**Describe the solution you'd like**
Cypher the password in settings.json. Or perharps add login/password in users.json

**Describe alternatives you've considered**

**Additional context**
I'm using zwave-js-ui 8.6.2 with MQTT (mosquitto) dans domoticz

**Comment by robertsLando** [comment]
Don't you have login enabled in settings?

**Comment by barrydouu** [comment]
Yes I have enable login. 

But it's not a reason for me to store plain text password in configuration file. It's not mandatory, but it's better for security.

**Comment by robertsLando** [comment]
So password should be crypted someway, because it must be reversible when I pass it to mqtt client. 

What I don't like about this is that giving the project is OSS anyone with a miniumun knowladge could take the crypted password and decrypt it. Do you have any suggestions regarding how I could improve security?

**Comment by barrydouu** [comment]
Perharps use crypto module and cypher/uncypher with "SESSION_SECRET" env variable as key ?

**Comment by robertsLando** [comment]
That's not  a problem, I already did it in another project, the problem is if this has some downside or not.

@chrisns opinions on this?

**Comment by robertsLando** [comment]
I created a PR with my idea, need to know if that could be good or not

**Comment by chrisns** [comment]
Closing with conversation and explanation continued in https://github.com/zwave-js/zwave-js-ui/pull/2861
