### ISSUE TITLE
Security : don't allow to download https certificate from store

### ISSUE THREAD

**Issue by barrydouu** [zwave-js/zwave-js-ui#2858]
**Is your feature request related to a problem? Please describe.**
By browsing the store you can download the certificate file (and replace or delete them). It's really simple to stole them.

**Describe the solution you'd like**
Not show those files in store ? Deny downloading/deleting/... ?

**Comment by jmgiaever** [comment]
Uhm, I suggest that you move it outside the store and the issue should be solved. It's a store, with an UI file browser not a vault.

**Comment by barrydouu** [comment]
I know it's not a vault, it's why I suggest this enhancement.
Putting the certificate outside of the store is a good way to do it too. But it's the default location.

Is there a simple way to move it outside of the store ? I use docker image, with a volume for store.

**Comment by robertsLando** [comment]
@barrydouu I suggest to follow @kpine suggestion for this. I could for sure prevent allowing to download them but IMO when you enable login to zui only admins should access it so the problem doens't exists. The store is there to simplify users the handling of all application files without ssh inside it that could be complex for someone

**Comment by barrydouu** [comment]
Yes it's what I'm doing.
I miss it in the documentation. Thank you.

I understand the utility of sotre (and it's great :) ). But I still think it could be a (small) enhancement to protect those files a little more.

**Comment by robertsLando** [comment]
What if someone wants to upload his custom certs using UI explorer for example? I'm quite sure that if I remove them from there there will be someone complainig, while I could agree about security implications, giving that there are alternatives, I prefer to keep it like it is
