### ISSUE TITLE
Feature request: Nightly z-wave heal and/or ping by cronjob 

### ISSUE THREAD

**Issue by f1lint** [zwave-js/zwave-js-ui#2859]
**Is your feature request related to a problem? Please describe.**
My network works quite well but some nodes mark as dead. Manual ping resolving this issue but it's inconvenient

**Describe the solution you'd like**
 It would be nice nightly z-wave heal and/or ping by cronjob as it realize in openhab binding.

**Comment by robertsLando** [comment]
This has been already discussed in the past and doing scheduled heal/pings is not a good practise in general. @AlCalzone What do you suggest here?

**Comment by robertsLando** [comment]
cc @AlCalzone

**Comment by robertsLando** [comment]
A possible solution could be to allow users providing cronjob driver function, in poor words users will be able to set a list of driver functions running using a specified cronjob string, what's your opinion about this @AlCalzone
