### ISSUE TITLE
Please add a `/healthcheck` or `/status` endpoint

### ISSUE THREAD

**Issue by unixorn** [zwave-js/zwave-js-ui#2863]
**Is your feature request related to a problem? Please describe.**

There's not an easy way to monitor the status of zwave-js-ui from an external system like nagios or uptime-kuma. I want my monitoring system to be able to send a notification if zwave-js-ui gets into an unhealthy state instead of noticing because my automations stop working.

**Describe the solution you'd like**

To make monitoring easier, it'd be good to have a `/healthcheck` or `/status` endpoint that reported `HEALTHY` or `UNHEALTHY` so a monitoring system could report issues. Ideally it'd return a json dictionary with one key for health and others describing status items like total number of devices, number of devices with firmware updates, but for the purposes of alerting even a dictionary with a `status` key that shows `HEALTHY` and `UNHEALTHY` would be great.

**Comment by EnochPrime** [comment]
https://zwave-js.github.io/zwave-js-ui/#/guide/healthcheck
