### ISSUE TITLE
FGBS-001, wrong status in MQTT Client start-up

### ISSUE THREAD

**Issue by rezzalex** [zwave-js/zwave-js-ui#2867]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.6.0.f033ee8

### ZwaveJS version

10.3.1

### Describe the bug

My MQTT client (Domoticz) is not showing the right status for my My FGBS001, at start-up.
probably the status is correct in ZwaveJS UI

My NAS is rebooted every day and I run ZwaveJS UI, Mosquitto and Domoticz on separate containers that start automatically.

When just restarting only the Domoticz container, the status remains "open" and is (most probably) not consistent with the status in ZwaveJs-UI.

### To Reproduce

Start the host, then 3 containers (ZwaveJS UI, Mosquitto and Domoticz)
in Domoticz, the device corresponding to the FGBS 001 is shown as open and a couple of seconds after withtout doing anything , to close (correct status)

If restarting only the DZ container, the DZ device will remain "open" and never get back to the correct status.

My workaround is to refresh the Zwave Node value in ZwaveJS, 

### Expected behavior

Having directly the correct status at start-up

**Comment by robertsLando** [comment]
Domoticz uses mqtt, if the status is correct on zui but not on domotics it means mqtt isn't connected or broker is down

**Comment by rezzalex** [comment]
but all others devices are correct, on DZ and ZUI sides....

**Comment by robertsLando** [comment]
> probably the status is correct in ZwaveJS UI

COuld you verify this?

**Comment by robertsLando** [comment]
>  the device status is CORRECT in ZUI and stay "wrong in DZ"...

And if you connect to broker using mqtt explorer does the status is correct?

**Comment by rezzalex** [comment]
Hello.
First time this morning that the problematic device did change status at start-up. I don't know why, I did not change anything....
Could it helps that I have just noticed that my lights have a status "off" at DZ container start-up, even if the light was already ON ?

**Comment by robertsLando** [comment]
This is hard to debug without testing on your side. You have to know at least how MQTT works, when a value changes on zwave I get an event on zui and I will publish a retained message to the valueId topic with the value. This means that when Domioticz connects to the broker and subscribes to that valueId it will always receive latest value sent to that topic, if you see the correct value on zui it means that it also sent the value to MQTT broker so the problem could be that for some reason Zui or DZ is not connected to broker or DM is not picking up the value on connection for some reason.
