### ISSUE TITLE
Incorrect device classes and measurement units now a problem with HA 2023.1.1

### ISSUE THREAD

**Issue by adwuk** [zwave-js/zwave-js-ui#2877]
### Version

Build/Run method:

[ ] Docker
[ ] Git Clone + yarn install + yarn run build + yarn start
[x ] Pkg

Z-Wave JS UI version: **[8.6.2]**
Z-Wave JS version: **[10.3.1]**

### Describe the bug

HA 2023.1.1 now complains when device entities report incorrect units for their defined device class.  I have manually edited the HA discovery JSON for the offending devices within Z-Wave JS UI and forced an MQTT rediscovery.  These changes have cured my errors.

The changes I made are as follows:

1. Fibaro Single Switch 2 (FGS213), Dimmer 2 (FGD212), Wall Plug UK (FGWPG-111), Double Switch 2 (FGS223) - electric_kwh_value_[12] needs a device class of energy, not power:

`"device_class": "energy", "unit_of_measurement": "kWh",`

2. AEON Labs Multisensor 6 (ZW100) - illuminance needs unit_of_measurement of 'lx', not 'Lux':

`"device_class": "illuminance", "unit_of_measurement": "lx",`

3. AEON Labs SmartSwitch 6 (ZW096) - v_value needs a device class of 'voltage' not 'power', a_value needs a device class of 'current' not 'power and kwh_value needs a device class of 'energy 'not 'power':

`"device_class": "energy", "unit_of_measurement": "kWh",`
`"device_class": "voltage", "unit_of_measurement": "V",`
`"device_class": "current", "unit_of_measurement": "A",`

I'd be happy to make the change if someone wants to point me in the right direction, if that is quicker/easier.

**Comment by adwuk** [comment]
From a first scan of the code, are all electricity based sensors being given a device_class of 'power' (lib/Constants.ts lines 189-198)?  If my understanding is correct then a fix here would address most of the above errors.

**Comment by robertsLando** [comment]
@adwuk would you like to submit a PR for that? So you can also check if the fix works for you

**Comment by adwuk** [comment]
@robertsLando I have created a PR which fixes most of the above issue.  I tried to do the same for the unit_of_measurement for illuminance sensors that report 'Lux' instead of 'lx' but it didn't seem to be working.  Any clues as to where to look for that?

**Comment by robertsLando** [comment]
Hi @adwuk, thanks for your PR. About the lux bug did you tried to add `unit_of_measurement` to props here: https://github.com/zwave-js/zwave-js-ui/blob/master/lib/Constants.ts#L186 ?

**Comment by adwuk** [comment]
@robertsLando yes I tried modifying that, and had to add to https://github.com/zwave-js/zwave-js-ui/blob/master/lib/Constants.ts#L19, but I am guessing that it is overridden somewhere else in the code. Does the device report units of measurement for the sensor, and does that override the value in Contants.ts?

**Comment by robertsLando** [comment]
> Does the device report units of measurement for the sensor, and does that override the value in Contants.ts?

Humm yeah: https://github.com/zwave-js/zwave-js-ui/blob/master/lib/Gateway.ts#L1534

You should move that line above this one: https://github.com/zwave-js/zwave-js-ui/blob/master/lib/Gateway.ts#L1531

**Comment by adwuk** [comment]
Thanks. That seems to have done the trick. I will submit as a separate PR.

**Comment by robertsLando** [comment]
@adwuk add it to the already open PR please, will merge it after you do that :)

**Comment by adwuk** [comment]
OK - done. Thanks for your help Daniel.

**Comment by robertsLando** [comment]
Thanks to you for the PR 🙏🏼
