### ISSUE TITLE
Reporting issues for QUBINO Smart Plug 16A - ZMNHYD1

### ISSUE THREAD

**Issue by jfhautenauven** [zwave-js/zwave-js-ui#2878]
Version
Build/Run method:

[ ] Docker
[ ] Git Clone + yarn install + yarn run build + yarn start
[x ] Pkg

Z-Wave JS UI version: [8.6.2]
Z-Wave JS version: [10.3.1]

Describe the bug
I see that for my device, which is a QUBINO Smart Plug 16A, running firmware 41.10 (latest to date), the reporting of the power consumption (kWh) is not getting reported correctly inside the UI, nor on MQTT. The value is supposed to be sent by the device everytime there is an increment of 0.1 kWh measured by the plug. I get correct updates for Watts and Amperes consummed.

if I press the "refresh" button when I get inside ZwaveJS UI, under the device tab / nodes / meter v4, the correct value is then refreshed and I can see there kWh increment.
I have to do this manually each time I want the value refreshed, seems like it is not refreshed automatically.
I checked the configs possible for the device, there is no parameter available to configure that.
The documentation of manufacturer says the value will be sent to the controller each time the kWh value increases by 0.1 kWh.
Value comes from COMMAND_CLASS_METER_V4 .

Not sure at this stage this is an issue from ZwaveJS / UI but I post the issue here in hope maybe a solution can be found.

Sadly I see no way to add manual polling on that value at the moment (I have already tried for other equipments to poll some values, for example, for fibaro roller shutter modules when the position was not refreshing quick enough for my taste but for the Qubino, that "hack" isn't even possible).

Also noting that ready the documentation, there are other possible configuration values exposed by the manufacturer, such as the possibility on the latest firmware to enable or disable the ondevice LED, but I don't see these in the parameters.

Should this be useful, here is the possible configs given by the manufacturer (see end of document).
https://qubino.com/wp-content/uploads/2019/04/Qubino_Smart-Plug-16A-PLUS-extended-manual_eng_2.6.pdf

I don't know if there is a place where configurations can be posted.
I understand tough that some commands are available or not based on firmware version ... so maybe that the reason the extra commands are not displayed in ZwaveJS UI ... 

For the rest, very pleased of the software, I hope someone can help with the issue :) 

Best regards,

JF

**Comment by jfhautenauven** [comment]
Long story short : 

Been battling the damn thing one extra time.

Tried : 
- reinterview node : ineffective
- changing parameters for power reporting threshold : ineffective

What solved it : 
- unplugged the thing from the wall and replug it after waiting 15 seconds

At this stage I'm pretty sure it comes from the device itself and not from Zwave JS UI.
I see the messages now being spontaneously transmitted from the plug to the controller.

What caused it : probable firmware glitch when I hit the button "reset accumulated values", which I guess needs then afterwards a "unplug/replug" action of the device. Never had that with fibaro ... so I guess it's a "feature" from the Qubino firmware :) 

Issue can be closed. I hope it may help someone some day reading this :) 

Cheers,

**Comment by jfhautenauven** [comment]
Manufacturer gave feedback and sent Firmware 41.11 to fix the issue I had encountered. :) Just to let people know if they encounter the same symptoms :)

**Comment by robertsLando** [comment]
Sorry for late reply @jfhautenauven, glad you fixed your issue :)
