### ISSUE TITLE
Cant enable/disable columns on mobile edge browser

### ISSUE THREAD

**Issue by ryanwinter** [zwave-js/zwave-js-ui#2890]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Z-Wave JS UI version

8.7.0

### ZwaveJS version

10.3.1

### Describe the bug

On the mobile edge browser, if I attempt to enable/disable columns in the UI view, it fails. It appears to be attempting to reorder the columns instead.

### To Reproduce

1. Access the zwave js ui from the mobile edge browser
2. Press the `COLUMNS` button to enter column editing mode
3. Attempt to disable one of the columns
4. Observe the column can't be disabled

### Expected behavior

Expect that columns can be enabled and disabled in the column editor.

**Comment by robertsLando** [comment]
Unfortunatrely I have no way to test this, does dragging columns woks?

**Comment by ryanwinter** [comment]
Yes columns dragging works. Actually that seems to be the problem, it looks like it's entering drag mode, even though I'm not using the drag handle.

I tested this with the chrome mobile browser and saw the same issue.

**Comment by robertsLando** [comment]
I moved the handle to just include the button and not the entire checkbox. Check with new version (plan to release it later today) and feel free to reopen this if not fixed

**Comment by ryanwinter** [comment]
Thanks! Works for me.

**Comment by robertsLando** [comment]
Thanks for the feedback
