### ISSUE TITLE
Add different icon for S2 vs S0 security in UI

### ISSUE THREAD

**Issue by mitchcapper** [zwave-js/zwave-js-ui#2894]
**Is your feature request related to a problem? Please describe.**
There are some important differences in traffic load and who can talk to who with s2 vs s0, while you can hover over a node to see if it is s2 or s0 it is a bit more of a hassle.

**Describe the solution you'd like**
Change the S2 icon from the S0 icon, we already have ZWAVE Plus version nodes could do something like that of 0 in a circle or 2 in a circle.

**Describe alternatives you've considered**
Hovering over a node works,  exporting a json dump and using a 3rd party filter works,  but natively I don't see a reason not to surface in the normal UI.

**Additional context**

**Comment by mitchcapper** [comment]
I am happy to do this PR as well just wanted to make sure it was something desired before I did so.

**Comment by robertsLando** [comment]
@mitchcapper Yeah feel free to do a PR if you wish, alternatively I can do this in next days or even today If I find the time

**Comment by robertsLando** [comment]
I used a different color for s0 security (orange), using green color for the s2
