### ISSUE TITLE
Last Seen field for monitoring battery devices?

### ISSUE THREAD

**Issue by jpoeppelman1** [zwave-js/zwave-js-ui#2896]
The zigbee2mqtt integration has a last_seen field that is updated based on the last inbound signal from the device.  Can we get the same for zwave-js-ui?  If so, then users would have the ability to standardize our Node Red approach when monitoring battery devices that stopped communicating to the z-stick.   I'm aware of the node_status entity populated in HA, but I want to know exactly the last time a device has communicated with the z-stick.   FYI - the HA last_update and last_changed fields populate on HA restart so they are useless.

**Comment by robertsLando** [comment]
It's already there:

![Schermata da 2023-01-20 11-39-12](https://user-images.githubusercontent.com/11502495/213675783-a83f3022-df50-4e54-9c4e-ec18af909948.png)

Is your request about publishing it to mqtt?

**Comment by jpoeppelman1** [comment]
> It's already there:
> 
> ![Schermata da 2023-01-20 11-39-12](https://user-images.githubusercontent.com/11502495/213675783-a83f3022-df50-4e54-9c4e-ec18af909948.png)
> 
> Is your request about publishing it to mqtt?

Yes, that is my request.  Looks like you added it, thank you!

**Comment by robertsLando** [comment]
Wait for next release or use master tag in case you are using docker

**Comment by jpoeppelman1** [comment]
I tried this out today, but I'm not seeing the new field (i.e. last_active) pass to HA as an attribute?  I know you don't manage HA code base, but shouldn't this automatically populate as an attribute on the device when viewing in Node Red?  The zigbee2mqtt integration populates last_seen as an attribute so wondering if we could do the same under zwavejs-ui?

**Comment by robertsLando** [comment]
I don't pass anything to hass, I'm even not awere how this could be done? Do you have some docs about mqtt discovery?

**Comment by jpoeppelman1** [comment]
> I don't pass anything to hass, I'm even not awere how this could be done? Do you have some docs about mqtt discovery?

Here is the info about MQTT discovery.  I'm using the HASS ZwaveJS integration which connects to your app using websockets.  I'd imagine there is a discovery message you could send that would setup the attribute?

https://www.home-assistant.io/integrations/mqtt/

**Comment by robertsLando** [comment]
> I'm using the HASS ZwaveJS integration which connects to your app using websockets.

Zwave-js integration isn't managed by me, you should open an issue on HA core repo for that.

**Comment by jpoeppelman1** [comment]
I noticed when the container is restarted, battery devices display "Never" under Last Active field.  Is there a way to persist the last active field value upon a restart so there is no data loss?

**Comment by robertsLando** [comment]
There is an open issue on zwave-js repo for that. Need to wait for that, @AlCalzone do you have a reference to that issue, cannot find it on zwave-js repo?

**Comment by AlCalzone** [comment]
https://github.com/zwave-js/node-zwave-js/issues/1608 and https://github.com/zwave-js/node-zwave-js/issues/985
