### ISSUE TITLE
Ability to compare two devices configuration

### ISSUE THREAD

**Issue by barrydouu** [zwave-js/zwave-js-ui#2897]
**Is your feature request related to a problem? Please describe.**
When adding a new device (with a lot of parameters), I want an easy way to compare the configuration of the new device with an existing one. 
To illustrate, when I motorized my curtains, it takes me long time to find the good parameters for the first one. Then, when I motorized the second one, I cannot compare value of the new one, with the old one easily. (I took a sheet of paper, write everything for the reference, and then compare with the new one).

**Describe the solution you'd like**
In the control panel, if I select to devices with the same product code, it activates a "compare" button.
When I hit compare button, I have a screen showing me on left all the values of the first selected, on the right, all the values of the second selected.
Cherry on the cake, add the hability to modify configuration of the first or second one directly from this screen

**Describe alternatives you've considered**
Keep my sheet of paper and my pen :)

**Comment by robertsLando** [comment]
For such things there is a snippet that you can call from Advanced Dialog > Driver Function, it's called clone config and allows to copy configurations from a node to another, just edit it with the nodes ids of the source and targets :) 

![Schermata da 2023-01-20 11-36-46](https://user-images.githubusercontent.com/11502495/213675360-4ac97c20-8746-4883-9f1a-cb66d221537a.png)

**Comment by barrydouu** [comment]
How great funtion. Thank's for the tip. Never search here ^^

What about a compare function ? It could be interesting for debugging. Sometimes, setting new value is not really taken (or all the values are not set), especially with battery device that need to be wake up.

**Comment by robertsLando** [comment]
> What about a compare function ? It could be interesting for debugging

You can do what you want :)
