### ISSUE TITLE
Scrollbars are so narrow they are nigh impossible to use as scrollbars

### ISSUE THREAD

**Issue by warthog9** [zwave-js/zwave-js-ui#2899]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Z-Wave JS UI version

8.6.3.c9cabbb

### ZwaveJS version

10.3.1

### Describe the bug

Scrollbars, as currently rendered, are so incredibly narrow they are not only hard to see, but nearly impossible to actually click on and drag around.  This presents a dramatically harder user interaction when you don't have a scroll wheel, a touchpad to multi-finger scroll, or a touch screen to just drag around.

Please consider making the scrollbars wider to help accessibility and those of us not prone to the same screen interactions the current design expects.

![image](https://user-images.githubusercontent.com/2334704/213653335-c3103a5f-422a-4daa-877b-917b9d7c63f2.png)

### To Reproduce

look to scrollbar, attempt to click on and drag scrollbar itself.

### Expected behavior

wider scrollbar (or leaving the native scroll bar as is) to allow for typical user interaction in moving up and down on the screen without some additional means of doing so, or relying on the keyboard for up/down pgup/pgdn movement

**Comment by robertsLando** [comment]
I have doubled them now, wait for next release :)
