### ISSUE TITLE
Add Create Virtual Device Option

### ISSUE THREAD

**Issue by Inshakoor** [zwave-js/zwave-js-ui#2903]
It would be really helpful to be able to create a virtual device so that it can be controlled via MQTT. 

For example, create a virtual device called Great Room. When Great Room triggers on via MQTT, it turns on 3 physical switches from Node-Red. Once Great Room is turned off, it turns off the same 3 physical switches and triggers another physical switch to turn on under cabinet lights. 

Thank you for this awesome utility!!

**Comment by robertsLando** [comment]
Hi @Inshakoor, I think this goes a bit off the scope of this project. BTW you could use scheduled jobs for such purposes
