### ISSUE TITLE
Release 8.7.0 is tagged but is not a release

### ISSUE THREAD

**Issue by Krakinou** [zwave-js/zwave-js-ui#2904]
Hello,
I'm using `https://api.github.com/repos/zwave-js/zwave-js-ui/releases` to get list of zwave-js-ui releases and automagically update the packaged version I've done for [Yunohost](https://github.com/YunoHost-Apps/zwave-js-ui_ynh)

It seems that 8.7.0 was not published as a release but only as a tag as the last version available is 8.6.3.
I'm not very familiar with these options and what is the difference between both, but I can see that:
- The version is visible in  `https://api.github.com/repos/zwave-js/zwave-js-ui/tags`but not  `https://api.github.com/repos/zwave-js/zwave-js-ui/releases`
- Same for `https://github.com/zwave-js/zwave-js-ui/releases` and `https://github.com/zwave-js/zwave-js-ui/tags`

Thanks

**Comment by robertsLando** [comment]
https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.7.0

**Comment by robertsLando** [comment]
That's sooo strange, could it be a GH issue??

**Comment by robertsLando** [comment]
Seems that 8.8.0 is listed correctly, no clue 🤷🏼‍♂️

**Comment by robertsLando** [comment]
Seems same happened with zwave-js 10.4.0 release so it's definetly a bug on GH

**Comment by robertsLando** [comment]
Should be listed now BTW
