### ISSUE TITLE
Filter OTA/OTW file uploads by extension

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js-ui#2915]
**Is your feature request related to a problem? Please describe.**

The OTA and OTW file upload dialogs currently don't specify any file types, so the dialog shows all files `*.*`.

![image](https://user-images.githubusercontent.com/791794/215031136-73d7cff0-f96e-4be8-8c36-8058771f9e8e.png)

This clutters the selection on a PC browser, since only certain file extensions are actually valid, but all files are shown. It would be preferable to filter to the relevant files to make it easier to find them and help prevent choosing incorrect files accidentally.

Use case: click a download link on a vendor site to get firmware, and usually it goes into my "Downloads" directory, which probably has a hundred or more files.

**Describe the solution you'd like**

Set the [unique file type specifiers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers) of the upload dialog to filter for only the relevant firmware file extensions. I think that's done with the [Accept](https://vuetifyjs.com/en/components/file-inputs/#accept) attribute.

Suggestions:

* End devices. This is the list of all firmware file extensions [supported](https://github.com/zwave-js/node-zwave-js/blob/c5973fa3a1978d64e2116d97a24b85076b1d8bab/packages/core/src/util/firmware.ts#L28-L49) by Z-Wave JS.
  * `.bin`
  * `.exe`
  * `.ex_`
  * `.hex`
  * `.ota`
  * `.otz`
  * `.gbl`
  * `.hec`
* Controllers:
  * `.gbl`
  * `.otz`

I don't know whether all of those formats above are valid for 500-series controllers. Maybe `.ota` and `.hex` also are, but I don't think they all are.

Bonus points for filtering based on the SDK of the target. For SDKs >= 7, only accept `.gbl`. But a static list of all the above would be a nice improvement.

**Describe alternatives you've considered**

None.

**Additional context**

A user can always switch to the "all" filter if needed. Browsers choose whether to honor the attribute or not and how to present it. It doesn't seem to have any effect on mobile Firefox, for example.

**Comment by robertsLando** [comment]
@AlCalzone do you agree about the file extensions? are there any else or less?

**Comment by AlCalzone** [comment]
Add hex (and maybe ota, not sure) for controllers, the rest is good.
