### ISSUE TITLE
Change Security Association

### ISSUE THREAD

**Issue by candrea77** [zwave-js/zwave-js-ui#2918]
I've got some devices that are included without any kind of security , and some other (same brand / model / firmware) that are included using S0 (with is better that nothing)

Is there a way to (let me say) double check again the device security feature , in order to force them communicate with the highest security possibile, without exclude and include it again ?

**Comment by webmogul1** [comment]
Try re-interviewing the device checking "reset security classes"

**Comment by candrea77** [comment]
Unfortunately ..... already tried this multiple times with different
devices..... but it does not work.


Just to undesrstand better : are you telling me that "reset security
classes" is provided for this exact reason ?





Il Sab 28 Gen 2023, 17:38 webmogul1 ***@***.***> ha scritto:

**Comment by candrea77** [comment]
> _If you want to change the security class, but don't want to lose the node ID, then you can: ..... omississ....._

Ok, that's exactly what I'm doing.
Thank you all for giving all the details!!!
