### ISSUE TITLE
MQTT Docs 

### ISSUE THREAD

**Issue by patricker** [zwave-js/zwave-js-ui#2924]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.8.2

### ZwaveJS version

10.5.4

### Describe the bug

I tried following the docs to `set` values via MQTT, but nothing would work.
I was migrating over from ZWave2MQTT and was a little frustrated that Z-Wave JS used a different format... except it doesn't. Only the docs say it does.

The docs say to send JSON, like this:
```
zwave/office/test/38/0/targetValue/set
{
    "value": 100
}
```

But if you look at the Example video, which I didn't look at until after I figured out you were just supposed to send the value, it shows the correct way, just like how we did it back in ZWave2MQTT.

Also, if you look at the JSON generated for Home Assistant (I am not using Home Assistant), you can see how it tells HA to call it, and those are correct. It's just a docs issue.

### To Reproduce

Try following the docs method of calling `set` via MQTT: https://zwave-js.github.io/zwave-js-ui/#/guide/mqtt?id=set-values

### Expected behavior

The docs provide a working method.

**Comment by patricker** [comment]
I'm using 0-99, and couldn't get it to work in the json style as shown in the docs

**Comment by robertsLando** [comment]
> But if you look at the Example video, which I didn't look at until after I figured out you were just supposed to send the value, it shows the correct way, just like how we did it back in ZWave2MQTT.

It work in both ways, it accepts both JSON and raw value formats: https://github.com/zwave-js/zwave-js-ui/blob/master/lib/MqttClient.ts#L508-L516

By default I suggest JSON just because you can also add set value options if needed

**Comment by patricker** [comment]
Hmm. I was testing with Node-Red. Is there a different tool I should use to make sure json is working for me?

**Comment by robertsLando** [comment]
[mqtt-explorer](http://mqtt-explorer.com/)
