### ISSUE TITLE
Error after updating to 1.6.1

### ISSUE THREAD

**Issue by yodashut** [zwave-js/zwave-js-ui#2927]
I am running Zwave-JS-ui 1.6.0.  When I updated to 1.6.1, the web ui for zwave JS would not load.  
From there, when I went into the addon and restarted it, I got the following error:

Failed to restart add-on
Can't create container from addon_a0d7b954_zwavejs2mqtt: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_a0d7b954_zwavejs2mqtt: Conflict ("Conflict. The container name "/addon_a0d7b954_zwavejs2mqtt" is already in use by container "d89bb24c3664f92612dfa237f5c993e29b78471954149c6f513c4e8a176d049d". You have to remove (or rename) that container to be able to reuse that name.")

I was able to restore 1.6.0 from backup and all is working well again.

Any ideas on how to keep this from happening when I upgrade?

**Comment by robertsLando** [comment]
I think the error is self explained but I dunno what could cause that as I don't maintain the addon, @frenck could you help here?

**Comment by frenck** [comment]
The Docker images for the add-on are hosted on the GitHub container registry. They had a service outage last night, causing these errors. GitHub has restored its services. Everything should be normal again.

../Frenck
