### ISSUE TITLE
missing parameter in NorthQ NQ-9121 gas reader

### ISSUE THREAD

**Issue by herm42** [zwave-js/zwave-js-ui#2930]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
There is a wrong device parameter which causes problems on domoticz side
What do you observe?
The "NorthQ gas meter" NQ-9121 is not handled correctly
What did you expect to happen?
autodetection should work
  
![image](https://user-images.githubusercontent.com/6725469/211738524-75d77d60-7a32-4cd3-a3e2-3310ccc9ad36.png)

there is a missing parameter in the discovery_payload which causes problems on ha/domoticz side not corectly autodetect the device.

 would suggest do add "device_class": "gas",

"discovery_payload": {
    "value_template": "{{ value_json.value }}",
    "unit_of_measurement": "Cubic meters",
    **"device_class": "gas",**
    "icon": "mdi:thought-bubble",
    "state_topic": "zwave/87/50/0/value/131073",
    "json_attributes_topic": "zwave/87/50/0/value/131073",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xe9a1d9f4_node87"
      ],
      "manufacturer": "NorthQ",
      "model": "NorthQ Gas Meter (NQ-9121)",
      "name": "Erdgas",
      "sw_version": "3.30"
    }

... but i'm not sure where this information is stored ...

### Device information

Manufacturer: 
Model name: 
Node ID in your network: 

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [X] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 10.3.1
`zwave-js-ui` branch: 8.6.3

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

-

**Comment by AlCalzone** [comment]
This is not a driver issue, but with the MQTT discovery

**Comment by herm42** [comment]
not sure if this is related, but domoticz receives only integer updates .... is there a way do send float instead of integer.

![image](https://user-images.githubusercontent.com/6725469/215794492-bd2b668b-080c-46c7-8f4c-956ae0673fb9.png)

![image](https://user-images.githubusercontent.com/6725469/215795154-5520bcc3-6890-4fd6-b4a7-f600ffa9135b.png)

**Comment by robertsLando** [comment]
This is something to ask to domoticz devs, I send the same value you see in ui

**Comment by herm42** [comment]
thx ... will ask them again
