### ISSUE TITLE
Failed to execute controller command after 1/3 attempts

### ISSUE THREAD

**Issue by jriker1** [zwave-js/zwave-js-ui#2942]
If i was getting the error in the subject on Windows 2022 with the Hyper-V role in the logs plus delays in responsiveness, and now I am not (going to be sorry I said that) was there something between release 8.8.0 and 8.8.3 that would have made a difference?

**Comment by jriker1** [comment]
Nevermind still broken just ran a couple days without failing.

**Comment by robertsLando** [comment]
What stick are you using? Are you using an extension usb cable?

**Comment by jriker1** [comment]
It is an Aerotec Z-Stick Gen5 with firmware 1.2.  It worked fine originally for years.  I have recently moved my HA environment, which I don't think is relevant to a new Hyper-V virtual and setup the Z-Wave components with your install on the Windows 2022 server with Hyper-V host.  After moving from a Linux virtual on VMware workstation to this started having issues.  Sometimes will work for a day sometimes a couple hours before devices respond slowly or not at all and the interface in Home Assistant stop displaying the status of things like lights.  Removing the stick and putting it back in or rebooting helps for a short period.  From what I understand the thought is it is related to this:

https://github.com/zwave-js/node-zwave-js/issues/5024

Thought the last update here fixed it as I went from:

**Comment by robertsLando** [comment]
@AlCalzone any updates on https://github.com/zwave-js/node-zwave-js/issues/5024 ?

**Comment by AlCalzone** [comment]
Nothing new. This is a bad interaction between the `serialport` library on Windows and something else, possibly `xstate`.

**Comment by jriker1** [comment]
If we are talking about my logs not sure but ZWave-JS UI is running on the host and it's known to my dislike that Hyper-V doesn't passthrough USB ports.  Not even an option to select one in the admin screens.

**Comment by jriker1** [comment]
Note I changed some settings in the gui like Disable DNS Discovery, disabled statistics, and disabled soft reset.  Saw this on some posts.  System ran for a couple days and then started acting up again. 

Note the stick still shows in device manager

![image](https://user-images.githubusercontent.com/1495536/217566750-fe8f30a0-512e-4212-9ee4-bf82874a2b80.png)

And the stick is still functioning just slow however no data being reported back to HA.  So Alexa again can turn lights on and off just slow to reply.
