### ISSUE TITLE
Missing "state_class" in HA MQTT discovery

### ISSUE THREAD

**Issue by opensource-alt** [zwave-js/zwave-js-ui#2943]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Didabling ZWaveJS HA WS Server integration and relying only on MQTT with automatic discovery breaks the statistic recordings on HA

What do you observe?
Missing energy statistics on HA

What did you expect to happen?
Have the statistics active with MQTT discovery only

  1. Have any ZWave device pith power metering
  2. Disable ZWaveJS WS HA integration and only rely on MQTT with automatic discovery
  3. On HA: the statistics are missing (because not recorded any more)

To fix it: the sensors related to class "enegy" sould have the additionnal attribute (maybe if applicable, fixed the issue on my side by modifying the default MQTT discovery message and adding the "state_class" attribute tu the JSON message and then resend the MQTT discovery):
    "state_class": "total_increasing",

### Device information

Manufacturer: Shenzhen Neo Electronics Co., Ltd.
Model name: NAS-WR01Z
Node ID in your network: Multiple, 2, 4, 5, 9 and 25

Manufacturer: Fibargroup
Model name: FGS223
Node ID in your network: 24

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Did you change anything?

yes (please describe)

### If yes, what did you change?

To fix the issue, I added
    "state_class": "total_increasing",
to the related sensons.

### Did this work before?

Yes (please describe)

### If yes, where did it work?

I guess the issue is only related to the MQTT only setup I now use. Never had this issue when WS HA server was active.

### Attach Driver Logfile

Discovery issue. Upgrades seems to redo the JSON updade on all related sensors.

For device 3 for example, had to change the default
{
  "type": "sensor",
  "object_id": "electric_kwh_value",
  "discovery_payload": {
    "value_template": "{{ value_json.value }}",
    "unit_of_measurement": "kWh",
    "device_class": "energy",
    "state_topic": "zwave/prise_ender3/50/0/value/65537",
    "json_attributes_topic": "zwave/prise_ender3/50/0/value/65537",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xe504565f_node2"
      ],
      "manufacturer": "Shenzhen Neo Electronics Co., Ltd.",
      "model": "Wall Plug Switch (NAS-WR01Z)",
      "name": "prise_ender3",
      "sw_version": "3.94"
    },
    "name": "prise_ender3_electric_kwh_value",
    "unique_id": "zwavejs2mqtt_0xe504565f_2-50-0-value-65537"
  },
  "discoveryTopic": "sensor/prise_ender3/electric_kwh_value/config",
  "values": [
    "50-0-value-65537"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_electric_kwh_value"
}

with

{
  "type": "sensor",
  "object_id": "electric_kwh_value",
  "discovery_payload": {
    "value_template": "{{ value_json.value }}",
    "unit_of_measurement": "kWh",
    "device_class": "energy",
    "state_topic": "zwave/prise_ender3/50/0/value/65537",
    "state_class": "total_increasing",
    "json_attributes_topic": "zwave/prise_ender3/50/0/value/65537",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xe504565f_node2"
      ],
      "manufacturer": "Shenzhen Neo Electronics Co., Ltd.",
      "model": "Wall Plug Switch (NAS-WR01Z)",
      "name": "prise_ender3",
      "sw_version": "3.94"
    },
    "name": "prise_ender3_electric_kwh_value",
    "unique_id": "zwavejs2mqtt_0xe504565f_2-50-0-value-65537"
  },
  "discoveryTopic": "sensor/prise_ender3/electric_kwh_value/config",
  "values": [
    "50-0-value-65537"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_electric_kwh_value"
}

**Comment by robertsLando** [comment]
Hi @opensource-alt , thanks for your issue, are you able to fix this your own in a PR so you can also test it? I could help you identify the lines and the changes to do

**Comment by opensource-alt** [comment]
Hello. I checked yesterday and today again inside the zwavejs container (I'm pulling zwavejs/zwavejs2mqtt:latest, using some "grep -R" commands) and I wasn't able to find the files building the JSON for MQTT discovery.
I confirm the container upgrade (had a new version today) removed the manual update in the UI.
It's probably genarated using template system somewhere.

I'll check if I'm able to have a working way to patch the file you gave me using container overrides.

**Comment by opensource-alt** [comment]
I'm unsure the file you gave me could be the starting point of a fix (and also I'm not an expert of nodejs :-) ).
Maybe in ./server/lib/Constants.js , function meterType(ccSpecific, configManager)
But it's first required to know if it's appropriate to add the missing class (and also it will be required to define it. It's a map so we just have to add it?). "energy" class is always a cumulative total? If yes, it could be pathced here. If not, the device database require additionnal information first.

**Comment by robertsLando** [comment]
Just try to add: 

```
"state_class": "total_increasing"
```

Below this line: 

https://github.com/zwave-js/zwave-js-ui/blob/d091834ad7512bf9be2b6c99051dcd09b6b8a864/lib/Constants.ts#L137

**Comment by opensource-alt** [comment]
PR https://github.com/zwave-js/zwave-js-ui/pull/2953
In docker container: works when patched the file server/lib/Constants.js / no change when updated lib/Constants.js
I didn't check the file origin using the Docker build process...

**Comment by robertsLando** [comment]
Thanks 🙏🏼
