### ISSUE TITLE
File editor in store does not handle long lines correctly on narrow screens

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js-ui#2945]
They get wrapped, but the line counter increases:
![grafik](https://user-images.githubusercontent.com/17641229/217022043-b13e9db6-3fa2-4e6d-a561-7a5d13160634.png)
(the highlighted text is actually part of line 47)

and at the end, some line numbers are missing due to this: 
![grafik](https://user-images.githubusercontent.com/17641229/217022444-8252909a-e57e-4613-b6af-cb0a7a220337.png)

When I make the screen wider, this does not happen:
![grafik](https://user-images.githubusercontent.com/17641229/217022571-41abb8b0-8c1c-44b1-ae21-d4ae9c0426c0.png)

**Comment by robertsLando** [comment]
This could be an issue with primsjs, I could try to upgrade it to latest

**Comment by robertsLando** [comment]
https://github.com/koca/vue-prism-editor/issues/87
