### ISSUE TITLE
Health Checks and Corrective actions

### ISSUE THREAD

**Issue by Hooverjc** [zwave-js/zwave-js-ui#2955]
I've read the documentation available on Health Checks, but i'm a bit confused when I run them why i'm getting the results I do despite everything working as expected from a network perspective:

![HC](https://user-images.githubusercontent.com/42452872/217903024-14525601-240f-45fb-9a16-703691100aad.png)

I've been troubleshooting some devices on the edge of my network that are occasionally dropping dead and revive with a ping or come back to life without intervention moments later (error "Failed to send the command after 3 attempts (Status NoAck) (ZW0204)"). I have 50+ devices total, most are 700 series with about 1/3 still 500. I started doing some connection testing nearest to my controller and then working my way out. The device above has 28 neighbors and is one hop away from the controller and the above screenshot is what I see. Is this indicative of a bad connection to the controller or bad routes between the controller and the device. I know I can't do much except heal the devices in question, but no amount of healing results in improvement in this respect. 

I don't recall seeing so many ping failures on health check previously, so maybe this is a bug or something, but wanted to check in case I was missing something and infarct do have my own local issue. really, any advice/clarity that can be provided regarding the topic of zwave and improving mesh health would be greatly appreciated.

Edit: I also did want to call out I do see the pings are rated directionally (from controller to node and the back from node to controller). just kinda wondering if this isn't why some of the ACK errors are coming up, the device is getting the command, but the responses are often timing out.

**Comment by robertsLando** [comment]
Based on the results seems controller has a good connection with device but not viceversa, I'm not an expert in trebleshooting such issues so I let @AlCalzone answer to you. Do you have an usb extension cable for your stick? That could improve network connectivity a lot

**Comment by Hooverjc** [comment]
> Based on the results seems controller has a good connection with device but not viceversa, I'm not an expert in trebleshooting such issues so I let @AlCalzone answer to you. Do you have an usb extension cable for your stick? That could improve network connectivity a lot

Thanks for the response. Yes, it is on an extension already and that did help when I did it originally. This issue specifically seems to be related to the fact that while this device can be controlled by the controller, and the mesh is confirming that its connected directly, its not able to respond directly, so I question why its not attempting to utilize other routes when the replies are failing or even removing the direct route all together. This isn't the only node I have in a similar situation, so using the principle of fixing issues closest to the controller, this seems like an issue to me:

![image](https://user-images.githubusercontent.com/42452872/218154334-3351bd99-7c39-4d76-aeff-727ad109d5a1.png)

I see there is possibly some discussion going on with this issue on the zwave base software, so i'll check that out and see if I can contribute at all there too.

**Comment by robertsLando** [comment]
>  so I question why its not attempting to utilize other routes when the replies are failing or even removing the direct route all together

I really have no clue why this happens but it's something related to driver, not zui. I suggest to follow the other issue, feel free to reopen this one if needed and I will move the conversation to zwave-js repo
