### ISSUE TITLE
MQTT Discovery complete support for Philio PSE04

### ISSUE THREAD

**Issue by MuadDibVV** [zwave-js/zwave-js-ui#2964]
### Version : 

Build/Run method:

[X ] Docker
[ ] Git Clone + yarn install + yarn run build + yarn start
[ ] Pkg

Z-Wave JS UI version: 8.8.4.4f4cd65
Z-Wave JS version: 10.7.0

### Describe the bug

Hello, my device Philio PSE04 (Multiple sound siren) is well recognized with Z-wave JS (except some minor problem `Driver: Sound Switch: "volume" is not a supported property (ZW0322)`), but the main switch ([XX-121-0-toneId] Play Tone) is not available in the MQTT AD config and then I can't use MQTT to command my Siren (I can only use it manualy with Z-Wave JS UI (so my siren is useless).
Is is possible to add this discovery ?

Thanks

**Comment by robertsLando** [comment]
Are you using it with home assistant or domoticz?

**Comment by MuadDibVV** [comment]
With domoticz

**Comment by robertsLando** [comment]
And what object do you expect to have for that? A binary switch? Is the property name toneId?

**Comment by robertsLando** [comment]
And what about when you trigger it from Control Panel UI? Does that work?

**Comment by MuadDibVV** [comment]
Yes, ok from Panel UI
And you are right, it's ok with mqtt msg with "set" and not "Set" => Thanks a lot

**Comment by robertsLando** [comment]
Maybe this could be used: https://www.home-assistant.io/integrations/select.mqtt/

**Comment by MuadDibVV** [comment]
Sorry I am on Domoticz.
With your correction I can create a dummy device and write a lua script to call mqtt.
If there is a MQTT AD Solution for the future it could be perfect.

**Comment by MuadDibVV** [comment]
Thanks a lot @robertsLando

**Comment by robertsLando** [comment]
You welcome @MuadDibVV :)
