### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by jriker1** [zwave-js/zwave-js-ui#2965]
Tried looking at the documentation but when I clicked on the link it just spun.

I am trying to do some diagnostic checks on Z-Wave devices.  Was going to use a tool I use for other device monitoring called NSClient++.  It can pass requests to something and expect a result back and report it.  Does ZWave-JS-UI have an API to query individual Z-Wave devices and get something back?   Be even nicer other than the info in the GUI if that can be pulled if there are calls that can be made to the Z-Wave devices and see if they respond.

**Comment by robertsLando** [comment]
Only websockets and MQTT, does NSClient++ works with them?
