### ISSUE TITLE
Error: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by hassan-xy** [zwave-js/zwave-js-ui#2973]
Hi,
I have unzipped the zwave-js-ui-v8.8.6-linux-arm64.zip file and when I run ./zwave-js-ui, 
I get the error message: Error: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found
I have tried updating my board using commands sudo apt update and sudo apt upgrade but it does not solve my issue. I will post the screenshot of my error and my board details.
![Screenshot from 2023-02-23 10-27-41](https://user-images.githubusercontent.com/125990448/220826705-e4c0c2a7-05eb-41b0-8cc8-90905ec36bf5.png)
![Screenshot from 2023-02-23 10-02-46](https://user-images.githubusercontent.com/125990448/220826723-cbc39048-4ff5-4b8b-9aba-8ad705f628c6.png)
![Screenshot from 2023-02-23 09-57-55](https://user-images.githubusercontent.com/125990448/220826733-56a31f0e-970d-4276-b255-31d9729e446a.png)
Please have a look and guide me.
Thanks
Hassan

**Comment by robertsLando** [comment]
@hassan-xy That's the same error that was happening with old os versions, I suggest to upgrade like @kpine suggested

**Comment by hassan-xy** [comment]
Hi guys,
Thanks for your reply.
My configurations are:
Operating System: Ubuntu 18.04.6 LTS                                                 
            Kernel: Linux 3.10.65                                                      
      Architecture: arm64

**Comment by hassan-xy** [comment]
Is there a way to run zwave-js-ui on older ubuntu versions, maybe a previous version of zwave-js-ui might help.
If you guys have an idea of a previous zwave-js-ui version compatible with ubuntu 18.04.6 then please let me know.

Thanks

**Comment by robertsLando** [comment]
@hassan-xy use docker :)

**Comment by hassan-xy** [comment]
@kpine @robertsLando  Thanks for your reply.
Can you provide me with the source code. I will try building using the official v16 release of Node.
If you have any documentation, steps, youtube tutorials that can help me in building from source then that would be great.
I appreciate any help that you guys can give as I am a complete beginner to all these things.

Thanks and Regards,
Hassan

**Comment by robertsLando** [comment]
I agree that upgrading would be easier, but also docker way should work, check [docs](https://zwave-js.github.io/zwave-js-ui/#/getting-started/docker)

**Comment by hassan-xy** [comment]
![Screenshot from 2023-02-27 10-44-00](https://user-images.githubusercontent.com/125990448/221480168-617535cc-a685-4174-b195-c3f8cc754456.png)
Hi guys,
Thanks for all the help.
I have tried the above steps in my board, but still facing some issues as the last step: **yarn pkg --skip-build --arch=arm64**
I have recieved the message:
Warning Cannot find module 'zwave-js/Utils' from '/root/zwave-js-ui/server/lib'  in /root/zwave-js-ui/server/lib/ZwaveClient.js
and then after few minutes list of failed messages, which i have attached below
![Screenshot from 2023-02-27 10-38-43](https://user-images.githubusercontent.com/125990448/221480153-15af5682-f691-4539-9738-f3cfc8633565.png)

![Screenshot from 2023-02-27 10-44-00](https://user-images.githubusercontent.com/125990448/221480159-779a152f-56a2-4211-9cc5-7df25a49eaae.png)
NOTE: I am not using docker over here as have no experience or knowledge regarding it, and find it confusing as of now.
 Trying to use the command: yarn start shows the following data
![Screenshot from 2023-02-27 10-50-07](https://user-images.githubusercontent.com/125990448/221480687-32a8aa22-2c84-4ece-82cd-d3ee9755b800.png)
And the web portal at http://localhost:8091/ does not run and shows the below message.
![Screenshot from 2023-02-27 10-51-34](https://user-images.githubusercontent.com/125990448/221480851-45bfa9ba-d676-4897-a843-291aeb3f160c.png)

Thanks and Regards,
Hassan

**Comment by hassan-xy** [comment]
If you guys have any suggestions then do let me know
Thanks

**Comment by hassan-xy** [comment]
@kpine Hi, thanks for you reply.
I was using yarn start to run the application, I could not see any binary file generated.
I was making a mistake using localhost. and now using my ip address i get a different error.
![Screenshot from 2023-02-27 11-18-11](https://user-images.githubusercontent.com/125990448/221484674-eb6b20f5-252f-4f6b-a349-7ff6e7cf9291.png)

**Comment by robertsLando** [comment]
Application is running well the problem is that you didn't built the frontend:

```
yarn build
```

**Comment by hassan-xy** [comment]
Hi guys, 
Thanks for all your help
It seems all the issues that I am facing right now is due to incompatibility between nodejs code and the nodejs version.
If you have a look at the previously sent screenshots you would notice the message **Failed to make bytecode node16-arm64**. Also their is a missing **settings.json** file in store directory.  I tried copying the settings.json file from another i.e zwave-js-ui version but recieved the below error.
![Screenshot from 2023-02-28 10-36-11](https://user-images.githubusercontent.com/125990448/221759396-c12fc4b4-7597-461c-9a0e-5a61de906323.png)
Can you guys assist me on how to make the node files and the node-version compatible with each other.
Also please share a settings.json file which is node-16 compatible

**Comment by robertsLando** [comment]
@hassan-xy I don't understand what you are doing here...

There are multiple ways to run zwave-js-ui (check docs):

- Docker
- PKG
- Snap
- Manually built

At start you tried the pkg version but both me and @kpine told you that the problem is your ubuntu version that need to be upgraded

Then you tried the manually built but you was using the wrong commands as you forgot to build frontend files so the UI wasn't working, also you was using yarn pkg to package your application and I dunno why

Now I dunno what you are asking for as from the logs you sent in above comment seems the application is running fine.

Based on this I could suggest you to read docs and choose one of the available ways to use ZUI or follow our suggestions of updating your ubuntu distro if you want to use the pkg version

**Comment by mdelmiro27-tech** [comment]
> > Warning Cannot find module 'zwave-js/Utils' from '/root/zwave-js-ui/server/lib' in /root/zwave-js-ui/server/lib/ZwaveClient.js
> 
> They are warnings, not errors. As far as I can tell, they are harmless, but I could be wrong. You won't know until you actually configure the USB stick and try things out.
> 
> > NOTE: I am not using docker over here as have no experience or knowledge regarding it, and find it confusing as of now.
> 
> IMO, learning Docker would be easier than what you are trying to do now.
> 
> > Trying to use the command: yarn start shows the following data
> 
> The point of running `yarn pkg` was to generate the binary that you originally were trying to run. If you are going to run `yarn start`, there's no reason to make the package file.
> 
> > And the web portal at http://localhost:8091 does not run and shows the below message.
> 
> Why are you using localhost? Is your screenshot from a web browser running on your ARM device? If not, it should be the IP of your device.

SOMEONE HELP ME I DID NOT WRITE THIS I DONT EVEN KNOW ANYTHING! 
IM HACKED AND NO ONE HELPS OR CARE
ITS TOTAL OF 6 DEVICES NOW ALL WITH THE SAME PROBLEM.

**Comment by mdelmiro27-tech** [comment]
The reson why its using local its because ive been hacked and Mdm device modiefied all kind of terrible things for over 5months its been hell! Can anyone explain or HELP PLEASE HELP 

![Image](https://github.com/user-attachments/assets/67a05a08-2e2f-43ca-a44d-3a826b08cc6a)
![Image](https://github.com/user-attachments/assets/16a2df01-5f9e-4818-9834-abec863b17da)
![Image](https://github.com/user-attachments/assets/af2ab98a-245b-4500-8935-451984194924) 
The reason i get all those screen shot is because i put my device info on google and it leads me to that
