### ISSUE TITLE
MQTT does not publish battery parameters

### ISSUE THREAD

**Issue by SmartHomeNewbie** [zwave-js/zwave-js-ui#2979]
Hi,
Most of my zwave battery devices does not publish /level and /isLow to MQTT, does anyone know how i make them do that.
I have some hieman smoke detectors, they all publish /level and /isLow everytime they wake up.

Thanks in advance

**Comment by SmartHomeNewbie** [comment]
Not sure how to manually refresh or poll them, but I got the battery level showing in the ui, so i assume zwavejsui is getting updates, then they should be published to battery level MQTT topic?

**Comment by robertsLando** [comment]
@SmartHomeNewbie So you say that what you see in the UI is not the same you see in mqtt topics? That's strange... Could you show me this with a screenshot of mqtt explorer and UI control panel? Maybe you are subscribing to the wrong topic?

**Comment by SmartHomeNewbie** [comment]
![image](https://user-images.githubusercontent.com/75638271/221552007-2a405423-d770-4ea4-90d4-6ebcb40a9daf.png)

![image](https://user-images.githubusercontent.com/75638271/221552226-f3a2b443-d6ed-43c0-871d-4b0bb89f28bb.png)

**Comment by robertsLando** [comment]
Can you show me in the events tab of expanded node if after the wake up event there is also a corrisponding value updated event regarding the battery?

**Comment by SmartHomeNewbie** [comment]
2023-02-25T11:40:52.637Z - SLEEP 
Arg 0:
0
2023-02-25T11:40:52.668Z - READY
2023-02-25T13:18:36.276Z - VALUE UPDATED 
Arg 0:
└─commandClassName: Notification
└─commandClass: 113
└─property: alarmType
└─endpoint: 0
└─newValue: 0
└─prevValue: 0
└─propertyName: alarmType
2023-02-25T13:18:36.277Z - VALUE UPDATED 
Arg 0:
└─commandClassName: Notification
└─commandClass: 113
└─property: alarmLevel
└─endpoint: 0
└─newValue: 0
└─prevValue: 0
└─propertyName: alarmLevel
2023-02-25T13:18:36.285Z - VALUE UPDATED 
Arg 0:
└─commandClassName: Notification
└─commandClass: 113
└─property: Access Control
└─propertyKey: Door state
└─endpoint: 0
└─newValue: 22
└─prevValue: 23
└─propertyName: Access Control
└─propertyKeyName: Door state
2023-02-25T13:18:52.089Z - VALUE UPDATED 
Arg 0:
└─commandClassName: Notification
└─commandClass: 113
└─property: alarmType
└─endpoint: 0
└─newValue: 0
└─prevValue: 0
└─propertyName: alarmType
2023-02-25T13:18:52.093Z - VALUE UPDATED 
Arg 0:
└─commandClassName: Notification
└─commandClass: 113
└─property: alarmLevel
└─endpoint: 0
└─newValue: 0
└─prevValue: 0
└─propertyName: alarmLevel
2023-02-25T13:18:52.097Z - VALUE UPDATED 
Arg 0:
└─commandClassName: Notification
└─commandClass: 113
└─property: Access Control
└─propertyKey: Door state
└─endpoint: 0
└─newValue: 23
└─prevValue: 22
└─propertyName: Access Control
└─propertyKeyName: Door state
2023-02-26T00:34:16.186Z - WAKE UP 
Arg 0:
1

**Comment by robertsLando** [comment]
I don't see any value update regarding battery CC here

**Comment by SmartHomeNewbie** [comment]
@robertsLando me too, here is the full events log
[event.txt](https://github.com/zwave-js/zwave-js-ui/files/10841876/event.txt)

**Comment by robertsLando** [comment]
@SmartHomeNewbie This means I'm not getting an event so without an event I will not send the mqtt message, I have a battery device too and  I cannot reproduce such issue

**Comment by SmartHomeNewbie** [comment]
So the device has never reported battery, therefor just left at 100% ?

**Comment by robertsLando** [comment]
At least this is what I see from the events there, tried to refresh values?

**Comment by SmartHomeNewbie** [comment]
I tried to refresh it just how, didnt see any changes, ill monitor it for a few days and see, thanks for the help so far

**Comment by robertsLando** [comment]
Ok let me know so

**Comment by SmartHomeNewbie** [comment]
I got one battery update, waiting to see what happens next time it wakes up, but the events tab is empty now, shouldn't I be able to see parameters in there too ?

**Comment by robertsLando** [comment]
What do you mean? You should see all node related events there

**Comment by SmartHomeNewbie** [comment]
Since yesterday i only had this, the device has been awake and reporting values with them showing in the event log
![image](https://user-images.githubusercontent.com/75638271/221940896-38817dd7-1e69-46f8-8ca3-6d804c258f49.png)

**Comment by robertsLando** [comment]
Seems it never wake up?

**Comment by SmartHomeNewbie** [comment]
I don't know what it means :) but I have 6 of these door sensors and its the same for all of them.
This is one of the same sensors:
![image](https://user-images.githubusercontent.com/75638271/222128887-ee30d1de-ba47-4d5a-82dd-4f63253e8337.png)

**Comment by SmartHomeNewbie** [comment]
but but, I just checked the sensor we been looking at, I changed wakeup interval to 1hr yesterday so I could troubleshoot, now the event log looks like this, is it normal for a device to wake up and go back to sleep without pushing any values?
[event1.txt](https://github.com/zwave-js/zwave-js-ui/files/10860579/event1.txt)

**Comment by robertsLando** [comment]
>  is it normal for a device to wake up and go back to sleep without pushing any values?

Good question for @AlCalzone

**Comment by AlCalzone** [comment]
> is it normal for a device to wake up and go back to sleep without pushing any values?

yeah it is. Sleeping devices **send** commands while they are asleep. However, they can only **receive** commands while awake.

To diagnose the original issue, please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs) of a re-interview, loglevel `debug` and attach it here as a file (drag & drop into the text field). Make sure to wake up the device, otherwise there won't be an interview in the logs.

**Comment by SmartHomeNewbie** [comment]
[zwave-js-ui-store.zip](https://github.com/zwave-js/zwave-js-ui/files/10928955/zwave-js-ui-store.zip)

**Comment by AlCalzone** [comment]
I'm not seeing any interview in that log.

**Comment by SmartHomeNewbie** [comment]
damn sorry, here is the right one:
[zwave-js-ui-store (1).zip](https://github.com/zwave-js/zwave-js-ui/files/10932042/zwave-js-ui-store.1.zip)

**Comment by AlCalzone** [comment]
Ok that looks normal, It also reports that battery CC v1 is supported. Are you still seeing the v0?

I can't see in the manual whether it's supposed to send battery reports from time to time. If not, you'll have to wait for https://github.com/zwave-js/node-zwave-js/issues/2589 to be implemented.

**Comment by SmartHomeNewbie** [comment]
It's the v1's I'm seeing here we're talking about right ? I also have no idea what that means, why are some v1 v2 and v4, before they were all v0 except for wakeup, it was v1 
![image](https://user-images.githubusercontent.com/75638271/224049980-bff3833a-9510-46c3-968e-15f639290f97.png)

**Comment by AlCalzone** [comment]
that's the version of the Command Class your device implements. v0 basically means "unknown", which indicates there was something wrong when querying that information.

**Comment by SmartHomeNewbie** [comment]
ok, so after re-interview, it might be working as it should? ill monitor it, and re-interview my other devices

**Comment by AlCalzone** [comment]
it might. I'm not sure though if it sends battery reports on its own.

**Comment by SmartHomeNewbie** [comment]
alright guess ill have to wait and see, thanks for the help!
waiting for this https://github.com/zwave-js/node-zwave-js/issues/2589 to be implemented, do we have an ETA on that :)?

**Comment by SmartHomeNewbie** [comment]
been watching this sensor the past few days, and there is no battery updates from it, seems it just doesn't send battery state. thanks for helping me understand the way it works :)

**Comment by robertsLando** [comment]
@SmartHomeNewbie I also have some battery devices and no one of them reports battery states correctly, it's not a driver issue BTW, are devices fw that mostly sucks on this

**Comment by AlCalzone** [comment]
https://github.com/zwave-js/node-zwave-js/pull/5560
will be released soon.
