### ISSUE TITLE
Removed Node is flooding logs

### ISSUE THREAD

**Issue by declankenny** [zwave-js/zwave-js-ui#2982]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.9.0.2d95700

### ZwaveJS version

10.10.0

### Describe the bug

I removed node 23 as it had failed, using Advanced-->Failed Nodes-->Remove.
The node was successfully removed, but after I restarted the server, my logs are getting flooded with the following messages

```
2023-02-26T18:52:52.107Z CNTRLR   [Node 023] is unknown - discarding received command...
2023-02-26T18:52:53.174Z CNTRLR   [Node 023] is unknown - discarding received command...
```

What do I need to do to correct this issue? I don't want me controller to have to deal with these unnecessary messages every second.
 
[nodes_dump.zip](https://github.com/zwave-js/zwave-js-ui/files/10834488/nodes_dump.zip)
[zwavejs_current.log](https://github.com/zwave-js/zwave-js-ui/files/10834489/zwavejs_current.log)

### To Reproduce

Remove a node and see if it still generates messages

### Expected behavior

I expect a remove node to not send/receive commands

**Comment by jmgiaever** [comment]
Hi, 

I think if you factory reset the node you removed will do the trick. Seems like it's trying to communicate with the controller?

**Comment by robertsLando** [comment]
That's not the way to remove nodes. You should only do that when the node is actually not working at all, you should use normal exclusion instead, in this case the node has been removed but can still communicate with controller so like @jmgiaever suggested the only solution for you is to factory reset that node now
