### ISSUE TITLE
Failing Inclusions with S2 Security

### ISSUE THREAD

**Issue by kars85** [zwave-js/zwave-js-ui#2993]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

YES, BUT a Z-Wave JS UI developer has told me to come here

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Attempting to include a Aeotec ZW189
What do you observe?
Erratic inclusion behavior from GUI. Says inclusion fails, but continues inclusion behind the inclusion menu.
What did you expect to happen?
Prompt for S2 Key and normal menu operation
Tried stopping ZJS, unplugging controller from docker host, reinserting and starting ZJS.

### Device information

Manufacturer: Aeotec
Model name: ZW189
Node ID in your network: Logs should show three times with successive increases in node ID's. They should be 50, 51, 52, 53

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

zwave-js-ui: 8.10.0.2a77652
zwave-js: 10.11.0
home id: 3745883352
home hex: 0xdf45a4d8

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

Have one of these months ago that included fine.

### Attach Driver Logfile

[zwavejs_2023-03-08.log](https://github.com/zwave-js/node-zwave-js/files/10925032/zwavejs_2023-03-08.log)
[zniff_3823.zlf.log](https://github.com/zwave-js/node-zwave-js/files/10925041/zniff_3823.zlf.log)

**Comment by kars85** [comment]
Got it @AlCalzone. Thanks for routing over. Here's some silly logs on the UI side. I staged the device wish the S2 key preadded, Not knowing what UI was the cause, I did this on the HA side of the house. ZJS/ZJS-UI keeps looping through provisioning nodes that ultimately end up as dead. I restarted ZJS after 4 or 5 phantom devices got created, FWIW.

[z-ui_2023-03-08.log](https://github.com/zwave-js/zwave-js-ui/files/10926168/z-ui_2023-03-08.log)
[zwavejs_2023-03-08.log](https://github.com/zwave-js/zwave-js-ui/files/10926169/zwavejs_2023-03-08.log)

**Comment by kars85** [comment]
Last comment until y'all that know what you're doing chime in. Appears that even after removing the failed nodes after restarting ZJS, upon another restart, the device tries to provision...

**Comment by robertsLando** [comment]
PR ready, seems there are issues both on ui and also on driver side. I fixed issues on my side but I also needed to downgrade driver to 10.10 in order to make it work again

**Comment by AlCalzone** [comment]
Seems like the driver side is broken after the step that was broken in the UI 😇
Working on a fix as we speak.
