### ISSUE TITLE
Z-wave User Lock Code Manager

### ISSUE THREAD

**Issue by skl111** [zwave-js/zwave-js-ui#2998]
![Screenshot 2023-03-13 032350](https://user-images.githubusercontent.com/25110469/224635634-a315dbf2-06f7-4aac-9c7e-235c625b2cf2.png)
**Is your feature request related to a problem? Please describe.**
An Official Z-wave user Lock Code manager

**Describe the solution you'd like**
A clean implementation of a Z-Wave Lock Code Manager, maybe integrate it into a larger Lock Code Manager.

**Describe alternatives you've considered**
I installed and used Keymaster when I was testing out HA. It was not user friendly.

**Additional context**
HomeSeer has this feature, and it works pretty well. I experimented to HA while HS was having issues with Google Home because HA worked with it, and User Lock Code management not having and officially supported user friendly option was a show stopper for me, which I hated because there were so many other features I liked and I got it working with the HomeSeer Zwave card!

I have attached a screenshot of the HomeSeer User Lock code management screen to show the ease of use of it.

**Comment by AlCalzone** [comment]
@robertsLando

**Comment by robertsLando** [comment]
Added to TODOs
