### ISSUE TITLE
zwave health check endpoint not indicating a zwave failure

### ISSUE THREAD

**Issue by mwolter805** [zwave-js/zwave-js-ui#2999]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.10.1

### ZwaveJS version

10.11.1

### Describe the bug

When zwavejsui loses connection to a TCP based zwave controller, /health/zwave does not indicate an issue. Not sure how locally connected usb controllers are affected. 

As stated in [Health check endpoints](https://zwave-js.github.io/zwave-js-ui/#/guide/healthcheck?id=health-check-endpoints) the http return code should be 200 if zwave client is connected. 

wget command run from container
```sh
wget --server-response --spider --quiet --no-check-certificate "http://localhost:8
091/health/zwave" --header "Accept: text/plain" 2>&1 | awk 'NR==1{print $2}'
```
response
```
200
```

PS the command listed in https://zwave-js.github.io/zwave-js-ui/#/guide/healthcheck?id=health-check-endpoint does not run on the container as curl does not exist.

Recommend using the command above instead.

Edited: removed browser response as the healthcheck endpoint is not meant to be viewed in a browser.

### To Reproduce

With the zwavejsui container running, reboot the tcp zwave controller. Then operate a device once the tcp controller reboots. 

### Expected behavior

Expect the /health/zwave page to indicate zwave is down as the connection to the controller is down.

### Additional context

[Logs when connected to tcp controller
](https://pastebin.com/fncTUfGi)
[Logs after tcp controller has been rebooted
](https://pastebin.com/asgwq9La)

**Comment by robertsLando** [comment]
@mwolter805 As described in docs the url must specify the header `"Accept: text/plain" ` in order to work, if not present (like when you open a web page) it is considered as a html request so it redirects it to frontend

**Comment by mwolter805** [comment]
@robertsLando Thank you for the response, however, please see the command and output above the picture.

**Comment by robertsLando** [comment]
@mwolter805 as I sad that healthcheck endpoint is not meant to be served on frontend, it's just an api that can be called with curl or what you prefer

**Comment by mwolter805** [comment]
@robertsLando thank you for the reply, yes I understand what you are saying, the healthcheck endpoint is not meant to be viewed from the browser. I have updated the issue and removed the browser issue.

However, I believe the issue with the healthcheck endpoint returning http return code 200 when zwave is down has not been addressed. Please see the command and output above. When zwave was down the healtcheck endpoint returned http return code 200 when none of the zwave devices (controller or switch) were operational.

**Comment by robertsLando** [comment]
Ok got it. I think this is a known issue on zwave-js driver side not detecting tcp errors: https://github.com/zwave-js/node-zwave-js/issues/4660

cc @AlCalzone

**Comment by mwolter805** [comment]
@robertsLando @AlCalzone Thanks, Zooz released an inexpensive 800 series controller hat ($25) for the Raspberry Pi that works well, except for this. As far as I can tell the Pi and controller are working well and this is the last major thing. Having an option for a controller over wifi or ethernet is very desirable and planning to do writeup on the forums for this once it's reliable.

**Comment by AlCalzone** [comment]
Correct, I'll need to figure out what broke in the detection of TCP disconnects.

**Comment by robertsLando** [comment]
@mwolter805 Can you follow updates on that issue please? Juswt subscribe to it, I close this one as it's not a zui issue and it's a dup of that

**Comment by mwolter805** [comment]
@robertsLando Sure thing, no problem. Thanks for your help.
