### ISSUE TITLE
zwavejsui does not reconnect to tcp controller

### ISSUE THREAD

**Issue by mwolter805** [zwave-js/zwave-js-ui#3000]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.10.1

### ZwaveJS version

10.11.1

### Describe the bug

If zwavejsui loses connection to the tcp zwave controller, zwavejsui does not attempt to reconnect.

This causes user experience issues as several things can cause this, such as:
- network (ethernet or wifi) has an issue for a few seconds
- ethernet switch or wifi access point reboots
- host running the tcp controller reboots

When this happens, the following resolves the issue:
- restart the zwavejsui docker container
- In zwavejsui GUI -> Settings -> Z-Wave and clicking "save" without changing anything

### To Reproduce

Reboot the tcp zwave controller.

### Expected behavior

zwavejsui container or the zwavejsui process restarts itself or zwavejsui attempts to reconnect to the tcp controller periodically.

### Additional context

[Logs when connected to tcp controller](https://pastebin.com/fncTUfGi)

[Logs after tcp controller has been rebooted](https://pastebin.com/asgwq9La)

**Comment by robertsLando** [comment]
Please follow updates on the issue linked by @kpine
