### ISSUE TITLE
fibaro door sensor behaviour change after update

### ISSUE THREAD

**Issue by redridinghood314** [zwave-js/zwave-js-ui#3003]
Hello,
I have something strange and didn t find anything on this,
i have upadated zwave-js-ui: to 8.9.0.2d95700 (was from zwavejs2mqtt), and now my fibaro door sensor fgw002 no more reports the state (open or Close) in binary mode
Now the type of sensor_notification_access_control_door_state is sensor and reports in text.
But before it was binary_sensor_door_state and was reporting as binary_sensor. Do you know why ? Is it a bug ??is there any possibility to change this behaviour ?

thanks for your help (i will post capture to show)

**Comment by robertsLando** [comment]
@redridinghood314 Could you give some more context please? You update from which version? Why didn't you updated to latest release 8.10.1 ? What are you using zui for? Home Assistant or domoticz? I think this is related to mqtt discovery

**Comment by redridinghood314** [comment]
sorry, i have forgotten which version i was before updating (but was still zwavejs2mqtt), and yes i use it with domoticz. but the issue seems to be in zwavejsui, here the sensor actually (fibaro door sensor) : 
[url=https://zupimages.net/viewer.php?id=23/11/26cq.png][img]https://zupimages.net/up/23/11/26cq.png[/img][/url]
[url=https://zupimages.net/viewer.php?id=23/11/qbe9.png][img]https://zupimages.net/up/23/11/qbe9.png[/img][/url]
and the same one before 
[url=https://zupimages.net/viewer.php?id=23/11/00ar.png][img]https://zupimages.net/up/23/11/00ar.png[/img][/url]
[url=https://zupimages.net/viewer.php?id=23/11/idts.png][img]https://zupimages.net/up/23/11/idts.png[/img][/url]

door state was binary, and now it reports only as sensor (not bianry_sensor).

i hope you can explain me.

thanks 

regards

**Comment by robertsLando** [comment]
From which version did you upgraded?

**Comment by redridinghood314** [comment]
sorry but i am not able to tell you (upgraded both operating system of my rapsberry and container from fresh install)

**Comment by robertsLando** [comment]
@redridinghood314 by checking the code what I do is to check how many states the valueId has, in case it has 2 posible states defined I create a binary sensor, if not I create a normal sensor:

https://github.com/zwave-js/zwave-js-ui/blob/master/lib/Gateway.ts#L1419

What I dunno is if something has changed on that specific valueId definition on driver side, @AlCalzone any clue?

**Comment by AlCalzone** [comment]
See https://github.com/zwave-js/node-zwave-js/discussions/5453

**Comment by redridinghood314** [comment]
thanks for answers, but i can't find anything on fibaro door sensor 2 reporting other value than open or closed (or i am not looking on the right place), here extract of fibaro manuel : 
`Notification report:
The device uses Notification Command Class to report different
events.
Notification Type Event
- Home Security Tampering, product covering removed
- Access Control Door/window opened
- Access Control Door/window closed
- Power Management Replace battery now
- Heat Alarm Overheat detected, unknown location
- Heat Alarm Underheat detected, unknown location`

it looks like it is specific to aeotec sensor. does the modification has to be make on all type of door sensors ?

**Comment by AlCalzone** [comment]
Can you share a driver log (level debug) of you opening the door?

**Comment by redridinghood314** [comment]
like this ? 👍 
`2023-03-21T18:54:10.974Z - VALUE UPDATED 
Arg 0:
└─commandClassName: Notification
└─commandClass: 113
└─property: Access Control
└─propertyKey: Door state
└─endpoint: 0
└─newValue: 23
└─prevValue: 22
└─propertyName: Access Control
└─propertyKeyName: Door state`

**Comment by redridinghood314** [comment]
`    {
      "time": "2023-03-21T18:54:10.974Z",
      "event": "value updated",
      "args": [
        {
          "commandClassName": "Notification",
          "commandClass": 113,
          "property": "Access Control",
          "propertyKey": "Door state",
          "endpoint": 0,
          "newValue": 23,
          "prevValue": 22,
          "propertyName": "Access Control",
          "propertyKeyName": "Door state"
        }
      ]
    }`

**Comment by robertsLando** [comment]
@AlCalzone I don't understand what you mean here, as you can see here: 

https://github.com/zwave-js/zwave-js-ui/blob/master/lib/Gateway.ts#L1434
https://github.com/zwave-js/zwave-js-ui/blob/master/lib/Gateway.ts#L1490

And: https://github.com/zwave-js/zwave-js-ui/blob/master/lib/Gateway.ts#L2447

I actually set the on/off payload in the discovery config, how could I discover it correctly without knowing the correct open state? 
I should check the value before sending it to mqtt and always send the same when it's an open state?

**Comment by redridinghood314** [comment]
sorry @AlCalzone if it's not what you wanted (please tell me where i can get driver log).

**Comment by AlCalzone** [comment]
All good. It's not what I asked for but I got what I need.

**Comment by redridinghood314** [comment]
do you know if it can be "easily" solved ?

**Comment by AlCalzone** [comment]
This needs to be solved in the MQTT discovery. @robertsLando should know how easy that is.

**Comment by robertsLando** [comment]
@redridinghood314 we are discussing about possible solutions to this

**Comment by redridinghood314** [comment]
thanks a lot ! tell me when you have found a solution and you want me to test !

**Comment by AlCalzone** [comment]
https://github.com/zwave-js/node-zwave-js/pull/5614 adds an additional door sensor which just has open/closed states

**Comment by robertsLando** [comment]
Awesome 🎉

**Comment by robertsLando** [comment]
I submitted the fix needed on my side too, just need to wait for a new zwave-js release

**Comment by redridinghood314** [comment]
will try as soon as possible (probably next week), i keep you informed ! thanks !!!

**Comment by redridinghood314** [comment]
hello,

sorry for delay, i have now a basic switch in domoticz, works perferct ! thanks !
