### ISSUE TITLE
Auto run heal network when any node fails/drops from network

### ISSUE THREAD

**Issue by TRusselo** [zwave-js/zwave-js-ui#3006]
**Is your feature request related to a problem? Please describe.**
Auto run heal network when any node fails/drops from network/enters error state. 

I think its pretty self-explanatory

**Comment by robertsLando** [comment]
We are against this kind of approach as it's generally not a good practise. If you really want to do this you could setup some scheduled job to do that

cc @AlCalzone

**Comment by TRusselo** [comment]
schedule would be helpful IF the device disappeared from network on some type of schedule but it does not.

the only device that disappears, is my front deadbolt.
kind-of the most important device in the home from some point of view.
and it goes offline randomly,  sometimes fine for days or weeks.

I am trying to set an automation though,  Trigger Front Deadbolt state : unknown
but i cannot find an action to start  Heal Network.

![image](https://user-images.githubusercontent.com/1154815/226208175-79282db8-0225-429f-b78a-ecff2f2c5e8f.png)

**Comment by robertsLando** [comment]
I don't know how to do that on Home Assistant side, maybe @kpine could help you with that

BTW you can do it also on ZUI, you can write scheduled scripts to run at specific intervals

**Comment by AlCalzone** [comment]
Heal Network is a pretty traffic-intensive task and unlikely to help if your're consistently experiencing connectivity issues.
It will instruct all nodes to find their neighbors (that's a LOT of pings), compute new routes for the nodes back to the controller, and tell each node the new routes.

Nodes being considered "dead" happens on the other direction. When the controller tries to reach a node, it first uses the last working route, then the one before that before falling back to explorer frames, which automatically find their way through the network through try-and-error basically. If all of those fail, **then** a node gets considered dead.

Also, there are a bunch of reasons a node can be unreachable:
- Bad controller placement
- Bad RF performance of the controller (all 700-series controllers before FW 7.17.2, and Z-Stick 7 EU version)
- Other nodes flooding the network
- External devices interfering
- Not enough repeaters
- ...

None of that is obvious from just looking at the "dead" state.

Giving the node a new route to report doesn't change anything about these problems. What you're attempting would flood the network for a few seconds to minutes in response to a single device temporarily having a flaky connection. Seems like a terrible idea to me.
