### ISSUE TITLE
Controller background rssi chart

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js-ui#3008]
cc @AlCalzone

**Comment by robertsLando** [comment]
ping @AlCalzone

**Comment by AlCalzone** [comment]
I think just in memory is fine. Need to fine-tune how much data to show in the graphs, but I think showing the last 2-3h is a good timespan.

**Comment by robertsLando** [comment]
what's the aprox frequency of background rssi updates?

**Comment by AlCalzone** [comment]
every 30s, but only if the controller is idle

**Comment by robertsLando** [comment]
For me:

Use uplot: https://github.com/skalinichev/uplot-wrappers
