### ISSUE TITLE
Eslint-loader looks to be out of date

### ISSUE THREAD

**Issue by jrgleason** [zwave-js/zwave-js-ui#3012]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Z-Wave JS UI version

latest

### ZwaveJS version

latest

### Describe the bug

Trying to build using `npm install` produces...

```
npm ERR! While resolving: zwave-js-ui@8.11.0
npm ERR! Found: eslint@8.36.0
npm ERR! node_modules/eslint
npm ERR!   optional eslint@"^8.21.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^6.0.0 || ^7.0.0" from eslint-loader@4.0.2
npm ERR! node_modules/eslint-loader
npm ERR!   optional eslint-loader@"^4.0.2" from the root project
npm ERR!
```

Upgrading eslint and eslint-loader to latest seems to fix it.

### To Reproduce

Raspberry Pi 4 B (Node 19)

1. Download Source
2. Run `npm i`
3. See Error

### Expected behavior

I would expect it to install deps with no error

**Comment by robertsLando** [comment]
you are using npm but you should be using yarn...

**Comment by jrgleason** [comment]
I am not sure closing this for that reason is the right approach when you still have out of date deps in your package file. At least remove them if they "don't matter"

**Comment by robertsLando** [comment]
Sorry @jrgleason what I meant is that you were using a wrong command to do the install. You should run `yarn` in order to install deps and not `npm`. Anyway eslint-loader is no longer used as dep, I will remove it now as I forgot about it
