### ISSUE TITLE
Configurable time and date format (12/24h & dd-mm-yyyy / mm-dd-yyyy / yyyy-mm-dd)

### ISSUE THREAD

**Issue by alexruffell** [zwave-js/zwave-js-ui#3013]
**Is your feature request related to a problem? Please describe.**
Even though I live in the USA I am European and 100% prefer the 24 hour system for time formatting. I could not find any setting to configure the time display to use the 24h system. Please add :)

<img width="145" alt="image" src="https://user-images.githubusercontent.com/4006944/226482717-97e51252-5dc1-4aeb-8789-b9a194acf7e4.png">

Being able to configure the date format would be awesome as well. Please do not attach it to locale or some other default setting based on location as that forces formats that may not match what the user needs/wants.

**Describe the solution you'd like**
Configuration for time and date formats in UI tab

**Describe alternatives you've considered**
None that I can think of

**Additional context**
None

Grazie Daniel!

**Comment by robertsLando** [comment]
Hi Alex, sorry for late reply, btw this is not so easy to do and also I don't think it's something useful to lot of users, will keep it here BTW and will see if I will find some time to implement it

**Comment by Justheretoreportanissue** [comment]
Hi!

I'll like to support this request with a +1.

Regards,

   /Jonas...

**Comment by robertsLando** [comment]
@Justheretoreportanissue https://support.cascade.app/docs/how-to-change-date-format-in-your-browser

**Comment by Justheretoreportanissue** [comment]
Right, somewhat sorted.

I am Swedish.
I prefer my computers to have US English as language.
I like to have date and time in the Swedish (24h, yyyy-mm-dd) format.
I read and speak Norwegian and Danish too.

This is what I came up with in Chrome:
![image](https://github.com/zwave-js/zwave-js-ui/assets/63780150/4ccfed18-717b-4e27-8507-db6cef515afc)

Now it shows like this:
![image](https://github.com/zwave-js/zwave-js-ui/assets/63780150/5e4f4178-0a28-4533-b1b2-952a58144f90)

Close, but not A+

Thanks,

/Jonas...

**Comment by robertsLando** [comment]
Dates are not localized on backend I just use a locale string conversion on UI to show dates based on the browser locale
