### ISSUE TITLE
Hass json device update don't work

### ISSUE THREAD

**Issue by barrydouu** [zwave-js/zwave-js-ui#3043]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.13.1

### ZwaveJS version

10.14.0

### Describe the bug

Hello
I've a FGR222 roller shutter.
I'd like to change the hass device json, to change the "position_template" of the cover_position (In Home Assistant entry of the device).
So I change  `"position_template": "{{ (value_json.value / 99 * 100) | round(0) }}",`   with `"position_template": "{{ value_json.value | round(0) }}",`
Then I hit "update" (on the right side)
Then I hit "rediscover"

But when I do that, the value pushed to the discovery topic is the old one

Here is the log
`2023-04-10 14:45:04.310 DEBUG SOCKET: Event HASS_API emitted to Sy4hC9hqEfRH2ASAAAAW
2023-04-10 14:45:04.311 INFO APP: Hass api call: discover
2023-04-10 14:45:04.312 DEBUG GATEWAY: Publishing discovery: {
type: 'cover',
object_id: 'position',
values: [ '38-0-currentValue', '38-0-targetValue', [length]: 2 ],
discovery_payload: {
command_topic: 'zwave/25/38/0/targetValue/set',
position_topic: 'zwave/25/38/0/currentValue',
set_position_topic: 'zwave/25/38/0/targetValue/set',
position_template: '{{ (value_json.value / 99 * 100) | round(0) }}',
position_open: 99,
position_closed: 0,
payload_open: '99',
payload_close: '0',
device: {
identifiers: [ 'zwavejs2mqtt_0xc7bf3f61_node25', [length]: 1 ],
manufacturer: 'Fibargroup',
model: 'Roller Shutter 2 (FGR222)',
name: 'VoletSalon2',
sw_version: '25.25'
},
name: 'VoletSalon2_position',
unique_id: 'zwavejs2mqtt_0xc7bf3f61_Node25_position'
},
discoveryTopic: 'cover/VoletSalon2/position/config',
persistent: false,
ignoreDiscovery: false,
id: 'cover_position'
}`

### To Reproduce

Go to home assistant of a device
update a hass definition
hit update
hit rediscover

### Expected behavior

I'd like the rediscover send the new "position_template"

**Comment by barrydouu** [comment]
I've just updated to 8.14.1, and now it's working perfectly

Thank you

**Comment by robertsLando** [comment]
@barrydouu thanks for the feedback 🙏🏻

**Comment by Call-Me-G-Now** [comment]
@robertsLando 
Changes made to the JSON payload are not published with the following workflow:
- edit JSON in webgui (NOTE that the auto refresh/json sysntax checking makes the pages/box jump back up on every keystroke)
- click "UPDATE"
- click "REDISCOVER" aka publish
- --> old payload is pushed.

it does seem to work with this workflow:
- edit JSON in webgui (NOTE that the auto refresh/json sysntax checking makes the pages/box jump back up on every keystroke)
- click "UPDATE"
- click "STORE" on the NODE type side
- click "REDISCOVER" aka publish on the component side (clicking REDISCOVER NODE will wipe all changes + the previously stored custom config!)
- --> new payload is pushed.

can you confirm this is not the intended behavior?

```
zwave-js-ui: 9.13.2.632ca88
zwave-js: 12.9.1
```

**Comment by robertsLando** [comment]
@Call-Me-G-Now It should work in the first way AFAIK, if not I have to test this myself and see what's broken

**Comment by Call-Me-G-Now** [comment]
ok, lemme know if you can reproduce it.

**Comment by robertsLando** [comment]
I cannot reproduce it, when I press update the in memory device is updated then when I press on rediscover I see it published to mqtt correctly

**Comment by Call-Me-G-Now** [comment]
Thanks for the feedback. I'll go back and test on my end once more to be sure. If still so, I'll record it.

**Comment by Call-Me-G-Now** [comment]
[zwavejs2.webm](https://github.com/zwave-js/zwave-js-ui/assets/125204742/e3707d1a-e577-4f7c-99ce-106f59b7fe78)

Unfortunately it's not working on my end.
You can also see in the end that moving away from this component and coming back to it the original name is display as payload again. Seem like it's not saved. As i'm running the docker i've check file/storage path permissions but they could not be an issue as all was masked 777, rwx for everyone.

**Comment by robertsLando** [comment]
@Call-Me-G-Now Could you try to restart your application?

**Comment by Call-Me-G-Now** [comment]
Yessir, this is video is after a fresh docker restart.
