### ISSUE TITLE
Feature request: Allow configuration of listen address for embedded web server

### ISSUE THREAD

**Issue by stanford-scs** [zwave-js/zwave-js-ui#3044]
Right now, zwave-js-ui always listens at INADDR_ANY, port 8091.  It would be great if this could be configured, so that people can use localhost to avoid remote accessibility, and other port numbers for when running other instances of zwave-js-ui.  Thanks.

**Comment by robertsLando** [comment]
Just use `HOST` env var. It's `0.0.0.0` by default. Check: https://zwave-js.github.io/zwave-js-ui/#/guide/env-vars?id=environment-variables
