### ISSUE TITLE
Device parameters revert to "Configuration vundefined" in ZUI some time after a successful interview

### ISSUE THREAD

**Issue by kdknigga** [zwave-js/zwave-js-ui#3045]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

YES, BUT a Z-Wave JS UI developer has told me to come here

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

I have a device, which after an interview looks correct.  The CCs I'd expect show up, etc.  Under "Configuration v4" I see the parameters I'd expect (being read out of a custom device config for now, as it's a brand-new device that hasn't been released yet), but no values for any of them.  If I click the "Refresh" button, the values are polled and displayed. 

Then time goes by... sometimes a couple of hours, sometimes a couple of days... and then I start seeing (on the same device as above) CCs "Configuration v4" and "Configuration vundefined".  Some params/values end up under v4 and some are in vundefined. 

Looking at my ZUI instance right now, it seems like all of the parameters are now in vundefined except for some that I update regularly via automation.  Those I touch regularly are in v4.

zwave-js-ui: 8.11.0
zwave-js: 10.12.0

### Device information

Manufacturer: Inovelli
Model name:  VZW31-SN
Node ID in your network: 90

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

Z-Wave JS UI HA Add-on: 1.8.0
zwave-js-ui: 8.11.0
zwave-js: 10.12.0

### Did you change anything?

yes (please describe)

### If yes, what did you change?

Custom device config file for an unreleased device.  It will be provided.

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

I'll send more information via email.

**Comment by robertsLando** [comment]
> Maybe this is some kind of race condition, where _updateValueMetadata is called before the node is ready

Hummmm I know someone else reported something like that but I don't understand how this could happen, also seems not to happen on startup but just on re-interview or other actions

**Comment by AlCalzone** [comment]
firmware updates cause re-interviews, so maybe those trigger it somehow.

**Comment by kdknigga** [comment]
Reinterview + refresh values fixes it... it breaks itself over time for reasons I can't figure out.

**Comment by AlCalzone** [comment]
does it stay in a broken state once broken? Have you tried restarting Z-Wave JS UI after it happens?

**Comment by robertsLando** [comment]
@AlCalzone when a node is re-interviewed the `ready` prop is false I think, right? Also, does metadata updated can be called before node is ready? If so the problem is simply that when reinterview is done on an already exising node and the metadata updated is called during inteview while node is not ready that if is skipped or maybe the endpoint is undefined for some reason that I don't know? Should I consider 0 when endpoint is undefined maybe? Does this happens only with configuration CC?
