### ISSUE TITLE
Promox container update now cant log in to ui

### ISSUE THREAD

**Issue by trev83** [zwave-js/zwave-js-ui#3057]
Hello i have a server running HA and zwave-js-ui. Its been running great for a while and have setup my z wave devices.

Today i ran an update script from here (https://tteck.github.io/Proxmox/) for Z-Wave JS UI LXC and it did the update and said everything went fine.

But now i cannot load the zwave ui where as i could load it fine before. Home assistant is still able to talk to Z-Wave JS UI fine as i can still switch my devices on and off and get updates from them within HA. Can anyone help with anything i can check please with getting the ui working again?

When ever i go to http://192.168.123.xxx:8091/ i just get 

This page isn’t working
192.168.123.xxx didn’t send any data.
ERR_EMPTY_RESPONSE

Many thanks

**Comment by trev83** [comment]
Right I reinstalled from scratch and all worked perfectly until I enable ssl auth. Then I can no longer access via an updated version chrome or edge.

**Comment by robertsLando** [comment]
This seems to me something related to your setup more then zwave-js-ui, BTW without any logs or error I cannot help you so much, I also never used Proxmox

**Comment by webmogul1** [comment]
try https instead of http
