### ISSUE TITLE
Can't add Yale YRM276 lock with the Black 700 series Zwave Module (AYR-MOD-ZW3)

### ISSUE THREAD

**Issue by fresnoboy** [zwave-js/zwave-js-ui#3059]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.14.1.46264f6

### ZwaveJS version

10.15.0

### Describe the bug

I can't seem to provision the YRM276 lock (it is the unit built into an Andersen patio door ( https://parts.andersenwindows.com/detail_9173094__d_yale_locks.html) with the new 700 series Zwave  module.

### To Reproduce

I put the lock into include mode and scan the QR code on the module on my phone (Pixel 6 with current android 13) using chrome to connect to the Zwave JS UI docker.  The web page says "Cannot initialize QR-code scanner: no available camera found".  So I snap a picture and then use the import option, I get "cannot read QR-Code".  So then I go to camera, and copy the text of the QR code into the QR Code Text line.  Now I get a "Error while calling parseQRCodestring:  Invalid QR Code: invalid checksum (ZW1406).

The QR code that was scanned was 

So I go to the Smart Start menu and try and add the provisioning string manually using the camera was: 900117125132261XXXXXX348566222811494510722012195284500101638500768022000297000040000100544 (I obscured 6 of the digits with X's for security reasons).  No trailing space either.  

Next I tried entering the DSK code in the smart start option and made an entry in the provisioning entries table.  The DSK code was recognized, but it's unclear what boxes are to be checked.  I can't find any documentation on what they are supposed to be configured.  So I selected all of them except for no security and then activated the entry.  

When I try to include the lock, it is detected, but doesn't seem to use the provisioned info, and asks me to select what security modes to use, so I select them, and then prompts again for the DSK.  I manually enter the DSK, but before I can complete the process, the lock times out on the include side, and ZwaveJS UI then adds the lock with no security.  However, in this state the lock responds to some of the queries, but times out on the interview process and leaves the lock not identified and unable to utilize the lock.

I tried this several times, and never did it seem to pay attention to the provisioning info I had typed in, nor would it successfully complete a secure inclusion.  

I even moved the module to a lock that is much closer to the coordinator (a zooz 700 stick), and had the same result there.  

### Expected behavior

That I could provision the lock using a camera scan of the QR code, or that it would use the DSK and other info in the provisioning entries table.  

### Additional context

I do have normal 500 series adapters for these doors, and this works OK to provision and use, though the lock is reported as the Yale YRM476.  One of the locks is located in an area where it has marginal signal, and even though I have placed repeaters nearby, this one lock doesn't seem to be reliable in accepting and responding to commands, though it seems to ping ok.  I figured I would try the 700 series module because it is supposed to have much better range.

**Comment by robertsLando** [comment]
> "Cannot initialize QR-code scanner: no available camera found".

Is it possible that for some reason your phone is blocking access to the cameras? I don't have Android but could be a setting problem on your browser.

>  So I snap a picture and then use the import option, I get "cannot read QR-Code"

The picture should not be too big (like just the qr code) or too small, try to place the qrcode in the center of the picture and with a correct size (like at most 1/4 of the photo)

> Now I get a "Error while calling parseQRCodestring: Invalid QR Code: invalid checksum (ZW1406).

This is a validation error of theQR, no clue what it could be. @AlCalzone for sure can help with that

> Next I tried entering the DSK code in the smart start option and made an entry in the provisioning entries table. The DSK code was recognized, but it's unclear what boxes are to be checked

Generally you should keep the boxes that are already checked and keep the others unckecked. The ones that are checked are the ones required by your device. Check: https://zwave-js.github.io/node-zwave-js/#/getting-started/security-s2?id=granting-security-classes

>  I manually enter the DSK, but before I can complete the process, the lock times out on the include side, and ZwaveJS UI then adds the lock with no security

This is a known problem with some lock devices, at least I already heard it but it's not related to zwave-js driver. The best would be to just include it with Smart Start so it includes itself without user interaction. Anyway again @AlCalzone can tell more about this.

**Comment by fresnoboy** [comment]
Thanks for the pointer to the zwave-js documentation - I was looking at zwavejs2mqtt and forgot it's a fork (?) of zwave-js.  That explains a lot about what the lock should want.

Is the ideal process for this device to add a provisioning entry in the smart start config?  I thought I did that, but it still prompted me to enter all the info interactively.  Could that be because I had not set the boxes properly?

**Comment by robertsLando** [comment]
> I was looking at zwavejs2mqtt and forgot it's a fork (?) of zwave-js

Nope the projectr has just been renamed

> Is the ideal process for this device to add a provisioning entry in the smart start config? 

Yes, once added there you don't have to do anything, the lock will add itself to the network (just need to wait some minute). No need to enable inclusion or else

> I thought I did that, but it still prompted me to enter all the info interactively. Could that be because I had not set the boxes properly?

Could be, retry

**Comment by fresnoboy** [comment]
@robertsLando I added the entry with the correct DSK, and then plugged the module in and power cycled the lock.  You right, not need to trigger an inclusion.  However it still didn't work.  Here's the log:

16:05:50.939 CNTRLR Received Smart Start inclusion request
16:05:50.941 CNTRLR NWI Home ID not found in provisioning list, ignoring request...
16:05:51.093 CNTRLR Received Smart Start inclusion request
16:05:51.095 CNTRLR NWI Home ID not found in provisioning list, ignoring request...
16:05:51.214 CNTRLR Received Smart Start inclusion request
16:05:51.216 CNTRLR NWI Home ID not found in provisioning list, ignoring request...

**Comment by fresnoboy** [comment]
So I realized now that the DSK on the module has 10 5 number groups in a 4x2 configuration.  I had tried at first going from left to right and then the 2nd row but that didn't work (it complained about not being a valid DSK).   So I had started entering it with top left, bottom left, etc... instead, but I think that was incorrect.  It still said it was a valid DSK, but with the flags being set wrong and trying to do the manual inclusion, and having it join with no security, it obscured the fact the DSK was wrong until I did the test this morning.

So I did another provisioning entry with the DSK entered top left to top right and then bottom left to bottom right, and low and behold, it provisioned and added correctly!  

I can't speak to why all the manual adding didn't work properly with the QR code scans etc.., but if you enter the right DSK, it does seem to add properly.

**Comment by fresnoboy** [comment]
Also, I can't seem to write user codes to this lock: 

2023-04-21 17:35:49.442 INFO Z-WAVE: Calling api writeValue with args: [
{
nodeId: 43,
commandClass: 99,
endpoint: 0,
property: 'userCode',
propertyKey: 2
},
2001,
{},
[length]: 3
]
2023-04-21 17:35:49.447 INFO Z-WAVE: Writing 2001 to 43-99-0-userCode-2
2023-04-21 17:35:49.452 ERROR Z-WAVE: Unable to write 2001 on 99-0-userCode-2
2023-04-21 17:35:49.454 INFO Z-WAVE: Success zwave api call writeValue false

Is this due to an issue with pairing or some other problem?

**Comment by AlCalzone** [comment]
You have to look at [driver logs](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` to diagnose that.
