### ISSUE TITLE
Add device info to compact view

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwave-js-ui#3060]
**Is your feature request related to a problem? Please describe.**
I was looking in the compact view (which is great btw) and saw a device with low battery. As I was mentally preparing to fetch a battery, I didn't know what to look for because I realized I didn't know what type of device it was. In the screenshot below, I clicked on the device in the compact view and got this modal.

The modal (which is what you see when expanding a node in the normal view) does _not_ contain any info on the device itself. No manufacturer, device model etc. I realize now that all that info usually is in the node table in the normal view.

I managed to find out what it was by deduction, and because the device id (`881-9-2..`) has a link to docs, which includes the device make/model.

**Describe the solution you'd like**
Some way of see what I'm looking at when in compact view. I think this can be done in many ways, maybe even some also benefitting the normal view:

* Add a text next to device id, see screenshot. I don't like this one.
* Add a menu point with "Device", see screenshot. "Device" will contain more info on the device itself
  * I'm dreaming, but does the z-wave db you have, include info on battery type and stuff like that? Could be cool to add this info under "Device".
* Like above, but put it under "Help". Help is pretty bare right now, especially for devices without a lot of text. Adding make/model/other info up top could make Help more .. helpful.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/1027111/233771558-1514a36b-f37e-4f26-b86b-071f635ca6e6.png)

Prototype, text next to device id:

![image](https://user-images.githubusercontent.com/1027111/233771903-d7b00cf9-3ad9-461c-b30f-9f1caa5cc7f9.png)

Prototype, add device menu point:

![image](https://user-images.githubusercontent.com/1027111/233772020-89c6ac06-e1a3-4002-83d9-eb742d215b52.png)

**Comment by robertsLando** [comment]
Done :)
