### ISSUE TITLE
Help with polling 

### ISSUE THREAD

**Issue by pvklink** [zwave-js/zwave-js-ui#3067]
Hi , just installed the latest docker image 8.14.2 on my rpi-4b with 64 latest bullseye.
Reason for installing zwave-js-ui is because i have to much trouble with domoticz and zwave.
I have played for two days, bricked a zwave controller and now finnaly have my config working, the basic.
I use domoticz, mqtt, and zwave-js-ui.

Problems i have:
1. My zwave device on the 2e floor is not found anymore, when i get them near the controller it works.
In the past this was solved by placing a good zwave device in the middle and let this one poll. I dont see any poll option anymore per device, 
@update
i understand that i have to add an "device value for polling per device".  
QUESTION: which value(s) do i have to add so that the device in the middle can check if its neighbours are there and comnmunicates for the device on the second floor to the controller?
The device on the 2e floor that cant be reached is a EUROTRONICS SPIRIT VALVE with battery

2. When i start "Network Graph" i see al my nodes. BUT, there are no lines between them after a day of waiting.
Does this has something to do with problem 1: polling? At least lines between nodes and controllers must be there ?

3. SOLVED: my sirene (Shenzen NEO Electronicz, siren alarm, NAS-AB01Z) 
        see https://devices.zwave-js.io/?jumpTo=0x0258:0x0003:0x0088:0.0
        did work in open zwave domoticz) does not work in zwave-js-ui.
        Devices are recognized but when enabling the switch in domoticz , no bell or alarm rings...

        log:
	When enable the sirene switch in domotics, this error exposes in the zwave-ui env
	2023-05-01 11:49:22.479 INFO MQTT: Message received on zwave/sirene/37/0/currentValue/set: 'true'
	2023-05-01 11:49:22.480 DEBUG GATEWAY: No writeable valueId found for sirene/37/0/currentValue
      @UPDATE: SOLVED!!  DID A RE_INTERVIEW and this works!

Forgot to say, but these docker is GREAT, dont want to go back anymore to earlier zwave solutions. So i must solve these last issues...

Thanks and the donation is coming.!

**Comment by robertsLando** [comment]
Hi @pvklink, sorry for the late reply but I was on vacation.

1. Did you tried to use an extension USB cable for your stick? This extremely easy solution improves connectivity a lot! Try with that first
2. Network graph can be incorrect sometimes, it needs a complete refactor as explained in #2517. So if you don't see any lines could be because not all nodes are reporting the right neighbors or else, but maybe if you fix point 1 this could be fixed too
3. Glad you solved the problem :)

**Comment by pvklink** [comment]
Hi Daniel, thanks for your reply, and a good holiday is more important then my domotica isssues 😊 Hope you had a nice time-out!
Lets focus on point one, meshing/polling irt my eurotronic spirit thermostat node thats on my second floor. 
All my other 5 non battery zwaves nodes work great, on floors 0, 1 and 2, So there must be good node to talk to.., 
but i understand that polling is by default off !!!

The Euro(troninc) did work on older open zwave installations within domoticz. 

I already use a usb cable on my rpi4 with docker zwave js, domoticz and mqtt

Scenario 1
When i add my zwave-js in include mode (on floor 0), my EURO on floor 2 does not recognize the include mode. 
There is a fibaro node on 2 floor that do works… SO perhaps polling could help here ?
Question is, what to enable to get polling on the fibaro right..to include and to let the EURO works ok…

Scenerio 2
Move the zwave stick, floor 0 to the EURO on floor 2, then include works!
But then the EURO asks to attache the EURO to the heater… and the sticks ends inclusion and goes off 
The stick  must be connected to the zwave-js on the 0 floor.

The node is recognised in zwave-js but is keeps informing. Heal etc. does not help…
When i ping the device it is recognized…so i cant remove it…

Question is:
How to attach a battery device
Can such a device use the polling options also with inclusion and what to do to get this working…

Peter


Verzonden vanuit Mail voor Windows

Van: Daniel Lando
Verzonden: dinsdag 2 mei 2023 08:46
Aan: zwave-js/zwave-js-ui
CC: peter van klink; Mention
Onderwerp: Re: [zwave-js/zwave-js-ui] Help with polling (Issue #3067)

Hi @pvklink, sorry for the late reply but I was on vacation.
1. Did you tried to use an extension USB cable for your stick? This extremely easy solution improves connectivity a lot! Try with that first
2. Network graph can be incorrect sometimes, it needs a complete refactor as explained in #2517. So if you don't see any lines could be because not all nodes are reporting the right neighbors or else, but maybe if you fix point 1 this could be fixed too
3. Glad you solved the problem :)

**Comment by robertsLando** [comment]
@pvklink I suggest you to try re-interview the node. 


BTW I think that what you need to setup is not poll but you want another device (that in your case must be main powered) to forward commands to the other device on second floor that has connectivity issues. 


So there is no way to specify this, it's something automatically handled by zwave protocol (the mesh network) so I can suggest to place that middle device and do a network heal or heal the main powered device and the battery one that has problems to make zwave protocol to update the routes

**Comment by pvklink** [comment]
Ok!
So i can delete the device value configs with polls enabled on the device in the middle ?

p.

Verzonden vanuit Mail voor Windows

Van: Daniel Lando
Verzonden: dinsdag 2 mei 2023 14:51
Aan: zwave-js/zwave-js-ui
CC: peter van klink; Mention
Onderwerp: Re: [zwave-js/zwave-js-ui] Help with polling (Issue #3067)

@pvklink I suggest you to try re-interview the node.
BTW I think that what you need to setup is not poll but you want another device (that in your case must be main powered) to forward commands to the other device on second floor that has connectivity issues.
So there is no way to specify this, it's something automatically handled by zwave protocol (the mesh network) so I can suggest to place that middle device and do a network heal or heal the main powered device and the battery one that has problems to make zwave protocol to update the routes

**Comment by pvklink** [comment]
Hi Lando,

Solved my problems, deleted the EUROTRONIC SPIRIT, seems to be a instable product (old version)
Last issue is that i the old situation with zwave in domoticz i changed the parameter of a node by executings a dzvents to the settings of this node
I think i have to do that with a mqtt message now…

Do you have an example of a (nodered) mqtt  message to update this value ?
When this is finished i migrated everything (except the radioatorvalve, that one is killed…”-))

See image and node info 28-112-0-7 , i want to set the alarm sound or doorbell sound
I added my gateway settings and mqtt settings 

I can make a message in nodered (or domoticz) but need some help with the content…
I think that the content structure has to do with settings i attached ?

Msg.topic = “xxxx”
msg.payload = [{"module":msg.module,"oscmd":msg.oscmd,"family":msg.family,"server":msg.server}];
return[msg]

THANKS !

Peter van Klink
Holland

Van: Daniel Lando
Verzonden: dinsdag 2 mei 2023 16:00
Aan: zwave-js/zwave-js-ui
CC: peter van klink; Mention
Onderwerp: Re: [zwave-js/zwave-js-ui] Help with polling (Issue #3067)

So i can delete the device value configs with polls enabled on the device in the middle ?
Yeah! It's useless and creates useless traffic too

**Comment by robertsLando** [comment]
>  i changed the parameter of a node by executings a dzvents to the settings of this node

Could you tell me what valueId you want to change using mqtt? Set values is really easy, see [docs](https://zwave-js.github.io/zwave-js-ui/#/guide/mqtt?id=set-values)

**Comment by pvklink** [comment]
Hi Daniel,

Need some last help with nodered..
Will publish my settings on the forum when it works, so others can use it 😊

I had the config working but not well documented and after some hangings i installed everything clean
Now i 
- Can switching zwave devices on or off from with domoticz with build in mqtt discovery interface, works fine, also with separate mqtt server on port 1884
- But my nodered config does not work anymore


MY SETTINGS
(think it has something to do with the GATEWAY settings irt my nodered msg)

Her are they!

Docker/mqtt
- I made a separe server/docker for z zwave mqtt to isolate the zwave messages from my solar panels
i have a lot of msg and my domotica went to slow. So i splitted my msg in two mqtt servers.
The zwave mqtt server is on port 1884 and seems to work

My zwave js config
- MQTT
-name: zwave-js-ui
-<ip>
-port 1884
- prefix zwave
-QOS 1
-reconnect 3000
-retain and store FALSE
- CLEAN and AUTH TRUE and name/pwd filled

- GATEWAY
- ValueID Topic
- JSON Time VALUE
- Use node name instead of numeric TRUE
- ignore location TRUE
- send ZWAVE events FALSE
- IGNORE status updates FALSE
- INCLUDE node info TRUE
- Publish node details TRUE
- MY object to change (with a NR msg)
- name sirene
-has a propertu [28-112-0-7]  Default siren sound (1 = siren, 2 is doorbell THIS ONE TO CHANGE
- HOME ASSISTANT
Discovery prefix: domoticz
MQTT discovery ON
WS server and retained discovery OFF

NODERED
- Injector node, to give the stream a kick
- Function node with the actual msg

msg = {}    // deurbel 1 or sirene 2
       msg.topic = "zwave/sirene/112/0/7/set"
msg.payload = { "value": 1 }
       return [msg]

- MQTT node to publish it to: settings
- TOPIC <empty>
- QOS and REATIN empty
- IP <> and port 1884
- connect auto, no TLS
- protocol MQTT v3.1.1.
- no clientid
- keep alive 60
- use clean session TRUE
- security <username/pwd>
