### ISSUE TITLE
Unable to stop level change on CCs that allow starting a level change

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js-ui#3075]
For example these 2:
![image](https://user-images.githubusercontent.com/17641229/236309468-35f550a2-a492-49b6-ac78-951b09e80cd6.png)

setting the value to `true` starts the level change, setting it to `false` stops it.

This probably needs some modification to the value metadata, so Z-UI can distinguish which "buttons" need to be split into mulitple.

**Comment by robertsLando** [comment]
> This probably needs some modification to the value metadata, so Z-UI can distinguish which "buttons" need to be split into mulitple.

Let me know when you do this

**Comment by robertsLando** [comment]
Ref #3089
