### ISSUE TITLE
The buttons are backwards on the lock schedule refresh "do you want to use the cache?" dialog

### ISSUE THREAD

**Issue by kdknigga** [zwave-js/zwave-js-ui#3093]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.16.1

### ZwaveJS version

10.20.0

### Describe the bug

![image](https://github.com/zwave-js/zwave-js-ui/assets/13860800/bc18d9e3-b4cb-43e3-b578-e176db406cac)

In the "Refresh schedules... Do you want to query the schedules..." dialog, clicking "Yes" results in:

`2023-05-19 16:20:15.333 INFO Z-WAVE: Calling api getSchedules with args: [ 87, { fromCache: true }, [length]: 2 ]`

Clicking "Cancel" results in:

`2023-05-19 16:21:07.463 INFO Z-WAVE: Calling api getSchedules with args: [ 87, { fromCache: false }, [length]: 2 ]`

### To Reproduce

Click 'Yes' or 'Cancel'.

### Expected behavior

The question is unclear.  Perhaps the "Yes" button should instead read "Use Cache", while "Cancel" should instead read "Query Device".

**Comment by robertsLando** [comment]
Thanks @kdknigga
