### ISSUE TITLE
Zwave stick showing are incorrect product code

### ISSUE THREAD

**Issue by calebcall** [zwave-js/zwave-js-ui#3096]
I have an Aeotec ZStick 7.  It's been working fine for months.  However, while troubleshooting some issues recently, I noticed it's showing in the UI as ZST10-700 for the product code.  I believe that's the Zooz 700 series stick.  Does this incorrect product code matter?  I believe the zwave chipset is the same, right?  So firmware will be the same.

FW: 7.19.2
SDK: 7.19.2

<img width="2470" alt="Screenshot 2023-05-21 at 1 03 08 PM" src="https://github.com/zwave-js/zwave-js-ui/assets/1132262/d7011621-37f8-4528-beb4-37041ad252ec">

**Comment by robertsLando** [comment]
No clue sincerly but @blhoward2 / @AlCalzone may know

**Comment by AlCalzone** [comment]
Yeah, I've been thinking of changing that. It's just a purely cosmetical issue though.

**Comment by blhoward2** [comment]
I thought we had changed that already a long time ago? Maybe it's just because sticks don't reinterview? 

Mine says "Silicon Labs - 700 Series-based Controller"

**Comment by AlCalzone** [comment]
> Mine says "Silicon Labs - 700 Series-based Controller" Unless it got changed back...

Correct that's the description field. The label is unchanged though.

**Comment by ridizy** [comment]
I'm having a similar issue with a new Zooz ZST10 700 that was migrated from a HUSBZB-1 using the NVM backup/restore process.  Here is what shows in my UI:

<img width="1350" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/33641/adf0052e-29d4-43ef-bf2b-f4905b81948d">

**Comment by AlCalzone** [comment]
Fixed by zwave-js/node-zwave-js#6022
