### ISSUE TITLE
Add Sync'ing of User Codes Across Locks

### ISSUE THREAD

**Issue by barndawgie** [zwave-js/zwave-js-ui#3110]
**Is your feature request related to a problem? Please describe.**
I have a handful of ZWave locks and in order to manage codes across all of them need to repeat the same additions/removals of codes for each one.

**Describe the solution you'd like**
I'd love a way to manage my user codes and have ZWave JS propagate/synchronize them to all nodes.

**Describe alternatives you've considered**
Manually updating all of them.

**Additional context**

**Comment by robertsLando** [comment]
What about a driver function?

**Comment by barndawgie** [comment]
> What about a driver function? 

Sorry - I'm not sure what that means. Is there a doc you can point me at?

**Comment by barndawgie** [comment]
Was thinking of something similar to https://github.com/FutureTense/keymaster, FYI

**Comment by robertsLando** [comment]
Driver function allows you to write custom async functions and give you access to all the instances created in the backend.

You can call it from Control Panel > Advanced > Driver Function


This is an example function you can use:

```
// replace `undefined` with the id of the node you want to clone
const node = driver.controller.nodes.get(undefined);

// list here all the nodes ids you want to copy configuration to
const clonedNodes = [].map(n => driver.controller.nodes.get(n));

const values = node.getDefinedValueIDs()

for (const clonedNode of clonedNodes) {
  for(const v of values) {
  	if(v.commandClass === 0x63) {
  		await clonedNode.setValue(v, 
  		  node.getValue(v)
  		)
  	}
  }
}
```

Then just press on `RUN` to run it

**Comment by robertsLando** [comment]
I don't understand your question, user codes are valueIds, in this snippet I simply clone all writeable values associated to Command Class UserCodeCC

**Comment by robertsLando** [comment]
As you imagine you can edit and improve this snippet as you want but it should do the trick as it is (locks should be of the same manufacturer/model btw otherwise you could end up writing value that doesn't exist and that would throw error). Also you could skip write of empty user codes. Anyway let me know if it works
