### ISSUE TITLE
GE 45606 / ZW3001 in-wall paddle dimmer doesn't report correct state

### ISSUE THREAD

**Issue by mhendu** [zwave-js/zwave-js-ui#3119]
Problem/Motivation
While this worked correctly with my old Vera hub, with Z-Wave JS UI the GE 45606 dimmer switch often does not show the correct device state.

Expected behavior
If the light is turned on, it should show as on in the UI.

Actual behavior
The light is turned on but shows as off in the UI.

Steps to reproduce
If the light is on, restart Home Assistant and it will invariably show as being turned off.

Proposed changes
Correctly detect the device state and display it properly.

**Comment by mhendu** [comment]
I toggled the switch on and off manually repeatedly, and it's currently off but reporting a value of 47% in both Home Assistant and Z-Wave JS UI. So it's not the first issue. The logs show a number of values from when I was pressing on the switch, so it is getting updates, just not always reflecting the current value.

I don't know what a Lifeline group is, but when I look at Groups in the UI it shows 'No data available.'

The link you sent didn't really describe how to enable polling, but I did find it here:

https://zwave-js.github.io/zwave-js-ui/#/device-support/polling

From there I was able to set a polling interval of 10s and it found that the switch was turned off. I'm assuming this should work then, but if there's a better preferred approach would appreciate the advice.

**Comment by mhendu** [comment]
1.13.3

**Comment by robertsLando** [comment]
That's the addon version, I need the version of zwave-js-ui. You copy/paste it from the info icon in top bar, on the right

**Comment by mhendu** [comment]
zwave-js-ui: 8.18.0
zwave-js: 10.23.1

**Comment by cornellrwilliams** [comment]
> When I look at Groups in the UI it shows 'No data available.

This is an association issue. If no associations are set when you physically turn the light on and off it will not report information to Z-Wave JS UI.  I verified this with several of my own devices. Here's two pictures that show what should and shouldn't see on the groups page.

![3fbdb6e46b68fa323f56c5c214be5bb8af754d36_2_690x302](https://github.com/zwave-js/zwave-js-ui/assets/92619869/8c66689a-883b-4d74-bfbf-db005545da03)
![950a469031ef8cdbbba6e79c24fa2116b2fa390f_2_690x302](https://github.com/zwave-js/zwave-js-ui/assets/92619869/2616d556-03a9-453b-92a8-0d8501e7e824)

**Comment by mhendu** [comment]
That doesn't seem to be the case for me - when I toggle the switch on/off manually it does report values to Home Assistant, but it doesn't necessarily report every value. So if I toggle it on and off several times in succession I'll see activity in the logs but the end state may not be reported correctly, which is where polling helps.
