### ISSUE TITLE
Suggest adding the default URL of a0d7b954-zwavejs2mqtt to the docs instead of localhost

### ISSUE THREAD

**Issue by zachfeldman** [zwave-js/zwave-js-ui#3120]
It took me forever to find this in the Home Assistant docs that the URL is ws://a0d7b954-zwavejs2mqtt:3000 instead of ws://localhost:3000. In fact, I don't see this URL anywhere in https://zwave-js.github.io/zwave-js-ui/#/usage/setup?id=home-assistant.

I'd be happy to make a pull request to https://github.com/zwave-js/zwave-js-ui/blob/master/docs/homeassistant/homeassistant-official.md if you agree but maybe there's a reason you're not putting this URL in?

Thanks for your consideration.

**Comment by jmgiaever** [comment]
Hi,

I guess that's simply because this project is not in any way related to the HA addon. But yes, you should make a PR with the HA repository with your suggested changes.

**Comment by zachfeldman** [comment]
Thanks both - I added it in a PR here in case you think this is worth of inclusion. I just think this will make some folks' lives easier if they were looking at the Home Assistant section of your docs!

Glad to change the formatting or anything.
