### ISSUE TITLE
Statistics are limited to rating only when doing multiple rounds of health checks

### ISSUE THREAD

**Issue by darkbasic** [zwave-js/zwave-js-ui#3127]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.18.0

### ZwaveJS version

10.23.1

### Describe the bug

When doing multiple rounds it's very annoying not being able to see results until all of them have been finished:
![image](https://github.com/zwave-js/zwave-js-ui/assets/1047358/bd845dab-ac3e-4f65-b10f-8f2921ed53df)

Since the server already returns the rating after each sound I guess it should be possible to retrieve the remaining stats as well.

### To Reproduce

Click on Network Graph, any node, diagnose, select multiple runs, start.

### Expected behavior

All of the stats should be returned after each run.

### Additional context

The browser is Chromium and the screen resolution is 2560x1440, OS is Gentoo Linux ppc64le (Raptor CS Talos 2).

**Comment by robertsLando** [comment]
Same of the other issue, follow updates of: https://github.com/zwave-js/node-zwave-js/issues/4075
