### ISSUE TITLE
Cannot stop health check once started

### ISSUE THREAD

**Issue by darkbasic** [zwave-js/zwave-js-ui#3128]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.18.0

### ZwaveJS version

10.23.1

### Describe the bug

Once you start an health check it's impossible to stop it, which is especially annoying if you are doing multiple rounds:
![image](https://github.com/zwave-js/zwave-js-ui/assets/1047358/3bd58766-311f-493f-8842-c403c5ce7d10)

Clicking on the close button doesn't stop it.

### To Reproduce

Click on Network Graph, any node, diagnose, select multiple runs, start, close. Then look at the looks: it's still running.

### Expected behavior

Either close should stop the health check or a stop button should be added.

### Additional context

The browser is Chromium and the screen resolution is 2560x1440, OS is Gentoo Linux ppc64le (Raptor CS Talos 2).

**Comment by robertsLando** [comment]
cc @AlCalzone
