### ISSUE TITLE
Store download via HTTP API - How to authenticate?

### ISSUE THREAD

**Issue by muhlba91** [zwave-js/zwave-js-ui#3133]
Hi,

I'm trying to implement a simple remote backup/restore solution and my idea was to target the exposed APIs.

1. According to https://github.com/zwave-js/zwave-js-ui/blob/master/app.ts#L1353 there should be an API to download the backup archive.
2. Similarly, I can use https://github.com/zwave-js/zwave-js-ui/blob/master/app.ts#L1368 with setting the parameter `restore` to restore an archive.

Are my findings correct so far?

---

Now, I tried to work with authentication, and can successfully retrieve a token by running `curl -X POST https://.../api/authenticate -H "Content-Type: application/json" -d '{ "username": "user", "password": "password" }'`.

However, I entirely fail to call any of the APIs.

According to https://github.com/zwave-js/zwave-js-ui/blob/master/app.ts#LL725C27-L725C41 I assume that setting a header like `Authorization: Bearer <token>` or `x-access-token: Bearer <token>` should work.

My curl requests look like this: `curl https://.../api/settings -H "Authorization: Bearer <token-from-authenticate-request>" -H "Accept: application/json"` (Note: I also tried using `x-access-token`, or any other API endpoint without success.)

I always receive `{"success":false,"message":"General Error","code":3}`

---

Could you point me to what I am missing here, or how I can achieve this?

**Comment by robertsLando** [comment]
@muhlba91 Could you check logs to see the reason of the general error?

**Comment by muhlba91** [comment]
@robertsLando sure, but unfortunately this doesn't tell a lot - i also wasn't able to find any [env var](https://zwave-js.github.io/zwave-js-ui/#/guide/env-vars) allowing debug logging or similar.

```
2023-06-08 08:42:56.724 INFO APP: GET /api/settings 200 10.213 ms - 52
2023-06-08 08:42:57.730 ERROR APP: Unhandled Rejection, reason: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```

**Comment by robertsLando** [comment]
Do you have any proxy in the middle or else? I never faced this issue, did you also tried doing it with nodejs/python just to see if it works there?

**Comment by muhlba91** [comment]
There's a traefik in between which is handling SSL termination. However, I don't believe this should have an effect since the UI works without any issues, and all other applications handled by it as well.

---

I tried the same with the Python `requests` module - no luck either.

Logs with the Python try:
```
2023-06-13 06:23:44.416 INFO APP: User admin logged in successfully from X.X.X.X
2023-06-13 06:23:44.425 INFO APP: POST /api/authenticate 200 220.670 ms - 221
2023-06-13 06:23:44.460 INFO APP: GET /api/settings 200 1.608 ms - 52
```

Python code:
```python
import requests

url = 'https://domain.com/api'
auth = { 'username': 'admin', 'password': 'XXXX' }

token = requests.post(url + '/authenticate', json = auth, headers = { 'Content-Type': 'application/json' }).json()['user']['token']
print(token)

settings = requests.get(url + '/settings', headers = { 'Accept': 'application/json', 'Authentication': 'Bearer ' + token })
print(settings.json())
```

Output:
```
<JWT TOKEN>
{'success': False, 'message': 'General Error', 'code': 3}
```

**Comment by robertsLando** [comment]
I did a test using [insomnia](https://insomnia.rest) and it works:

![Schermata da 2023-06-13 17-21-43](https://github.com/zwave-js/zwave-js-ui/assets/11502495/1daa923b-86c9-4599-871a-52ac0532f368)

**Comment by muhlba91** [comment]
@robertsLando i have raised the PR #3140 which fixes this issue. could you please have a look, and provide feedback?

**Comment by robertsLando** [comment]
The fix looks good to me, I dunno why I never faced that issue BTW
