### ISSUE TITLE
Snap missing serial-port

### ISSUE THREAD

**Issue by Louis-Xavier** [zwave-js/zwave-js-ui#3135]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Z-Wave JS UI version

v8.17.1

### ZwaveJS version

last/stable

### Describe the bug

cmd:> zwave-js-ui.enable
Missing plug: «serial-port»

### To Reproduce

root@pi4:~# 
root@pi4:~# snap connect zwave-js-ui:raw-usb
root@pi4:~# snap connect zwave-js-ui:hardware-observe
root@pi4:~# snap interface serial-port
name:    serial-port
summary: allows accessing a specific serial port
plugs:
  - zwave-js-ui
root@pi4:~# zwave-js-ui.enable
Missing plug: «serial-port»
Service enabled!
- If you have turned OFF «log to file», follow logs with:
  $ snap logs zwave-js-ui -f
- If you have turned ON «log to file», follow logs with:
  $ tail -f /var/snap/zwave-js-ui/189/*.log

root@pi4:~# snap set system experimental.hotplug=true
root@pi4:~# systemctl restart snapd
root@pi4:~# snap interface serial-port
name:    serial-port
summary: allows accessing a specific serial port
plugs:
  - zwave-js-ui

### Expected behavior

to connect to my usb aeon stick

**Comment by jmgiaever** [comment]
Hi. Are you sure you need this plug? Have you tried without it, with the options listed within ZUI? So far I only know about GPIO devices that need this, such as RazBerry HATs.

**Comment by Louis-Xavier** [comment]
Hi, are started the process without snap (ie bare metal) without any issue. So permission issue using snap (it was working for the last 2 years without any issue) to access the /dev usb device

**Comment by jmgiaever** [comment]
Which permission issues are you referring to? Nothing in your issue explains it.

**Comment by jmgiaever** [comment]
@robertsLando I think you can close this as I think TS have misunderstood the concept of `serial-port` and that this issue is none-related to ZUI itself nor the snap package.

**Comment by robertsLando** [comment]
👍🏼 Thanks @jmgiaever
