### ISSUE TITLE
ZWave-JS-UI >=8.2.0 does not start on docker on RPI4 under Ubuntu 22.04

### ISSUE THREAD

**Issue by olivierboudet** [zwave-js/zwave-js-ui#3138]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

\>=8.2.0

### ZwaveJS version
  
\>=8.2.0

### Describe the bug

I am using ZWaveJS-UI on Ubuntu 22.04 and run it on docker.
It works well with version 8.1.0 but not version 8.2.0 and higher, which exit with code 132.
There is no log at all.

### To Reproduce

```
docker run --net=host --name zwavejsui zwavejs/zwave-js-ui:8.18.0
docker inspect zwavejsui | grep "ExitCode"
```

### Expected behavior

It should start successfully.

**Comment by robertsLando** [comment]
https://github.com/zwave-js/zwave-js-ui/issues/2725

**Comment by olivierboudet** [comment]
I saw this issue, but : 
- I am on Ubuntu 22.04, based on debian bookworm I think (not on buster)
- I already have the libseccomp2 installed
- I do not have this log : 
```
#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ed0149c
```
In fact I have no log at all

**Comment by robertsLando** [comment]
Giving that this happens starting on the exact version 8.2.0, in an rpi, I really think the error is related to that.

Unfortunately the only way to reproduce that would be having your rpi with your OS and I don't have it, I would need at least some log or else that tells me what is causing the error
