### ISSUE TITLE
User is not prompted to grant security classes or enter PIN when inclusion is not started manually

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js-ui#3141]
When an inclusion controller includes a node and the driver calls the `inclusionUserCallback`s, the user is not prompted to do anything. This is a node that's being included by another controller (so the user did not open the "include node" dialog before):
![grafik](https://github.com/zwave-js/zwave-js-ui/assets/17641229/9da035fa-deaf-4f92-8a92-9bd9dc0f8790)

The application logs show that the `grantSecurityClasses` callback was called by the driver:
```
2023-06-14 15:18:22.246 INFO Z-WAVE: [Node 004] Found
2023-06-14 15:18:22.613 INFO Z-WAVE: Grant security classes: { securityClasses: [ 0, 1, 7, [length]: 3 ], clientSideAuth: false }
```

but then nothing happens. 4 minutes later, bootstrapping is aborted:
```
2023-06-14 15:22:22.623 WARN Z-WAVE: Inclusion aborted
2023-06-14 15:22:22.682 DEBUG Z-WAVE: [Node 004] Binding to node events
2023-06-14 15:22:22.683 DEBUG Z-WAVE: [Node 004] Has been added to nodes array
2023-06-14 15:22:22.684 INFO Z-WAVE: [Node 004] Added with security None
```

**Comment by robertsLando** [comment]
Yeah I have not handled this yet

**Comment by robertsLando** [comment]
I think the solution to this is to move the DialogNodeManager component to App.vue and add a socket event listener for grantSecurityClasses, once that event is triggered and the dialog is not already opened open it and direct the user to the grant step

**Comment by robertsLando** [comment]
Also:

Use `updateOptions` to setup/remove callbacks when there is at least one user connected to socket

**Comment by AlCalzone** [comment]
As discussed with @marcelveldt and @robertsLando we think the best course of action will be:
1. `zwave-js-server` and Z-UI change the callbacks dynamically. Z-UI takes over when the UI is open, `zwave-js-server` otherwise.
2. `zwave-js-server` exposes a method Z-UI can call to have the server set/restore its own user callbacks. Maybe `setInclusionUserCallbacks()`.
3. Z-UI will call this to hand over control, either when initializing the server while the UI is not open, or when the UI gets closed.
