### ISSUE TITLE
Next Page Navigation Button Obscured by Floating Hamburger Button

### ISSUE THREAD

**Issue by The00Dustin** [zwave-js/zwave-js-ui#3147]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.18.1

### ZwaveJS version

10.23.2

### Describe the bug

When in the table (not `COMPACT`) view of the `Control Panel` page on a desktop browser with more than 10 devices, one cannot switch to the next page because the floating hamburger menu button completely covers the right arrow while scrolled all the way down.  Scrolling up slightly makes the button visible, but attempts to click it still trigger the floating hamburger menu instead.

### To Reproduce

Add at least 10 devices and set the `Rows per page:` dropdown to 10.

### Expected behavior

I should be able to go to the next page to see more devices.

### Additional context

As a workaround one can increase the number of rows per page or switch to compact view.

**Comment by robertsLando** [comment]
@The00Dustin Will fix this ASAP!
