### ISSUE TITLE
Allow endpoint configuration values to be changed through GUI

### ISSUE THREAD

**Issue by jasonwragg** [zwave-js/zwave-js-ui#3151]
**Is your feature request related to a problem? Please describe.**
I have a SES 302 Secure Meters Temperature sensor which has config option for each end point, at the moment you can only configure those options on the first endpoint.

**Describe the solution you'd like**
Be able to edit the configuration values on each endpoint

**Describe alternatives you've considered**
Any that means i can change the values.

**Comment by jasonwragg** [comment]
![Screenshot 2023-06-26 144615](https://github.com/zwave-js/zwave-js-ui/assets/53080867/56691930-89da-40cb-b090-1f5aa7365dde)

**Comment by robertsLando** [comment]
@jasonwragg You should be able to do that with latest version

**Comment by jasonwragg** [comment]
Is it in the latest docker container? I'm not seeing and option for it.

**Comment by robertsLando** [comment]
Check you are using version 8.19.0, yes it's available both on docker and github containers

**Comment by jasonwragg** [comment]
![image](https://github.com/zwave-js/zwave-js-ui/assets/53080867/5cacb55a-51b4-46c7-9e01-290d807acee1)
This is what I'm seeing, am I doing something wrong? 

I'm on verison 8.19.0

**Comment by robertsLando** [comment]
@jasonwragg It could be that your device configuration hasn't been updated with the configurations on the endpoints. Could you paste here the device id / link you can find in the ui please?

cc @AlCalzone

**Comment by jasonwragg** [comment]
Is this it? https://devices.zwave-js.io/?jumpTo=0x0059:0x000d:0x0002:1.0

**Comment by robertsLando** [comment]
Yeah

**Comment by AlCalzone** [comment]
Ohh... I only updated the SES303, not 302

**Comment by AlCalzone** [comment]
@jasonwragg does the device actually have parameters 3 and 4 (humidity)? Our existing config file claims this is just a temperature sensor, not temperature + humidity. Your manual says otherwise.

**Comment by jasonwragg** [comment]
@AlCalzone no mine doesnt have humidity I think the manual is for 2 different models.

**Comment by AlCalzone** [comment]
Perfect, this should be fixed in the next release
