### ISSUE TITLE
Lock Schedule Cache isn't being read correctly

### ISSUE THREAD

**Issue by kdknigga** [zwave-js/zwave-js-ui#3159]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

YES, BUT a Z-Wave JS UI developer has told me to come here

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

Refreshing a node's lock schedule from cache loads nothing.

![Peek 2023-05-19 13-55](https://github.com/zwave-js/node-zwave-js/assets/13860800/d7e5abbe-5b15-4185-9d1a-c802a662dae6)

What did you expect to happen?
I expected to see the schedule I had created.

### Device information

Manufacturer: 
Model name: 
Node ID in your network: 

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
zwave-js-ui: 8.16.1
zwave-js: 10.20.0

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

[zwavejs_2023-05-19.log](https://github.com/zwave-js/node-zwave-js/files/11520194/zwavejs_2023-05-19.log)

**Comment by AlCalzone** [comment]
Another update: After reloading the entire page, the information is now there:
![grafik](https://github.com/zwave-js/zwave-js-ui/assets/17641229/4227dd5d-b423-4b25-b7a2-130c0b8495e8)

**Comment by AlCalzone** [comment]
The `enabled` state isn't correct though, even after pressing "ENABLE" a few times. The information from cache is correct:
```
2023-07-10 12:16:52.417 INFO Z-WAVE: Calling api driverFunction with args: [
  'const { logger, zwaveClient, require } = this\n' +
    'const {ScheduleEntryLockCC} = require("zwave-js");\n' +
    'const node = driver.controller.nodes.get(2);\n' +
    'const enabled = ScheduleEntryLockCC.getUserCodeScheduleEnabledCached(\n' +
    '  driver, node, 1\n' +
    ');\n' +
    'console.log("enabled:", enabled);',
  [length]: 1
]



enabled: true
```

but the UI doesn't think so:
![grafik](https://github.com/zwave-js/zwave-js-ui/assets/17641229/8dbe1b53-4185-4f5a-a76f-2201e61d3947)
