### ISSUE TITLE
Feature request: Add a list of recently executed driver functions

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js-ui#3160]
**Is your feature request related to a problem? Please describe.**
I often find myself debugging something with a driver function. Those take a while to write, then I go check something else and when I need the driver function again, it is gone if I didn't first save it elsewhere. So I start from scratch or try to reproduce it from the UI logs.

**Describe the solution you'd like**
A list of recently executed driver functions. When selecting one, it gets put into the code editor. I guess 10 or so should be enough.

**Describe alternatives you've considered**
none

**Additional context**
\-

**Comment by jmgiaever** [comment]
`+1` from me. 

I also think it would be a neat feature if you have loaded a saved snippet/script from the store and made a change to the file, that you can save the changes.
