### ISSUE TITLE
Zooz Zen16 Does not report state changes in zwavejs or to hass when using switches

### ISSUE THREAD

**Issue by marksmanaz** [zwave-js/zwave-js-ui#3171]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.20.0

### ZwaveJS version

11.42.2

### Describe the bug

Updates to latest version of zwavejs and now Zooz Zen16 realy states are no longer reflected in zwavejs ui when using a physical switch

### To Reproduce

use a wire to jump dry contact for each switch, none of the relay/switch states change in the ui

### Expected behavior

When using a switch to turn a relay off and on zwave ui would reflect these changes to the relay state in the ui and pass it on to hass. 

### Additional context

The main switch in the ui turns on the three relays but does not change the indicators for the relays in the ui for all relays

**Comment by robertsLando** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

**Comment by marksmanaz** [comment]
My apologies, the issue is resolved by updating the Zen16 firmware to V1.20.1 which Addressed issues with reporting when relays are triggered via Sw inputs when Multirelay is added with S2U security on select platforms.
