### ISSUE TITLE
Unable to removed failed node.

### ISSUE THREAD

**Issue by hmjgriffon1** [zwave-js/zwave-js-ui#3189]
So I added a device and it created a duplicate that was broken. I excluded the device and re included it and it added successfully but the old broken duplicate remains. In the network graph it says FAILED: next to this device but it shows fine in the control panel, other than having a last active date from 5 days ago. I am unable to remove it by clicking remove failed nodes. I also don't understand why it hasn't been marked failed or dead not having checked in for 5 days.

**Comment by robertsLando** [comment]
> I am unable to remove it by clicking remove failed nodes. I also don't understand why it hasn't been marked failed or dead not having checked in for 5 days.

This is a known bug of version 8.21. Did you tried to upgrade to latest? 8.21.2

**Comment by hmjgriffon1** [comment]
Nope, I see it, but since this is my security system I will try when I get home, thanks!

**Comment by robertsLando** [comment]
Let me know

**Comment by hmjgriffon1** [comment]
this worked, thanks!

**Comment by robertsLando** [comment]
Thanks for your feedback, glad it worked :)
