### ISSUE TITLE
Node properties panel of network map not fully visible in certain resolutions

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js-ui#3191]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.21.2

### ZwaveJS version

11.6.0

### Describe the bug

On my laptop display I cannot fully see the Node properties panel in the network map. This makes it difficult to access the Diagnostics, Heal, and Ping buttons. The support banner is covering it.

The laptop resolution is 1920x1080 with 150% scale.

### To Reproduce

Set resolution small enough. My laptop is 1920x1080 with 150% scale.

### Expected behavior

The controls are fully visible.

### Additional context

This is my web browser fully maximized (cropped for privacy). You can see the buttons truncated.

![image](https://github.com/zwave-js/zwave-js-ui/assets/791794/b69eeca0-0944-4b2b-b06c-90ee0d0a4991)

Here is the same with the banner removed.

![image](https://github.com/zwave-js/zwave-js-ui/assets/791794/87b78f17-e85a-4701-972a-9ee89ed4aa21)

It seems the size calculation of the panel doesn't account for the support banner?

**Comment by robertsLando** [comment]
@kpine what browser is that?

**Comment by robertsLando** [comment]
What I don't understand is would you like to have it above the footer? In you first screenshot you should just drag the node panel a little bit up to see the controls

**Comment by robertsLando** [comment]
Ok so that's the issue so, maybe I should extend the drag area to allow you to drag it up?

**Comment by robertsLando** [comment]
> I also just realized that I can move the node properties window and make the bottom revealed. It would be nice if it were accessible by default, as it needs to be moved every time you select a node (position not persisted), but that basically solves the issue...

Yeah that's what I asked you in my comment above, the panel is draggable :) I could try to save the panel position so when you reopen it it stay there. What do you think?
