### ISSUE TITLE
Cannot get RaZberry rev. 2 GPIO RazBerry hat working / zwave-js-ui dont detect serial port

### ISSUE THREAD

**Issue by AlfaBravoX** [zwave-js/zwave-js-ui#3192]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Z-Wave JS UI version

8.19.0.487524b

### ZwaveJS version

11.0.0

### Describe the bug

On raspberry pi 2 board  version ```a01041``` with 32 bit Rasbian Stretch I am trying to make RaZberry hat working with no success ending by this message:

```
Driver: Failed to open the serial port: Error: Operation not permitted, cannot open /dev/ttyAMA0 (ZW0100)
```

```
zwave-js-ui: 8.19.0.487524b
zwave-js: 11.0.0
```

```
zwave-js-ui.help
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Missing plug: «serial-port»
zwave-js-ui - v8.19.0

IMPORTANT! The DAEMON/SERVICE is disabled by default after installation.
You have to manually 'daemonize' it with executing the command

$ zwave-js-ui.enable

Set your configuration as descrived below

Server configuration values: {
	"server": {
		"force-disable-ssl": false,
		"host": "0.0.0.0",
		"port": 8091,
		"ssl": false
	}
}

- server.ssl: Use secure communication
- server.host: IP address to bind to, e.g 127.0.0.1
- server.port: Port to reach the web interface

Session configuration values: {
	"session": {
		"cookie-secure": "",
		"secret": "83702340-2ca5-11ee-removed-83d0c18a2d51"
	}
}

- session.secret: Used as secret for session. If not provided a default one is used.
- session.cookie-secure: Set the cookie secure option. See: https://github.com/expressjs/session#cookiesecure

Session configuration values: {
	"mqtt": {
		"name": ""
	}
}

- mqtt.name: The name used as client name when connecting to the mqtt server.

Set options with:         $ snap set zwave-js-ui param=key
For example:              $ snap set zwave-js-ui server.host=0.0.0.0

Other settings can be set in the UI after start.

If you have turned OFF «log to file», follow the log(s) with
  $ sudo snap logs zwave-js-ui -f

OR if you have turned ON «log to file», tail the logs with
  $ tail -f /var/snap/zwave-js-ui/198/*.log

Other commands
Disable the daemon:       $ zwave-js-ui.disable
Restart the daemon:       $ zwave-js-ui.restart

Info on the serial-port plug:
 This plug requires the experimental hotplug feature in snapd.
 Enable it with
  $ sudo snap set system experimental.hotplug=true

 And restart snapd with:
  $ sudo systemctl restart snapd

 Now list available serial slots with:
  $ sudo snap iterface serial-port

 And connect it to zwave-js-ui with:
  $ sudo snap connect zwave-js-ui:serial-port <slot name>
```

It looks snap in unable to see /dev/ttyAMA0 device as it is not listed

```
sudo snap interface serial-port 
name:    serial-port
summary: allows accessing a specific serial port
plugs:
  - zwave-js-ui
```

I also modified  /boot/config.txt

```
force_turbo=1
enable_uart=1
```

My concern is if this is snap or zwave-js-ui issue.

Please advise 

### To Reproduce

install snap and zwave-js-ui on RPI 2 board, run zwave-js-ui on port 8091 and try to connect to RaZberry shield

### Expected behavior

RPI will be able to access RaZberry shield on ttyAMA0 device

**Comment by jmgiaever** [comment]
You have to connect with the `pi:bt-serial`

**Comment by AlfaBravoX** [comment]
thanks

adding:

```sudo snap connect zwave-js-ui:serial-port pi:bt-serial```

results with:

```error: snap "pi" is not installed```

can you advise further?

**Comment by jmgiaever** [comment]
Can you check

```
sudo snap connections pi
```

and give me the output.

**Comment by jmgiaever** [comment]
You're running this on a raspberry pi, yes?

**Comment by AlfaBravoX** [comment]
> You're running this on a raspberry pi, yes?

yes, on raspberry pi 2 board version a01041 with 32 bit Rasbian Stretch. No BT on board.

**Comment by AlfaBravoX** [comment]
> Can you check
> 
> ```
> sudo snap connections pi
> ```
> 
> and give me the output.

```
sudo snap connections
Interface         Plug                          Slot                   Notes
hardware-observe  zwave-js-ui:hardware-observe  :hardware-observe      -
network           zwave-js-ui:network           :network               -
network-bind      zwave-js-ui:network-bind      :network-bind          -
raw-usb           zwave-js-ui:raw-usb           :raw-usb               -
serial-port       zwave-js-ui:serial-port       :usb-serialcontroller  manual
```

```
sudo snap connections pi
error: snap "pi" not found
```

**Comment by jmgiaever** [comment]
Ah, I checked now. Seems like this gadget snap is only available for the Ubuntu Core installs. I guess you're running a classic system, such as Ubuntu Server, Raspbian etc?

I'll have to check if there are alternatives for the classic systems.

**Comment by AlfaBravoX** [comment]
> Raspbian

Yes, I run standard Raspbian from official repositories

**Comment by jmgiaever** [comment]
Ok, it actually seems like I've been digging into this before: https://forum.snapcraft.io/t/acessing-serial-device-from-a-snap-package/29052

If you're just using this device for ZUI, you should consider installing Ubuntu Core to it. If it's available for RPi 2.

**Comment by AlfaBravoX** [comment]
Thanks a lot for digging. I prefer to use existing machine and just extend it by ZUI, but as I was afraid it looks I need another board just dedicated as ZUI node which I wanted to avoid. I will try one more attempt with Docker install instructions from here [https://zwave-js.github.io/zwave-js-ui/#/getting-started/docker](https://zwave-js.github.io/zwave-js-ui/#/getting-started/docker) and if it still fails, I will probably need to go with Ubuntu Core and dedicated ZUI RPI board.

**Comment by Euton2020** [comment]
Hello, do you think that an evolution of zwave-js-ui is possible to make it compatible with a Razberry card ? Cordially

**Comment by AlfaBravoX** [comment]
I would like to stay with raspbian, so unfortunately i had to give up zw js
ui and stay with z-way me that works out of the box with raspbian.

**Comment by Euton2020** [comment]
hello Kpine,
ah ! thank you for this precision, I did not know exactly where the problem came from.
So I renew my request: do you think of making zwave-js-ui compatible with an Rpi 2?
thank you in advance for your answers and your wonderful work

**Comment by AlfaBravoX** [comment]
Not exactly. I reported the issue like that:

Z-Wave JS UI does not work with Razberry(used v2) controllers with raspbian. I used RPI 3, RPI2 and Jessie, Buster, Bullseye and SNAP. Non of combination worked. Serial port was not detected by SNAP.

**Comment by AlfaBravoX** [comment]
I did not even say single word that solution was not provided. People above were re-asking what was the problem, so I just did recap. I am not going with Ubuntu core for my reasons. Maybe I will try later docker path. 

From my end, issue can be closed.

**Comment by Euton2020** [comment]
hello again, for my case, do you think it works with a Rpi 2 Debian 11 and a Razbarry v1 card under Docker?

**Comment by AlfaBravoX** [comment]
> hello again, for my case, do you think it works with a Rpi 2 Debian 11( already installed and working) and a Razbarry v1 card under Docker? thanks in advance

I tried that with Rpi 2 Debian 11 and docker install, it does not work. Serial port not accesible. I Tried that the same on Rpi 3 and it works w/o any issues. I am giving up with Rpi2 and moving to Rpi 3. According to Razberry support, it should work, but it does not. I tried few Rpi 2 boards and Razberry did not work on any of them. Not sure where the problem is.

**Comment by AlfaBravoX** [comment]
> Sorry, I misunderstood. I was mostly responding to the comment "Z-Wave JS UI does not work with Razberry(used v2) controllers with raspbian.", I guess you meant "with Snap". My mistake.

No worries at all :-) Yeap, just meant snap. No issues with docker with Rpi3 and Razberry hat.

**Comment by Euton2020** [comment]
Hello,I just installed Docker and Docker-compose then Zwave-js-ui on Docker with my Rpi 2 and my Razberry. that doesn't work either

**Comment by robertsLando** [comment]
Snap issue, seems everything is ok with other builds

**Comment by jmgiaever** [comment]
On classic systems, most likely yes. But that's nothing we do with it.
