### ISSUE TITLE
Wrong time stamp in log files

### ISSUE THREAD

**Issue by Bertels999** [zwave-js/zwave-js-ui#3202]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.21.2.c16958a

### ZwaveJS version

11.6.0

### Describe the bug

Events written in the logs are two hours earlier than the time on my raspberry pi.

### To Reproduce

-trigger an event
-look in log

### Expected behavior

time stamp is the same as the time on my raspberry pi

**Comment by robertsLando** [comment]
@Bertels999 Did you checked the Timezone set on the docker container? Check TZ env var

**Comment by Bertels999** [comment]
Thanks, Yes, I saw it later. However, it should not be necessary. By default, it should select the local time zone as set in the Raspberry Pi?

So with hindsight, it is an enhancement and not a bug.

Bert

**Comment by robertsLando** [comment]
> Thanks, Yes, I saw it later. However, it should not be necessary. By default, it should select the local time zone as set in the Raspberry Pi?

Nope, that's why that env var exists
