### ISSUE TITLE
Automatically detect unresponsive controller

### ISSUE THREAD

**Issue by trankin** [zwave-js/zwave-js-ui#3203]
I've been using the product for a while now and have a few locations that are using it.  One of the features that I really liked is that it raises an MQTT event when the controller is removed and added.  I have however detected an occasional occurrence where the controller simply becomes unresponsive and sensor data stops being raised via MQTT, but zwave-js UI seems to think that everything is working fine.  I can't seem to find a way to automatically detect when this occurs, in my thought process I could send a command to the controller that would require some serial communication that would be confirmation that the controller is connected and communicating.

I imagine I could do this by sending a command to do an inclusion or exclusion and wait to see if it actually goes in the the proper mode, but I was hoping for something a bit less obtrusive.

Any thoughts or insight would be much appreciated.

Regards,

Tom

**Comment by robertsLando** [comment]
@trankin There is already an open issue about this in zwave-js driver. Follow updates there: https://github.com/zwave-js/node-zwave-js/issues/2723
