### ISSUE TITLE
Upgrade to mqtt 5.0.1 breaks MQTT

### ISSUE THREAD

**Issue by timothyh** [zwave-js/zwave-js-ui#3206]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Z-Wave JS UI version

8.22.0.538cd31

### ZwaveJS version

11.8.1

### Describe the bug

With mqtt 5.0.1 I get the following message on startup

ERROR MQTT: Error while connecting MQTT Cannot read properties of undefined (reading 'connect')

and MQTT both publish and subscribe does not work.

Reverting to mqtt 4.3.7 fixes the problem

### To Reproduce

See description above

### Expected behavior

For MQTT to work

**Comment by robertsLando** [comment]
Nodejs version?

**Comment by robertsLando** [comment]
Thanks for the report, fixed on master release is coming
