### ISSUE TITLE
Values get mixed across devices

### ISSUE THREAD

**Issue by bostjane** [zwave-js/zwave-js-ui#3216]
I use Zwave JS UI in Domoticz via mqqt mosquitto broker. I'm getting strange behaviour that I got new "devices" in Domoticz that doesn't even exists. For example, device for Aeotec Multisensor 6 is created for electric A, V and W values, which is obviously wrong. Similary I get new devices For Fibaro Wall plug for Air temperature which is also obviously wrong.

I guess Zwave JS UI sends out those "devices" as Domoticz probably doesn't simply make them up. It doesn't happen a lot, but from time to time, so it's not quite easy to log.

What is going on?

![Capture](https://github.com/zwave-js/zwave-js-ui/assets/7306524/4202ec2f-80ab-493b-ad10-a4f114f430be)

**Comment by robertsLando** [comment]
@bostjane Firstly, do you see those values in UI? I mean go to control panel, click (expand) the node row and check if it reports support for those command classes. Some nodes report support for command classes they should not and that's a possible reason of this issue

**Comment by bostjane** [comment]
I have already checked that in the beginning and forgot to mention it in my first post.

If device sends a specific value, does it stay in GUI forever (with exception to re-interview)? I checked Multisensor 5 and Fibaro Wall Plug and they do not have this invalid values in GUI, but they do appear in Domoticz. Maybe there is a problem when values are pushed to the mqqt broker?

**Comment by bostjane** [comment]
I'll send log as soon as next such event occurs...

In my previous post I wondered if anything can be determined theoretically, without log. In particular documentation says "_The sending node supports an older version of the Meter or Multilevel Sensor CC that do not support querying which meters/sensors the device supports._" as case when it can't be done anything to prevent wrong data to be accepted. Is "Multilevel Sensor v5" old enough for such statement? Or is it new and device could be queried and wrong values discarded as a result.

**Comment by robertsLando** [comment]
without a log it's difficult to say

**Comment by bostjane** [comment]
Here are logs and screenshot of wrong devices in Domoticz. The most probable time when the wrong devices appeared is the "Last seen" time in Domoticz.
[zwavejs_2023-08-09.log.gz](https://github.com/zwave-js/zwave-js-ui/files/12329967/zwavejs_2023-08-09.log.gz)
[zwavejs_2023-08-10.log.gz](https://github.com/zwave-js/zwave-js-ui/files/12329968/zwavejs_2023-08-10.log.gz)
[zwavejs_2023-08-11.log.gz](https://github.com/zwave-js/zwave-js-ui/files/12329962/zwavejs_2023-08-11.log.gz)
[zwavejs_2023-08-12.log.gz](https://github.com/zwave-js/zwave-js-ui/files/12329963/zwavejs_2023-08-12.log.gz)
[zwavejs_2023-08-13.zip](https://github.com/zwave-js/zwave-js-ui/files/12329965/zwavejs_2023-08-13.zip)

![Capture](https://github.com/zwave-js/zwave-js-ui/assets/7306524/b29bda2d-d6c5-4ef3-95e4-c5017dcbb60f)

**Comment by robertsLando** [comment]
@AlCalzone do you think this is related to: https://zwave-js.github.io/node-zwave-js/#/troubleshooting/nonsensical-values ?

**Comment by AlCalzone** [comment]
Yeah it is. The W report at the bottom is received 3 times with the same content. So if it is not from node 28, the node ID was likely corrupted somewhere along the route and a repeater repeated the same corrupted command multiple times.

In general, this mesh is not healthy. Tons of repeated messages, much too much reporting going on. Essentially the mesh flooded to its limits just from the meter/sensor reports.

I suggest following these steps:
1. If you haven't already, https://zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=general-troubleshooting
1. https://zwave-js.github.io/node-zwave-js/#/troubleshooting/network-health?id=optimizing-the-reporting-configuration
1. https://zwave-js.github.io/node-zwave-js/#/troubleshooting/network-health?id=testing-the-connection-strength

**Comment by bostjane** [comment]
Yes, the world tends not to be ideal and neither is my mesh :) I'll follow recommendations above as much as I can, but of course I can not move my washing machine and motion sensor just to have better reception :)

Just for seconds let us leave the fact of flooded mesh, bad transmissions, etc and focus on corrupted message that Zwave JS got - it could be the only message in an day and still be something that needs to be addressed. So, could ZWave JS somehow detect this corrupted message and discard it, that's something that might be done and improve the overall reliability, not just in my case but for all?

My thinking... corrupted message must have originated from nodes where Aeon Labs Smart Switch 6/7 are connected. Only those nodes can send electric V, A and W values in "Meter v3". As Node 28 does not have "Meter v3", shouldn't/couldn't Zwave JS simply ignore such data? If not unconditionally, I suggest new feature that Zwave JS accepts them in first inclusion or Re-Interview (as now), but not later anymore. Or maybe to introduce check option in GUI per-device or globally that would prevent receiving values that device doesn't have.

I think such upgrade would be very useful.

**Comment by AlCalzone** [comment]
> As Node 28 does not have "Meter v3", shouldn't/couldn't Zwave JS simply ignore such data?

Indeed, this is on the todo list: https://github.com/zwave-js/node-zwave-js/issues/5510

That said, improving the mesh health and reducing the traffic goes a long way in preventing such issues altogether.

**Comment by AlCalzone** [comment]
> Indeed, this is on the todo list: [zwave-js/node-zwave-js#5510](https://github.com/zwave-js/node-zwave-js/issues/5510)

I have scheduled this for the next release, FYI.

**Comment by robertsLando** [comment]
The https://github.com/zwave-js/zwave-js-server/blob/master/src/lib/server.ts#L509 PR has been merged many months ago and this should be fixed now
