### ISSUE TITLE
Key disconnecte after a setting save

### ISSUE THREAD

**Issue by Idaho947** [zwave-js/zwave-js-ui#3218]
Hello,

I've an issue with zwave JS 8.22.0 on my jeedom set.
When I'm in setting parameter and change something (like disable soft reset or enable log) and click on save, the serveur became disconnect and I have to unplug\plug the key on my intel nuc in order to use the key and zwave JS again.

I use a zooz 700 usb key.

Zwave JS : 11.8.0
Zwave JS UI : 8.22.0
SDK : 7.18.3
FW : 7.18.3

Have you already see that ? How can I fix that ?

**Comment by robertsLando** [comment]
Upgrade to 8.22.3

**Comment by Idaho947** [comment]
Ok I ask jeedom for the upgrade and come back here for the result.

**Comment by Idaho947** [comment]
Ok in 8.23.0 thanks !
