### ISSUE TITLE
Add configuration settings for controller region and power levels

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js-ui#3222]
**Is your feature request related to a problem? Please describe.**
Z-Wave JS now supports persistent configuration of controller region and tx power levels via driver settings: https://github.com/zwave-js/node-zwave-js/pull/6159

This ensures the controller is always configured correctly, even if something like a firmware update reverts them to defaults.

**Describe the solution you'd like**
Add matching Z-Wave configuration settings in ZUI. These should be optional, which would use the current behavior, that is the user sets them manually in the control panel.

**Describe alternatives you've considered**
None.

**Additional context**
An open question would be what happens if a user configures these, but then changes them manually in the control panel. Z-Wave JS would change them on next startup if still configured. Maybe that is OK, it could just be documented in the help text.

**Comment by robertsLando** [comment]
PR ready, thanks @kpine for the reference
