### ISSUE TITLE
Show when devices needs to be reinterviewed

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js-ui#3225]
Ref: https://github.com/zwave-js/node-zwave-js/pull/6170/files

Use the new node `hasDeviceConfigChanged` method. This can be added in `dumpNode` function and then show a badge or else on node table/compact view to warn user that device may need a re-interview

**Comment by AlCalzone** [comment]
I think a good time to check this is in the node `ready` event handler.

**Comment by robertsLando** [comment]
How would you show this in UI?
