### ISSUE TITLE
Some messages not updating MQTT values.

### ISSUE THREAD

**Issue by cinadr** [zwave-js/zwave-js-ui#3227]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.22.3.8607bd8

### ZwaveJS version

11.9.2

### Describe the bug

Some of my topics on MQTT server are not updating. My motion sensor (48/0/Motion)  and my Danalock V3 98/0/targetMode and 98/0/currentMode are refreshing as expected but my DoorSensor sensor status 48/0/Any is always true. Also my Danalock 98/0/boltStatus is sticking to "locked" just as latchStatus and doorStatus not changing. The log shows  a DEBUG message that these MQTT messages are sent but along this there is no update in MQTT topics (openhab not receiving values and MQTT explorer shows no update and the History list missing these updates).

### To Reproduce

I've tried to stop/start my stack of mqtt  zwavejs2mqtt containers but keeps the same.

### Expected behavior

All values should update as before. This is apearing with the latest update (docker HUB says 3 hours ago).

### Logs
[zwave-js-ui-store.zip](https://github.com/zwave-js/zwave-js-ui/files/12375594/zwave-js-ui-store.zip)

**Comment by robertsLando** [comment]
@cinadr is storage enabled on MQTT settings? If so could you try by disabling it?

**Comment by cinadr** [comment]
I've tried to disable storage but still no luck. currentMode/targetMode of the lock is refreshing and the lock can be controlled via MQTT but the MQTT values of bolt/lock/latchStatuses are not updated despite the logs. 

Screencapture
![image](https://github.com/zwave-js/zwave-js-ui/assets/16361576/2786ae27-4713-4dbc-80b1-2d1ad7cf9418)

**Comment by JGtHb** [comment]
Are you using Mosquitto as your MQTT broker using the latest eclipse-mosquitto Docker image? I had the same symptoms with a different door sensor and eventually narrowed it down to the new 2.0.16 Mosquitto release. Rolling back to version 2.0.15 resolved the issue for me.

**Comment by cinadr** [comment]
> Are you using Mosquitto as your MQTT broker using the latest eclipse-mosquitto Docker image? I had the same symptoms with a different door sensor and eventually narrowed it down to the new 2.0.16 Mosquitto release. Rolling back to version 2.0.15 resolved the issue for me.  

Yes. That solve my issue. Thank you for your help.

**Comment by robertsLando** [comment]
Thanks @JGtHb for the help
