### ISSUE TITLE
Compact view sort

### ISSUE THREAD

**Issue by GitHubGoody** [zwave-js/zwave-js-ui#3228]
I like the new compact view, but would appreciate the ability to sort the tiles more than the default (Node ID). If it helps (cannot be added all at once), this is the order I would prefer options to be added:

Name
Location
Last Active
Status
Power
etc.

**Comment by robertsLando** [comment]
Adding sorting there is not that easy, anyway would you like all this sorting together or only one for time? I could add an input to choose the sorting wanted

**Comment by GitHubGoody** [comment]
I'm sorry, but I don't understand your question.

**Comment by robertsLando** [comment]
No worries, I add this to my TODOs and will implement as soon as I will be back from vacations

**Comment by GitHubGoody** [comment]
Still requested please
