### ISSUE TITLE
Weiser GED2150 suddenly not showing boltStatus / lock status in HA

### ISSUE THREAD

**Issue by daytonturner** [zwave-js/zwave-js-ui#3231]
I'm not sure whats happening here, I recently noticed that my Weiser SmartCode 10 Touchscreen lock is not reporting boltStatus correctly as lock state in Home Assistant.  This was working previously.  Not sure if it has to do with the recent upgrade to 2023.8.2, but all the other parameters are reporting correctly.

I've tried to step through debugging, but its not clear to me how HA maps zwave-js parameters to HA entity state.

Looking at the zwave-js-ui, as well as the websocket raw packet information, I do see that the node is reporting proper boltState as locked:

```
2023-08-18T19:51:52.297Z - VALUE UPDATED 
Arg 0:
└─commandClassName: Door Lock
└─commandClass: 98
└─property: boltStatus
└─endpoint: 0
└─newValue: locked
└─prevValue: locked
└─propertyName: boltStatus
```
![Screenshot 2023-08-18 at 1 54 04 PM](https://github.com/zwave-js/zwave-js-ui/assets/11683785/080807fe-8fd8-4431-9398-ef615286b0f9)

And value updates show in zwaveJS logs
```
2023-08-18 13:38:19.530 INFO Z-WAVE: [Node 009] Value updated: 98-0-doorStatus open => open
2023-08-18 13:38:19.537 INFO Z-WAVE: [Node 009] Value updated: 98-0-boltStatus locked => locked
2023-08-18 13:38:19.541 INFO Z-WAVE: [Node 009] Value updated: 98-0-latchStatus open => open
```
I also see latchStatus in these updates:

```
2023-08-18T19:51:52.301Z - VALUE UPDATED 
Arg 0:
└─commandClassName: Door Lock
└─commandClass: 98
└─property: latchStatus
└─endpoint: 0
└─newValue: open
└─prevValue: open
└─propertyName: latchStatus
```

But looking in my HA states, i see:
![Screenshot 2023-08-18 at 1 51 55 PM](https://github.com/zwave-js/zwave-js-ui/assets/11683785/ec3a28a0-cc2a-4354-a62f-3b8bc3217c7b)
![Screenshot 2023-08-18 at 1 52 19 PM](https://github.com/zwave-js/zwave-js-ui/assets/11683785/69406ba4-bd0c-465e-84a9-e7720a20b6b2)

All of the other data seems to be populating into the HA Device:
![Screenshot 2023-08-18 at 1 53 32 PM](https://github.com/zwave-js/zwave-js-ui/assets/11683785/3d36f299-5c96-44ee-8238-cdf2f15dc770)

But despite the boltStatus being correct in zwave-js, HA doesnt seem to be reporting it in the lock state.

What else can I check to verify that the boltStatus is being correctly interpreted by HA?

Apologies if i'm posting this in the wrong repository, i wasnt sure if it should start here or in node-zwave-js

**Comment by daytonturner** [comment]
Well.. that would certainly explain it, I didn’t realize it wasn’t coming from boltStatus. I’m not sure why all of a sudden “current lock mode” would fail to report status when other values are definitely updating, and lock control commands work, but I suppose I can start by re-interviewing or excluding/including again.

Thanks for the insight!

Dayton

________________________________

**Comment by JGtHb** [comment]
Since this was working previously, this could be due to a bug in the latest Mosquitto MQTT broker. I had similar symptoms with different devices. 

If you are using Mosquitto 2.0.16 try rolling back to 2.0.15. Issue link: https://github.com/eclipse/mosquitto/issues/2876
