### ISSUE TITLE
/dev/serial/by-id/ not supported on Proxmox

### ISSUE THREAD

**Issue by remyderuysscher** [zwave-js/zwave-js-ui#3233]
Running HA on Proxmox 8 with Open VA image and latest Z-Wave UI addon. While configuring the Z-Wave device port only USBX is shown. When I enter the right configuration /dev/serial/by-id/usbSilicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_3889d89b3494eb11acfa3a703d98b6d1-if00-port0 it's not working (obviously) but I have a number of other USB devices which show up as well.  I have no way to tell which is which. 

The Skyconnect is using the same CP2102N chipset and has the same hardware id. 

How can I use and passthrough only the correct port to the addon? Is this configurable in docker?

 ls -l /dev/serial/by-id
total 0
lrwxrwxrwx    1 root     root            13 Aug 19 08:42 usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_3889d89b3494eb11acfa3a703d98b6d1-if                                                                      00-port0 -> ../../ttyUSB0

**Comment by robertsLando** [comment]
Dunno if this could help: https://github.com/tteck/Proxmox/issues/30

**Comment by remyderuysscher** [comment]
> Did you tried to use `/dev/serial/by-path/xxx` ? Are you using docker? If so can I see your docker-compose file please? I never used Proxmox anyway so I dunno how it's mapping usb, it could be you need to create a custom udev rule in order to make this work

Yes I tried it. I'm using the add-on in Home Assistant on the OVA image so I can (will) not modify anything docker related since it's handled by HA image. These things break when upgrading.

**Comment by remyderuysscher** [comment]
I found the problem, it's Proxmox. When you pass thru a full USB port the /dev/serial/by-id is respected.
