### ISSUE TITLE
heal network booting devices out of auth mode

### ISSUE THREAD

**Issue by josh-m-sharpe** [zwave-js/zwave-js-ui#3235]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.11.1

### ZwaveJS version

?

### Describe the bug

Context: Have a lot of nodes connected.  Mostly Inovelli. Most of them are connected with S2Auth.  They work well.

I added a few new hardwired nodes and was experiencing connectivity issues, so I ran a network heal.

It seems that it is booting all my previous nodes to Security: None.

After this heal finishes I plan on updating to latest and retrying the network heal.

This screenshot taken mid-heal.  The highlighted nodes previously popped up with the second sreenshot and are now connected without security.
![Z-Wave_JS_UI](https://github.com/zwave-js/zwave-js-ui/assets/39473/af448bfa-bc85-4c79-975f-e6d647f20d1d)

Each node popped up with this:
![Z-Wave_JS_UI](https://github.com/zwave-js/zwave-js-ui/assets/39473/0d644cf6-d6a7-4adb-b116-929926864bc0)

### To Reproduce

unclear.  I've run heals before and this never happened.

### Expected behavior

Nodes previously connected with S2 Auth would remain so.

**Comment by josh-m-sharpe** [comment]
Original heal finished.
Updated to latest (8.23.0) and a second heal is not fixing this issue.

**Comment by josh-m-sharpe** [comment]
Something is totally foobared.  Since original post I have:

1) Updated to latest (8.23.0)
2) Healed - This was slow, kicked all my nodes to security: none and failed halfway through.
3) A few power cylces later, decided to:
4) Manually excluded everything. ~40 nodes
5) hard reset my controller (via the zwave-js-ui)
6) Re-included 7 hard-wired Inovelli nodes closest to the hub.  All with S2 Auth.
7) Healed.  This worked.
8) Tried adding 3 nodes a bit further way (but previously paired fine - for months and months, no issue).  Kept timing out.  
9) thought it might be something with 8.23, so backed down to 8.14.2.  Why 8.14.2? Because it added the new Inovelli VZW31-SN (which I have, but isn't one of the 10 nodes above).
10) Excluded and added the same 3 nodes from (8) above. Finally got them added.  They identified as the correct device types too.
11) Tried healing again
12) see (2) above.  Everything fell off back to Security none.  And they're unuseable.  They look like they're borked in the UI.   There should be more options than Configuration here:

![Z-Wave_JS_UI](https://github.com/zwave-js/zwave-js-ui/assets/39473/4615c495-2ae5-42d4-aab1-b5cef306e1c2)

**Comment by robertsLando** [comment]
PLease attach logs

**Comment by robertsLando** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

**Comment by josh-m-sharpe** [comment]
Unfortunately the time for that has come and gone.  I've forcibly excluded everything, deleted my zwave-ui-js configs and started fresh on the latest version.

Maybe this is a Feature Request to somehow halt the healing process mid-way if things start going poorly?  Not sure if that's entirely possible or not, but it would have been great to stop it after I noticed the first few nodes failing in this matter.  THEN I could've gotten you your device logs.

But as it went down there was no way to stop it and eventually all the nodes ended up listed as Security:None.  They were functionally unresponsive too as seen in my second screenshot.

**Comment by robertsLando** [comment]
@AlCalzone any clue?

**Comment by AlCalzone** [comment]
There must have been something else going on. Healing just discovers neighbors and re-creates routes.
Unfortunately that something else cannot be debugged without driver logs.

**Comment by josh-m-sharpe** [comment]
> Maybe this is a Feature Request to somehow halt the healing process mid-way if things start going poorly? Not sure if that's entirely possible or not, but it would have been great to stop it after I noticed the first few nodes failing in this matter. THEN I could've gotten you your device logs.
