### ISSUE TITLE
add button at end of inclusion/exclusion to do it all again

### ISSUE THREAD

**Issue by josh-m-sharpe** [zwave-js/zwave-js-ui#3236]
**Is your feature request related to a problem? Please describe.**
I want to walk around the house manually include or exclude nodes one by one.  I want the UI to help me to do that

**Describe the solution you'd like**
After a successful inclusion/exclusion, the UI should have a button that just starts the process again: "Include another?" or something.
This would eliminate a few clicks to restart it.

**Describe alternatives you've considered**
n/a - using existing buttons to do this

**Additional context**

![Z-Wave_JS_UI](https://github.com/zwave-js/zwave-js-ui/assets/39473/493e96e4-6146-4905-802c-d69030464aab)

**Comment by josh-m-sharpe** [comment]
To be clear, I don't actually want to walk around my house including/exclusing all the nodes.  Other issues are forcing me into this position.

**Comment by robertsLando** [comment]
You can just press on action to go back, did you tried?

**Comment by josh-m-sharpe** [comment]
yea, that works. thanks for the tip!  seems non-obvious to have actionable buttons up in the header of a modal though.
