### ISSUE TITLE
Cannot restore NVM backup from SDK 6.84 on a HUSBZB-1

### ISSUE THREAD

**Issue by windsurferwill** [zwave-js/zwave-js-ui#3238]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

1.15.5

### ZwaveJS version

Driver Version:
11.9.2
Server Version:
1.30.0

### Describe the bug

Migrating from zwave HUSBZB-1 running SDK 6.84 to Zooz ZAT39LR (800 series).
Successfully created NVM backup from old HUSBZB.  When restoring from NVM backup to zooz controller, get the following message:
2023-08-20 10:24:13.440 INFO Z-WAVE: Did not find a matching NVM 500 parser implementation! Make sure that the NVM data belongs to a controller with Z-Wave SDK 6.61 or higher. (ZW0280) restoreNVM undefined
After the error, only the new controller shows up in zwave JSUI.  No nodes.

### To Reproduce

Disable zwave integration in home assistant.
Stop zwave JS UI add-on.
plug in new stick
Start zwave JS UI add-on
Correct the zwave entry for DEVICE
Restart zwave JS UI add-on
Restore NVM -> gives error message
Enable zwave integration

### Expected behavior

restore NVM from backup without error

**Comment by robertsLando** [comment]
Follow updates on the issue linked above
