### ISSUE TITLE
unknown Manufacturer, unknown Product name

### ISSUE THREAD

**Issue by Piet8** [zwave-js/zwave-js-ui#3248]
Cannot get Zwave-JS-UI working, is there a troubleshooting guide available?

Really don't know where to look, none of my z-wave switches or sensors are working 
Searching for days and cannot find a solution to get this beast working
Hardware Raspberry Pi 2B, Aotec Zwave stick, Fibaro and Neo Coolcam devices, Sensative sticks, have been using OZW for years, as end-user don't know much about Debian.
Currently Running Debian 11, was using Migratee Openzwave to Zwave-JS-UI guide already tried 3x from the start but still stuck.

![docker-compose yml](https://github.com/zwave-js/zwave-js-ui/assets/143402513/1928cdb7-3532-476b-be1f-4a4a6a274f2c)
[zwavejs_current.log](https://github.com/zwave-js/zwave-js-ui/files/12455093/zwavejs_current.log)
![control Panel](https://github.com/zwave-js/zwave-js-ui/assets/143402513/c5899bb9-5903-44d8-86f7-115c1e5a9c41)

**Comment by robertsLando** [comment]
@Piet8 `/dev/serial/by-id/../../` is just wrong, you should replace it with the correct serial id instead of `../../`

**Comment by Piet8** [comment]
Thank you for your answer, but still unable to fix it.

Would you please be so kind to show me how this line should be filled with the correct value (did try loads of possibilities)
![serial_by-id](https://github.com/zwave-js/zwave-js-ui/assets/143402513/beccdc57-0e28-47e4-b702-e4360a41edbe)

**Comment by robertsLando** [comment]
`/dev/serial/by-id/usb-0658_0200-if00`

**Comment by Piet8** [comment]
thank you for your fast reply, 

Last 3 weeks did try a lot of combinations of the serial-id (my guess was the ../../ttyACM0 also has to be included somehow) 

Changed value in docker-compose.yml back to /dev/serial/by-id/usb-0658_0200-if00 
but that did not solve the unknown Manufacturer/Product name.
System is sill giving me the exact same values on the Zwave JS UI control panel

Would be great if you could help me get this working struggling for 3 weeks already, don't know what steps to take to troubleshoot this problem.

**Comment by Piet8** [comment]
Sorry but I  don't know what information is needed to solve the problem 

![serial_by-id](https://github.com/zwave-js/zwave-js-ui/assets/143402513/e4be59e7-995c-427c-9a70-133c44e4c3a4)
[z-ui_current.log](https://github.com/zwave-js/zwave-js-ui/files/12479748/z-ui_current.log)
[zwavejs_current.log](https://github.com/zwave-js/zwave-js-ui/files/12479749/zwavejs_current.log)

**Comment by robertsLando** [comment]
cc @AlCalzone seems all nodes are not responding to pings

**Comment by Piet8** [comment]
As all nodes were non responding, 
[z-ui_current.log](https://github.com/zwave-js/zwave-js-ui/files/12486146/z-ui_current.log)
[zwavejs_current.log](https://github.com/zwave-js/zwave-js-ui/files/12486147/zwavejs_current.log)
also tried to reset and include one of the Fibaro wall plugs using Zwave JS UI, but system did not find the wall plug, wall plug distance was less then 1 meter.

**Comment by Piet8** [comment]
yesterday evening tried to reinstall from scratch, running into the exact same error. 
is there a way to investigate how to solve the issue, am i the only one with all of my nodes being non responding.

**Comment by Piet8** [comment]
what would be the correct syntax for usb Zwave stick in docker-compose.yml

if I want to use /dev/ttyUSB0 instead of 
devices:
    - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave' 

did try a few combinations but only received errors

**Comment by AlCalzone** [comment]
The devices are detected, so the communication with the stick itself is clearly working, which means the port setting is okay too - prefer the `by-id` paths though, that saves you some trouble down the line.

Please share a driver log of the startup, not a random point in time. To do this, enable the option "log to file" in the Z-Wave section, save (this will cause a restart), then wait 2-3 minutes to make sure enough is captured.

**Comment by Piet8** [comment]
Ok did run a restart of Domoticz as Z-wave log to file was already on (log level Silly)
hope this is what you need

[Domoticz.log](https://github.com/zwave-js/zwave-js-ui/files/12511483/Domoticz.log)
[z-ui_current.log](https://github.com/zwave-js/zwave-js-ui/files/12511484/z-ui_current.log)
[zwavejs_current.log](https://github.com/zwave-js/zwave-js-ui/files/12511485/zwavejs_current.log)

**Comment by AlCalzone** [comment]
None of your devices respond to commands. Did you move the stick when switching to Z-Wave JS? Is it on an [USB extension](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=general-troubleshooting)?

Also:
> 2023-09-04T07:53:33.738Z CNTRLR   SUC has node ID 65

Is Z-Wave JS not the primary controller in your network?

**Comment by Piet8** [comment]
Don't think i moved the USB stick but did try  both USB0 and USB1 (with a reboot) or do i need to change a configuration somewhere.

The USB stick is directly connected to the PI 2B
I only have 1 Domoticz controller in my Network

Would it be possible there is something wrong with the config-db, I am unable to connect to the directory
/usr/src/app/store/.config-db
![config-db](https://github.com/zwave-js/zwave-js-ui/assets/143402513/24f7b0e4-4473-4759-b4b1-9d3c7fb43a14)

**Comment by AlCalzone** [comment]
> Don't think i moved the USB stick

I mean physically. Like from a bookshelf to the server rack.

> The USB stick is directly connected to the PI 2B

Try a USB extension and place it away from other electronics.

**Comment by AlCalzone** [comment]
Did you try the USB extension yet?

**Comment by Piet8** [comment]
moved the pi to a guest room (where it was located earlier) in the middle of the house far away from electronics in the centre of most of the zwave devices.

what do you mean by USB extension a USB extension cable or something different?

**Comment by AlCalzone** [comment]
Yes, a USB extension cable. Without it, the stick is still close to the Pi (electronics!).

**Comment by Piet8** [comment]
Did try the extension cable (no effect on the sleeping nodes)

Tried to use my currently unused Pi 3B starting from scratch following Domoticz/Migrate Openzwave to Zwave-JS-UI google documents
After installation&connecting the Zwave stick with extension cord Domoticz gives me the exact same problem.

Is it possible the problem is related to docker permissions, 
while trying to run Zwave-JS-UI using "docker compose up -d" 
ran into a permission error (please check attachment)

after running "sudo docker-compose up -d" docker started running
no problem with the rest of the installation.

![Docker permission](https://github.com/zwave-js/zwave-js-ui/assets/143402513/0ed7139d-bc05-4959-b637-37a1cc06df2a)

Currently running heal network (but don't expect this will solve my problem)

**Comment by Piet8** [comment]
Mosquitto while installing received the error 1883 already in use
is this a normal error if not  where can I check what process is already using this port?
can i use any other port, adapting Mosquitto.conf and MQTT? 

![Mosquitto](https://github.com/zwave-js/zwave-js-ui/assets/143402513/5a550e5f-a668-46db-889f-16b79819d4f8)

**Comment by robertsLando** [comment]
> Mosquitto while installing received the error 1883 already in use

You have the mosquitto running as service and then you have run `mosquitto -v` that spawns a new instance of mosquitto. That's why you receive that error, mosquitto is already running...

About your issue with zui please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

**Comment by Piet8** [comment]
please start looking from 11.36 timestamp after I rebooted MQTT problems seemed to be gone (guess they were related to me stopping/restarting Mosquitto)

running sudo lsof -i TCP:1883 (port 1883 looks ok)

![port 1883](https://github.com/zwave-js/zwave-js-ui/assets/143402513/66a93c6f-c9c6-4796-8886-cebd76d58bb3)
[z-ui_current (1).log](https://github.com/zwave-js/zwave-js-ui/files/12548226/z-ui_current.1.log)
[zwavejs_current.log](https://github.com/zwave-js/zwave-js-ui/files/12548227/zwavejs_current.log)

**Comment by Piet8** [comment]
Domoticz, Docker & Mosquitto seem to be running ok but my nodes are still sleeping

[Domoticz.log](https://github.com/zwave-js/zwave-js-ui/files/12561777/Domoticz.log)
![Docker](https://github.com/zwave-js/zwave-js-ui/assets/143402513/b4798ecf-fbc2-45f5-89b8-ad04102a2bdd)
![Mosquitto](https://github.com/zwave-js/zwave-js-ui/assets/143402513/3278e782-04e6-458a-bd1d-6980df386945)

**Comment by robertsLando** [comment]
Nodes sleeping is ok, if them are battery powered they will always sleep except if you manually wake them up or on the wake up interval set in their configuration

**Comment by Piet8** [comment]
We are only using a handful of battery powered devices rest is all 230V,  all my nodes are sleeping.

Installed Aeotec simplicity studio software to check the USB stick values am able find a lot of keys but strange thing is I cannot find the network key I was looking for, or am I looking at the wrong place? 

In the mean time also tried to use the S2Unauthenticated key value and Nework key S0  in Zwave-JS-UI Zwave settings (did not change anything, all nodes still sleeping)

100% sure my Domoticz network key was "0102030405060708090A0B0C0D0E0F10"  

Still no working system any help is welcome.

![Domoticz Aeotec security network key](https://github.com/zwave-js/zwave-js-ui/assets/143402513/be99a9c1-98a5-43c1-983e-852a72c91252)
![AEOTEC security settings](https://github.com/zwave-js/zwave-js-ui/assets/143402513/523d2277-75f8-437d-b826-38cb1b979f52)

**Comment by AlCalzone** [comment]
Your devices are still not responding at all.

Anyways, this is a physical issue between the controller and the devices.
- It is **not** due to a wrong security key
- It is **not** because of something with MQTT
- It is **not** due to a misconfigured Docker or anything

Not sure if you changed the RF region of the stick somehow (Aeotec tool maybe?). If not even devices close to the stick respond, this is the only thing left I can imagine.

**Comment by Piet8** [comment]
Checking the Simplicity software I am unable to change RF region or power settings as these options are greyed out (unable to view/change) Don't think in Domoticz I am able to change these settings.

What would be my options
1. feels like i will never be able to get my current Node settings in UI. Tried contacting Aeotec they point at UI being the cause of the problems.
2. Resetting the zwave stick, starting from scratch and re-adding all devices seems to be a problem, I did a reset of a Fibaro wall plug but it is still impossible to add this device in Zwave-JS-UI Nodes Manage Inclusion. 
3. Will Zwave-JS-UI be able to fully connect to the stick after a factory reset? 

![Nodes manager](https://github.com/zwave-js/zwave-js-ui/assets/143402513/37b1db81-b247-4dbe-a3df-9a03d2407aad)

**Comment by Piet8** [comment]
After factory resetting the Zwave stick and re-adding most of the plug-in devices I do have a basic working system.
Had to use the Stick to re-add my devices, did try adding them via Zwave-JS-UI but did not succeed.
A few of my devices appear as dead nodes after placing them away from the stick (at the same spot where a used to have a node) will try a heal network.

Now I have to find a guide on how to use the Zwave-JS-UI (or is there a youtube guide for fools like me).
Do I need to use Zwave-JS-UI or can I still use Domoticz to react on door, motion sensors and light switches?

regards and thank you for your help and patience

**Comment by robertsLando** [comment]
I suggest you to give a look at official docs: https://zwave-js.github.io/zwave-js-ui/#/

> Do I need to use Zwave-JS-UI or can I still use Domoticz to react on door, motion sensors and light switches?

You can use Domoticz or Home assistant, mqtt or yeah the Control panel in order to control your devices

**Comment by Piet8** [comment]
my 4 Shenzhen Neo Coolcam Motionsensors are not getting recognised in the database.

I cannot find a type on the sensor or in the little document in the box 
on the invoice it said  "NEO_MotionSet4-NEO_SS01Z" 
on the box the was this number 6924715900544

**Comment by robertsLando** [comment]
> my 4 Shenzhen Neo Coolcam Motionsensors are not getting recognised in the database.

Could you show me a screenshot of mqtt discovery entities of that node, you can find them on control panel by expanding the node and switch the tab to home assitant

**Comment by AlCalzone** [comment]
I know you've heard this before...

Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

That log should include a re-interview of the problematic device. Don't forget to wake up sleeping devices. How that works is explained in the device manual.

**Comment by Piet8** [comment]
Don't think I understand what you mean by the MQTT discovery entities of that Node.
Please find the screenshots and log files Related nodes are Node20 and Node21
![ControlPanel_nodes](https://github.com/zwave-js/zwave-js-ui/assets/143402513/16707cde-3a85-4a11-ae50-40fcd8ca3fbe)
![ConTrolPanel_Node21](https://github.com/zwave-js/zwave-js-ui/assets/143402513/286082cd-de47-4dce-96eb-781a6df5a971)
![ConTrolPanel_Settings_MQTT_HomeAssistent](https://github.com/zwave-js/zwave-js-ui/assets/143402513/ff97122c-7235-4911-ab43-bfdb224144d2)
[z-ui_current.log](https://github.com/zwave-js/zwave-js-ui/files/12647539/z-ui_current.log)
[zwavejs_current.log](https://github.com/zwave-js/zwave-js-ui/files/12647540/zwavejs_current.log)

**Comment by robertsLando** [comment]
I need to see this on UI:

![Schermata da 2023-09-18 15-20-56](https://github.com/zwave-js/zwave-js-ui/assets/11502495/4de38372-c472-4be2-9c11-bf05577b2c72)

**Comment by Piet8** [comment]
Unable to find the Home Assistent Tab on the left side of the screen.
My guess would be because I am using Domoticz settings.
How can I change the setup to show Home Assistent Information or does that damage the Domoticz connection?
![ControlPanel_NodeInfo](https://github.com/zwave-js/zwave-js-ui/assets/143402513/84165556-5e93-4eb2-be44-977eb56627de)

**Comment by Piet8** [comment]
Right it does show the Home Assistant  info on the known Nodes

![ControlPanel_HomeAssistent](https://github.com/zwave-js/zwave-js-ui/assets/143402513/41414c71-3f92-40d8-ae28-772a92cdec33)

**Comment by AlCalzone** [comment]
Quote:
> Don't forget to wake up sleeping devices. How that works is explained in the device manual.

Node 20 and 21 were never woken up during those logs, so their interview never happened.

**Comment by AlCalzone** [comment]
> would expect they are awake when movement occurs and the light goes on

No, they are not. Being awake means listening for commands. To report motion, they only leave deep sleep for a very short time to save battery. Waking devices up usually involves pressing the Z-Wave button on them, sometimes once, sometimes for a longer time, sometimes in a pattern.

> On Control Panel after selecting Node 20 and 21 did try to start Update, Heal, Refresh, Re-interview 

That does nothing when they are asleep.

Not sure if [this](http://manuals-backend.z-wave.info/make.php?lang=en&sku=NEOEMS01Z) is your sensor:
> To wakeup the device please perform the following action:
You can press the button once to wake up the sensor and send wakeup notification to gateway. If press successfully, LED light will blink one time.

**Comment by Piet8** [comment]
Yes this sensor is very similar to my sensors. (in the meanwhile did find the part in the doc explaining to wakeup the device)

Tried several times yesterday and today to wakeup the device pushing button once the LED light turned on but the devices are still unknown in the Control Panel.

Did try to check the log files but don't which part of the info of Node 20 & 21 I have to look for.

[z-ui_current (1).log](https://github.com/zwave-js/zwave-js-ui/files/12690843/z-ui_current.1.log)
[zwavejs_current (1).log](https://github.com/zwave-js/zwave-js-ui/files/12690844/zwavejs_current.1.log)

**Comment by AlCalzone** [comment]
The only node I see wake up there is 22, not 20 or 21.

**Comment by Piet8** [comment]
Thank you for your help.
Strange thing is I just added the 3rd Motion Sensor and this one does get recognised. 

Please help advise what to do with the other 2 devices (please do check attachment) where all devices do get a  number reflecting Zwavw-JS-UI number in Domoticz these 2 sensors get a different Number. 
Can I just exclude and Include them again, will the exclude process also delete them in Domoticz
![Control_Panel](https://github.com/zwave-js/zwave-js-ui/assets/143402513/96ec275d-fcfa-4b3c-8d34-3196f991ac2c)
![Domoticz_Devices](https://github.com/zwave-js/zwave-js-ui/assets/143402513/2b36471f-bb82-493d-a7f6-97493451c38e)
?

**Comment by Piet8** [comment]
re-tried the other 3 Coolcam Motion sensors (i bought in one pack of 4).
1 Tried remove sensor from Network / Include sensor
2. Remove sensor / Restore Factory settings / Include sensor

Sensors are only added in the Zwave-JS-UI view, they are not added in Domoticz devices

Only 1 sensor works as expected, 3 other sensors are still giving a Unknown Manufacturer Unknown Product Name

![Control_Panel](https://github.com/zwave-js/zwave-js-ui/assets/143402513/bd82bec9-6066-438d-8fdf-ddf0e3b4f3cf)
![Domoticz_Devices](https://github.com/zwave-js/zwave-js-ui/assets/143402513/80287229-489b-4795-82a4-1c367e7f5334)


[z-ui_current.log](https://github.com/zwave-js/zwave-js-ui/files/12706105/z-ui_current.log)
[zwavejs_current.log](https://github.com/zwave-js/zwave-js-ui/files/12706106/zwavejs_current.log)

**Comment by AlCalzone** [comment]
> Please help advise what to do with the other 2 devices

If you are able to exclude them, you can try that. Then factory-reset them for good measure, and include them again.
If excluding doesn't work, simply factory-reset them and remove the two broken entries using the "remove failed node" feature afterwards.

**Comment by Piet8** [comment]
1. Used the Stick to exclude & Include the devices taht only worked for 1 device.
2. Using the Zwave-JS-UI Nodes Manager to exclude/Include the devices the Motion Sensors did get accepted and recognised.

Currently all 4 Motion sensors are working.

Thank you for your help and patience.
Regards Piet

**Comment by AlCalzone** [comment]
Great! Guess we can close then?
