### ISSUE TITLE
Network Auto Heal schedule assistant / configuration option

### ISSUE THREAD

**Issue by jfhautenauven** [zwave-js/zwave-js-ui#3253]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to have an option to chose to activate auto heal network (from what I could understand reading here and there, it's active by default). Also, I would really like to have some sort of configuration to chose when to heal the network (scheduling).

The idea would be to avoid having the heal happening during times when my whole installation is susceptible to be in active use, and therefore avoid having lags / delays etc. 

Also, I would prefer to be able to set the frequency at which that happens (daily, weekly, monthly).

Just throwing an idea here, maybe I'm the only one thinking about those things, I can get geeky sometimes :)

**Comment by jfhautenauven** [comment]
@kpine yeah I understand that. I've read somewhere that somehow, every night, ZwaveJs(UI) does an auto heal ... but absolutely not sure it is true or not ... what i'm looking for is scheduling it at a greater interval / different times etc ...

@robertsLando and @AlCalzone  : can you confirm there is a auto heal every night ?

**Comment by robertsLando** [comment]
> can you confirm there is a auto heal every night

Never existed

**Comment by AlCalzone** [comment]
I think OpenHAB used to do this in the beginning. We don't for the reasons mentioned above.

**Comment by Trblz42** [comment]
so how i respond when ZWAVEJS UI shows my node heal status as "failed" but the log shows

> 2023-10-04 19:49:20.505 INFO APP: GET /health/zwave 301 1.362 ms - 191
> 2023-10-05T02:49:22.066Z CNTRLR « [Node 014] neighbor list refreshed...
> 2023-10-05T02:49:22.070Z CNTRLR » [Node 014] deleting return routes (attempt 1)...
> 2023-10-05T02:49:22.071Z CNTRLR » [Node 014] Deleting all return routes...
> 2023-10-05T02:49:22.170Z CNTRLR » [Node 014] assigning return routes to the following nodes:
> 1
> 2023-10-05T02:49:22.173Z CNTRLR » [Node 014] assigning return route to node 1 (attempt 1)...
> 2023-10-04 19:49:22.174 INFO Z-WAVE: Controller status: Rebuild Routes process IN PROGRESS. Healed 5 nodes
> 2023-10-05T02:49:22.176Z CNTRLR » [Node 014] requesting node neighbors...
> 2023-10-05T02:49:22.195Z CNTRLR « [Node 014] node neighbors received: 1, 9, 10, 11, 12
> 2023-10-05T02:49:22.197Z CNTRLR Rebuilding routes for sleeping nodes when they wake up
> 2023-10-05T02:49:22.199Z CNTRLR rebuilding routes completed
**> 2023-10-04 19:49:22.201 INFO Z-WAVE: Controller status: Rebuild Routes process COMPLETED. Healed 5 nodes**
> 2023-10-04 19:49:22.211 INFO Z-WAVE-SERVER: Client disconnected
> 2023-10-04 19:49:50.657 INFO APP: GET /health/zwave 301 2.400 ms - 191
> 2023-10-04 19:50:20.803 INFO APP: GET /health/zwave 301 1.362 ms - 191
> 2023-10-04 19:50:30.605 INFO Z-WAVE: [Node 010] Value updated: 102-0-currentState 0 => 0
> 2023-10-04 19:50:30.611 INFO Z-WAVE: [Node 010] Value updated: 102-0-position 0 => 0
