### ISSUE TITLE
Controller statistics improvements : for clarity and easier view of issues 

### ISSUE THREAD

**Issue by jfhautenauven** [zwave-js/zwave-js-ui#3254]
**Is your feature request related to a problem? Please describe.**
Not really a problem. Sometimes I get dropped RX or TX messages in the controller view.
Also it's not very clear in my head looking at the stats what all the values mean (CAN, NAK, etc). Sadly on that last point, google proved more confusing than helping in its answers :(

**Describe the solution you'd like**

- I would like to be able to click on the Dropped RX / TX and be given a list of what node experienced the issue.
- I would like to be able to hover the labels of the exposed metrics (CAN, NAK, etc.) and be given a tooltip or something that explains what it means / represents and if these values are indicative of any useful stats / health overview of my infrastructure.

**Describe alternatives you've considered**
- When clicking on the RX/TX : popup with more details ? 
- Instead of hovering over metrics titles showing a tooltip, it could also be a popup or something

PS : pardon the term "tooltip", that's how it is called in .NET (my domain of competence), maybe it has another name in js :) 

Thanks in advance :)

**Comment by robertsLando** [comment]
Here more info: 
Node statistics: https://zwave-js.github.io/node-zwave-js/#/api/node?id=quotstatistics-updatedquot
Controller statistics: https://zwave-js.github.io/node-zwave-js/#/api/controller?id=quotstatistics-updatedquot
