### ISSUE TITLE
Search Box in Desktop View

### ISSUE THREAD

**Issue by amosyuen** [zwave-js/zwave-js-ui#3255]
**Is your feature request related to a problem? Please describe.**

A search box for filtering devices in control panel exists in mobile view (small width) 
![image](https://github.com/zwave-js/zwave-js-ui/assets/422794/56785676-7bec-4cb0-9bad-453b1cf282bd)
. But disappears in desktop view (large width) 
![image](https://github.com/zwave-js/zwave-js-ui/assets/422794/667199b8-f142-4d40-bb1a-942ae9cd4fc8).

The desktop view with the table is much nicer, but there is no way to quickly search for a specific device.

**Describe the solution you'd like**

Also show the search box in the desktop view and filter the table by the search box.

**Describe alternatives you've considered**

**Additional context**

**Comment by robertsLando** [comment]
@amosyuen each column has a filter icon, by clicking on that you can enter the filters you want :)

**Comment by amosyuen** [comment]
Oh, totally missed that. Thanks for pointing that out.
