### ISSUE TITLE
"Indicate when a node should be re-interviewed" shows an incorrect status (never changes)

### ISSUE THREAD

**Issue by jfhautenauven** [zwave-js/zwave-js-ui#3258]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Z-Wave JS UI version

8.24.0

### ZwaveJS version

11.13.0

### Describe the bug

Since the latest release, with introduced new feature (Show icon when a node should be reinterviewed), that new icon doesn't go away even after doing a new interview of the node (or of all the nodes).

I get the blue icon since 8.24.0 first started up. Tried to reinterview each node, no effect.
Tried to refresh configs manually and then reinterview, no effect
Reboot, no effect

Included 2 new nodes today in my network, they also get the blue icon.

![image](https://github.com/zwave-js/zwave-js-ui/assets/83645528/80057174-549a-4ae1-949e-0735d52fb540)

### To Reproduce

- Update to version 8.24.0
- Start ZwaveJS-UI
- Blue icons show up on every device
- Re-interview each node, no effet

### Expected behavior

- Blue icon should go away after node has been reinterviewed
- Blue icon should not show up when there is no new config available

**Comment by snowmangh** [comment]
I have the same exact issue after I updated the firmware for two devices.
- Aeotec Siren 6
- Inovelli LZW30


**Z-Wave JS UI version** : 8.24.0
**ZwaveJS version** : 11.13.0

Not only do the blue icons don't disappear after a re-interview, the two devices are showing as "unknown". Pairing and re-pairing the devices do not fix the issue.

**Comment by rezzalex** [comment]
Hello,

Same plus lots of my nodes are "not answering" and/or even don't respond quickly or not at all to re-interview.

![Screenshot_2023-09-02-20-15-52-831_com.android.chrome.jpg](https://github.com/zwave-js/zwave-js-ui/assets/35136439/73fd7d46-47dd-47fd-bea7-45540577ab10)

**Comment by pa3fat** [comment]
Experience same on at least 1 of my Neo Coolcam nodes. V8.24.0

**Comment by robertsLando** [comment]
I have submitted a PR to fix the problem about the icon that doesn't hide after a re-interview. I don't understand why it's positioned like that in safari, I need to check what's going on there

**Comment by snowmangh** [comment]
Hello Robert,

I am still having issues with the latest fix. I now see an orange icon. I click on it and it seems to be doing something but the icon does not disappear and my two affected devices still show as "unknown". 

I tested the UI fix with Safari v15.6.1 and Firefox v116.0.3.

Un-pairing and re-pairing the device does not fix the issue.

![image](https://github.com/zwave-js/zwave-js-ui/assets/90811206/e31c9f9c-64c0-4ea4-a37e-3e412067233a)

**Comment by robertsLando** [comment]
Yeah seems now there is a bug on driver side 😢 I need to update driver and bump a new version

**Comment by robertsLando** [comment]
https://github.com/zwave-js/node-zwave-js/pull/6240

**Comment by jfhautenauven** [comment]
@robertsLando : thanks for the quick fix, I'll give it a shot as soon as the edge snap package version is refreshed :)

**Comment by jfhautenauven** [comment]
@robertsLando : if it can help you : this is how it looks in my chrome browser, latest version

![image](https://github.com/zwave-js/zwave-js-ui/assets/83645528/739f8287-a095-4332-b906-646193e8b1a4)

**Comment by robertsLando** [comment]
@jfhautenauven are you using docker `master` tag?

**Comment by jfhautenauven** [comment]
@robertsLando : nah, i'm using snap package diffused by giaver, edge version, 8.24.0
Docker was not an option (hosting on synology, too much issues). I run the whole thing inside a Debian 12 VM

**Comment by robertsLando** [comment]
OK so you need to wait I release a new version with the update of the driver. It's on master now but not released yet. Dunno if there is a channel on snap that picks updates from master

cc @jmgiaever

**Comment by robertsLando** [comment]
8.24.2 is building

**Comment by jmgiaever** [comment]
It's baking at this moment. Should be out in about 30 minutes. 32 bit will take a bit longer. 😊

**Comment by jfhautenauven** [comment]
No problemo, got a bit of time this evening to give it a shot, i'll report here the results :)

**Comment by jfhautenauven** [comment]
@jmgiaever : I see 8.24.2 avail on edge channel,  that's good already :p do you know when it gets promoted to candidate ? :p

**Comment by jmgiaever** [comment]
32 bit is finishing now, and is in the release step of the cycle. It's probably done in a few minutes and all builds will be promoted to candidate then. I can notify you.

**Comment by jmgiaever** [comment]
Finished now and promoted.

**Comment by jfhautenauven** [comment]
@robertsLando : confirmed to be working here, after restart, all blue bubble for reinterview are gone :)
I cannot give you a screen shot of the display of the blue bubble anymore, but what matters most is that the blue bubbles are working as they should now :) 

Thanks to you and mister @jmgiaever for making it happen so fast :) 

Cheers from Belgium :)

**Comment by snowmangh** [comment]
Thanks for trying to fix the issue. I can confirm that the blue or orange icon no longer displays itself. 👍 

Despite this fix, I still have the original issue after I updated the firmware for two devices. All entities show as "unknown".

Aeotec Siren 6 - Upgraded FW to version 1.9
Inovelli LZW30 - Upgraded FW to version 1.22

It is a curious coincidence and don't know what to do next.

**Comment by snowmangh** [comment]
All good now. I triggered the alarm (of my Siren 6) and the entity state changed from "unknown" to "on" and then "Off". Weird. No longer in an "unknown" state.

**Comment by jfhautenauven** [comment]
@snowmangh : when you do firmware update on any device, it's always a good idea to re-interview the devices and then (personal technique) I ask for the refresh of all value (Refresh all CC)
