### ISSUE TITLE
TypeError: t.newZwave.rf is undefined

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js-ui#3262]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.24.2

### ZwaveJS version

11.14.0

### Describe the bug

This error is seen in the Javascript console with a brand new installation.

I'm not sure if this has an effect on functionality or not, at first glance everything seems OK.

Related to this, if the `txPower` key is missing from settings.json, the settings page refuses to load completely. I get a second error:

```
TypeError: t.newZwave.rf.txPower is undefined
```

The settings.json file (snipped for brevity):

```
{
  "zwave": {
    "rf": {
      "region": 9
    }
}
```

I manage my settings file outside of ZUI. It would be nice to not have to set empty keys for settings which are optional. This is the case for most options in fact.

### To Reproduce

For case 1, start ZUI with a new configuration. Go to Settings and observe the error in the dev tools console.

For case 2, set a region but not power levels. Stop ZUI and manually edit the settings.json file. Remove the empty `"txPower": {}` key from the rf settings.

### Expected behavior

An error should not occur.

**Comment by robertsLando** [comment]
@kpine could you tell me the line that triggers that issue? I would need the entire stack to understand
