### ISSUE TITLE
8.25.0 docker tag won't load UI

### ISSUE THREAD

**Issue by abscondment** [zwave-js/zwave-js-ui#3267]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.25.0

### ZwaveJS version

11.14.0

### Describe the bug

After updating my docker tag to 8.25.0, the web application only shows a blank screen. Resources fail to load, as pictured below.

<img width="1281" alt="Screenshot 2023-09-06 at 2 51 01 PM" src="https://github.com/zwave-js/zwave-js-ui/assets/36872/adb41c0c-3a2c-42d0-b1c3-29c788a767d5">

If I change my tag back to `8.24.2`, the application loads successfully again:

<img width="1728" alt="Screenshot 2023-09-06 at 2 52 19 PM" src="https://github.com/zwave-js/zwave-js-ui/assets/36872/4d7f47cd-c553-4805-8de2-88ed960952b9">

### To Reproduce

* Run the `latest` or `8.25.0` docker tag
* Attempt to access the control panel

### Expected behavior

The application should load

### Additional context

Happy to provide my full docker-compose if that's necessary.

**Comment by abscondment** [comment]
Looks like I'm 7 minutes behind the times, probably should close this as a duplicate of #3267 :)

**Comment by robertsLando** [comment]
@abscondment try to remove `/control-panel/` from the url and retry

**Comment by abscondment** [comment]
Ah, there we go. Could be worth redirecting the old structure 🤷 

<img width="1728" alt="Screenshot 2023-09-06 at 11 26 08 PM" src="https://github.com/zwave-js/zwave-js-ui/assets/36872/c43f7a95-1322-4f3e-9424-f4c24e7aab84">

**Comment by robertsLando** [comment]
> Could be worth redirecting the old structure

I had to switch to a hash based history in order to make it working well behind a proxy :)
