### ISSUE TITLE
Uesr Codes are in the Wrong Sort Order

### ISSUE THREAD

**Issue by barndawgie** [zwave-js/zwave-js-ui#3270]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.25.0

### ZwaveJS version

11.14.0

### Describe the bug

I was making some updates to usercodes to remove code 6 out of the 7 codes I have. After the update, code 6 seemed to disappear, but then I found it at the bottom of the User Codes UI. Even after updating the value, refreshing the User Code CC's, etc... it remains out of sort order.

![User Code Order](https://github.com/zwave-js/zwave-js-ui/assets/11252867/9a8fd654-67e2-4d10-b617-cdf606ccad7f)

### To Reproduce

Setup 7 user codes
Mark code 6 as available

### Expected behavior

Code 6's settings remain in order between code 5 and 7

**Comment by robertsLando** [comment]
@barndawgie why aren't you using the Users codes table instead?

![Schermata da 2023-09-07 17-00-42](https://github.com/zwave-js/zwave-js-ui/assets/11502495/a891105e-e6b1-4bec-83b5-5d1038c6b85d)

**Comment by barndawgie** [comment]
Haha good point! I didn't realize those fields were editable until now...
