### ISSUE TITLE
`Actions` Section Still Referenced in Documentation

### ISSUE THREAD

**Issue by The00Dustin** [zwave-js/zwave-js-ui#3274]
It appears the documentation may not have been updated when the `Actions` dropdown was changed to a floating hamburger menu (or some sections may have been missed).  As I'm not even sure on the correct name for this menu and don't know how to create proper replacement GIF, I wanted to provide a list of locations where the documentation currently appears to reference the previous UI configuration:

- https://zwave-js.github.io/zwave-js-ui/#/usage/nodes-management refers to a buton under `Actions` under the **Managing Nodes** header.
- https://zwave-js.github.io/zwave-js-ui/#/usage/driver_function has references "clicking on Actions > Advanced Actions > Driver Function" just above the **Examples** header.
- https://zwave-js.github.io/zwave-js-ui/#/usage/driver_function has a GIF at the bottom of the page that uses the old button locations.

**Comment by robertsLando** [comment]
@The00Dustin Thanks! Fixed
