### ISSUE TITLE
Calling getNodeNeighbors api in MQTT returns no result

### ISSUE THREAD

**Issue by mayzyo** [zwave-js/zwave-js-ui#3276]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.25.0

### ZwaveJS version

11.14.1

### Describe the bug

`getNodeNeighbors` does not return any result despite being successful. I can call the other APIs fine, including `discoverNodeNeighbors`, which does return a boolean value in `result`.

### To Reproduce

Publish { "args": [3] } to zwave/_CLIENTS/ZWAVE_GATEWAY-zwave/api/getNodeNeighbors/set

### Expected behavior

Return an array of numbers.

### Additional context

I am connected to Mosquitto MQTT and use MQTT Explorer to trigger apis. My whole zwave setup works without any issue. I can get targetValue and set targetValue. 

I am using `set` and I have tried nodes that are active/sleeping. There's just no result being returned despite being successful.

The UI displays the neighbors to the node without any issue.

**Comment by robertsLando** [comment]
Try using `discoverNodeNeighbors`

**Comment by mayzyo** [comment]
I have tried `discoverNodeNeighbors` which returned result: true

**Comment by robertsLando** [comment]
Sorry I missed a return. Fixed on master
