### ISSUE TITLE
Yarn Installation Method Failing Dependencies

### ISSUE THREAD

**Issue by solomonj1963** [zwave-js/zwave-js-ui#3282]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Z-Wave JS UI version

8.25.1

### ZwaveJS version

11.14.2

### Describe the bug

When installing with yarn, the "yarn install" step gives multiple errors related to dependency failures.  I have attempted clearing the yarn cache and installation errors remain.  
<img width="1146" alt="Screenshot 2023-09-13 at 1 02 15 AM" src="https://github.com/zwave-js/zwave-js-ui/assets/21295474/dc4fc86b-2166-41ab-9a5a-2addfb0881e8">

### To Reproduce

Delete zwave-js-ui entirely, run "yarn cache clean", then run yarn installation steps per instructions on site.  Warnings seen while "yarn install" step is executing.  If you ignore the warnings and continue with "yarn run build", you get warnings there also, shown below.  
<img width="948" alt="Screenshot 2023-09-13 at 1 11 58 AM" src="https://github.com/zwave-js/zwave-js-ui/assets/21295474/72782ecd-c83d-4c9b-b844-bda2d971dc7c">
Then I copy the "store" folder with the configuration from the previous version into the new version.  Running "yarn start" appears to be running until you try to access the control panel at http://<host-ip>:<port>/control-panel which results in the following errors from the running compiled code and the control panel fails to open.  
<img width="932" alt="Screenshot 2023-09-13 at 1 20 38 AM" src="https://github.com/zwave-js/zwave-js-ui/assets/21295474/b5dcee39-b11c-4a10-b6bf-61d1187b7757">

### Expected behavior

Normal behavior on previous versions installed likewise per instructions operate normally and the control panel operates as expected.

### Additional context

I have never used the snap package because I'm on MacOS, current version.  The packaged versions you offer does not include the MacOS platform.  So I have always compiled from source with yarn as described in your documentation with no issues until this release.  My Node-JS version is v20.6.1 and npm version 9.8.1.  Yarn version 3.2.1.   Running "yarn explain peer-requirements pd92f5"  results in the following, which seems to indicate dependency definition issues.  
<img width="932" alt="Screenshot 2023-09-13 at 1 30 28 AM" src="https://github.com/zwave-js/zwave-js-ui/assets/21295474/6fd8adc1-098e-44cc-9d20-84266cee66be">

**Comment by robertsLando** [comment]
There is no blocking issue here, just warnings that can be ignored. The problem you are facing is https://github.com/zwave-js/zwave-js-ui/issues/3267. 

Just remove `/control-panel` from the url and everything will work

**Comment by solomonj1963** [comment]
You are 100% correct, thank you, and I apologize for not catching that!  I assumed that was a docker issue only based on the title.

On Sep 13, 2023, at 2:34 AM, Daniel Lando ***@***.***> wrote:



There is no blocking issue here, just warnings that can be ignored. The problem you are facing is #3267<https://github.com/zwave-js/zwave-js-ui/issues/3267>.

Just remove /control-panel from the url and everything will work
