### ISSUE TITLE
Clarify Home Assistant question in bug report issue template

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js-ui#3284]
Some users take the question about HA too literally:

> Are you using HomeAssistant?

It leads them to submit issues to the HA project just because they use HA, even when the issue is encountered when using ZUI itself, for example using the control panel, network map, etc.

It's a hard question to phrase clearly, but my first thought was something like:

> Were you using Home Assistant when you encountered the problem? Answer no if you have installed Home Assistant but you were using Z-Wave JS UI, such as the Control Panel, Network Map, etc.
>
> If yes, please open your issue at [https://github.com/home-assistant/core/issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
UNLESS a developer told you to come here.

That's not great either, but you probably get the idea.

**Comment by robertsLando** [comment]
What about just asking if they are expecting issue on zui or hass side?

> Are you using HomeAssistant? If the issue is related to something not working as expected on Zwave-JS UI such as Control Panel, Network Map, etc open the issue here, otherwise please open your issue at [https://github.com/home-assistant/core/issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
UNLESS a developer told you to come here.

**Comment by robertsLando** [comment]
So what should we do here?

**Comment by Hilo4321** [comment]
I think keeping it very simple might be a good move:

"Are you using Home Assistant to configure your Z-Wave network?"

or possibly add more clarification (though I think this gets quite muddy for those unaware of zjsui)

"Are you using Home Assistant (as opposed to zwave-js-ui) to configure your Z-Wave network?"
