### ISSUE TITLE
Serial Port doesn't support soft links based on udev rules

### ISSUE THREAD

**Issue by skyw33** [zwave-js/zwave-js-ui#3286]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.25.1

### ZwaveJS version

11.14.2

### Describe the bug

A udev rule was created resulting in this link /dev/zwave700 -> ttyUSB0
If I select ttyUSB0 from the "Serial Port" dropdown in the UI, then it works.  "zwave700" is not in the dropdown, so I type it in manually, but that does not work.  It gives me the following error:
```
2023-09-15T00:30:19.608Z DRIVER version 11.14.2
2023-09-15T00:30:19.609Z DRIVER
2023-09-15T00:30:19.609Z DRIVER starting driver...
2023-09-15T00:30:19.609Z DRIVER opening serial port /dev/zwave700
2023-09-15T00:30:28.626Z DRIVER Failed to open the serial port: Error: No such file or directory, cannot open
/dev/zwave700
2023-09-15T00:30:28.626Z DRIVER destroying driver instance...
2023-09-15T00:30:28.627Z DRIVER driver instance destroyed
```
Here are the permissions:
`lrwxrwxrwx 1 root root 7 Sep 14 14:53 /dev/zwave700 -> ttyUSB0`
`crwxrwxrwx 1 root root 188, 0 Sep 14 14:53 /dev/ttyUSB0`

### To Reproduce

Install zwavejsui via docker
`sudo docker run --name "zwavejs-ui_zwave700" --restart always -d -p 8092:8091 -p 3001:3000 --device=/dev/zwave700 -v /volume1/docker/zwavejs700/store:/usr/src/app/store zwavejs/zwave-js-ui:latest`
Change the serial port to a soft link
zwavejsui doesn't recognize the device

### Expected behavior

I would expect the link to work the same as the ttyUSB0 file

**Comment by robertsLando** [comment]
Problem here is that you are using docker, you need to create a map from the host machine device to the docker container. 

Like kpine suggested you could use: `--device=/dev/zwave700:/dev/zwave700` that explained is `--device=<host-dev>:<container-dev>`

**Comment by skyw33** [comment]
I changed my command line to `--device=/dev/zwave700:/dev/zwave700` and it worked.  Thanks for the quick replies.  Closing...
