### ISSUE TITLE
ERROR MQTT: Mqtt client error connect ECONNREFUSED 127.0.0.1:1883

### ISSUE THREAD

**Issue by gkyprios** [zwave-js/zwave-js-ui#3287]
Hi guys,

I migrated from HASS OS running on a Pi4 to HASS Container running in Docker some time ago. I followed a support post about migrating  ZwaveJS at the time and its all working fine. I have Mosquitto & Home Assistant setup in other containers.

However I see this error in the ZwaveJS Logs every 3 seconds, which makes log review very difficult:

2023-09-17 13:29:50.813 INFO MQTT: MQTT client reconnecting
2023-09-17 13:29:50.814 ERROR MQTT: Mqtt client error connect ECONNREFUSED 127.0.0.1:1883
Error: connect ECONNREFUSED 127.0.0.1:1883
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
2023-09-17 13:29:50.824 INFO MQTT: MQTT client closed

Here is my MQTT config:
![image](https://github.com/zwave-js/zwave-js-ui/assets/81947775/1ea45198-4ece-47b6-8679-15be0de03a33)

My apologies in advance if I should have posted this elsewhere.

Can someone assist me please?

**Comment by robertsLando** [comment]
@gkyprios Are you using mqtt discovery? The best way to work with home assistant is to use official home assistant integration paired with zwave-js-ui.

See: https://zwave-js.github.io/zwave-js-ui/#/homeassistant/homeassistant-official

**Comment by gkyprios** [comment]
Thanks @robertsLando. I'm using the official HA integration and its working fine. I dont need MQTT discovery. I dont think I ever enabled this for the new docker install. What am I missing?

![image](https://github.com/zwave-js/zwave-js-ui/assets/81947775/be7a04f4-e881-43d0-812f-9324f5ac6517)

**Comment by robertsLando** [comment]
![2023-09-18_11-10](https://github.com/zwave-js/zwave-js-ui/assets/11502495/385487be-3348-4d9b-a488-2b4922dbb216)

Just turn on this and you are done so :)
