### ISSUE TITLE
sytem start very slow upon startup (device was rebooted)

### ISSUE THREAD

**Issue by zeev-mindali** [zwave-js/zwave-js-ui#3290]
Dear all,

installed the zwave-js-ui via docker, and all works fine.
but when it's starting after reboot, the cpu is very high (100%) and it's takes up to an half an hour (10 devices) to start working.
i see the devices in the ui, but the status is in question mark.
how i can tell the system to save the info after first interview, and use it on next boot

**Comment by robertsLando** [comment]
Please share your docker-compose file or the command used to start zui and also attach driver logd

**Comment by zeev-mindali** [comment]
docker command :
docker run --rm -it -p 8091:8091 -p 3000:3000 --name=zwave --device=/dev/ttymxc6:/dev/zwave -v $(pwd)/store:/usr/src/app/store zwavejs/zwave-js-ui:latest

[zwave-js-ui-store.zip](https://github.com/zwave-js/zwave-js-ui/files/12673844/zwave-js-ui-store.zip)

**Comment by robertsLando** [comment]
cc @AlCalzone

**Comment by AlCalzone** [comment]
The log is showing some really weird pauses during startup, for example:
```
2023-09-20T13:19:44.672Z CNTRLR   [Node 053] The node is alive.
2023-09-20T13:28:03.896Z CNTRLR   Retrieving priority route to node 53...
2023-09-20T13:28:03.943Z CNTRLR   [Node 053] The node is ready to be used
```
I think the priority route stuff is initiated by Z-Wave JS UI as part of the "ready" callback, so something is blocking there for 8 minutes, before the driver can continue.

Also several serial messages are received multiple times. Not sure what could cause this, but it being on the OS/hardware side isn't entirely unlikely.

**Comment by zeev-mindali** [comment]
i using it on variscite som imx6ul-var-dart

product specefication data:
CPU NameNXP/Freescale iMX6UL / 6ULL / 6ULZ
CPU Type900MHz Cortex™-A7
Memory & Storage1 GB DDR3L,  128 GB eMMC
EthernetDual 10/100Mbps
WiFi/BT 802.11 ac/a/b/g/n, Bluetooth 5.2/BLE
Power consumptionUnder 5mA in suspend

**Comment by robertsLando** [comment]
@zeev-mindali Do you have locks devices?

**Comment by zeev-mindali** [comment]
nope, but i have glass9 from mcoHome (two of them),
once i removed it from the the zwave net, everything start to work faster...
node 53 that you mentaioned before.
my question, if the network and the node was already probe, why i need to wait again for probing after reboot,
does it not save the info to sqlite3 db file?

**Comment by robertsLando** [comment]
Does node 53 support schdule CC? @AlCalzone What I do in node ready is to also popolate schedule CC, BTW I fetch them from cache so that should not take this much....

@zeev-mindali Are you using latest version, right? I mean 8.25.1?

**Comment by AlCalzone** [comment]
You mean **Schedule Entry Lock CC*.
**Schedule CC** is a different one that zwave-js doesn't support yet. 

The missing device configs shouldn't cause this.

**Comment by robertsLando** [comment]
Yeah I mean Schedule Entry Lock CC.

So i have no clue what else could cause this sincerly

**Comment by AlCalzone** [comment]
Are there application logs that could give a hint what's happening in the time between the driver logs?

**Comment by robertsLando** [comment]
@AlCalzone could be.

@zeev-mindali Could you upload logs again but this time select application logs instead?

**Comment by zeev-mindali** [comment]
sure, i will connect the glass9 again later on, and send the entire logs directory

thanks for the help :)

**Comment by zeev-mindali** [comment]
where i can find the appllication logs

**Comment by zeev-mindali** [comment]
[zwavejs_current.log](https://github.com/zwave-js/zwave-js-ui/files/12685598/zwavejs_current.log)

**Comment by AlCalzone** [comment]
Application logs: https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=application-logs
Driver logs: https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs

**Comment by zeev-mindali** [comment]
find the error, it's mcoHome glass 9 product, sending a lot of information and retiries, once i took it out, system started to work faster
