### ISSUE TITLE
container has no permissions on USB device

### ISSUE THREAD

**Issue by Herbs851** [zwave-js/zwave-js-ui#3307]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.0.1

### ZwaveJS version

12.0.0

### Describe the bug

After upgrading from 8.26 to 9.0, the container no longer has rights to the key.

Before : 

![image](https://github.com/zwave-js/zwave-js-ui/assets/51154851/ba923c22-45d4-4479-be42-6402d9ab8f71)

After :

![image](https://github.com/zwave-js/zwave-js-ui/assets/51154851/78b81e47-6d2b-4e94-bd77-619712768b50)

I use zwave js ui in a podman container, my podman run : 

```
podman run -dt --name zwavejs -v /etc/localtime:/etc/localtime:ro -p 8091:8091 -p 3000:3000 \
--device /dev/serial/by-id/usb-0658_0200-if00:/dev/ttyACM0 -v /data/2_daily/zwavejs/config:/usr/src/app/store \
--group-add keep-groups zwavejs/zwavejs2mqtt:latest
```

Normally `--group-add keep-groups` for using device in podman ct is the good thing to do.

It seems to be the same as on this issue : 

https://github.com/zwave-js/zwave-js-ui/issues/1894

And disabling "soft reset" fix the problem.

### To Reproduce

1. Run the latest docker image
2. Get permission denied on /dev/ttyACM0

### Expected behavior

I should be able to access /dev/ttyACM0 inside my container

### Additional context

If i rollback to 8.26 everything works again without disabling "soft reset"

**Comment by robertsLando** [comment]
@Herbs851 Nothing has changed on code that could cause this, I think this is something related to podman or other tools that you are using to run the container

**Comment by Herbs851** [comment]
Thanks for you reply.

I'll investigate podman side.

last question: is there any risk in deactivating "soft reset" ?

**Comment by robertsLando** [comment]
@Herbs851 You shouldn't disable it, you should instead use /dev/serial/by-id path

**Comment by Herbs851** [comment]
I'm not sure I understand.

I should change ?

`--device /dev/serial/by-id/usb-0658_0200-if00:/dev/ttyACM0`

to

`--device /dev/serial/by-id/usb-0658_0200-if00:/dev/serial/by-id/usb-0658_0200-if00`

**Comment by robertsLando** [comment]
Oh nope sorry I didn't saw you were already using the by-id mapping. It's ok to use it like you are doing now, maybe try to change `/dev/ttyACM0` with `/dev/zwave` and use that inside the container.

**Comment by Herbs851** [comment]
Unfortunately it doesn't work : 

![image](https://github.com/zwave-js/zwave-js-ui/assets/51154851/432e3715-9912-4f62-9e55-4796549195f4)

**Comment by robertsLando** [comment]
@AlCalzone Can this be related to https://github.com/zwave-js/node-zwave-js/issues/6341 ?

**Comment by AlCalzone** [comment]
Not sure about podman, but at least Proxmox/LXC requires setting the ACL as part of udev rules:
https://github.com/AlCalzone/ioBroker.zwave2/blob/master/docs/en/vm-usb.md#proxmoxlxc

I assume this is because the stick reconnects during soft-reset and the ACL isn't restored properly. I'd recommend looking into that first and only disable soft-reset if you don't find a solution.

**Comment by Herbs851** [comment]
@robertsLando  @AlCalzone 

Thanks for support.

I've updated the Aeotec Gen5 firmware to version 1.2 => no effect 

I've also tried : 

```
KERNEL=="ttyACM[0-9]*", SUBSYSTEM=="tty", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200", SYMLINK="k-zwave", MODE="0777", GROUP="users"
```

and

```
KERNEL=="ttyACM[0-9]*", SUBSYSTEM=="tty", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200", SYMLINK="k-zwave", MODE="0777", GROUP="dialout"
```

And then in "my podman run"

`--device /dev/k-zwave:/dev/ttyACM0`

But no effect either, after that I have to admit that I'm not very comfortable with the udev rules.

**Comment by AlCalzone** [comment]
To be honest I have no clue about podman and USB either.
You may just have to disable soft-reset in the options manually. Z-Wave JS probably did that for you on the old version, but it no longer does.

**Comment by Herbs851** [comment]
ok, so let's go deactivate "soft reset".

Thank you both for your help ;) !!!
