### ISSUE TITLE
SyntaxError: Unexpected token '??=' at node_modules/@zwave-js/cc/build/lib/API.js:51

### ISSUE THREAD

**Issue by phippodoplis** [zwave-js/zwave-js-ui#3310]
### Checklist

- [x]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Z-Wave JS UI version

9.0.2

### ZwaveJS version

9.0.2

### Describe the bug

Sep 29 10:47:22 wopr systemd[1]: Started Zwave to Home Assistant bridge.
Sep 29 10:47:22 wopr npm[266401]: > zwave-js-ui@9.0.2 start /var/local/hass/zwavejs2mqtt
Sep 29 10:47:22 wopr npm[266401]: > node --preserve-symlinks server/bin/www.js
Sep 29 10:47:22 wopr npm[266413]: /var/local/hass/zwavejs2mqtt/node_modules/@zwave-js/cc/build/lib/API.js:51
Sep 29 10:47:22 wopr npm[266413]:         requireSupport ??= !endpoint.virtual;
Sep 29 10:47:22 wopr npm[266413]:                        ^^^
Sep 29 10:47:22 wopr npm[266413]: SyntaxError: Unexpected token '??='
Sep 29 10:47:22 wopr npm[266413]:     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
Sep 29 10:47:22 wopr npm[266413]:     at Module._compile (internal/modules/cjs/loader.js:1078:27)
Sep 29 10:47:22 wopr npm[266413]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
Sep 29 10:47:22 wopr npm[266413]:     at Module.load (internal/modules/cjs/loader.js:979:32)
Sep 29 10:47:22 wopr npm[266413]:     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
Sep 29 10:47:22 wopr npm[266413]:     at Module.require (internal/modules/cjs/loader.js:1003:19)
Sep 29 10:47:22 wopr npm[266413]:     at require (internal/modules/cjs/helpers.js:107:18)
Sep 29 10:47:22 wopr npm[266413]:     at Object.<anonymous> (/var/local/hass/zwavejs2mqtt/node_modules/@zwave-js/cc/src/cc/AssociationCC.ts:19:1)
Sep 29 10:47:22 wopr npm[266413]:     at Module._compile (internal/modules/cjs/loader.js:1114:14)
Sep 29 10:47:22 wopr npm[266413]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
Sep 29 10:47:22 wopr npm[266401]: npm ERR! code ELIFECYCLE
Sep 29 10:47:22 wopr npm[266401]: npm ERR! errno 1
Sep 29 10:47:22 wopr npm[266401]: npm ERR! zwave-js-ui@9.0.2 start: `node --preserve-symlinks server/bin/www.js`
Sep 29 10:47:22 wopr npm[266401]: npm ERR! Exit status 1
Sep 29 10:47:22 wopr npm[266401]: npm ERR!
Sep 29 10:47:22 wopr npm[266401]: npm ERR! Failed at the zwave-js-ui@9.0.2 start script.
Sep 29 10:47:22 wopr npm[266401]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Sep 29 10:47:22 wopr npm[266401]: npm ERR! A complete log of this run can be found in:
Sep 29 10:47:22 wopr npm[266401]: npm ERR!     /var/local/hass/.npm/_logs/2023-09-29T09_47_22_748Z-debug.log

### To Reproduce

This happens every time I try to start the service

### Expected behavior

Not crash

### Additional context

This started with 9.0.0. If I rewind back to v8.26.0 it works.
The log file mentioned looks like this:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.18
3 info using node@v14.21.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zwave-js-ui@9.0.2~prestart: zwave-js-ui@9.0.2
6 info lifecycle zwave-js-ui@9.0.2~start: zwave-js-ui@9.0.2
7 verbose lifecycle zwave-js-ui@9.0.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle zwave-js-ui@9.0.2~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/local/hass/zwavejs2mqtt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle zwave-js-ui@9.0.2~start: CWD: /var/local/hass/zwavejs2mqtt
10 silly lifecycle zwave-js-ui@9.0.2~start: Args: [ '-c', 'node --preserve-symlinks server/bin/www.js' ]
11 silly lifecycle zwave-js-ui@9.0.2~start: Returned: code: 1  signal: null
12 info lifecycle zwave-js-ui@9.0.2~start: Failed to exec start script
13 verbose stack Error: zwave-js-ui@9.0.2 start: `node --preserve-symlinks server/bin/www.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid zwave-js-ui@9.0.2
15 verbose cwd /var/local/hass/zwavejs2mqtt
16 verbose Linux 6.1.0-0.deb11.11-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v14.21.3
19 verbose npm  v6.14.18
20 error code ELIFECYCLE
21 error errno 1
22 error zwave-js-ui@9.0.2 start: `node --preserve-symlinks server/bin/www.js`
22 error Exit status 1

**Comment by robertsLando** [comment]
@phippodoplis Nodejs version? Min nodejs required version is now 18

**Comment by phippodoplis** [comment]
I'm on Debian Buster (oldstable) and that has nodejs 14.21.3

Shame it doesn't tell me that, but nevermind, I'll stick to the working 
zwavejs till I upgrade.

You can close this ticket.

Thanks,

Tim.

On 2023-09-29 14:45, Daniel Lando wrote:

> @phippodoplis [1] Nodejs version? Min nodejs required version is now 18
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/phippodoplis
[2] 
https://github.com/zwave-js/zwave-js-ui/issues/3310#issuecomment-1740923499
[3]

**Comment by robertsLando** [comment]
> I'm on Debian Buster (oldstable) and that has nodejs 14.21.3

That's not correct, you can install the nodejs version you prefer. I suggest to use [nvm](https://github.com/nvm-sh/nvm) to handle nodejs version
