### ISSUE TITLE
9.0.3 release failed

### ISSUE THREAD

**Issue by myoung34** [zwave-js/zwave-js-ui#3313]
### Checklist

- [x]  I am not using Home Assistant. Or: a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.0.3

### ZwaveJS version

12.0.2

### Describe the bug

The [docker publish action for 9.0.3](https://github.com/zwave-js/zwave-js-ui/actions/runs/6351216064) has failed

### To Reproduce

```
➜  ~ docker pull docker.io/zwavejs/zwave-js-ui:9.0.3
Error response from daemon: manifest for zwavejs/zwave-js-ui:9.0.3 not found: manifest unknown: manifest unknown
```

### Expected behavior

Should pull =)

**Comment by robertsLando** [comment]
Seems release job failed for some unknown reason, I triggered the action again, thanks for the report. Feel free to open if this fails again: 

https://github.com/zwave-js/zwave-js-ui/actions/runs/6351216064
