### ISSUE TITLE
Show dialog with changelog on upgrades

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js-ui#3315]
Similar to statistics dialog when an upgrade is detected we should show the changelog in a popup when a user opens the UI, the changelog should be fetched from GH release body and shown only once.

May be useful to also include release notes of zwave-js as well when there is a driver update (this could be done by using a regex on changelog to get new driver version)

CC @AlCalzone

**Comment by jeffjensen** [comment]
This is helpful for upgrading decision - I usually manually check the multiple releases to see.  Having it right with the upgrade notification is really nice.

**Comment by jmgiaever** [comment]
That is great. It probably should show for zwave-js-server too, as it's shipped with ZUI and its change log normally mention breaking changes for Home Assistant.

**Comment by robertsLando** [comment]
@kpine why not opt-out?

**Comment by jmgiaever** [comment]
I think @kpine is asking if it can be enabled by default, so the user actively needs to disable it.

**Comment by robertsLando** [comment]
> I think @kpine is asking if it can be enabled by default, so the user actively needs to disable it.

Nope, opt-in means the user must enable it, disabled by default, it's the opposite of opt-out that means the user will have to explicitly disable that function that is enabled by default

Anyway I understand you @kpine but you are very involved in the project so I think it's normal for you to check the changelog, normal users don't and this create issues and misunderstandings when upgrading. I think that making it opt-out will allow to reach more users, I can add a checkbox on the dialog like "Never show this again" to disable it easily

**Comment by robertsLando** [comment]
I store this on settings.json yeah
