### ISSUE TITLE
Node status shows alive but it has been unplugged for more than a day

### ISSUE THREAD

**Issue by bagobones** [zwave-js/zwave-js-ui#3321]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.0.3.c37f5a4

### ZwaveJS version

12.0.2

### Describe the bug

My NGD00Z-4 has been unplugged for more than 24hrs, shows a last active time stamp of noon yesterday but has a status of Alive still.

### To Reproduce

Node shows as alive but is unplugged.. not much more too it.

### Expected behavior

I would expect notes, especially ones that are powered / router devices to show as dead almost immediately if unplugged or at the very least after a configurable time.

### Additional context

In zigbee2mqtt it is possible to define how long a device can go unseen before reporting it as dead. I see no similar option in z-wave JS. 

O looked at the cron ping option but it states it is a bad idea for the network so I assume something is broken if the alive state is not updating.

**Comment by robertsLando** [comment]
@bagobones Follow updates there please
