### ISSUE TITLE
Traefik base path manipulation for Z-Wave JS UI not working anymore since version 9.0.0

### ISSUE THREAD

**Issue by airhead1234** [zwave-js/zwave-js-ui#3326]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.1.0

### ZwaveJS version

12.0.3

### Describe the bug

I am running Z-Wave JS UI via Docker and Traefik and used to access it via https://mydomain.com/zwave. The neccessary base path manipulation was take care of by the Traefik middleware described below.

Up until version 8.26.0 the base path manipulation worked and I could access Z-Wave JS UI as described above. Since version 9.0.0 my broswer does not load the Z-Wave JS UI interface fully anymore using https://mydomain.com/zwave. Rolling back to version 8.26.0 fixes the problem.

Even with version 9.0.0 and above I can access Z-Wave JS UI via port 8091 and my zwave network works as expected. So the only issue is the broken access via the manipulated base path.

This is the Traefik middleware code I use to manipulate the base path:
- traefik.http.middlewares.zwave-js-strip-basepath.stripprefix.prefixes=/zwave
- traefik.http.middlewares.zwave-js-inject-basepath.headers.customRequestHeaders.X-External-Path=/zwave/

Thank you!

 

### To Reproduce

Access Z-Wave JS UI with version 9.0.0 or above via Docker and Traefik via a subfolder path, e.g. https://mydomain.com/zwave, while trying to manipulate the base path through Traefik middleware.

### Expected behavior

Be able to access Z-Wave JS UI with the browser in a subfolder, e.g. https://mydomain.com/zwave, as it used to work in the versions before 9.0.0.

**Comment by robertsLando** [comment]
Did you checked this? https://github.com/zwave-js/zwave-js-ui/issues/3267

**Comment by airhead1234** [comment]
Yes, had checked #3267 before. I have made sure to remove "/control-panel/" from the URL, but still no success.

**Comment by robertsLando** [comment]
Never used Traefik, anyway this is how I make it work with nginx: https://github.com/zwave-js/zwave-js-ui/blob/master/docker/nginx/conf.d/default.conf#L42

Also could you tell me the error you see on browser console?

**Comment by airhead1234** [comment]
Thank you @robertsLando. I have fixed it now. Starting with Z-Wave JS UI version 9.0.0 it takes one additional "/" in the Traefik configuration. This it what works now:

- traefik.http.middlewares.zwave-js-strip-basepath.stripprefix.prefixes=/zwave/
- traefik.http.middlewares.zwave-js-inject-basepath.headers.customRequestHeaders.X-External-Path=/zwave/

**Comment by robertsLando** [comment]
Glad you fixed it :)
