### ISSUE TITLE
Incorrect variable name?

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js-ui#3327]
I think this should be `powerlevel`, not `powerLevel`?

https://github.com/zwave-js/zwave-js-ui/blob/1741fac56a5b4a75a5f3446c4988e77b63cfd374/src/stores/base.js#L28

Referenced here (I think):

https://github.com/zwave-js/zwave-js-ui/blob/1741fac56a5b4a75a5f3446c4988e77b63cfd374/lib/ZwaveClient.ts#L2137-L2143

I don't think it's causing an issue if you change settings via the UI, but something I noticed.

**Comment by BenjaminQuandt** [comment]
Both should be powerLevel, not powerlevel as u want to stay with camelcase!
https://google.github.io/styleguide/tsguide.html#identifiers

But I think u have a point in reporting inconsistent variables.

**Comment by robertsLando** [comment]
@kpine Yes, typo! Thanks
