### ISSUE TITLE
[feat] Create FakeDriver for ZwaveClient tests

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js-ui#333]
@ahochsteger As discussed, we should create a fake driver to allow testing. The FakeDriver should emit events based on a queue of events we decide, this queue could be stored in an array and could have the format used in the actual `event` emitted by zwaveClient. What we could do is to run the application with a real driver, catch those events,  create an array with them and store it somewhere for testing.

**Comment by ahochsteger** [comment]
I guess this would be a good reference to borrow from:
https://github.com/zwave-js/node-zwave-js/blob/798516f18aff53949b218252a3cac8a91f2bc49f/packages/zwave-js/src/lib/test/mocks.ts#L44
