### ISSUE TITLE
Unable to apply update 9.1.2

### ISSUE THREAD

**Issue by Tomadoggy** [zwave-js/zwave-js-ui#3333]
Seeing pop-up box in interface stating v9.1.2 is available but no way to apply the update.  Not showing anywhere in Home Assistant.  I am currently running v9.1.0.

Is there a manual way to apply the update?  Thanks in advance.

**Comment by Tomadoggy** [comment]
Thank you for the reply...but not sure I follow.   Here is my add-on:
![image](https://github.com/zwave-js/zwave-js-ui/assets/62314433/59b19e24-107c-47d8-a5ea-7ed91c5fa62c)

And I am being notified that there is an update withing the UI...how should I go about updating?

![image](https://github.com/zwave-js/zwave-js-ui/assets/62314433/8269d900-7d2e-4460-9653-e6ed30f349b0)

**Comment by Tomadoggy** [comment]
???  So why am I seeing the "New version available"?  Sorry if this is an ID10t question, but trying to learn here.

**Comment by robertsLando** [comment]
9.1.2 fixes the notification issue. No need to disable the changelog

**Comment by robertsLando** [comment]
> Well, I didn't mention anything about changelog. 😆

Yeah I know that was just because someone could have suggested that as solution, 9.1.2 made it opt-in so if someone wants can enable that on settings :)
