### ISSUE TITLE
cannot set value to shutter

### ISSUE THREAD

**Issue by zeev-mindali** [zwave-js/zwave-js-ui#3334]
Dear All,

i have a shutter from MCOHOME
<img width="1665" alt="Screenshot 2023-10-11 at 15 33 11" src="https://github.com/zwave-js/zwave-js-ui/assets/23069323/3bdd8e17-a817-4db7-be70-48d2bd4622ba">

i can control the binary switch by the control panel
<img width="891" alt="Screenshot 2023-10-11 at 15 33 22" src="https://github.com/zwave-js/zwave-js-ui/assets/23069323/ae32c5f3-20d5-4f64-9d7e-36ef3c5ea91f">

and sending mqtt command 37 , true false, which is working

but i can not control the value from the ui:
<img width="507" alt="Screenshot 2023-10-11 at 15 33 35" src="https://github.com/zwave-js/zwave-js-ui/assets/23069323/d563e989-596a-4483-9580-bb6eca2aed57">

and any attempt to send also value is not effecting the shutter.

**Comment by robertsLando** [comment]
@zeev-mindali YOu should use targetValue to control the state

**Comment by zeev-mindali** [comment]
i using targetValue, as i mantion, i can send true/false, and the shutter goes up and down.
but when i send a value:
{
    "value":50
}

northing happend

**Comment by zeev-mindali** [comment]
my topic is :
zwave/sallon/shutter/38/0/currentValue/set

json:
{
   "value":50
}

**Comment by robertsLando** [comment]
I mean:

`zwave/sallon/shutter/38/0/targetValueValue/set`

**Comment by zeev-mindali** [comment]
my mistake, i did use :zwave/sallon/shutter/38/0/targetValue/set
on the ui there is no target to cc 38 as i showed in the picture, the value is read only on the ui

**Comment by robertsLando** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field)

@AlCalzone any clue?

**Comment by zeev-mindali** [comment]
on it, moving to docker and sending logs

**Comment by AlCalzone** [comment]
Is there a Window Covering CC in the list? If so, use that.

**Comment by zeev-mindali** [comment]
sorry, but there is no window covering
<img width="1642" alt="Screenshot 2023-10-15 at 9 30 33" src="https://github.com/zwave-js/zwave-js-ui/assets/23069323/ee2bf1b8-49fb-4bf8-898f-05a4da304829">

the only setting i have is this:
<img width="1467" alt="Screenshot 2023-10-15 at 9 31 25" src="https://github.com/zwave-js/zwave-js-ui/assets/23069323/bdfa13fc-442b-42bc-b233-2c2d47041ed3">

but i can not send any mqtt command to it using command 38, or setting the value in the ui

the manufactor is:
<img width="1646" alt="Screenshot 2023-10-15 at 9 30 47" src="https://github.com/zwave-js/zwave-js-ui/assets/23069323/b74003d2-e9a0-435b-b48d-ec216418d987">

**Comment by zeev-mindali** [comment]
does the problem related to the issue unkown product?

**Comment by zeev-mindali** [comment]
i found the config file that i need, where i need to drop the file?
if i enter via docker and creating in store a folder config,manufactor hex code and the confing

<img width="459" alt="Screenshot 2023-10-15 at 18 00 26" src="https://github.com/zwave-js/zwave-js-ui/assets/23069323/3ffd412d-3b09-4933-a37f-9c4a2ea751b2">

i still getting unknown product
<img width="724" alt="Screenshot 2023-10-15 at 18 01 17" src="https://github.com/zwave-js/zwave-js-ui/assets/23069323/8b40837e-ccaf-4b8e-a6c7-5e52a4b2ead2">

what am i missing?

**Comment by zeev-mindali** [comment]
i can see the driver was loaded finally,

<img width="608" alt="Screenshot 2023-10-16 at 7 53 16" src="https://github.com/zwave-js/zwave-js-ui/assets/23069323/965bb7d9-1165-4d9c-bc64-905ff703dfbc">

but i still not have option to edit the value, and i don't see the options that are inside the config file

**Comment by AlCalzone** [comment]
As asked before, please share the driver log of the interview. Just screenshots don't help diagnose this.

**Comment by zeev-mindali** [comment]
can you please send the link for how to active the driver log?
sorry

**Comment by AlCalzone** [comment]
https://github.com/zwave-js/zwave-js-ui/issues/3334#issuecomment-1758971695

**Comment by zeev-mindali** [comment]
[zwave-js-ui-store.zip](https://github.com/zwave-js/zwave-js-ui/files/12915324/zwave-js-ui-store.zip)

**Comment by AlCalzone** [comment]
The device claims it doesn't support Multilevel Switch CC when queried for the CC version. We can override that in a config file, but we currently don't have any for the device - which is also why it wasn't identifying with a label at first.

Where do you have your config file from?

**Comment by zeev-mindali** [comment]
i got the config file from your github

and the information from :
https://devices.zwave-js.io/?jumpTo=0x015f:0xc321:0x5102:0.0

but the config file, the configuration paramter are wrong.
i editing now the config file for my devices.

how can i override the multilevel switch?

**Comment by zeev-mindali** [comment]
this my config file for mh-c521/mh-c621 that is working:

[mh-C621.json](https://github.com/zwave-js/zwave-js-ui/files/12919123/mh-C621.json)

but still i need to override the multilevel to writeable

**Comment by AlCalzone** [comment]
You'll have to add it via a compat flag: https://zwave-js.github.io/node-zwave-js/#/config-files/file-format?id=commandclassesadd
Not sure which version of the CC is supported, maybe your manual explains it?

**Comment by zeev-mindali** [comment]
yeeessssssss, made it to work :) 
you are the best, thanks for all the help,
