### ISSUE TITLE
Also listen to IPv6 by default

### ISSUE THREAD

**Issue by zargony** [zwave-js/zwave-js-ui#3347]
**Is your feature request related to a problem? Please describe.**
zwave-js-ui listens to 0.0.0.0:8091 by default, which is IPv4 only, so it doesn't respond to IPv6 requests.

**Describe the solution you'd like**
It would be nice to listen to IPv6 as well by default since IPv6 is widely used everywhere nowadays. All that's needed is bind to `::` instead of `0.0.0.0` (e.g. by setting `HOST="::"` in the current version). Imho, this should be the default. (Generally, it works well binding to `::` as this listens on IPv6 and IPv4 on dual stack systems. Not sure if there are systems out there that would bind to IPv6 only with `::`)

**Describe alternatives you've considered**
The alternative to listen to IPv6 only by default would be possible but maybe a step too far for now ;)

**Comment by robertsLando** [comment]
@zargony I'm wondering if this could create any kind of problems in docker container? I mean `::` should extend the  previous `0.0.0.0`, right?

**Comment by zargony** [comment]
@robertsLando Yes, I suppose. I actually discovered it running zwave-js-ui in k8s with IPv6 only while it previously worked in my dual stack k8s. So it definitely works in containers. From what I understand, binding `0.0.0.0` always binds IPv4 only while binding `::` usually binds IPv6 and IPv4. Details might depend on the library that parses the address and/or the library that actually binds the socket via libc. Not sure which part exactly is responsible for choosing IPv6 *and* IPv4 when you give `::`, though.

Btw, the same goes for the websocket server on port 3000. It binds to IPv4 only `0.0.0.0` by default until setting "Server Host" under "Home Assistant" in the settings to `::`.

**Comment by robertsLando** [comment]
Ok let me do some checks

**Comment by Jypy** [comment]
FYI this affect hosts with IPv6 support disabled.
The fix is to set the HOST environment (back) to 0.0.0.0, in case someone else run into the issue :)

**Comment by robertsLando** [comment]
@Jypy Do you mean that if ipv6 is disabled this would prevent the UI to be reached?

**Comment by Jypy** [comment]
yep, actually, it crashes because it can't bind to ::

**Comment by robertsLando** [comment]
Oh that's bad... Let's see if this is a recurring issue I could do a revert in case. I dunno if there are more that benefit from this change then the ones that have problems.

**Comment by Jypy** [comment]
> I dunno if there are more that benefit from this change then the ones that have problems.
No idea, you'll soon be aware if that's the case.

> Thanks for your report!
No problem, happy to help!
Thanks for the app/tool :)

**Comment by Skullduggeryism** [comment]
just an FYI - this change broke my docker-compose environment where I have ipv6 disabled. I had to fix by setting an environment variable of HOST and setting it to the value of the container IP

For some reason setting HOST back to 0.0.0.0 did not fix it either

**Comment by robertsLando** [comment]
> According to [server.listen](https://nodejs.org/docs/latest-v18.x/api/net.html#serverlisten) docs (emphasis mine):
> 
> 
> 
> > If **host is omitted**, the server will accept connections on the [unspecified IPv6 address](https://en.wikipedia.org/wiki/IPv6_address#Unspecified_address) (::) **when IPv6 is available**, or the [unspecified IPv4 address](https://en.wikipedia.org/wiki/0.0.0.0) (0.0.0.0) otherwise.
> 
> 
> 
> Maybe that would support both cases?

This maybe a good alternative! I will try, sorry for the issues guys

**Comment by Rickerdo** [comment]
My rock solid install would not restart after upgrading to 9.2.1 because of this issue. Even downgrading to 9.2.0 didn't help. Per Skullduggeryism's post, I added "- HOST=0.0.0.0" to my docker-compose.yml file, did an upgrade to 9.2.1, and all is well again.

FWIW - I also have IPv6 disabled through the kernel because I have no need for IPv6 on my LAN.

**Comment by robertsLando** [comment]
Can someone of you give a try to: https://github.com/zwave-js/zwave-js-ui/pull/3362 ?

I can build a test docker container for it

**Comment by robertsLando** [comment]
@zargony could you confirm me that `test` tag works for ipv6 too? I got confirmation that it's working for the once that had the problem described above but dunno if still works for you

**Comment by zargony** [comment]
@robertsLando Using image `zwavejs/zwave-js-ui:test`, without setting `HOST`, its UI is reachable via IPv6 and it connects to IPv6 mqtt fine. However, websocket (port 3000) doesn't seem to be reachable via IPv6 when you leave "Server Host" empty in "Home Assistant" section of settings.

**Comment by robertsLando** [comment]
Good for the UI side, for the ZwaveJsSide the problem is that they set `defaultHost` to 0.0.0.0, see https://github.com/zwave-js/zwave-js-server/blob/master/src/lib/server.ts#L509.

My suggestion is to open an issue there to suggest the change like I did on my side to simply not provide the host as default. I can merge the fix on my side

**Comment by zargony** [comment]
Makes sense. Thanks!
