### ISSUE TITLE
SyntaxError: Invalid or unexpected token with v9.2.3

### ISSUE THREAD

**Issue by gonzo09** [zwave-js/zwave-js-ui#3376]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

No idea (as it won't start)

### ZwaveJS version

9.2.2

### Describe the bug

SyntaxError: Invalid or unexpected token at container startup
See stacktrace below.

### To Reproduce

Pull image 9.2.3 and start zwave js container

### Expected behavior

Startup sucessfully

### Additional context

Zwave JS container won't start with 9.2.3 version (tag latest). Therefore, the UI is not accessible.
There is no problem with the 9.2.2 version. 
Here is all the logs I got when starting the container:
```
pi@raspberrypi:/home/domotique $ sudo docker-compose up zwavejs2mqtt
Recreating zwavejs2mqtt ... done
Attaching to zwavejs2mqtt
zwavejs2mqtt     | /usr/src/app/node_modules/fast-deep-equal/index.js:1
zwavejs2mqtt     | 
zwavejs2mqtt     | 
zwavejs2mqtt     | 
zwavejs2mqtt     | SyntaxError: Invalid or unexpected token
zwavejs2mqtt     |     at internalCompileFunction (node:internal/vm:73:18)
zwavejs2mqtt     |     at wrapSafe (node:internal/modules/cjs/loader:1176:20)
zwavejs2mqtt     |     at Module._compile (node:internal/modules/cjs/loader:1218:27)
zwavejs2mqtt     |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
zwavejs2mqtt     |     at Module.load (node:internal/modules/cjs/loader:1117:32)
zwavejs2mqtt     |     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
zwavejs2mqtt     |     at Module.require (node:internal/modules/cjs/loader:1141:19)
zwavejs2mqtt     |     at require (node:internal/modules/cjs/helpers:110:18)
zwavejs2mqtt     |     at Object.<anonymous> (/usr/src/app/node_modules/@homebridge/ciao/src/coder/records/NSECRecord.ts:2:1)
zwavejs2mqtt     |     at Module._compile (node:internal/modules/cjs/loader:1254:14)
pi@raspberrypi:/home/domotique $ 
```

**Comment by robertsLando** [comment]
It works on my side. Could you tell me the output of `uname -a` command?

**Comment by gonzo09** [comment]
Sure: 
`Linux raspberrypi 5.10.103-v8+ #1530 SMP PREEMPT Tue Mar 8 13:06:35 GMT 2022 aarch64 GNU/Linux`

**Comment by robertsLando** [comment]
Could be that docker arm64 container is bugged. I only have docker x64, I would need some other user to tell me if they have problems with that too

**Comment by robertsLando** [comment]
@gonzo09 could it be that your sd card is corrupted maybe? Could you try with another device? Or could you try to pull another image maybe by using **master** tag instead?

**Comment by gonzo09** [comment]
@robertsLando I'm on SSD and everything else works fine. I rollbacked to 9.2.2 and it's working too (so no hurry for me). 
I just saw that image zwavejs/zwavejs2mqtt is deprecated but still maintain. I'll try to switch to zwavejs/zwave-js-ui image and/or master tag.

**Comment by robertsLando** [comment]
OK let me know so

**Comment by robertsLando** [comment]
Closing, feel free to reopen
