### ISSUE TITLE
Cant find any device. Nether from Home Assistant, then UI

### ISSUE THREAD

**Issue by Schmandre** [zwave-js/zwave-js-ui#3379]
Dump:
[config_entry-zwave_js-668b86c8274e71c6b5fdbe9a391e8eb8.json.txt](https://github.com/zwave-js/zwave-js-ui/files/13169434/config_entry-zwave_js-668b86c8274e71c6b5fdbe9a391e8eb8.json.txt)

### Version

Build/Run method:

[X] Docker
[ ] Git Clone + yarn install + yarn run build + yarn start
[ ] Pkg

Z-Wave JS UI version: **zwave-js-ui: 9.2.3.1454eca
Z-Wave JS version: **zwave-js: 12.2.1**

### Describe the bug

Maybe Iam fkin stupid, but Iam not able to pair the ABUS Smoke Sensors. 

I press the "pairing" button three times, the LED is flashing green. I run pairing mode in Home Assistant and Z-Wave UI. Both are same. The device wont be discovered. I have the MQTT disabled, cause there was an error after start that mqtt cant be startet on default port. 

I run deconz  container (zigbee) with ConBeeII stick also on the same system. Here is anything fine and working. 

If I enable the mqtt, I got spammed with this error messages
```zwave-js-ui  | 2023-10-25 20:39:53.327 INFO MQTT: MQTT client closed
zwave-js-ui  | 2023-10-25 20:39:56.327 INFO MQTT: MQTT client reconnecting
zwave-js-ui  | 2023-10-25 20:39:56.330 ERROR MQTT: Mqtt client error connect ECONNREFUSED 192.168.0.250:1883
zwave-js-ui  | Error: connect ECONNREFUSED 192.168.0.250:1883
zwave-js-ui  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
zwave-js-ui  | 2023-10-25 20:39:56.332 INFO MQTT: MQTT client closed
```

What did I make wrong :(

Thanks in advanced

**Comment by Schmandre** [comment]
Thank you for your reply and assistance.

>You need to enable inclusion mode in HA/ZUI first, then perform the action on the device. The manual should have these instructions. 

Done like that now, doesnt work :(

>If [this](https://products.z-wavealliance.org/products/3089?selectedFrequencyId=-1) is your device, then the ZWA DB also has [network management instructions](https://products.z-wavealliance.org/products/3089/network).

Yes, that is the device :)

> A.) Slide the base unit from the mounting plate and remove the safety strip from the battery compartment
> **B.) Click the + (Add) button in your Z-Wave App and follow the further instructions**
> C.) **Press the Network-button 3 times within 1.5 seconds** and the Status-LED on the base unit front will flash 3 times. The App > will show if the Add device process was successful and the Status-LED will turn off. Repeat the inclusion process from step B if it was not successful.

Did exactly like that, Ill attach a short clip
https://github.com/zwave-js/zwave-js-ui/assets/47451170/c43e760f-71b4-4fe3-a6e3-db12ceb4ec0f

> You don't need to turn on mqtt if you are using the HA integration. If you turn on mqtt, you should then configure it with a broker address.

Perfect. But why it wont work anyway :(

Here are the log files, I cant see any communication:
```
2023-10-26 17:18:02.363 DEBUG SOCKET: New connection ZR5LK273Rb3NV3lwAAAJ
2023-10-26 17:18:02.374 INFO APP: GET /favicon.ico 304 2.762 ms - -
2023-10-26 17:18:02.395 DEBUG SOCKET: Event INITED emitted to ZR5LK273Rb3NV3lwAAAJ
2023-10-26 17:18:02.415 INFO APP: GET /favicon.ico 304 3.796 ms - -
2023-10-26 17:18:03.497 INFO APP: GET /api/settings 200 1215.410 ms - 13810
2023-10-26 17:18:03.534 INFO APP: GET /api/auth-enabled 304 5.746 ms - -
17:18:07.414 DRIVER   all queues busy
17:18:07.423 SERIAL » 0x0103003bc7                                                         (5 bytes)
17:18:07.425 DRIVER » [REQ] [GetBackgroundRSSI]
17:18:07.431 SERIAL « [ACK]                                                                   (0x06)
17:18:07.435 SERIAL « 0x0107013b9491917f29                                                 (9 bytes)
17:18:07.441 SERIAL » [ACK]                                                                   (0x06)
17:18:07.446 DRIVER « [RES] [GetBackgroundRSSI]
                        channel 0: -108 dBm
                        channel 1: -111 dBm
                        channel 2: -111 dBm
17:18:07.455 DRIVER   all queues idle
2023-10-26 17:18:17.781 DEBUG SOCKET: Event ZWAVE_API emitted to ofS-h_t2t4Hs3KQvAAAH
2023-10-26 17:18:17.785 INFO Z-WAVE: Calling api startInclusion with args: [ 0, { forceSecurity: false, name: '', location: '' }, [length]: 2 ]
17:18:17.788 CNTRLR   Starting inclusion process with strategy Default...
17:18:17.793 DRIVER   all queues busy
17:18:17.799 SERIAL » 0x0105004ac10574                                                     (7 bytes)
17:18:17.801 DRIVER » [REQ] [AddNodeToNetwork]
                        node type:    Any
                        high power:   true
                        network wide: true
                        callback id:  5
17:18:17.811 SERIAL « [ACK]                                                                   (0x06)
17:18:17.815 SERIAL « 0x0108004a0501000000b9                                              (10 bytes)
17:18:17.819 SERIAL » [ACK]                                                                   (0x06)
17:18:17.825 DRIVER « [REQ] [AddNodeToNetwork]
                        status:      Ready
                        callback id: 5
17:18:17.830 CNTRLR   The controller is now ready to add nodes
2023-10-26 17:18:17.831 INFO Z-WAVE: Controller status: Secure inclusion started
2023-10-26 17:18:17.834 INFO Z-WAVE: Success zwave api call startInclusion true
17:18:17.840 DRIVER   all queues idle
17:18:37.415 DRIVER   all queues busy
17:18:37.423 SERIAL » 0x0103003bc7                                                         (5 bytes)
17:18:37.425 DRIVER » [REQ] [GetBackgroundRSSI]
17:18:37.431 SERIAL « [ACK]                                                                   (0x06)
17:18:37.435 SERIAL « 0x0107013b9391917f2e                                                 (9 bytes)
17:18:37.439 SERIAL » [ACK]                                                                   (0x06)
17:18:37.444 DRIVER « [RES] [GetBackgroundRSSI]
                        channel 0: -109 dBm
                        channel 1: -111 dBm
                        channel 2: -111 dBm
17:18:37.450 DRIVER   all queues idle
17:18:47.787 CNTRLR   stopping inclusion process...
17:18:47.791 DRIVER   all queues busy
17:18:47.796 SERIAL » 0x0105004ac50673                                                     (7 bytes)
17:18:47.802 DRIVER » [REQ] [AddNodeToNetwork]
                        action:       Stop
                        high power:   true
                        network wide: true
                        callback id:  6
17:18:47.809 SERIAL « [ACK]                                                                   (0x06)
17:18:47.816 SERIAL « 0x0108004a0606000000bd                                              (10 bytes)
17:18:47.820 SERIAL » [ACK]                                                                   (0x06)
17:18:47.834 DRIVER « [REQ] [AddNodeToNetwork]
                        status:      Done
                        callback id: 6
17:18:47.837 CNTRLR   The inclusion process was stopped
2023-10-26 17:18:47.839 INFO Z-WAVE: Controller status: Inclusion stopped
17:18:47.851 DRIVER   all queues idle
```
At the log (before log to file) I found that there was a message with sth. like frequency USA? Maybe that's an issue? I live in Germany and use the german product.

**Comment by mojomojoman** [comment]
I am not familiar at all with your specific device but with most devices there is a method to do a factory reset of the device.  If yours has this you should try it first.  I sometimes have to do this with troublesome zwave devices because if for some reason the device thinks it is associated already to a controller then it will not join a new one.  If the device does not have a factory reset method then you could try following the Exclusion process (even though it was never included properly).  Once the reset or exclusion is complete try the normal inclusion process again.  

Also I have had some devices that will not include properly unless they are close enough to the actual controller that they can speak directly instead of through the zwave mesh network.  So you may try finding some way to get them closer.  Once included they usually can be moved further away as zwave will make a mesh network and other powered devices act as repeaters for the network. (battery powered devices do NOT act as repeaters though).
