### ISSUE TITLE
Z-Wave JS UI 3.0.0 - dark mode no longer working

### ISSUE THREAD

**Issue by ahahamyan** [zwave-js/zwave-js-ui#3382]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

3.0.0

### ZwaveJS version

HA 2023.10.5

### Describe the bug

Dark mode on UI is not working, even though set, it shows white background. When toggled on and off, it works, but then when you go back in, it is back to white background again even though dark mode toggle is on.

### To Reproduce

open Zwave JS UI, and set dark mode. Go to another part of HA and then come back to zwave-js-ui and it will be back with white background even though dark mode toggle is on.

### Expected behavior

When dark mode is selected, it should remain persistent until changed.

**Comment by nathan-curtis** [comment]
+1
a permanent Dark mode user here - 3.0.0 pops in "blind me" mode first time I open the main JS_UI screen no matter what is selected in the Settings: UI menu

Install mode: JS_UI 3.0.0 HA Addon

**Comment by robertsLando** [comment]
When you change the dark mode in settings do you press save?

**Comment by Trblz42** [comment]
I have the same issue. To reproduce

1. updated to JS_UI 3.0.0                                 .... now the UI is in light mode.
2. ZwaveJS -> Settings -> UI                           .... Dark Mode switch is still in Enabled
3. Dark Mode switch on -> off 
4. Dark Mode switch off -> on                         ..... now the UI is in dark mode
5. Save 
6. Switch to another view
7. Switch back to Zwave JS UI                           ....its back in light mode.

**Comment by nathan-curtis** [comment]
Exact same repro/workflow here @robertsLando

**Comment by robertsLando** [comment]
I'm sorry for the issue guys, I will fix it ASAP 🙏🏻 in the meantime downgrade to previous version. I will try to reproduce this on my end
