### ISSUE TITLE
Documentation seems incorrect for "Send with options" should include /set to be clear

### ISSUE THREAD

**Issue by jrgleason** [zwave-js/zwave-js-ui#3387]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

latest

### ZwaveJS version

latest

### Describe the bug

If you go to the documentation and got to set (https://zwave-js.github.io/zwave-js-ui/#/guide/mqtt?id=set-values) then look for set with options the topic name reads

<img width="400" alt="Screen Shot 2023-10-29 at 5 18 49 PM" src="https://github.com/zwave-js/zwave-js-ui/assets/1319151/5d637160-7717-4080-a506-cca9666168a4">

However as previous it should include the set like 

`zwave/office/light/38/0/targetValue/set`

This is correct in the regular set documentation above it.

### To Reproduce

Try to call a similar topic without the /set on your local and notice it doesn't work. Add the /set and notice it still respects the options.

### Expected behavior

I would expect the documentation to have the correct topic with the /set

**Comment by robertsLando** [comment]
Correct. Let me fix this asap
