### ISSUE TITLE
Dark mode setting is ignored

### ISSUE THREAD

**Issue by jfhautenauven** [zwave-js/zwave-js-ui#3392]
### Checklist

- [x]  I am not using Home Assistant. Or: a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Z-Wave JS UI version

9.3.0

### ZwaveJS version

12.2.3

### Describe the bug

Since latest update, version 9.3.0 the dark mode doesn't stay enabled.

Dark mode was enabled and working before the update.
After the update, the UI goes back to White mode, even though Dark mode is still enabled in the settings.

Toggling dark mode makes it enabled again, until you Save the settings, then it goes back to white mode.

### To Reproduce

Scenario 1 :
Enable dark mode in previous version.
Update to 9.3.0.

Scenario 2 : 
Enable dark mode in the settings
Hit "Save"

### Expected behavior

Dark mode is enabled and stays enabled as expected

**Comment by jfhautenauven** [comment]
Sorry, hadn't seen it in the list :) Thanks for the fix mate :)

**Comment by robertsLando** [comment]
No worries, release is coming :)
