### ISSUE TITLE
Include `WAKEUP` in `HELP` Section of Device Information

### ISSUE THREAD

**Issue by The00Dustin** [zwave-js/zwave-js-ui#3395]
**Is your feature request related to a problem? Please describe.**
Wakeup methods for battery devices vary as wildly as inclusion and exclusion, but they aren't shown in the device information.

**Describe the solution you'd like**
I would like the `HELP` section of the device information to include `WAKEUP` in addition to `INCLUSION`, `EXCLUSION`, and `RESET`.

**Describe alternatives you've considered**
One can use the device link to open the DB online, but this requires Internet availability.

**Additional context**
When I want to change the configuration of my devices, I have to check the DB or find the manual.  For instance, the [ZEN34 entry](https://devices.zwave-js.io/?jumpTo=0x027a:0x0004:0xf001:0.0) includes wakeup in the device instructions, and I have created a [pull request to do the same for the ZSENS930](https://github.com/zwave-js/node-zwave-js/pull/6474).  I was also pointed to what may be the appropriate [line of code](https://github.com/zwave-js/zwave-js-ui/blob/7b8d2e794a0a3c10ba99ad10ba999d8c73765c93/src/components/nodes-table/ExpandedNode.vue#L352) to effectuate this change in Discord, but I didn't want to blindly submit a PR that might risk breaking something if other changes could be necessary to make this happen.

**Comment by robertsLando** [comment]
Fixed, thanks for the detailed issue @The00Dustin ! :)
