### ISSUE TITLE
Lost my aeotec key during an update or restart of zwavejs UI

### ISSUE THREAD

**Issue by jerome6994** [zwave-js/zwave-js-ui#3400]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.3.1.f26b79e

### ZwaveJS version

12.2.3

### Describe the bug

Good morning

When updating my docker container or restarting the container I have an error that occurs: no more presence or connection with the aeotec gen5 key.

For this to come back I have to physically remove the key and restart the container

The phenomenon appeared during the August or September update, I don't really know anymore.
I thought an update would fix the problem but apparently no

### To Reproduce

To reproduce the phenomenon, you must launch a container update or restart the container

### Expected behavior

May the key be reconnected without problems as in the past

### Additional context

zwavejs UI is on the same container as zigbee2mqtt and I had to fix the ports a long time ago because there were changes when restarting the containers sometimes
But I had the operation over a year ago

**Comment by robertsLando** [comment]
Please attach your docker-compose file, I have a feel you miscopnfigured the volume

**Comment by robertsLando** [comment]
Check out this: https://github.com/zwave-js/node-zwave-js/issues/6341

**Comment by jerome6994** [comment]
Good evening

Thanks for sharing this link.

I give my feeling and my emotion to reading it!
I find that we are degrading the situation of many users who, like me, are not experts in the command line, coding and other uses of this kind.

The situation has become so painful that some of us around me are thinking of leaving zwave

I already have point 1 which is OK as is point 3 (because no ESXI but proxmox).
I think point 4 is ok
I have a spare so I'm going to try updating my gen5 firmware to see

The TCP part doesn't speak to me at all, so inaccessible for me!

So after you have to upgrade to version 700 or 800, does it have to be compatible with my hardware?

Really tonight is total depressionv

**Comment by jerome6994** [comment]
I ignored it because I didn't understand what to do at the time of my reading and disappointment.
I re-read the whole thing in detail.
I updated the spare key to see and everything worked.
I just saw the soft reset button which I disabled.
I will see the next update of the container
Thank you for this additional insight
