### ISSUE TITLE
Driver: Failed to open the serial port

### ISSUE THREAD

**Issue by chma73** [zwave-js/zwave-js-ui#3403]
Hello, 
I need your support, today I got after HA restart this message

Driver: Failed to open the serial port: Error: No such file or directory, cannot open /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_ea141d913d85ed11aa41c89f9d1cc348-if00-port0 (ZW0100)

I'm not 100% sure what that means, could it be that the z-wave stick is damaged; I don't see the stick in the system?
Thanks for your help and hints

**Comment by robertsLando** [comment]
Check out this: zwave-js/node-zwave-js#6341

**Comment by chma73** [comment]
Thanks, but unfortunately I don't see my Z-Wave stick
![image](https://github.com/zwave-js/zwave-js-ui/assets/137674516/c9b7d613-4017-46f5-bfe5-0237cd671d32)

**Comment by robertsLando** [comment]
Are you using docker or what else?

**Comment by chma73** [comment]
you are right I found the issue, it was not the Zwave stick the Intel NUC USB port is demaged

**Comment by chma73** [comment]
Thanks for your hint
