### ISSUE TITLE
Scheduled Jobs not functioning with MQTT Gateway disabled

### ISSUE THREAD

**Issue by anjanms** [zwave-js/zwave-js-ui#3404]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.3.1

### ZwaveJS version

12.2.3

### Describe the bug

Having previously disabled the MQTT Gateway, as I'm using the websocket with Home Assistant. I created scheduled jobs to get some Z-Wave specific tasks out of HA. Over the next few days I realized the scheduled jobs were not running, but the code would correctly perform its task when ran manually via Driver Function.

After watching the logs and reading the source, I realized the scheduled jobs were not being created at runtime due to me having disabled MQTT. Enabling the MQTT Gateway brought the scheduled jobs to life.

I did not see anything in the docs about this dependency, however I don't think this is intentional.

### To Reproduce

Create a scheduled job, such as one that runs every minute and logs a message. Observe logs to see that scheduled job functions. Then toggle on the `Disable MQTT Gateway` switch. Observe logs to see that no scheduled jobs function.

### Expected behavior

Scheduled jobs should function irrespective of the enabled/disabled state of MQTT.

### Additional context

Relocating the [event binding](https://github.com/zwave-js/zwave-js-ui/blob/49ccf974d414cbc3d3485b85140ec0c8f7330a7a/lib/Gateway.ts#L282-L305) and having the event handler for [_onDriverStatus](https://github.com/zwave-js/zwave-js-ui/blob/49ccf974d414cbc3d3485b85140ec0c8f7330a7a/lib/Gateway.ts#L2115) check `this.mqttEnabled` like [_onNodeInited](https://github.com/zwave-js/zwave-js-ui/blob/49ccf974d414cbc3d3485b85140ec0c8f7330a7a/lib/Gateway.ts#L2003) does is one solution.

Assuming I haven't missed some actual MQTT dependency somewhere.

**Comment by robertsLando** [comment]
I can look at this issue on Monday, thanks for the detailed report
