### ISSUE TITLE
404 errors after Upgrade from 8.23.2

### ISSUE THREAD

**Issue by yakclock** [zwave-js/zwave-js-ui#3406]
Hello there,

I have successfully in the past upgraded zwave-js-ui by building the new version in another directory the redirecting a symbolic link to new new version, and repointing the store in the new version to the existing store.

However, when trying to upgrade to 8.24.2 (I've also tried 8.26.0 and 9.3.1) I get 404 errors on startup and the console does not load. It seems like there is a mismatch between the 'uuid' of the css and js files that it cannot find.

Can you advise on what I might be missing when upgrading ? Like I say I have got this to upgrade this way in the past. Thank you.

```
2023-11-05 12:57:28.422 INFO APP: GET /static/css/app.053fff1961b248890e05.css 404 264.534 ms - 1271
2023-11-05 12:57:28.431 INFO APP: GET /static/js/app.53e6d7317a5c72f6b135.js 404 267.906 ms - 1271
```

These are the files I can see in the new build:

```
# find /opt/zwave-js/zwave-js-ui.v8.24.2/dist/ -type f -name "app\.*s"
/opt/zwave-js/zwave-js-ui.v8.24.2/dist/static/js/app.7b66bffb2d79a3bde7ef.js
/opt/zwave-js/zwave-js-ui.v8.24.2/dist/static/css/app.880ba8ae9e500ab06367.css
```

**Comment by robertsLando** [comment]
Did you checked this issue? https://github.com/zwave-js/zwave-js-ui/issues/3267

**Comment by yakclock** [comment]
I'm building like this:

```
yarn install
yarn run build
```

Then symbolically linking the store directory to the store directory containing the configuration from the previous version.

I then run from systemd:

```
/usr/local/bin/yarn --cwd /opt/zwave-js/zwave-js-ui start
```

**Comment by robertsLando** [comment]
Try to clean everything:

```
rm -rf node_modules dist server
```

then:

```
yarn install
yarn build
```

**Comment by yakclock** [comment]
My apologies, it looks like this was caused by haproxy caching the name of the app.<HASH>.js file from the previous version. I removed all caching from haproxy and it started working immediately.
