### ISSUE TITLE
everytime i update the zwavejs2mqtt docker on unraid my settings get deleted 

### ISSUE THREAD

**Issue by The-Math-God** [zwave-js/zwave-js-ui#3407]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

v9.3.1

### ZwaveJS version

v9.3.1

### Describe the bug

pretty simple everytime i have to update zwavejs2mqtt on unraid all of my settings get nuked 
which in turn breaks home assistant
and having to redo my settings everytime i have to update is driving me crazy 
so could you please fix it

### To Reproduce

just update the docker container on unraid

### Expected behavior

all of my settings get nuked

**Comment by The-Math-God** [comment]
i don't understand how to configure a persistent volume could you help i looked at the docs

**Comment by robertsLando** [comment]
You have two ways:

1. https://zwave-js.github.io/zwave-js-ui/#/getting-started/docker?id=run-using-volumes
2. https://zwave-js.github.io/zwave-js-ui/#/getting-started/docker?id=run-using-a-local-folder
