### ISSUE TITLE
node interview taking 2 minutes

### ISSUE THREAD

**Issue by zeev-mindali** [zwave-js/zwave-js-ui#3410]
Dear all,

i have McoHome glass9 product.
when i adding it to the system, the interview is taking 2:30 minutes (node 19).
i already take out the parts i don't need, espically command 44(0x2c) , but i still see it on the logs.

how i can achive faster node interview??

logs attached:
[z-ui_2023-11-06.log](https://github.com/zwave-js/zwave-js-ui/files/13266028/z-ui_2023-11-06.log)
[zwavejs_2023-11-06.log](https://github.com/zwave-js/zwave-js-ui/files/13266029/zwavejs_2023-11-06.log)

**Comment by robertsLando** [comment]
This issue is releated to the underlying [Z-Wave JS Driver](https://github.com/zwave-js/node-zwave-js), please report it [here](https://github.com/zwave-js/node-zwave-js/discussions/new?category=request-support-investigate-issue)

**Comment by zeev-mindali** [comment]
found the problem, there was a lot of unused information that the device sent.
after removing the unneccesery command, i manage to move from 2.5 minutes to only 15 seconds :)
