### ISSUE TITLE
9.3.2 is released but it's not present on Docker Hub

### ISSUE THREAD

**Issue by witten** [zwave-js/zwave-js-ui#3413]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

12.3.0

### ZwaveJS version

9.3.2

### Describe the bug

The 9.3.2 container tag on Docker Hub does not appear to be present, and the `latest` tag timestamp indicates it's not 9.3.2 (because it's too old). Just filing this in case you're not already aware of this.

### To Reproduce

 Example:

```bash
sudo docker pull docker.io/zwavejs/zwave-js-ui:9.3.2
Error response from daemon: manifest for zwavejs/zwave-js-ui:9.3.2 not found: manifest unknown: manifest unknown
```

Same behavior with Podman. If I change the tag to 9.3.1 (with either Docker or Podman), then the pull works. 

### Expected behavior

The 9.3.2 tag is present on Docker Hub and the pull works.

### Additional context

Just in the interests of full disclosure: I totally lied and I _am_ using Home Assistant, but I don't believe it has any bearing on this ticket. The pull behavior reproduces on a system that has never had Home Assistant installed.

**Comment by RobertD502** [comment]
Most likely due to the [Docker Release action failing](https://github.com/zwave-js/zwave-js-ui/actions/runs/6812618827). Even the github registry doesn't have the `latest` tag docker image corresponding to 9.3.2. The master tag image is there though as the Docker Release action for the master tag completed successfully.

**Comment by witten** [comment]
Looks like a timeout installing dependencies?

```
 #30 [linux/arm/v7 build-zui  6/12] RUN yarn install --immutable
Error: The action has timed out.
```

**Comment by robertsLando** [comment]
Retried now. Thanks for the report

**Comment by robertsLando** [comment]
Should be ok now

**Comment by witten** [comment]
Confirmed working now. Thank you!

**Comment by RobertD502** [comment]
@robertsLando looks like the 9.4.0 docker build action failed as well.

**Comment by robertsLando** [comment]
@RobertD502 I saw, I sincerly have no clue why that happens... yarn install simply get stuck on armv7 for no reason

**Comment by robertsLando** [comment]
Ok some news here, seems a bug related to yarn: https://github.com/yarnpkg/berry/issues/4916

https://github.com/zwave-js/zwave-js-ui/actions/runs/6901465072/job/18776332328#step:11:530
