### ISSUE TITLE
Don't Obscure Info Popup on When Copying Mobile

### ISSUE THREAD

**Issue by The00Dustin** [zwave-js/zwave-js-ui#3416]
Any time I need to see the version information within the Z-Wave JS UI HA Addon, I must tap the information button since there is no "hovering" on mobile devices, but then the information is obscured for something like 3 seconds by the "Copied to clipboard" toast notification.  Tapping `CLOSE` on this notification clears the information popup, so I am forced to wait for it to go away on its own.

**Describe the solution you'd like**
I'd like to be able to see this information when I tap the information icon.

**Describe alternatives you've considered**
I currently wait for the toaster notification to go away as described above, and I had previously considered pasting the information into another app, but the paste only included the fields and not their data when I tried that (I was going to report this as a bug, but it seems to be resolved after upgrading).

**Additional context**
![IMG_2847](https://github.com/zwave-js/zwave-js-ui/assets/91274634/eb60af26-0ff8-4cba-a8bc-16b5418ddb47)

**Comment by robertsLando** [comment]
@The00Dustin wondering if moving snackbar on bottom center would be better for mobile UI?

**Comment by The00Dustin** [comment]
That might be a good option.  You already made space for the floating hamburger menu to not block the page navigation elements on the non-compact view, so there is probably space there.  It could potentially be left of the hamburger menu to further minimize obstruction.  OTOH, I just looked at the compact view, and it would likely cover the bottom info on the last node row there.  You might be able to make that view scroll a bit further the same way.  Another option might be to have the info pop up in front of the snackbar depending on how much layer control there is.
