### ISSUE TITLE
Latest version of the application is not published on Snap store

### ISSUE THREAD

**Issue by jfhautenauven** [zwave-js/zwave-js-ui#3435]
Hello,

Little question to ask if it's normal that the latest version of the app is still not available via the Snap store ? :) 

Thanks in advance,

JF

**Comment by robertsLando** [comment]
I don't maintain the snap package. That's a question for @jmgiaever.

Just for context, you are not aware, I' having problems with docker releases, see #3430. BTW that should not be blocking for snap as it builds from source AFAIK

**Comment by jmgiaever** [comment]
I'm sorry, but I've been so worked out, and with the change in the layout I haven't been able to update it. 

I will see what I can do this weekend.

**Comment by robertsLando** [comment]
@jmgiaever I have tagged you on the pr to help you to track changes that may be in your interest. Essentially all backend code related stuff has been moved to api folder so you must keep track of it and ignore some others files

**Comment by jfhautenauven** [comment]
> I'm sorry, but I've been so worked out, and with the change in the layout I haven't been able to update it.
> 
> I will see what I can do this weekend.

No worry bro, I understand that :) Was just wondering if it was the same issue as the docker stuff.
I'm in no hurry anyways :) version 9.3.2 is pretty stable :)

**Comment by jfhautenauven** [comment]
Latest version has been published as expected, closing the issue @robertsLando
