### ISSUE TITLE
When including a node with S2 during manual inclusion, don't prompt for the DSK if it matches one on the provisioning list

### ISSUE THREAD

**Issue by mbbush** [zwave-js/zwave-js-ui#3438]
**Is your feature request related to a problem? Please describe.**
Today when adding my Zooz ZEN04 smart plug, I started by scanning the QR code on the smart start tab. For some reason, it didn't automatically get included like happens with most devices, so I did the manual inclusion process (not re-scanning the QR code). I got a prompt asking for the first digits of the DSK, just like you'd expect during S2 pairing of an unknown device.

**Describe the solution you'd like**
This wasn't an unknown device. ZwaveJS already knew the full DSK because it was on the provisioning list. That's where I eventually copy-pasted the PIN from. I would like it if the prompt was skipped and the PIN filled in automatically.

**Additional context**
I had put a node name and location on the provisioning list, and once the interview completed those showed up on the new node, which was a nice touch.

**Comment by robertsLando** [comment]
This issue is releated to the underlying [Z-Wave JS Driver](https://github.com/zwave-js/node-zwave-js), please report it [here](https://github.com/zwave-js/node-zwave-js/discussions/new?category=request-support-investigate-issue)
