### ISSUE TITLE
"bash: ./zwave-js-ui: No such file or directory" error on startup

### ISSUE THREAD

**Issue by ezequielandrush** [zwave-js/zwave-js-ui#3445]
Hi. I am running a bare bone raspbian on a raspi4 board. I am trying to set a service using the binaries for the latest release.
https://github.com/zwave-js/zwave-js-ui/releases/download/v9.4.1/zwave-js-ui-v9.4.1-linux-arm64.zip

Ther issue I have is that when I try to start zwave-js-ui I get this error

`root@raspberrypi:/home/Zeke# ./zwave-js-ui 
bash: ./zwave-js-ui: No such file or directory
`

I managed to get a different error trying to use sh instead of bash. Looks like there is a lib missing. Any ideas?

`root@raspberrypi:/home/Zeke# sh ./zwave-js-ui
./zwave-js-ui: 1: ELF·´4s@p: not found
./zwave-js-ui: 1:Påtd©}©}©}èèQåtdRåtdhbµhb¶hb¶ÝÝ/lib/ld-linux-aarch64.so.1GNUGNUˑ¯%3: not found
./zwave-js-ui: 2: cannot open În»ùø: No such file
./zwave-js-ui: 26: uP°@Î: not found
./zwave-js-ui: 27: Syntax error: "(" unexpected
root@raspberrypi:/home/Zeke# 1;2c
`

Thanks in advance
Zeke

**Comment by ezequielandrush** [comment]
Hi! thanks for your quick reply.

Still the same problem. 
For the record, I am having this issue with previous versions too.

**Comment by robertsLando** [comment]
@ezequielandrush Are you starting it from vscode terminal? If so please try to use another terminal

**Comment by ezequielandrush** [comment]
I am starting it from an ssh terminal (currently using x-terminal-emulator) I also tried it connecting a monitor and keyboard to the raspberry pi board and running the command via tty1. It's the same result in both cases

**Comment by ezequielandrush** [comment]
Now I feel dumb.
In fact my arch is aarch64. The armv7 package worked like a charm!
I'm sorry to have bothered you with such a silly issue. Thanks a lot!

**Comment by robertsLando** [comment]
No worries, glad you fixed it now :)
