### ISSUE TITLE
Release 9.5.0, error running linux zip

### ISSUE THREAD

**Issue by luckyjay** [zwave-js/zwave-js-ui#3458]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.5.0

### ZwaveJS version

12.4.0

### Describe the bug

I downloaded https://github.com/zwave-js/zwave-js-ui/releases/download/v9.5.0/zwave-js-ui-v9.5.0-linux.zip and it gets an error when executing. 
![image](https://github.com/zwave-js/zwave-js-ui/assets/3222139/b7f229da-1944-404c-9db7-7279352b1564)

OS is Ubuntu 22.04.3 LTS, 64 bit, with latest updates as of a few moments ago.

### To Reproduce

See bug description

### Expected behavior

Executable should successfully run.

**Comment by luckyjay** [comment]
Deploy method is not Docker, I wasn't sure what to select in my case. Docker is not being used.

**Comment by bostjane** [comment]
Windows version is not working either...

**Comment by cornellrwilliams** [comment]
I get the exact same error message as the OP when running in Windows.

**Comment by merdely** [comment]
I'm having the same problem on a Pi4.

Even after the "try downloading it again now" and I get this:

```
$ sudo /opt/zwave/zwave-js-ui
Error: Cannot find module '/snapshot/zwave-js-ui/node_modules/axios/dist/node/axios.cjs'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1098:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1091:15)
    at resolveExports (node:internal/modules/cjs/loader:567:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:119:18)
```

**Comment by luckyjay** [comment]
Seems good now, thank you!

**Comment by robertsLando** [comment]
I have fo fix all them, I keep this open as a reminder, may fix it tomorrow

**Comment by merdely** [comment]
Thank you so much!

**Comment by webmogul1** [comment]
Has the name changed to zwave-js-ui from zwave-js-ui-linux?

**Comment by robertsLando** [comment]
Wait for 9.5.1, locally worked
