### ISSUE TITLE
Battery level reporting 0% after upgrading firmware on Aeotec  Trisensor ZWA005  - Upgraded to 2,21 from 2.16

### ISSUE THREAD

**Issue by RockMonkey** [zwave-js/zwave-js-ui#3465]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.5.1

### ZwaveJS version

12.4.0

### Describe the bug

Battery level was 100% on trisensor prior to upgrading firmware on ZWA005 to firmware level 2.21, now it reads 0%

### To Reproduce

Update firmware on sensor to 2.21

### Expected behavior

Expected battery value is 100% as it was prior to upgrading the firmware

**Comment by RockMonkey** [comment]
This is a brand new sensor with a new battery, reading is below. I have 7 of these sensors, 5 existing and 2 new. I only updated one of the new ones. I will try upgrading another and see is the battery changes from 100%

[74-128-0-level] Battery level
0 %
[74-128-0-isLow] Low battery level
false

I did notices in the firmware release notes the following "(V2.16 - 2.21) - Adjusts battery calibration method for factory production (does not require recalibration of battery for older hardware)"
So I thought perhaps that changed something that affected the reading. 

I will  upgrade another sensor and see what happens.

Thanks

**Comment by AlCalzone** [comment]
This is an issue with the device or firmware, not zwave-js. Aeotec are the ones that can help with this.

**Comment by Aeotec-ccheng** [comment]
​The resolution involves power cycling the TriSensor to refresh its hardware and data:
1. Remove power to your TriSensor (remove battery)
2. Wait 6 minutes
3. Power up your TriSensor (Insert battery)
- LED should flash green which indicates that the TriSensor hardware was properly powered down and it should update all sensor reports including battery. 

This should fix the battery report after updating.
