### ISSUE TITLE
Support for reproducible builds

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js-ui#3466]
**Is your feature request related to a problem? Please describe.**
The build process currently does not support reproducible builds. This is necessary for some packaging systems, like Nix.

**Describe the solution you'd like**
Support reproducible builds by updating the [`package-lock.json`](https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#packages) file to include `integrity` and `resolved` fields.

**Describe alternatives you've considered**
N/A

**Additional context**
I am trying to package zwave-js-ui for [Nix](https://nixos.org/). However, the build system fails because the lockfile is missing the integrity hashes, which it uses to copy the node modules from a cache store.

I'm not sure how you generated the lock file? When I do the following (from `alpine:3.18.4` image), I get something completely different than what currently exists:

```console
/src # node --version
v18.18.2
/src # npm --version
9.6.6
```

```console
rm -rf node_modules
rm package-lock.json
npm cache clean -f
npm install
```
Here is the result: https://github.com/kpine/zwave-js-ui/commit/e6a83809002ec10387fe015dcef9c21081309fe1

Of course, if you do the same at a different time, the dependent packages may update.

I also noticed the Dockerfile is using `npm install`. This seems less than ideal as it is possible for npm to update packages? This makes the Docker builds also non-reproducible. Along with the lockfile update, the Dockerfile should probably use `npm ci` for installation. My understanding is that `npm ci` will not re-write any packages.

**Comment by robertsLando** [comment]
> I also noticed the Dockerfile is using npm install

yeah it does but when doing releases that line is not triggered as it will re-use node_modules from the previous action step, I did this to optimize the build. Anyway for consistency that could be converted to npm ci :) 

https://github.com/zwave-js/zwave-js-ui/blob/f499d5b4069074a6ecb5c3d8f4fef45ee39b8cee/.github/workflows/docker-release.yml#L78-L81

I sincerly have no clue why my package-lock is missing those declaration. I'm using nodejs 20.8.0 with npm 10.1.0. Let me investigate
