### ISSUE TITLE
Unknown log severity level in log files

### ISSUE THREAD

**Issue by duylong** [zwave-js/zwave-js-ui#3468]
Hi,

Console log output with Docker is colored to facilitate the severity level. However when I put the logs in a file, I lose the severity level. Is it voluntary? 

I have difficulty doing research when I activate DEBUG mode over several days.

**Comment by robertsLando** [comment]
The logs severity is present in my log files, it is not in zwave-js logs. 

zwave-js:

```
2022-10-04T06:26:30.335Z DRIVER   version 10.3.0
```

zui:

```
2023-11-27 14:52:10.314 INFO APP: Listening on port 8091 protocol HTTPS
```

Dunno if @AlCalzone could consider adding it on his side

**Comment by robertsLando** [comment]
that error is from zui, not zwave-js

**Comment by robertsLando** [comment]
Open an issue on zwave-js repo if you wish to add severity to logs, them are present on zui side as showed
