### ISSUE TITLE
assositaion usage

### ISSUE THREAD

**Issue by zeev-mindali** [zwave-js/zwave-js-ui#3471]
Dear all,

when i use simple commands to open close switch, i can see the value is changing in the mqtt,
but when i using sw1 epid1 to open sw3 epid root or 1/2/3 with assosiation, it not telling me that all three lights are on 

what am i missing?

**Comment by AlCalzone** [comment]
I can't make sense of this either. Please explain exactly what you did, and which associations you have set up, ideally with a link to the device manual.

**Comment by AlCalzone** [comment]
Check if your target device for the associations has a configuration setting to send a report to the controller when toggled. If not you might be out of luck.

"Following" all associations and querying the target devices' state isn't feasible.

**Comment by zeev-mindali** [comment]
my problem is that when i start assosiation on device 1, it open all three light in the second device.
but in zwave-js-ui or home bridge, i don't see the change or see the first button only.
is it related to report in th assosiation (SW1_REPORT) or the configuration in the device itself?

**Comment by AlCalzone** [comment]
What associations do and trigger is device-specific and not standardized in Z-Wave (except what the Lifeline association needs to do). So I have no idea how your first device triggers the 2nd device and what that device does and reports in that case. Not sure if the device 2 is just not reporting anything or Z-Wave JS isn't interpreting it correctly. At the very least, I'd need to look at driver logs (loglevel debug) of such an interaction and device manuals explaining the associations and config parameters.

I once had a virtual 3-way switch using associations (device 1 triggers device 2 and vice versa), and this worked completely fine, including reporting back the state change of both devices to the controller. So this **can** work, but it depends on the devices' implementation.

**Comment by zeev-mindali** [comment]
here is the logs files:

**Comment by zeev-mindali** [comment]
also here the manual from manufactorer:
[MH-S613 - Glass 3 switches.pdf](https://github.com/zwave-js/zwave-js-ui/files/13626995/MH-S613.-.Glass.3.switches.pdf)

it's the same for 1/2/3 gang

**Comment by zeev-mindali** [comment]
i found out, that when i do manually refresh it's getting the correct values, is there a way to make refresh from home bridge?

**Comment by robertsLando** [comment]
> i found out, that when i do manually refresh it's getting the correct values, is there a way to make refresh from zwave-js-ui automatticly?

You could by using scheduled jobs but it's not an ideal solution...

**Comment by zeev-mindali** [comment]
is there any command, that i can add to json driver to make more refresh time? or add anything else?
on rp4 i didn't get any error, only on variscite imx6ul som

**Comment by AlCalzone** [comment]
Z-Wave JS does not automatically refresh values from other devices you didn't control directly.
