### ISSUE TITLE
Stopped being able to access USB Dongle, nothing changed or added.

### ISSUE THREAD

**Issue by Audio-Lefty** [zwave-js/zwave-js-ui#3472]
zwave-js ui suddenly stopped seeing USB.
Have no idea what I can do.
Nothing was changed. have tried rolling install back a few days, as well as trying to re allocate the serial port.
My Devices Home Assistant Yellow and Zwave Me 500 series
My Log is below.

From restore from 5 days ago, when it was working.
> 2023-12-07T08:01:44.481Z DRIVER   
> 2023-12-07T08:01:53.503Z DRIVER   Failed to open the serial port: Error: No such file or directory, cannot open 
>                                   /dev/serial/by-id/usb-0658_0200-if00
> 2023-12-07 19:01:53.505 INFO Z-WAVE: Restarting client in 15 seconds, retry 382

When I tried changing to    
/dev/ttyAMA0
LOG
> 2023-12-07 19:04:42.895 INFO APP: GET /health/zwave 301 1.460 ms - 191
> 2023-12-07T08:04:43.873Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
>                                   n 100 ms.
> 2023-12-07T08:04:44.984Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
>                                   n 1100 ms.
> 2023-12-07T08:04:47.095Z DRIVER   Failed to initializ”
> 
When I tried
 /dev/ttyAMA1
LOG
> 2023-12-07 19:07:43.584 INFO APP: GET /health/zwave 301 1.276 ms - 191
> 2023-12-07T08:07:49.130Z DRIVER   Failed to open the serial port: Error Resource temporarily unavailable Cannot 
>                                   lock port
> 2023-12-07 19:07:49.132 INFO Z-WAVE: Restarting client in 15 seconds, retry 5

And     
/dev/ttyAMA2

> 2023-12-07T08:12:02.676Z DRIVER   version 12.3.0
> 2023-12-07T08:12:02.676Z DRIVER   
> 2023-12-07 19:12:02.683 INFO Z-WAVE: Zwavejs usage statistics ENABLED
> 2023-12-07 19:12:02.684 WARN Z-WAVE: Zwavejs driver is not ready yet, statistics will be enabled on driver initialization
> 2023-12-07T08:12:03.691Z CONFIG   version 12.3.0
> 2023-12-07T08:12:04.887Z CNTRLR   querying Serial API capabilities...
> 2023-12-07T08:12:05.898Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
>                                   n 100 ms.
> 2023-12-07T08:12:07.005Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
>                                   n 1100 ms.
> 2023-12-07T08:12:09.114Z DRIVER   Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK 
>                                   from the controller (ZW0200)
>                                       at Driver.sendMessage (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts
>                                   :5240:23)
>                                       at ZWaveController.identify (/opt/node_modules/zwave-js/src/lib/contro

**Comment by robertsLando** [comment]
@Audio-Lefty Try to disable soft reset in settings

**Comment by AlCalzone** [comment]
Have you tried re-plugging the 500 series stick after disabling soft-reset? In some cases the entire host or VM may need to be restarted.

**Comment by Audio-Lefty** [comment]
Yes I left Soft-Reset off. Tried different combinations of restart including removing from power

If I insert the silicon labs 700, JS UI offers…
/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_228d707f9b76ed118d1df6fafdf7b791-if00-port0
/dev/ttyAMA0
/dev/ttyAMA1
/dev/ttyAMA2,
/dev/ttyUSB0

With Zwave me JS UI offers
/dev/ttyAMA0
/dev/ttyAMA1
/dev/ttyAMA2.

I also found online that I should be able to access the ZWave me with Silicon Labs Simplicity Studio.
I updated the Silicon Labs Firmware with it prior to installing in HA Yellow.
The ZWave Me is seen by windows , appears as COM4, but can’t force it to be seen by Simplicity Studio.

Not sure what it all means.

Are there more things I can do?
If not I would be grateful if I can recover my missing nodes with the 700.


From: AlCalzone ***@***.***>
Date: Friday, 8 December 2023 at 7:10 am
To: zwave-js/zwave-js-ui ***@***.***>
Cc: Audio-Lefty ***@***.***>, Mention ***@***.***>
Subject: Re: [zwave-js/zwave-js-ui] Stopped being able to access USB Dongle, nothing changed or added. (Issue #3472)

Have you tried re-plugging the 500 series stick after disabling soft-reset? In some cases the entire host or VM may need to be restarted.

**Comment by Audio-Lefty** [comment]
Have tried everything suggested.
I there a way to recover my network that was connected to the 500 series USB to my new USB 700 series?

**Comment by robertsLando** [comment]
Where are you running zui and what deploy method did you used?

**Comment by Audio-Lefty** [comment]
Z-ui.
Not sure of deploy method, been running for 6 months. I was new to HA at time and blindly followed a tutorial. Did migrate from Zwave.me I recall.

Also MQTT was using test-mosquito and changed to local  core-mosqito port 1883 recently. If there is a connection

Allan Rich
0418 176 511
________________________________

**Comment by robertsLando** [comment]
Ok so I think you installed z-ui as an home assistant addon? Not docker, right? Also if you are using it with home assistant why are you also using mqtt? The suggested way to work with it is using the zwave-js integration: https://zwave-js.github.io/zwave-js-ui/#/homeassistant/homeassistant-official

Anyway apart from this where did you installed z-ui? Is it a nuc an rpi? What os are you using?

**Comment by Audio-Lefty** [comment]
Yes direct through HA
On Rpi HA Yellow

Allan Rich
0418 176 511
________________________________

**Comment by Audio-Lefty** [comment]
Also…
Getting this message now

2023-12-11 20:01:01.431 INFO MQTT: Subscribed to zwave/_CLIENTS/ZWAVE_GATEWAY-Mosquitto/multicast/#
2023-12-11 20:01:19.064 INFO APP: GET /health/zwave 301 4.423 ms - 191
2023-12-11 20:01:49.182 INFO APP: GET /health/zwave 301 4.215 ms - 191
2023-12-11 20:02:19.309 INFO APP: GET /health/zwave 301 3.053 ms - 191


Allan Rich
0418 176 511
________________________________

**Comment by robertsLando** [comment]
> Add UI if I need the functionality or want to get my head around MQTT.

As I said, you don't need MQTT at all with Home Assistant, just enable zwave-js server in settings and install zwave-js integration on home assistant

**Comment by Audio-Lefty** [comment]
Understood thanks

Allan Rich
0418 176 511
________________________________
