### ISSUE TITLE
Network graph accuracy

### ISSUE THREAD

**Issue by dwmw2** [zwave-js/zwave-js-ui#3474]
Not sure if this is a bug, I'll start as a question... I don't believe the Network Graph is telling me the truth, or I just don't understand it.

Here's a sample:
![Screenshot from 2023-12-07 13-23-16](https://github.com/zwave-js/zwave-js-ui/assets/911239/88872f05-b4a9-43aa-91e1-ac909424416b)

There's weirdness in some of these routes but that might be true — for example the "Bathroom light" has "Connie light" as a neighbour, and that would be fewer hops. But I've seen nodes shown in grey as not accessible, even when I can ping them (and check back afterwards that they're still shown as inaccessible). Surely *that* can't be true?

But mostly... see that 'Primary controller' that's allegedly routing only to the ZWave-JS-UI 'Controller'? That's the real primary controller of this network., running on my production Domoticz box that I haven't yet converted to use ZWave-JS-UI. It works just fine when the USB stick that I'm using for testing ZWave-JS-UI is unplugged, so I'm fairly sure that it does have more routes of its own.

Am I misunderstanding? I know that operating as a secondary controller is not fully supported — is that what's making the routes get reported strangely?

**Comment by cornellrwilliams** [comment]
There are different types of routes. You have ones that the controller uses to communicate with the nodes and then you have ones that the nodes use to communicate with the controller. I'm not 100% sure but I guess the map just shows the routes that the controller uses to communicate with the nodes. If you go to the statistics page of a device in the Z-Wave JS Integration you can see the last working route the controller used to communicate with a device.
![LWR](https://github.com/zwave-js/zwave-js-ui/assets/92619869/befa1b07-2724-4716-a586-b46153720373)

**Comment by cornellrwilliams** [comment]
In home assistant go to Settings > Devices & Services > Click Z-Wave Logo > Click # Devices > Click on the device you want to view >  Click : > Click Statistics > Click Last Work Route to see more details.

**Comment by robertsLando** [comment]
The network graph is built using the most accurated info we have from controller like: 

LWR: Last working root
NLWR: Next last working route
Priority route: A custom route the user can set as the route the packets will take  from controller to node
Priority return route: A custom route the user can set as the route the packets will take from node to controller

Everything is build using the internal zwave protocol algorithm and sometimes it's known to do some weird things, that's why we added the possibility to customize the routes

**Comment by dwmw2** [comment]
Ah, I'm only using ZWave-JS-UI, not Home Assistant. Once it's set up and running, I *only* really want it for the MQTT bridge (and the UI will just be taking memory on my router for nothing, as discussed in #3473).

**Comment by robertsLando** [comment]
> But only for some links?

What do you mean? Generally the priority is only shown if you set it. The LWR details can be detected based on the color of the link, see legend
