### ISSUE TITLE
sh: npm: not found error....

### ISSUE THREAD

**Issue by MYeager1967** [zwave-js/zwave-js-ui#3475]
I updated the zwavejs/zwavejs2mqtt docker image today to the latest and began getting nothing but the error listed in the subject. I rolled back to the 9.3.1 tag and everything is fine. I just saw that zwavejs2mqtt has been renamed to zwave-js-ui so here I am. 

I'm running on an Intel i5 processor running Alpine Linux and Docker. Everything was fine until I pulled whatever the latest is. 9.4.1 didn't work either so I went with 9.3.1. Guessing it's something I need to do, but so far I haven't figured out what...

**Comment by robertsLando** [comment]
Could you paste here the full error log you see in console? 

That's strange as many other users already updated to latest without any problem

**Comment by robertsLando** [comment]
Post at least a screenshot of the command you lunch+the output

**Comment by robertsLando** [comment]
I would also try to pull master tag instead of latest to see if something changes

**Comment by electrofloat** [comment]
I also wanted to update to the latest just now and getting:
```
start container error: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown
```

**Comment by MYeager1967** [comment]
Here's the docker-compose for the service.

```  zwave-js-ui:
    container_name: zwave-js-ui
#    image: zwavejs/zwave-js-ui:latest
    image: zwavejs/zwavejs2mqtt:9.3.1
    restart: always
    tty: true
    stop_signal: SIGINT
    devices:
      - /dev/ttyACM0
    environment:
      - TZ=America/New_York
      - AUTOHEAL_CONTAINER_LABEL=true
    volumes:
      - /home/Mike/docker/zwavejs2mqtt/store:/usr/src/app/store
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8091:8091"
      - "3000:3000"
    command: sh -c "apk --no-cache add curl & npm run start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091"]
      interval: 30s
      timeout: 5s
      retries: 3
```
With the image that's commented out, the only thing that shows in the log (under portainer) is the error listed in the subject. It just repeats over and over... I don't have a log in my config folder at the moment.

**Comment by MYeager1967** [comment]
I didn't add the command line, it came from one of the guides somewhere else. That said, I missed the reference to npm in it. As for the healthcheck, I'll check your version out as I'm always interested in a better way to do it although I think I already incorporated it from the github documentation. :-)

**Comment by robertsLando** [comment]
Yeah like @kpine said the problem is the command you use to start the application, dunno where you picked that up from but I suggest to always refer to official docs:

https://zwave-js.github.io/zwave-js-ui/#/getting-started/docker?id=healthcheck

**Comment by MYeager1967** [comment]
Back when I added the healthcheck, I didn't see anything in the docs about it. The command was added from another guide to add curl for the healthcheck. It's been long enough that I actually forgot about it and missed it when looking over things when it suddenly didn't work. Thank you for all for helping e figure this out. All is well again. :-)
