### ISSUE TITLE
Unstable pairing for yale lockset while using S2 security.

### ISSUE THREAD

**Issue by hassan-xy** [zwave-js/zwave-js-ui#3478]
Hi guys,
So I am trying to pair yale lockset using S2 based pairing method, however I see that the pairing in some cases downgrades to S0 and the pairing is incomplete though displayed as complete in the ui. (MID/PID/ battery percentage is missing). But the lockset itself announces as paired, but uncontrollable from the ui. I have tried re-interviewing the node, healing, ping and all other remedies but to no avail.
Can you guys have a look at the logs and support me in finding the root cause of the issue and to come up with a possible solution.

My product code is ZST10-700. The product is FW: v7.15.4, SDK: v7.15.4. My chipset is ZGM130S037HGN 700 series.
Unfortunaltely I cant modify or upgrade to the latest versions.
[zwave_yale_pairing_fail.zip](https://github.com/zwave-js/zwave-js-ui/files/13631331/zwave_yale_pairing_fail.zip)

Thanks and regards,
Hassan

**Comment by robertsLando** [comment]
This issue is releated to the underlying [Z-Wave JS Driver](https://github.com/zwave-js/node-zwave-js), please report it [here](https://github.com/zwave-js/node-zwave-js/discussions/new?category=request-support-investigate-issue)
