### ISSUE TITLE
About `optionalDependencies` on `package.json`

### ISSUE THREAD

**Issue by alexojegu** [zwave-js/zwave-js-ui#3486]
It is really necessary to have packages like `eslint`, `mocha`, `c8`, etc. as `optionalDependencies`. If I'm not ignoring something, it seems that it would be more correct for them to be `devDependencies`.

I say this because when installing `zwave-js-ui` as an NPM package it installs 1172 packages and among them I can see for example:
```
# ls -l /usr/local/lib/node_modules/zwave-js-ui/node_modules/ | grep eslint
drwxr-xr-x    1 root     root            20 Dec 15 21:11 @eslint
drwxr-xr-x    1 root     root            38 Dec 15 21:11 @eslint-community
drwxr-xr-x    1 root     root           256 Dec 15 21:11 conventional-changelog-eslint
drwxr-xr-x    1 root     root           116 Dec 15 21:12 eslint
drwxr-xr-x    1 root     root            96 Dec 15 21:11 eslint-import-resolver-node
drwxr-xr-x    1 root     root           394 Dec 15 21:11 eslint-module-utils
drwxr-xr-x    1 root     root           114 Dec 15 21:11 eslint-plugin-babel
drwxr-xr-x    1 root     root            62 Dec 15 21:11 eslint-plugin-es
drwxr-xr-x    1 root     root           224 Dec 15 21:12 eslint-plugin-import
drwxr-xr-x    1 root     root            86 Dec 15 21:11 eslint-plugin-node
drwxr-xr-x    1 root     root           112 Dec 15 21:11 eslint-plugin-promise
drwxr-xr-x    1 root     root            62 Dec 15 21:12 eslint-plugin-vue
drwxr-xr-x    1 root     root            92 Dec 15 21:11 eslint-rule-composer
drwxr-xr-x    1 root     root            70 Dec 15 21:11 eslint-scope
drwxr-xr-x    1 root     root           164 Dec 15 21:11 eslint-utils
drwxr-xr-x    1 root     root            70 Dec 15 21:11 eslint-visitor-keys
drwxr-xr-x    1 root     root           116 Dec 15 21:11 vue-eslint-parser

# npm -g ls eslint
/usr/local/lib
└─┬ zwave-js-ui@9.6.0
  ├─┬ eslint-plugin-babel@5.3.1
  │ └── eslint@8.55.0 deduped
  ├─┬ eslint-plugin-import@2.29.1
  │ └── eslint@8.55.0 deduped
  ├─┬ eslint-plugin-node@11.1.0
  │ ├─┬ eslint-plugin-es@3.0.1
  │ │ └── eslint@8.55.0 deduped
  │ └── eslint@8.55.0 deduped
  ├─┬ eslint-plugin-promise@6.1.1
  │ └── eslint@8.55.0 deduped
  ├─┬ eslint-plugin-vue@9.19.2
  │ ├─┬ @eslint-community/eslint-utils@4.4.0
  │ │ └── eslint@8.55.0 deduped
  │ ├── eslint@8.55.0 deduped
  │ └─┬ vue-eslint-parser@9.3.2
  │   └── eslint@8.55.0 deduped
  └── eslint@8.55.0
```

**Comment by robertsLando** [comment]
Them are there just because: 

> The term optional dependencies apply to dependencies that won't cause a failure during the installation of an application or project since npm will ignore them if they fail. Whether these dependencies are present or not, the application will still work as expected

**Comment by alexojegu** [comment]
I suppose it will be useful for CI, for the rest of the cases I don't quite see the usefulness because those dependencies for production do not seem to be necessary and for development they seem highly recommended (although not required).

I do not know why:
```
npm install -g --omit=optional zwave-js-ui
```
Installs the same 1172 dependencies and doesn't skip the optional ones.

**Comment by robertsLando** [comment]
Could be an issue with your npm version? What is your npm/nodejs version?

**Comment by alexojegu** [comment]
I was previously using nodejs 18, this last weekend I upgraded it to nodejs 20 and retry to install zwave-js-ui with same result.
 - nodejs: v20.10.0
 - npm: 10.2.5

**Comment by robertsLando** [comment]
I may be missing something here but optional dependencies should be skipped, I will look at this tomorrow, thanks for letting me know 🙏🏻

**Comment by alexojegu** [comment]
Great, now it install 445 packages vs previous 1172 packages.

**Comment by robertsLando** [comment]
@alexojegu thanks for your feedback Alex glad the issue is now solved 🙌🏻
