### ISSUE TITLE
Err_connection_refused

### ISSUE THREAD

**Issue by MikeyMan83** [zwave-js/zwave-js-ui#3487]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Z-Wave JS UI version

9.5.1

### ZwaveJS version

¿

### Describe the bug

Hi,

Since yesterday I get an error with zwavejs. 
Err_connection_refused.

Its installed on a pi with snap.

Tried checking the settings, updating the pi, rebooting the whole pi and manually starting zwavejs.

Didn't change anything in the config. It's been running flawlessly for a long, long time now.

### To Reproduce

Go to 10.0.0.30:8091

### Expected behavior

Functioning without error

**Comment by MikeyMan83** [comment]
Been checking a bit further... Seems there is nothing listening at port 8091. Dont know if it was the case before btw:

```
sudo ss -ltn
State      Recv-Q     Send-Q         Local Address:Port         Peer Address:Port    Process
LISTEN     0          128                  0.0.0.0:22                0.0.0.0:*
LISTEN     0          128                127.0.0.1:6010              0.0.0.0:*
LISTEN     0          128                        *:6144                    *:*
LISTEN     0          128                     [::]:22                   [::]:*
LISTEN     0          128                        *:8080                    *:*
LISTEN     0          128                        *:443                     *:*
LISTEN     0          128                    [::1]:6010                 [::]:*

```

**Comment by MikeyMan83** [comment]
Also tried the help function. Seems to be okay:

```
zwave-js-ui - v9.5.1

IMPORTANT! The DAEMON/SERVICE is disabled by default after installation.
You have to manually 'daemonize' it with executing the command

$ zwave-js-ui.enable

Set your configuration as descrived below

Server configuration values: {
        "server": {
                "force-disable-ssl": false,
                "host": "0.0.0.0",
                "port": 8091,
                "ssl": false
        }
}

- server.ssl: Use secure communication
- server.host: IP address to bind to, e.g 127.0.0.1
- server.port: Port to reach the web interface

```

**Comment by O2Graphics** [comment]
I'm having the same problem.
I wouldn't be surprised if snap had updated something behind our back. In my case, everything was working well and the problem appeared this morning when I rebooted my Domoticz device (an Odroid XU4 board which also running zwave-js-ui).

**Comment by MikeyMan83** [comment]
Started yesterday evening... Question is; how to solve it ;)

**Comment by O2Graphics** [comment]
Yeah, I'm also wondering how to solve this problem :-)

The problem is probably with the last version, as the snap package was released yesterday: https://snapcraft.io/zwave-js-ui
I'll search if we can find logs somewhere.

**Comment by O2Graphics** [comment]
In /var/log/syslog, I'm finding multiple logs like:

`Dec 16 10:35:04 odroid systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Scheduled restart job, restart counter is at 5.
Dec 16 10:35:04 odroid systemd[1]: Stopped Service for snap application zwave-js-ui.zwave-js-ui.
Dec 16 10:35:04 odroid systemd[1]: Started Service for snap application zwave-js-ui.zwave-js-ui.
Dec 16 10:35:04 odroid root: zwave-js-ui: Missing plug: «serial-port»
Dec 16 10:35:04 odroid root: zwave-js-ui: Connect with:
Dec 16 10:35:04 odroid root: zwave-js-ui: $ sudo snap connect zwave-js-ui:serial-port <slot name>
Dec 16 10:35:05 odroid zwave-js-ui.zwave-js-ui[1302]: node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
Dec 16 10:35:05 odroid systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Main process exited, code=exited, status=127/n/a
Dec 16 10:35:05 odroid systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Failed with result 'exit-code'.
Dec 16 10:35:06 odroid systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Scheduled restart job, restart counter is at 6.`

**Comment by MikeyMan83** [comment]
Let me also check those logs...

**Comment by MikeyMan83** [comment]
Any way to force snap to install 9.4.1?

**Comment by MikeyMan83** [comment]
I have these as well:

```
Dec 16 11:09:33 raspberrypi zwave-js-ui.zwave-js-ui[1607]: node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
Dec 16 11:09:33 raspberrypi systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Main process exited, code=exited, status=127/n/a
Dec 16 11:09:33 raspberrypi systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Failed with result 'exit-code'.
Dec 16 11:09:33 raspberrypi systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Scheduled restart job, restart counter is at 10.
Dec 16 11:09:33 raspberrypi systemd[1]: Stopped Service for snap application zwave-js-ui.zwave-js-ui.
Dec 16 11:09:33 raspberrypi systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Start request repeated too quickly.
Dec 16 11:09:33 raspberrypi systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Failed with result 'exit-code'.
Dec 16 11:09:33 raspberrypi systemd[1]: Failed to start Service for snap application zwave-js-ui.zwave-js-ui.
```

**Comment by O2Graphics** [comment]
> Any way to force snap to install 9.4.1?

Yes, I just got back to a previous version and now it's working!
In "/snap/zwave-js-ui/", I have 2 folders "287" and "304" and a symlink "current" pointing to "304".
I deleted the symlink with "ln -s 287 current".

**Comment by O2Graphics** [comment]
> [libatomic.so.1](node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory)

I hope someone will be able to help solve this problem :-)

**Comment by MikeyMan83** [comment]
> > Any way to force snap to install 9.4.1?
> 
> Yes, I just got back to a previous version and now it's working! In "/snap/zwave-js-ui/", I have 2 folders "287" and "304" and a symlink "current" pointing to "304". I deleted the symlink and then created a new one with "ln -s 287 current".

How did you do that? Can you prevent snap updating?

**Comment by MikeyMan83** [comment]
```
pi@raspberrypi:~ $ sudo apt install libatomic1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libatomic1 is already the newest version (10.2.1-6+rpi1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```

**Comment by O2Graphics** [comment]
> > > Any way to force snap to install 9.4.1?
> > 
> > 
> > Yes, I just got back to a previous version and now it's working! In "/snap/zwave-js-ui/", I have 2 folders "287" and "304" and a symlink "current" pointing to "304". I deleted the symlink and then created a new one with "ln -s 287 current".
> 
> How did you do that? Can you prevent snap updating?

I don't know snap very well. I just use it because it's less worse than using "node" directly or Docker.

Check if you have a "287" folder in "/snap/zwave-js-ui/".

If OK, then:

> cd /snap/zwave-js-ui/
rm 304
ln -s 287 current
reboot


You can later go back to the new version by deleting the "current" symlink and creating a new one linking to the "304" folder.

**Comment by O2Graphics** [comment]
> libatomic already installed.

I'm not sure how snap works, but I think it uses it's own libraries. So "libatomic" should be in the snap folder of "zwave-js-ui", not just your device's folder.

In my case:

> # find / -name libatomic.so.1
/snap/zwave-js-ui/287/usr/lib/arm-linux-gnueabihf/libatomic.so.1
/usr/lib/arm-linux-gnueabihf/libatomic.so.1

And the library is not in "/snap/zwave-js-ui/340/usr/lib/arm-linux-gnueabihf/libatomic.so.1" (the last version of "zwave-js-ui")


> might be a compile error with zwave-js.

So, yes, but I don't know how to solve that problem. Probably the maintainers of zwave-js-ui should release a new version with this library.

**Comment by MikeyMan83** [comment]
Ah, that's progress... 

Somehow i cant remove the dir, even with snapd and zwave-js-ui stopped...

```
pi@raspberrypi:/snap/zwave-js-ui $ sudo rmdir 304
rmdir: failed to remove '304': Device or resource busy

```

**Comment by O2Graphics** [comment]
It's a symlink, so use "rm", not "rmdir" :-)

Yes, it's a temporary solution, snap will update someday and will break again if the package isn't fixed.

**Comment by MikeyMan83** [comment]
rm was complaining it was a directory...

Fixed it with umount.

**Comment by MikeyMan83** [comment]
```
pi@raspberrypi:/snap/zwave-js-ui $ snap list
Name         Version    Rev    Tracking       Publisher       Notes
core         16-2.60.4  16207  latest/stable  canonical✓      core
core20       20231123   2106   latest/stable  canonical✓      base
hello-world  6.4        29     latest/stable  canonical✓      -
zwave-js-ui  v9.5.1     304    latest/stable  giaever-online  -
pi@raspberrypi:/snap/zwave-js-ui $ sudo systemctl stop snapd
Warning: Stopping snapd.service, but it can still be activated by:
  snapd.socket
pi@raspberrypi:/snap/zwave-js-ui $ dir
287  304  current
pi@raspberrypi:/snap/zwave-js-ui $ umount 304
umount: /snap/zwave-js-ui/304: must be superuser to unmount.
pi@raspberrypi:/snap/zwave-js-ui $ sudo umount 304
pi@raspberrypi:/snap/zwave-js-ui $ dir
287  304  current
pi@raspberrypi:/snap/zwave-js-ui $ rmdir 304
rmdir: failed to remove '304': Permission denied
pi@raspberrypi:/snap/zwave-js-ui $ dir
287  304  current
pi@raspberrypi:/snap/zwave-js-ui $ sudo rmdir 304
pi@raspberrypi:/snap/zwave-js-ui $ dir
287  current
pi@raspberrypi:/snap/zwave-js-ui $ nano current
pi@raspberrypi:/snap/zwave-js-ui $ cd current
pi@raspberrypi:/snap/zwave-js-ui/current $ dir
bin                 etc     lib   meta.jq  nodejs  snap     usr
command-jq.wrapper  helper  meta  meta.yq  sbin    snap.yq  var
pi@raspberrypi:/snap/zwave-js-ui/current $ cd ..
pi@raspberrypi:/snap/zwave-js-ui $ sudo rmdir current
rmdir: failed to remove 'current': Not a directory
pi@raspberrypi:/snap/zwave-js-ui $ rm current
rm: cannot remove 'current': Permission denied
pi@raspberrypi:/snap/zwave-js-ui $ sudo rm current
pi@raspberrypi:/snap/zwave-js-ui $ dir
287
pi@raspberrypi:/snap/zwave-js-ui $ ln -s 287 current
ln: failed to create symbolic link 'current': Permission denied
pi@raspberrypi:/snap/zwave-js-ui $ sudo ln -s 287 current
pi@raspberrypi:/snap/zwave-js-ui $ dir
287  current
pi@raspberrypi:/snap/zwave-js-ui $ reboot
```

**Comment by MikeyMan83** [comment]
`sudo snap revert zwave-js-ui --revision 287`

seems to work to get back to 9.4.1. But it doesnt solve the connection refused error

**Comment by MikeyMan83** [comment]
Should server.host be localhost, 127.0.0.1 or 0.0.0.0? Tried them all, but no luck yet...

**Comment by MikeyMan83** [comment]
Damnit... Had to be enabled again... 

with sudo zwave-js-ui.enable

No clue how that is different from a restart, but i'll take it... Back online.

**Comment by O2Graphics** [comment]
> 
> after reboot 304 is back:
> 
> ```
> pi@raspberrypi:/snap/zwave-js-ui $ dir
> 287  304  current
> pi@raspberrypi:/snap/zwave-js-ui $
> ```

Yes, 304 is still here, but "current" should point to "287" (= the previous version).
So it's OK to still have "304", zwave-js-ui will "current", which means "287".


> `sudo snap revert zwave-js-ui --revision 287`
> 
> seems to work to get back to 9.4.1. But it doesnt solve the connection refused error

Weird. I don't know "snap" much, does revert activate "287"? Or does it just install it?
Do you have others errors in your log file?



> Should server.host be localhost, 127.0.0.1 or 0.0.0.0? Tried them all, but no luck yet...
At least one of them should work. Does it listen to 8091?
```
# netstat -apn | grep 8091
tcp        0      0 0.0.0.0:8091            0.0.0.0:*               LISTEN      923/node
```

**Comment by O2Graphics** [comment]
> Damnit... Had to be enabled again...
> 
> with sudo zwave-js-ui.enable
> 
> No clue how that is different from a restart, but i'll take it... Back online.

Ah! Great! :-D
I don't know why it got disabled on your device, but at least it works for now! :-)

**Comment by ntpckr** [comment]
Thanks!

**Comment by subtrEM** [comment]
Until fixed: after the temporary downgrade, is it worth considering holding refreshes?
`snap refresh --hold zwave-js-ui`
to re-enable all checks:
`snap refresh --unhold`

**Comment by MikeyMan83** [comment]
Very good suggestion. Also hope for a very quick fix.

**Comment by DeWitteWama** [comment]
Dear all,
I had the same problem since yesterday morning 16/12/2023 and your suggestions worked fine. However I did not have a directory 287 and 304, but 304 and 314. 

sudo snap revert zwave-js-ui --revision 314 solved by problem. 
Followed by 
sudo zwave-js-ui.enable.

Happy Sunday!

**Comment by MikeyMan83** [comment]
@DeWitteWama that would mean that 314 solves the issue... That's good news...

**Comment by O2Graphics** [comment]
@DeWitteWama, nice, thanks!
On my device, it has been automatically updated:
```
# ll /snap/zwave-js-ui/
total 18
drwxr-xr-x  4 root root   5 déc.  16 22:42 ./
drwxr-xr-x  6 root root   7 sept.  2 00:45 ../
drwxr-xr-x 14 root root 239 déc.   7 04:06 304/
drwxr-xr-x 14 root root 239 déc.  16 17:39 314/
lrwxrwxrwx  1 root root   3 déc.  16 22:42 current -> 314/
```
and like you said: it does work! :-D

I just found out on this page: https://snapcraft.io/zwave-js-ui that there is a repository dedicated to the snap package here: https://github.com/giaever-online-iot/zwave-js-ui and the issue related to the problem was reported and fixed here: https://github.com/giaever-online-iot/zwave-js-ui/issues/8

**Comment by MikeyMan83** [comment]
Cool! So that means 9.6.1 in the ui then?

**Comment by O2Graphics** [comment]
@MikeyMan83, no, it's still 9.5.1.
Maybe 9.6.0 is too new and we will have to wait a few more days before having the snap package?

**Comment by O2Graphics** [comment]
If you check at the top of the page: https://snapcraft.io/zwave-js-ui , just in front of the green "Install" button, there's a listbox:
- latest/stable | v9.5.1
- latest/candidate | v9.6.0
- latest/edge | v9.6.0

**Comment by robertsLando** [comment]
Hi guys, unfortunately I'm not maintaining the snap package, that is owned by Joachim and I already saw that this bug seems to have been solved recently, open a new issue on https://github.com/giaever-online-iot/zwave-js-ui
