### ISSUE TITLE
Firmware Update Show Confirmation / Show Additional Information on Modal

### ISSUE THREAD

**Issue by zackbcom** [zwave-js/zwave-js-ui#3488]
### Is your feature request related to a problem? Please describe.
I have trouble remembering what exact version / device I'm upgrading, and feel worried about selecting the wrong update. Especially for Zooz who has up to 4 different hardware versions. I have to double check the firmware version and product code a few times to feel comfortable when upgrading firmware.

### Describe the solution you'd like
It would be nice to show a confirmation or additional data on firmware upgrade modal that lists the following:
- Device Name
- Device Product Code
- Device Current Version
- Potentially read the selected file version, if possible, and show the upgrading to version.
- Poorly executed Example 
![image](https://github.com/zwave-js/zwave-js-ui/assets/1888323/978d5a0c-569f-49f4-9b2b-93feef5efc41)

### Describe alternatives you've considered
Either Additional Data in the Modal, or a confirmation listing that data.

### Additional context###
This modal. 
![image](https://github.com/zwave-js/zwave-js-ui/assets/1888323/8d769b4a-8bd0-46e7-a8e5-516b7c5f50f6)

**Comment by robertsLando** [comment]
It makes sense, I add this to my TODOs

**Comment by pumrum** [comment]
love this change! would it be possible to include the Product Code as well? particularly in the case of Zooz, having the product code (e.g. ZSE42) is a good safety check against what's physically printed on the device.

**Comment by robertsLando** [comment]
@pumrum Done
