### ISSUE TITLE
homeassistant with zwave-js is not working properly

### ISSUE THREAD

**Issue by zeev-mindali** [zwave-js/zwave-js-ui#3489]
Dear all,

i switched from homebridge to home assistant with zwave-js-ui as backend for zwave devices.
but when i look into the home assistant, if the button is multilevel, i don't have the option to change the item to behave like other item.

<img width="514" alt="Screenshot 2023-12-17 at 19 00 30" src="https://github.com/zwave-js/zwave-js-ui/assets/23069323/97a6c1d6-ca1c-442d-b035-089635627c5a">

here i can change the show as in home assistant (regular button)
<img width="525" alt="Screenshot 2023-12-17 at 19 00 53" src="https://github.com/zwave-js/zwave-js-ui/assets/23069323/cf9b2bf5-ef31-4772-8702-d84e07ecbd02">

the option show as , dissapper and i get a multilevel item.

**Comment by robertsLando** [comment]
Hi @zeev-mindali, this is not the right place for such questions, I suggest to ask them in home assistant core repo or discord.

@kpine may be able to help you

**Comment by zeev-mindali** [comment]
o.k.
i thought since the integration is zwave-js in home assistant, maybe it is the right place.
it's shows shutters as light dimmers without ability to change the device.
i will try my luch in ha
