### ISSUE TITLE
Priority route not visible with "star"

### ISSUE THREAD

**Issue by Beer17HWAM** [zwave-js/zwave-js-ui#3492]
My friend and I both have the same zwave-js-ui 9.3.2 version. I can see all the Priority routes, visible with "star" in the network graph. My friend isn't seeing any "star".

How is that posible?

**Comment by robertsLando** [comment]
But did you set that priority route manually or what?
Firstly switch to latest 9.6.0

**Comment by Beer17HWAM** [comment]
Yes we both added routes manually. We did mainly the same things. Just add some priority routes. I use those to have a more stable situation. Since I use priority routes it works better. My friend want those too but isn't seeing any "stars". I know that there are newer versions but my friend hasn't got any "stars" for months now. And I do. The only difference is I run a separate docker and my friend has the hassio addon. Very stange, we use the same version and the same hardware zwave dongle.

**Comment by robertsLando** [comment]
This explanation alone doesn't give me enough context to tell you what's going on there, what I can think is that for some reason he did a route update and the priority route has been removed and it became a LWR route instead

**Comment by Beer17HWAM** [comment]
No, the priority route isn't removed. It's still there. But I see all small "stars" in the network graph view but in his network graph no starts are visible.

**Comment by robertsLando** [comment]
I dunno, if your friend has such issue he should upload nodes json so I can give it a look

**Comment by Beer17HWAM** [comment]
[nodes_dump.json](https://github.com/zwave-js/zwave-js-ui/files/13730339/nodes_dump.json)
This is his json export.

**Comment by robertsLando** [comment]
The only one with an application route set is node 22 and it has:

```
"lwr": {
        "protocolDataRate": 2,
        "repeaters": [
          3
        ]
 },
"nlwr": {
        "protocolDataRate": 3,
        "repeaters": [],
        "rssi": -54,
        "repeaterRSSI": []
},
"applicationRoute": {
      "repeaters": [],
      "routeSpeed": 3
    },
```

Does he see the star on the link from 22 to the controller? I have a feel if he doesn't it could be because the nlwr mathes the application route

**Comment by Beer17HWAM** [comment]
He doesn't see any star, no stars at all. And when he sets more priority routes the don't stick. After he sets a priority route and leave the popup and click the node again the priority route is gone. Only on node 22 it stays. Setting priority routes is nog going well and he doesn't see any star.

**Comment by robertsLando** [comment]
I need driver logs that show the tries of setting a priority route

**Comment by jeroen84s** [comment]
[zwave-js-ui-store.zip](https://github.com/zwave-js/zwave-js-ui/files/13740330/zwave-js-ui-store.zip)
Are those the correct log file? If not, can you explain how to create the driver logs?

**Comment by robertsLando** [comment]
Them are correct. Thanks. I need to ask @AlCalzone to review them. Anywat could you also try to upgrade to latest ? 9.6.0?

**Comment by robertsLando** [comment]
I only see a successfull try in logs and no fail: 

```
2023-12-21T10:31:23.954Z DRIVER » [REQ] [SetPriorityRoute]
                                    node ID:     24
                                    repeaters:   none
                                    route speed: 100k
2023-12-21T10:31:23.957Z SERIAL « [ACK]                                                                   (0x06)
2023-12-21T10:31:23.964Z SERIAL « 0x01050193180171                                                     (7 bytes)
2023-12-21T10:31:23.966Z SERIAL » [ACK]                                                                   (0x06)
2023-12-21T10:31:23.970Z DRIVER « [RES] [SetPriorityRoute]
                                    success: true
2023-12-21T10:31:23.975Z CNTRLR   Retrieving priority route to node 24...
2023-12-21T10:31:23.981Z SERIAL » 0x010400921871                                                       (6 bytes)
2023-12-21T10:31:23.983Z DRIVER » [REQ] [GetPriorityRoute]
                                    node ID: 24
2023-12-21T10:31:23.986Z SERIAL « [ACK]                                                                   (0x06)
2023-12-21T10:31:23.988Z SERIAL « 0x010a0192181000000000036d                                          (12 bytes)
2023-12-21T10:31:23.990Z SERIAL » [ACK]                                                                   (0x06)
2023-12-21T10:31:23.992Z DRIVER « [RES] [GetPriorityRoute]
                                    node ID:     24
                                    route kind:  Application
                                    repeaters:   none
                                    route speed: 100k
```

**Comment by jeroen84s** [comment]
I can't update to a newer version, because I use hassio addon

**Comment by Beer17HWAM** [comment]
Again, in my opinion it has nothing to do with the version because I use the same version in a docker. I see beautiful "stars". :-)

**Comment by AlCalzone** [comment]
@robertsLando how are the stars drawn? Are they text/emojis or SVG?

**Comment by Beer17HWAM** [comment]
![networkgraph](https://github.com/zwave-js/zwave-js-ui/assets/97590748/afa5ccb3-8e0f-45d9-9681-0407d3ba1942)
See jpg

**Comment by Beer17HWAM** [comment]
> @robertsLando how are the stars drawn? Are they text/emojis or SVG?
> 
> Can we somehow confirm whether Z-UI sees the routes as priority routes? In other words, can we confirm whether this is a pure display issue?

It's not only a display issue. The priority routes @jeroen84s is making are not saved. He can set a route (and back) but after closing the node and opening the node the priority route is gone.

**Comment by AlCalzone** [comment]
Ok I'll try to look at the logs tonight. Maybe I'll see something.

**Comment by robertsLando** [comment]
@AlCalzone them are SVG and as said I don't see any error in the logs he uploaded above. Anyway IMO this seems to me a display issue but I may be wrong

**Comment by Beer17HWAM** [comment]
Not only a display issue!! I already said:
The priority routes @jeroen84s is making are not **saved**. He can set a route (and back) but after closing the node and opening the node the priority route is gone.

**Comment by AlCalzone** [comment]
@jeroen84s is showing that several communication attempts succeed using the priority routes, e.g.
```
2023-12-21T10:30:05.168Z DRIVER « [REQ] [SendData]
                                    callback id:            1
                                    transmit status:        OK, took 90 ms
                                    routing attempts:       3
                                    protocol & route speed: Z-Wave, 40 kbit/s
                                    routing scheme:         Priority Route
                                    ACK RSSI:               -68 dBm
                                    ACK channel no.:        1
                                    TX channel no.:         1
```

and that several priority routes are known, e.g.:
```
2023-12-21T10:30:07.275Z DRIVER « [RES] [GetPriorityRoute]
                                    node ID:     46
                                    route kind:  Application
                                    repeaters:   5
                                    route speed: 100k
```

Also, assigning the routes works too:
```
2023-12-21T10:31:23.940Z CNTRLR   Setting priority route to node 24...
2023-12-21T10:31:23.944Z DRIVER   all queues busy
2023-12-21T10:31:23.952Z SERIAL » 0x010900931800000000037e                                            (11 bytes)
2023-12-21T10:31:23.954Z DRIVER » [REQ] [SetPriorityRoute]
                                    node ID:     24
                                    repeaters:   none
                                    route speed: 100k
2023-12-21T10:31:23.957Z SERIAL « [ACK]                                                                   (0x06)
2023-12-21T10:31:23.964Z SERIAL « 0x01050193180171                                                     (7 bytes)
2023-12-21T10:31:23.966Z SERIAL » [ACK]                                                                   (0x06)
2023-12-21T10:31:23.970Z DRIVER « [RES] [SetPriorityRoute]
                                    success: true
2023-12-21T10:31:23.975Z CNTRLR   Retrieving priority route to node 24...
2023-12-21T10:31:23.981Z SERIAL » 0x010400921871                                                       (6 bytes)
2023-12-21T10:31:23.983Z DRIVER » [REQ] [GetPriorityRoute]
                                    node ID: 24
2023-12-21T10:31:23.986Z SERIAL « [ACK]                                                                   (0x06)
2023-12-21T10:31:23.988Z SERIAL « 0x010a0192181000000000036d                                          (12 bytes)
2023-12-21T10:31:23.990Z SERIAL » [ACK]                                                                   (0x06)
2023-12-21T10:31:23.992Z DRIVER « [RES] [GetPriorityRoute]
                                    node ID:     24
                                    route kind:  Application
                                    repeaters:   none
                                    route speed: 100k
```

What **might** be happening: This node is a sleeping node, so there are no route statistics yet to draw the route. I think Z-UI isn't handling the case where there are no statistics, but the priority route is known. @robertsLando

**Comment by Beer17HWAM** [comment]
@AlCalzone Can you see the routes back also? The route back isn't shown in the Node when you open it again in the Network Graph after setting it. And why do I see "stars" and @jeroen84s not? I think it's all very strange. Why this complete other reaction than I have. I also set priority routes to sleeping Nodes.

**Comment by AlCalzone** [comment]
The routes back require communication with the node, which doesn't happen when the node is asleep. It has to be woken up for the return route to actually be saved.
After that there has been communication with the node, which means there are routing statistics, which means this display bug in Z-Wave JS UI probably won't trigger anymore for that node.

As for routes to and from powered nodes: I need to see a log of that.

**Comment by jeroen84s** [comment]
Your vision about the sleeping nodes looks correct. Both wall plugs has a priority route (also return route). And the star in is not showing up in the graphic

**Comment by Beer17HWAM** [comment]
> Your vision about the sleeping nodes looks correct. Both wall plugs has a priority route (also return route). And the star in is not showing up in the graphic

No stars. Maybe with Christmas. Just wait. ;-)

**Comment by robertsLando** [comment]
@nmpu can't you just drag the dialog a bit higher? it can be moved where you want

**Comment by nmpu** [comment]
@robertsLando yes, that does work. I'm not used to web dialogs being moveable. Pretty fancy. Once you know there's a [Ping] button, you can blindly click on the top edge.

Should I also see stars in the app? I don't.

The 'Show return routes' and 'Show priority routes' checkboxes get disabled in the global view, but are enabled in the node view. However, the previous state remains when grayed. Is that how it's supposed to work?

**Comment by Beer17HWAM** [comment]
With the latest HAOSS zwave still NO STARS.

**Comment by Beer17HWAM** [comment]
I also have one gray node but this one is also working without problems. And I have stars, lucky me!

![WhatsApp Image 2024-01-23 at 09 20 27](https://github.com/zwave-js/zwave-js-ui/assets/97590748/64210dcd-b688-4fdd-8895-507854458201)

**Comment by nmpu** [comment]
@Beer17HWAM Do you see stars in the app? I'm not sure that's even a thing.

**Comment by Beer17HWAM** [comment]
> @Beer17HWAM Do you see stars in the app? I'm not sure that's even a thing.

Yes, it's a sign for priority routes. But not all people have those stars in their Graph. I allways had them.

**Comment by nmpu** [comment]
It can't be a display issue. I'm running **HAOS** as an x86 VM. The install is only about a month old. I recently switched from 500 series to 800 series radio. I never saw stars in either case. I have 40 nodes. You have fewer. Your friend is in the middle. Does something happen with newer installs? Larger networks? I think it's a configuration setting.

**Comment by nmpu** [comment]
@Beer17HWAM how does your graph change if you uncheck 'Show priority routes' in the drop-down section?

**Comment by Beer17HWAM** [comment]
> @Beer17HWAM how does your graph change if you uncheck 'Show priority routes' in the drop-down section?

Is grayed out, cannot disable 'Show priority routes'.

![WhatsApp Image 2024-01-23 at 09 57 31](https://github.com/zwave-js/zwave-js-ui/assets/97590748/71ed0357-c870-4d81-917b-03ab07899753)

**Comment by nmpu** [comment]
If 'Node properties' is shown, the checkboxes will be ungrayed. It's not clear what's going on there.

**Comment by Beer17HWAM** [comment]
> If 'Node properties' is shown, the checkboxes will be ungrayed. It's not clear what's going on there. Do you see stars in the node (zoomed) view? You know what I'm trying to do right? I'm trying to make you lose _your_ stars. :)

I'm not able to "remove" the stars. I can toggle the switches, see results. In the main Graph stars never disappear.

![WhatsApp Image 2024-01-23 at 10 30 57](https://github.com/zwave-js/zwave-js-ui/assets/97590748/61913cb2-108d-4972-b91c-800d3e419de7)
![WhatsApp Image 2024-01-23 at 10 30 46](https://github.com/zwave-js/zwave-js-ui/assets/97590748/2a6ac5ca-68ef-4509-9f0c-038234164582)
![WhatsApp Image 2024-01-23 at 10 30 26](https://github.com/zwave-js/zwave-js-ui/assets/97590748/0bad3b3f-1ad5-4548-81d0-a9c7357fd319)
![WhatsApp Image 2024-01-23 at 10 30 13](https://github.com/zwave-js/zwave-js-ui/assets/97590748/e32a6839-1992-4b87-bc8e-28356e80f796)

**Comment by robertsLando** [comment]
I have a feel that the start issue is something browser related as it is passed as an svg... Could I ask you to open dev tools and see in network tab if the svg request is fullfilled correctly?

**Comment by Beer17HWAM** [comment]
The file is simply not available!!

![WhatsApp Image 2024-01-23 at 11 52 55](https://github.com/zwave-js/zwave-js-ui/assets/97590748/adff78d2-d635-4992-ba98-ab4624342ef6)

**Comment by Beer17HWAM** [comment]
In my case it is available:

![WhatsApp Image 2024-01-23 at 11 54 43](https://github.com/zwave-js/zwave-js-ui/assets/97590748/f7b3b46f-91c4-421d-b3d8-3dc8d0f1bf48)

**Comment by Beer17HWAM** [comment]
Why is the star.svg file not available in the hassio add-in version?? I still have it in my separate docker environment, not as add-in.

**Comment by Beer17HWAM** [comment]
The star.svg file not available in the hassio add-in version. That's why nobody with hassio has stars. I run a separate docker environment outside Home Assistant that's why I have the star.

![WhatsApp Image 2024-01-23 at 15 46 02](https://github.com/zwave-js/zwave-js-ui/assets/97590748/993a9532-cfb8-4c6d-b555-9cfd144a4231)

**Comment by Beer17HWAM** [comment]
The https://github.com/zwave-js/zwave-js-ui version has a star:

![WhatsApp Image 2024-01-23 at 15 51 50](https://github.com/zwave-js/zwave-js-ui/assets/97590748/d390cf08-68e0-4a62-8fdf-c26a0ba4797d)

**Comment by robertsLando** [comment]
star should be in  `dist/star.svg`

**Comment by Beer17HWAM** [comment]
It's still not fixed in the latest release. Please fix.

**Comment by robertsLando** [comment]
I sincerly have no clue how to fix this as it's working on all my instances

**Comment by Beer17HWAM** [comment]
The star.svg is not available in his environment. How can he fix this?

**Comment by robertsLando** [comment]
I cannot help so much as the error seems to be on addon side, only @frenck could help here and I already tagged him

**Comment by Beer17HWAM** [comment]
Please help us with this problem. @frenck isn't available???

**Comment by AlCalzone** [comment]
https://github.com/hassio-addons/addon-zwave-js-ui/issues

**Comment by Beer17HWAM** [comment]
I give it up. My separate zwave docker is working fine. I see stars. My friend doesn't have stars in his HA zwave addon. If the developers of zwave and the HA addon are not able to fix it I give up.
See https://github.com/hassio-addons/addon-zwave-js-ui/issues/692

**Comment by TheDK** [comment]
@frenck says:

> > The file is simply not available!!
> 
> Correct, as the path is not right. The `X-External-Path` isn't honored by upstream. That is not an add-on issue.
> 
> ../Frenck

I can confirm that it does not work when packaged as the HA Add-on.

**Comment by robertsLando** [comment]
The star svg path is passed in this way: 

https://github.com/zwave-js/zwave-js-ui/blob/37dfcd3f5c4c59cc1dbf3d7c6ad67941d32eb104/src/components/custom/ZwaveGraph.vue#L379

Same for the logo you see in top left corner:

https://github.com/zwave-js/zwave-js-ui/blob/37dfcd3f5c4c59cc1dbf3d7c6ad67941d32eb104/src/App.vue#L18

So sincerly I dunno why the star request doesn't respect the X-External-Path. It could be that for some reason vis-network is loading it in a wrong way?

**Comment by AlCalzone** [comment]
Looks like `vis-network` is doing the request itself. Can you filter/redirect it using the service worker maybe?

**Comment by Beer17HWAM** [comment]
I guess nobody is going to fix this for the HA addin users. Just run zwave separate in a docker and you can see beautiful stars. :-)

**Comment by robertsLando** [comment]
@AlCalzone I was looking at vis-network code, wondering if using https://github.com/visjs/vis-network/blob/master/lib/network/CachedImage.js#L7 cold work. Let me try

**Comment by robertsLando** [comment]
Works 🎉

**Comment by Beer17HWAM** [comment]
Works!!! Thanks!!
![image](https://github.com/user-attachments/assets/3f830604-16d6-40a8-bbc6-5e94a2872bd2)

**Comment by hugo-leij** [comment]
Nice! i'm still waiting for an update via hassio add-on

**Comment by Beer17HWAM** [comment]
Hassio Addin Version 3.9.3 is available.

**Comment by hugo-leij** [comment]
I see! uhm, the update is not (yet) available via home assistant. Hopefully, tomorrow

**Comment by hugo-leij** [comment]
Yea! 
![IMG_5878](https://github.com/user-attachments/assets/7bf58369-3d10-49d6-a7e4-540bec31d1e9)
