### ISSUE TITLE
Devices values wrong after some days

### ISSUE THREAD

**Issue by duylong** [zwave-js/zwave-js-ui#3498]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.6.2.6e369a1

### ZwaveJS version

12.4.1

### Describe the bug

Hi,

After a first interview, my modules work without problem. The values are well defined and I don't touch anything. 

However, after a while, new groups of values appear for no reason even though I have not done an interview, added a module or other actions.

For example, I have a Qubino ZMNHJD device that has "WakeUp v1", "Basic v0", "Binary Sensor v0" or "Multilevel Sensor v3" value groups that should not be there. A "WakeUp v1" for a powered module is strange... 

So I find myself from time to time with the following WARNINGS:
```
23:58:04.055 CNTRLR » [Node 052] Multilevel Sensor CC values may be stale, refreshing...
23:58:04.055 CNTRLR » [Node 052] querying current sensor reading...
23:58:16.818 CNTRLR [Node 052] Timed out while waiting for a response from the node (ZW0201)
```
If I do a interview again, all its unknown values disappear and I have no problem until the next change.

On another module, a Fibaro FGMS001, I end up with the values "[96-48-0-unknown (0x82)] Sensor state (unknown (0x82))", "[96-48-0-unknown (0x1c) ] Sensor state (unknown (0x1c))" or "[96-48-0-unknown (0x17)] Sensor state (unknown (0x17))" in "Binary Sensor v1". Once again, an interview erases its "unknown" values.

Have you ever had a similar problem? 

I would like to decide for myself whether an interview is necessary or not, is there an automatic scheduling of interviews?

### To Reproduce

I'm afraid I don't have the logs, the problem being random, I don't have logs on the exact moment of the changes.

### Expected behavior

I shouldn't see new values added after an interview.

**Comment by robertsLando** [comment]
Hi @duylong, sorry for the delay but I took a break during Christmas/new years's eve holidays. 

This seems to be an issue on device side, did you tried to follow: https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index ?

**Comment by duylong** [comment]
From what I've read, equipment configurations can be changed due to associations.

Issue on device side? What I don't understand is why it affects so many different modules in my home.

I still had an AEON Labs ZW117 repeater that added a "Wake Up v1" to its configuration. Concerning its association, I only have one "Root Endpoint Lifeline".
For 2 identical modules (Qubino ZMNHAD) with the same firmware, I end up with one that has "Wake Up v1" and the other does not. Really weird...

I gave up doing the interviews each time since it comes up randomly each time.

It's difficult at the moment to have precise logs. I have 87 modules, that's a lot of logs and I don't have a time period to isolate the information.

I hope other people have also noticed this problem, that was the point of this issue. 
I will try to continue my investigations...

**Comment by robertsLando** [comment]
@duylong Try to share a full log when you have it, that's the only thing that could help! Are you using an  usb extension cord?

**Comment by duylong** [comment]
No usb extension cord.

I understand about the logs, I will try to isolate the problem if I can.

**Comment by robertsLando** [comment]
@duylong Could you try to use one? It improoves communication a lot

**Comment by duylong** [comment]
Isn't Zwave mesh made for that?
In any case I don't have too many network problems, a few bugs because of my zooz 700 key but overall it works.

I put in an extension to test, we'll see if it's any better, that doesn't explain the crazy configuration addition. 

I thought that initially an interview remained frozen until the next interview, I did not think that a device itself could force the addition of a new configuration with an association.

**Comment by robertsLando** [comment]
>  I did not think that a device itself could force the addition of a new configuration with an association.

I don't understand what you mean here

**Comment by duylong** [comment]
> > I did not think that a device itself could force the addition of a new configuration with an association.
> 
> I don't understand what you mean here

I simply wanted to indicate that it was strange that a module could change its configuration (adding classes in Values) without an interview.

I think I'll close this issue as you think it's a device specific issue. I had the impression of a general bug. If possible, I would create one issue per device.

**Comment by robertsLando** [comment]
IMO that's caused by some communication problem and commands received by the device are misinterpreted by the controller
