### ISSUE TITLE
SmartStart status in Control Panel

### ISSUE THREAD

**Issue by trainman419** [zwave-js/zwave-js-ui#3516]
**Is your feature request related to a problem? Please describe.**
I've been adding a bunch of SmartStart devices over the past few weeks, and I find myself watching the logs to determine
* Is the hub in SmartStart listening mode? (Or did it get stuck in inclusion somewhere?)
* Has a new device been discovered? Did SmartStart succeed or fail?

I find that the logs indicate that a new device has been discovered within a few seconds, but the UI takes 30-60 seconds before it shows that the node has been added successfully.

**Describe the solution you'd like**
It would be great to be able to see the SmartStatus status somewhere in the Control Panel; maybe along with the other icons in the upper left?

**Describe alternatives you've considered**
:shrug: . I'm open to other UI ideas; this is just the first thing that came to mind.

**Additional context**

**Comment by robertsLando** [comment]
Actually I'm not sure if there are even apis on driver in order to get this status. @AlCalzone any clue?

**Comment by AlCalzone** [comment]
Need to double check. Could be a nice feature to have if it's not a yet.

**Comment by AlCalzone** [comment]
Thanks!

**Comment by robertsLando** [comment]
@kpine Is there also an event emitted to watch for inclusion state changes? Cannot find it

**Comment by AlCalzone** [comment]
There isn't.

**Comment by robertsLando** [comment]
So the alternative for now would be to just do a periodic check with an interval I think

**Comment by AlCalzone** [comment]
At least while you don't know there is an active inclusion or exclusion. Those have events.

**Comment by robertsLando** [comment]
I already show inclusion/exclusion status in top bar, would that be enough ? 🤔

**Comment by trainman419** [comment]
> I already show inclusion/exclusion status in top bar, would that be enough ? 🤔 Maybe I can also add the other statuses like busy and so on

I find the top bar a bit confusing; it seems like it shows the most recent message or action (like `Backup NVM progress: 100%` ), but it's hard to tell how old that message is, so it's hard to tell if it indicates and action that is in progress, or an action that completed successfully. ( But that's a much bigger conversation than the original request here. )

With that in mind, I'd be happier with a dedicated status widget, but even showing the inclusion/exclusion status in the top bar would be great for visibility.

**Comment by robertsLando** [comment]
I'm thinking about where to put it so, maybe an icon next to that with different colors:

```
 /** The controller isn't doing anything regarding inclusion. */
 Idle = Grey
    /** The controller is waiting for a node to be included. */
 Including = Purple
    /** The controller is waiting for a node to be excluded. */
Excluding = Red
    /** The controller is busy including or excluding a node. */
 Busy = Yellow
    /** The controller listening for SmartStart nodes to announce themselves. */
 SmartStart = Blue
```

With a tooltip shown when you hover

**Comment by robertsLando** [comment]
See https://github.com/zwave-js/zwave-js-ui/pull/3527#issuecomment-1898525551 for a preview

**Comment by trainman419** [comment]
Amazing! Yes, that's exactly what I was hoping for! Thank you!!!!
