### ISSUE TITLE
[UI] Changelog popup links should open in a new tab

### ISSUE THREAD

**Issue by gzone156** [zwave-js/zwave-js-ui#3520]
**Is your feature request related to a problem? Please describe.**
All the links to GitHub Issues/PR present in the Changelog popup dialog opens in the same location of the Z-Wave JS UI.

**Describe the solution you'd like**
Links to github Issues/PR should open in a new tab.

**Describe alternatives you've considered**
CTRL+Click the link 🤣 

**Additional context**
See attachment:

![image](https://github.com/zwave-js/zwave-js-ui/assets/62515544/bfcd0bdc-af17-4fe5-b43e-e8d9c59d3415)

**Comment by gzone156** [comment]
Faster than light! Thanks @robertsLando !

**Comment by robertsLando** [comment]
Prego Fabio 🙌🏻
