### ISSUE TITLE
For Electric Consumption [kWh] and Electric Consumption [W] only id is displayed

### ISSUE THREAD

**Issue by thejoef** [zwave-js/zwave-js-ui#3522]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.7.0

### ZwaveJS version

12.4.1

### Describe the bug

For Electric Consumption [kWh] and Electric Consumption [W] only id is displayed.
All devices that have these data points are affected. (Fibaro, Shelly...)

### To Reproduce

![meter_endpoint_wrong](https://github.com/zwave-js/zwave-js-ui/assets/149879786/42b22fca-73e6-4b98-8673-49e6ff2486c8)
![meter_endpoint_wrong2](https://github.com/zwave-js/zwave-js-ui/assets/149879786/fbe492b1-60a3-4bcf-b961-ddc4135e8e6e)

### Expected behavior

?

**Comment by robertsLando** [comment]
@thejoef Yeah that is expected, the topic is built using the valueId (the one you see between square brackets as prefix in the label). BTW you could customize that topic using gateway values table if needed
