### ISSUE TITLE
Docker release action failed (9.7.1)

### ISSUE THREAD

**Issue by RobertD502** [zwave-js/zwave-js-ui#3523]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.7.0

### ZwaveJS version

12.4.1

### Describe the bug

Looks like the [Docker release action](https://github.com/zwave-js/zwave-js-ui/actions/runs/7544818747/job/20539020247) has failed for version `9.7.1`. Would you mind manually running it again in order for the `latest` tagged image to get published?

### To Reproduce

N/A

### Expected behavior

N/A

**Comment by robertsLando** [comment]
Damn, hate this flacky docker builds... thanks for letting me know @RobertD502 ! Just triggered another build now

**Comment by RobertD502** [comment]
@robertsLando Have you considered using the [retry action](https://github.com/marketplace/actions/retry-step) or perhaps sending a notification (on failure) to yourself via a personal discord server or another notification method? I know github does email notifications, but I miss those myself when I have actions fail.

**Comment by robertsLando** [comment]
usually I get a notification on gh but seems this doesn't happen every time, It makes sense BTW, maybe to give a try to the retry action you suggested 👍🏼
