### ISSUE TITLE
Philio PAN04 bug in created entities

### ISSUE THREAD

**Issue by Abruzzi04** [zwave-js/zwave-js-ui#3546]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Home Assistant Add-on

### Z-Wave JS UI version

3.2.1

### ZwaveJS version

12.4.1

### Describe the bug

When added, the Philio PAN04 module creates 3 sensors of each type (On/off, Khw, Watt, Ampere, etc.). One for relay 1, another for relay 2 and another for both relays simultaneously. The Ampere, KHW and other sensors have a bug. The values are not changed and appear frozen, or everything appears at zero. The Watt Sensors of the individual relays do not work. Just the sum. I have other pan04 modes on another gateway (VERA) and everything works without any problems.

### To Reproduce

Created entities do not work

### Expected behavior

Consumer entities operate for each individual relay

**Comment by robertsLando** [comment]
Hi @Abruzzi04, If you are using zwave-js-ui with home assistant zwave-js integration you should open this issue on home hassistant core instead, I have no control over the entities created on home assistant side, them are handled by the integration.
