### ISSUE TITLE
setNodeName/set not working 

### ISSUE THREAD

**Issue by cyberumut** [zwave-js/zwave-js-ui#3551]
I wanna setnodename with mqtt 

zwave/_CLIENTS/ZWAVE_GATEWAY-zwave-js-ui/api/setNodeName/set -m  "{ "args": [4,'test'] }"

but not working. where is wrong ?

**Comment by robertsLando** [comment]
Do you see any error in logs?

**Comment by robertsLando** [comment]
The message is wrong, should be:

```
zwave/_CLIENTS/ZWAVE_GATEWAY-zwave-js-ui/api/setNodeName/set -m  "{ "args": [4, \"test\"] }"
```

You must ensure the payload is a valid JSON. I still suggest you to use mqtt explorer as tool for such things...

**Comment by cyberumut** [comment]
> The message is wrong, should be:
> 
> ```
> zwave/_CLIENTS/ZWAVE_GATEWAY-zwave-js-ui/api/setNodeName/set -m  "{ "args": [4, \"test\"] }"
> ```
> 
> You must ensure the payload is a valid JSON. I still suggest you to use mqtt explorer as tool for such things...

MQTT: Publishing to zwave/_CLIENTS/ZWAVE_GATEWAY-zwave-js-ui/api/setNodeName: {
  success: false,
  message: 'Invalid Node ID',
  args: [ [length]: 0 ],
  origin: '{args:["4","test"]}'
} with options { qos: 1, retain: false }

**Comment by cyberumut** [comment]
<img width="530" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/105754498/633eb928-63da-4d59-b78a-825de067de97">

**Comment by robertsLando** [comment]
Now you added `"` to the nodeId too and that's become a string and not a number......

**Comment by cyberumut** [comment]
> Now you added `"` to the nodeId too and that's become a string and not a number......

<img width="837" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/105754498/8e851715-b6ca-4492-8e7e-bd6752b8d6dd">
still error

**Comment by robertsLando** [comment]
`args` must have `"` too....

> zwave/_CLIENTS/ZWAVE_GATEWAY-zwave-js-ui/api/setNodeName/set -m  "{ "args": [4, \"test\"] }"

Why you didn't simply pasted the code I gave you above?? Also why aren't you checking the JSON is valid??

**Comment by cyberumut** [comment]
now working  "{\"args\":[4,\"test\"]}"

**Comment by cyberumut** [comment]
thank u sir
