### ISSUE TITLE
Auth check ignores X-External-Path set by reverse proxy

### ISSUE THREAD

**Issue by frenck** [zwave-js/zwave-js-ui#3553]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Home Assistant Add-on

### Z-Wave JS UI version

9.8.0

### ZwaveJS version

12.4.2

### Describe the bug

The Z-Wave JS UI seems to ignore the `X-External-Path` header for the check if auth is enabled. While this request happens in the frontend, it should have taken into account its current external path.

Causing the request to end up in Home Assistant Core itself instead of the add-on running Z-Wave JS UI.

![CleanShot 2024-01-25 at 09 20 43@2x](https://github.com/zwave-js/zwave-js-ui/assets/195327/44199cf4-42cc-4c1a-8569-5ec8990fe3b5)

Seems to be a regression of #3519

### To Reproduce

Add `https://github.com/hassio-addons/repository-edge` to an Home Assistant instance, and install the Z-Wave JS UI add-on from that repository. The current version there is `372025b`, which contains v9.8.0.

### Expected behavior

See above.

**Comment by robertsLando** [comment]
This must be a regression introduced by: https://github.com/zwave-js/zwave-js-ui/pull/3519

Specifically I had to use `fetch` instead of `axios` here in order to catch redirects:

https://github.com/zwave-js/zwave-js-ui/pull/3519/files#diff-d7f53e719265cb3954839aced2a1b16c28e5e81ac33cf1ca9fa6163ec1e4956aR62

Let me check how I could fix this 🙏🏼

**Comment by robertsLando** [comment]
Was an easy fix, patch release is coming

**Comment by frenck** [comment]
Works like a charm. Thanks! 👍 

../Frenck

**Comment by robertsLando** [comment]
Thanks for the feedback! :)
