### ISSUE TITLE
Node added Unknown manufacturer 0xXXXX - 0xXXXX

### ISSUE THREAD

**Issue by papabak** [zwave-js/zwave-js-ui#3556]
Something went wrong but the node was added without the proper information. It is the Heatit Z-TRM3, with the Product Identifiers: 0x0003:0x0203. How can this information be added? I have not found the option (that will be available somewhere) to remove this node and start over.
The SmartStart option to scan the QR code doesn't work as it can't find the camera in my iPhone. Not so smart perhaps?
I have previously added this device to Z-wave JS UI. That was successful but it also took a lot of trial and error.
The have started all over to HA on an Odroid N2+

**Comment by robertsLando** [comment]
Try to re-interview of your device, just click on the node in the table > advanced > re-interview

**Comment by papabak** [comment]
Regrettably this doesn't solve the problem. 
I have to enter the details of the device somehow or ultimately remove this node and start over.
I see no option to remove the node because it does respond with a ping. It is not dead it is 'only' unspecified.

**Comment by papabak** [comment]
I finally solved it. I had to switch the thermostat to Off, then arrow down to CON and Enter. Then a square start circling. That is the time to exclude the node from the add-on using the Web-gui.
Afterwards I added the unit in the proper way and had no problems afterwards.

**Comment by robertsLando** [comment]
I was going to tell you to try excluding and include it again, glad that worked :)
