### ISSUE TITLE
Z-Wave client not connected

### ISSUE THREAD

**Issue by McFcologne** [zwave-js/zwave-js-ui#3560]
Before submitting a bug please read: <https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/bug_report>

If you are using the Home Assistant Z-Wave JS integration, please add a full dump:

Home Assistant --> settings --> Integrations --> Z-Wave JS --> Configure --> Create dump --> zip the json file and post it here.
[config_entry-zwave_js-b1aecae4468c2c0ccac055ea79ed4881.json.txt](https://github.com/zwave-js/zwave-js-ui/files/14072259/config_entry-zwave_js-b1aecae4468c2c0ccac055ea79ed4881.json.txt)

### Version

Build/Run method:
Installed in a Rapberry Pi 4 version B with Aeotec Z-Stick 7

Z-Wave JS UI version: **9.8.1**
Z-Wave JS version: **12.4.2**

### Describe the bug
Whatever i try to see, i always get: Z-Wave client not connected (e.g.:Error while calling getProvisioningEntries: Z-Wave client not connected)

A clear and concise description of the bug.
Installed Z-Wave JS UI to analyze battery drain of my devices, but always get "Z-Wave client not connected" in Z-Wave JS UI, although Z-Wave is running and my sensors are working.

**Comment by robertsLando** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

**Comment by McFcologne** [comment]
Saving the configuration raised an error: "invalid configuration" and then i had to select the serial port... this is not working, since Home Assistant is already using it be itself and now i have a permanent error (red bar on top): "Driver: Failed to open the serial port: Error Resource temporarily unavailable Cannot lock port (ZW0100)"

**Comment by McFcologne** [comment]
i expected it to be a simple plugin to get a better monitoring. This would also mean, that i have to re-pair all of my devices? that was not, what i intended to solve with that...

My journey until now:
- discontinued using Devole Home Control (no more maintained)
- Bought Hompey Pro
- figured out, that my smoke detectors are not supported by Homey Pro
- Got the recommendation, to use Home Assistant for Z-Wave, because of the Devolo smoke detector support
- Smoke detectors started draining their batteries within  week since connected to Home Assistant
- got the recommendation to install Z-Wave JS UI to catch more Information
- got stuck, because its not only a simple plugin,but e replacement to the whole Z-Wave stack of Home Assistant

Its not your fault, but that is all way above what i initally expected from switching an deprecated system with a maintained community system. Seems like the old legacy was still in a better shape...

I will try it anyway... but im deeply frustrated with that overall experience.

Thanks for now.

**Comment by robertsLando** [comment]
> got stuck, because its not only a simple plugin,but e replacement to the whole Z-Wave stack of Home Assistant

I'm sorry for that but this is well explained in docs, the ones that suggested you to move to Z-UI should have explained you that better. Anyway I'm quite sure that once you will have Z-UI up and running you will not regret it, if you have any truble just open an issue here or even better ask for support in our discord channel: https://discord.gg/HFqcyFNfWd
