### ISSUE TITLE
Network map legend should not use "Unconnected" when device route information isn't known

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js-ui#3562]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.8.1.04f1c76

### ZwaveJS version

12.4.3

### Describe the bug

The network map legend has a case for "Unconnected":

![image](https://github.com/zwave-js/zwave-js-ui/assets/791794/76919457-e1b7-4565-b661-8d14d656d4dc)

But that really just means the node doesn't have any known route information:

https://github.com/zwave-js/zwave-js-ui/blob/89063584b01ce6c6f1c3dd466ea49a73445cc63b/src/components/custom/ZwaveGraph.vue#L948-L955

"Unconnected" gives the impression that the device is not "connected" to the Z-Wave network, but since it really means there's no known routes, it should say that instead. This can be common for battery devices where the route isn't known until the controller sends a command and then obtains the route info, and route information is not persisted in the cache. Thus it is confusing because these battery devices can be reporting info as normal, but the map suggests something is wrong.

I'd recommend using "Unknown" or something similar, like that edge does.

### To Reproduce

Not sure. Probably wipe Z-Wave JS cache and restart ZUI, route info should be unavailable for battery devices.

### Expected behavior

Something not as confusing as "Unconnected".

**Comment by robertsLando** [comment]
I agree that label is misleading. @AlCalzone Are you ok to change that to `Unknown` instead?
