### ISSUE TITLE
MQTT AD - Option to globaly exclude config node

### ISSUE THREAD

**Issue by MuadDibVV** [zwave-js/zwave-js-ui#3571]
Hello,

  We have now all the config parameters on objects but it creates too many devices on my system (MQTT AD creations).
Is it possible to have a global parameter to avoid sending creation request for all this config parameters ?

**Comment by robertsLando** [comment]
@MuadDibVV What software is managing the MQTT discovery? Home assistant? Domoticz? Openhab?

cc @ccutrer

**Comment by apella12** [comment]
FWIW- As a temporary workaround ; 1) From the Node Homeassistant tab I disabled all the HA-device discoveries, then enabled the ones I was using (need ZUI 9.8), put in the Store (for persistence) 2) Set the Home Assistant tab to manual discovery "saved" 3) Using MQTT explorer deleted all the homeassistant topics. 4) Back to ZUI, turn off manual discovery and hit save again.

Did this a couple of days ago, so might not remember order exactly, but you get the idea.

I also think it could be good if the config items could be disabled by default, then up to the user to add the ones that are needed

**Comment by MuadDibVV** [comment]
> @MuadDibVV What software is managing the MQTT discovery? Home assistant? Domoticz? Openhab?
> 
> cc @ccutrer

Domoticz

**Comment by ccutrer** [comment]
I would recommended opening a feature (or bug!) request with Domoticz to handle enabled_by_default: false, then. In the meantime, it doesn't seem like the worst thing in the world for zwave-js-ui to have an option to not publish enabled_by_default: false entities.

**Comment by robertsLando** [comment]
It sounds to me more like an issue on Domoticz but yeah in the meanwhile I could simply skip sending publish when that is set to false in the meanwhile... maybe I could make this opt in with an env var?

**Comment by Claude2666** [comment]
Indeed. It would be nice to have a global option to disable the config topics as now they create a huge amount of extra devices, which most people have no use for.  I think zwavejs-ui does an excellent job in setting up the configuration of the devices. In my case, for 99% of the settings, the defaults are used and the few other settings are set once at inclusion and never changed anymore. 

So it would be really help to have a global option to disable the config items for people who have no need for them, keeping their configuration less complex.  For now, I stick to an older version of zwavejs-ui.

Thanks for this great software.

**Comment by robertsLando** [comment]
Ok so I will add an env var to disable this, ok?

**Comment by apella12** [comment]
It is possible to deal with today by using "manual discovery" and then disabling the individual HA "devices" you don't want to see, then use the discovery as needed.  I'd see the value for someone who doesn't have manual discovery enabled and adds a new device with lots of configs. Having the `enabled by default: false` HA devices automatically disabled could save them from dealing with those devices afterward. FWIW

**Comment by Claude2666** [comment]
Indeed, an option or an environment variable to disable it would be highly appreciated. Thank you.
