### ISSUE TITLE
Slave activity statistics

### ISSUE THREAD

**Issue by duylong** [zwave-js/zwave-js-ui#3575]
Hi, 

I have several powered modules and repeaters for routing my network. 

However I don't see any traffic in the statistics. Maybe I'm wrong ?
How do I know that one module is more used than another? or that my repeater is useless/useful at the chosen location?

For example in the statistics of one of my repeaters, I only have this:

![statistic repeater](https://github.com/zwave-js/zwave-js-ui/assets/3019703/9fa3bbdd-531b-4d3f-a6f3-4ce1b46d54c8)

**Comment by robertsLando** [comment]
Tried to check network map?

**Comment by duylong** [comment]
Yes, but I have no guarantee that a module will take the indicated path. For the moment I have the impression that the slave modules operate transparently and without visibility, I would have liked to see more clearly (if we can).

**Comment by apella12** [comment]
`For the moment I have the impression that the slave modules operate transparently and without visibility` From the zniffing I have done on my own networks IMO this is mostly not true. There are routing tables in both the controller and devices and that information is sent with the message. The network map is pretty accurate. Before I starting using the Zniffer (and not having access to the Zwave-js-ui map I would put in devices to help routing and I found after monitoring the packets they were not used at all.  My two cents

**Comment by duylong** [comment]
Thank you for these clarifications. Outside of the map, it's just that we don't see any trace of traffic, that's why I was wondering. If the map is the only help, I'll be content with that :)

**Comment by robertsLando** [comment]
Maybe @AlCalzone can tell you more about this but I don't see any issue here
