### ISSUE TITLE
No HA configs for CT101 thermostat

### ISSUE THREAD

**Issue by apella12** [zwave-js/zwave-js-ui#3576]
I have a fully working ZUI production environment on Openhab (Rpi4-Docker) using the Zwave MQTT section to get values.  

In a test environment (WSL-docker) I'm trying to use the HA configs.  All seems fine except for my thermostats (no climate configs).  This seems odd since when I first tried using HA configs last July, I recall seeing climate configs for these devices. The one thing that changed between now and then was some "compat;" options in the device json. 
[ct101.json](https://github.com/zwave-js/zwave-js-ui/files/14142617/ct101.json)

Poking around ZUI /api/hass/devices I noted a custom(?) entry for my device.
[Radio Thermostat.json](https://github.com/zwave-js/zwave-js-ui/files/14142642/Radio.Thermostat.json)

So the question: Does the endpoint 1 elements in the hass config cause a problem with generating the HA config since the device json compat removes them?

**Comment by robertsLando** [comment]
> So the question: Does the endpoint 1 elements in the hass config cause a problem with generating the HA config since the device json compat removes them?

Yeah must be that as the values mapped in the custom entry are using endpoint 1. You should fix it based on the values you have or disable that entity for your device in customs (send a PR)

**Comment by apella12** [comment]
Thanks !  I used an old ct101.json and the HA configs appeared, so that is the problem.

Have to think about best path forward for PR as the custom config is for a number of devices.  I will eventually find it, but where/how do the devices that are under the custom config get grouped/mapped? Basically folder to use for to disable?
