### ISSUE TITLE
Intercept node name and location changes from outside UI

### ISSUE THREAD

**Issue by spudwebb** [zwave-js/zwave-js-ui#3591]
I'm creating a ZWave driver for HomeSeer based on ZWave JS UI and using the ZWaveJS.NET library to communicate with the ZWave JS server.
I want to be able to update the name and location of a node so that when those values are updated within HomSseer they are also updated in ZWaveJS UI.  
To do that I tried to use the `ZWaveNode.SetName()` and `ZWaveNode.SetLocation()` methods of the .NET library which correctly set the values in the ZWaveJS cache (in  store/xxxxxxxx.values.jsonl), but it seems that ZWave JS UI completely ignore those values and uses its own instances of name and location that are saved in store/nodes.json.

So my question is: is there a way to update the name and location of a node displayed by ZWave JS UI using a command sent to the ZWave JS server?
Alternatively would it be possible to modify ZWave JS UI behavior so that either
(a) if there is no name/location in nodes.json then it uses the name and location from the ZWave JS cache
or
(b) add a setting that will force ZWave JS UI to always use the name and location from the ZWave JS cache

Related discussion https://github.com/zwave-js/ZWaveJS.NET/discussions/60

**Comment by robertsLando** [comment]
@spudwebb Problem is that actually I have no way to detect that node name and location changed on driver so that's why you don't see it there, if you restart the application you probably will see it correctly

**Comment by AlCalzone** [comment]
That's correct

**Comment by robertsLando** [comment]
@spudwebb Could you give a try to #3592?

**Comment by spudwebb** [comment]
@robertsLando I tested the SYNC-NODE-NAME-LOC branch, and the fix only works for node that supports the "Node Naming and Location" CC.  Name and Location of nodes that do not support it remain blank after a name or location update on the driver.

**Comment by robertsLando** [comment]
@AlCalzone What is the behaviour when node doens't support name/location CC? Do you still list that cc in defined valueIds or do you emit the `'node added'` event? If none of this that's the problem, I actually subscribe valueId observers on `node ready `and on `value added` events, if you only emit `value changed` I don't subscribe to it

**Comment by AlCalzone** [comment]
`getDefinedValueIDs` should only return value IDs for CCs that are supported by the device.

I think you should ignore the `Node Naming and Location CC` for the list of value IDs (since you already have a dedicated UI for those properties) and instead read and subscribe to `NodeNamingAndLocationCCValues.name` and `NodeNamingAndLocationCCValues.location` for populating and updating the naming UI.

**Comment by robertsLando** [comment]
@spudwebb try now

**Comment by spudwebb** [comment]
@robertsLando , still not working, I don't see any name or location in the UI even though they are set on the driver side. And now it isn't working either for nodes that support name/location CC.

**Comment by robertsLando** [comment]
Ops, typo. Try now sorry

**Comment by spudwebb** [comment]
This is working well now. Thank you!

**Comment by robertsLando** [comment]
Thanks for the feedback! Merging now

**Comment by spudwebb** [comment]
@robertsLando, I'm reopening this because it seems that it doesn't work the first time I set the name and location for a node, in this case the driver emit some "Value added" events which does not trigger the renaming in UI  
```
2024-02-19 13:42:40.018 INFO Z-WAVE: [Node 084] Value added: 119-0-name => HomeSeer Technologies HS-MS100+
2024-02-19 13:42:40.026 INFO Z-WAVE: [Node 084] Value added: 119-0-location => loc1
```

if I set again the same name and location for the same node, now "Value updated" events are emitted and it works
```
2024-02-19 13:42:40.036 INFO Z-WAVE: [Node 084] Value updated: 119-0-name HomeSeer Technologies HS-MS100+ => HomeSeer Technologies HS-MS100+
2024-02-19 13:42:40.043 INFO Z-WAVE: [Node 084] Value updated: 119-0-location loc1 => loc1
```

**Comment by robertsLando** [comment]
@spudwebb Could you try this: https://github.com/zwave-js/zwave-js-ui/pull/3612?

**Comment by spudwebb** [comment]
@robertsLando  it works as expected now thanks!

Not related but I wanted to mention it: on my windows machine when I try to run `"npm run build"` as stated in the docs I get the following error:
```
> zwave-js-ui@9.9.0 build
> npm-run-all 'build:*'

ERROR: Task not found: "'build:*'"
```

So my workaround was to run the 2 build commands separately and it worked:
```
npm run build:server
npm run build:ui
```

**Comment by spudwebb** [comment]
I followed the exact instructions found here: https://zwave-js.github.io/zwave-js-ui/#/getting-started/other-methods?id=nodejs-or-pkg-version
So, yes I ran `npm install` before running `npm run build`:

![image](https://github.com/zwave-js/zwave-js-ui/assets/5427056/6136e8f2-bf6d-44e2-885c-c92a673fb02f)

**Comment by AlCalzone** [comment]
Might be a Windows thing with the single quotes.

**Comment by robertsLando** [comment]
@spudwebb That's really strange because it's exactly what I do on my side, it could be it's a windows issue? I'm not aware of any issue using `npm-run-all` package on windows BTW it should be cross platform

**Comment by spudwebb** [comment]
yes it looks like it's a windows issue with the single quotes. If I remove the single quotes for the build target in package.json it works as expected:

    `"build": "npm-run-all build:*",`

**Comment by robertsLando** [comment]
Ok I think there is no issue in removing it on my side too, thanks for letting me know
