### ISSUE TITLE
Search/filter in both compact view and regular view

### ISSUE THREAD

**Issue by 1920x1200** [zwave-js/zwave-js-ui#3595]
If I am in "[compact view](https://i.imgur.com/u4HDCId.png)" there is a search box that allows me to filter the devices based on what I type. If I turn off the compact view, [the search box goes away](https://i.imgur.com/9EUXKgn.png)

It would be be helpful if one could filter/search from within the regular/non compact layout.

**Comment by robertsLando** [comment]
Because the table allows you to filter ALL columns, just press in the filter icon next to the header

**Comment by 1920x1200** [comment]
> Because the table allows you to filter ALL columns, just press in the filter icon next to the header

That works, but its a few extra steps that add up to be an annoyance. For example: 

**Compact Mode:**
1. Click into the Search box
2. Type first few letters of device 
3. Results are displayed on the screen.

**Big Table Mode:**
1. Locate the small filter icon next to the Name column and click it
2. Click into the search box
3. Type first few letters of the device
4. Click ok to close out of the popup that's covering the table
5. Results are displayed on the screen.

Having the same search box at the top of the screen, just like in compact mode would make this process a lot quicker and easier to find.
