### ISSUE TITLE
Settings -> General -> Devices values configuration, labels for Topic and Value seem to be swapped

### ISSUE THREAD

**Issue by TheKorn2** [zwave-js/zwave-js-ui#3604]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Z-Wave JS UI version

9.8.2.c09b638

### ZwaveJS version

12.4.3

### Describe the bug

When defining values for a device type in Settings, General, Device Values configuration, if you click the drop down by Value you get a list of topics. When you click on topics, you get a freeform text box.

### To Reproduce

Go to settings, general, device values, click on "New Value", select a device type (whatever, just pick one), then click on value. See drop down box of topics.

### Expected behavior

Should get a list of topics when clicking on topics, and a freeform text box for the value.

### Additional context

Whoops. Confused the heck out of me the first time!

**Comment by TheKorn2** [comment]
<img width="927" alt="shot" src="https://github.com/zwave-js/zwave-js-ui/assets/6579539/995f7562-9741-4b2f-b3e1-2b037edce000">

According to this, for my sensor I'm modifying the topic "F", and giving it the value "temperature scale". Mmmm, think I'm actually modifying the topic "temperature scale" and giving it the value "F".

**Comment by robertsLando** [comment]
@TheKorn2 Nope you understood it wrong.

You Select a device type, then you select the ValueID (in your case it's Temperature Scale) and you assign to that valueId a specific topic that will be used instead of it's id appended adter the name/location prefix for all devices with the same type

**Comment by TheKorn2** [comment]
So does this essentially remap (or maybe copy) from one topic to another?

I thought it was trying to make a user defined default value for a topic.

**Comment by robertsLando** [comment]
> So does this essentially remap (or maybe copy) from one topic to another?

It just sets a CUSTOM topic for that valueID. You override the default topic that valueId would be published on MQTT and that depends on your gateway/mqtt settings. Please read [docs](https://zwave-js.github.io/zwave-js-ui/#/guide/mqtt)
