### ISSUE TITLE
ERROR MQTT: Mqtt client error connect ECONNREFUSED ::1:1883

### ISSUE THREAD

**Issue by jrevans** [zwave-js/zwave-js-ui#3614]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

PKG executable

### Z-Wave JS UI version

>=9.3.2

### ZwaveJS version

>=12.3.0

### Describe the bug

I was running v9.1.2 with mosquitto v2.0.11  everything was working fine.  I updated to v9.9.0 and received the connect error.  After rolling back the update, I played with the various version since I last updated and discovered that 9.3.1 works/connects fine, but after that the error shows up.

The error happens right away on startup.  My config has not changed url:port = localhost:1883

I can connect to mosquitto using various mqtt utilities.  The config has not changed there.  The only change is updating the zwave-js-ui application.  I have gone through the docs and changelogs looking for what might have happened, but I did not notice anything (I suppose I could have missed something obvious).  Any help on this would be appreciated.

### To Reproduce

launch zwave-js-ui v9.9.0 and configure to connect to mosquitto server localhost:1883

### Expected behavior

connection should happen without error

**Comment by robertsLando** [comment]
@jrevans Could you paste here the full error log please?

**Comment by robertsLando** [comment]
> ECONNREFUSED ::1:1883

`::1` is ipv6, for some reason it's resolving localhost using ipv6 instead of ipv4 so try what @kpine suggested may fix your issue

**Comment by jrevans** [comment]
Sure enough, that was the ticket.  I currently do not have IPv6 configured and so I was slow to pick-up on the fact that '::1' indicated that was what was happening.  Thanks.
