### ISSUE TITLE
zwave-js-ui container keeps restarting (loops)

### ISSUE THREAD

**Issue by hvoorend** [zwave-js/zwave-js-ui#3631]
After spinning up the zwave-js-ui container, I'm able to access it via my browser. After zwavejs-ui configuration (according to the instructions here (https://www.domoticz.com/wiki/Zwave-JS-UI)), I do see devices coming into the zwavejs-ui but after about 50 seconds they disappear and I can see from "docker ps" that my container restarted. Then it starts all over again. Any idea what could be wrong or help on how to investigate ? (also see this topic in Domoticz forum https://www.domoticz.com/forum/viewtopic.php?t=42062).
pi@raspberrypi:~ $ **ls /dev/serial/by-id -l**
total 0
lrwxrwxrwx 1 root root 13 Feb 23 22:36 usb-0658_0200-if00 -> ../../ttyACM0
lrwxrwxrwx 1 root root 13 Feb 23 22:36 usb-RFXCOM_RFXtrx433_A12WY8N-if00-port0 -> ../../ttyUSB0

So **usb-0658_0200-if00** is my Aeon zStick 5 
(as you can see I also have a RFXCOM dongle installed: usb-RFXCOM_RFXtrx433_A12WY8N-if00-port0).

Aeon zStick Gen5 runs firmware 1.0.

Here the contents of /opt/zwavejs-ui/docker-compose.yml:

version: "3.7"
services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mySecretSession
      - TZ=Europe/Amsterdam
    devices:
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - "8091:8091" # port for web interface
      - "3000:3000" # port for Z-Wave JS websocket server

Starting the container with "docker-compose up" show the following error after about 50 seconds:
pi@raspberrypi:/opt/zwavejs-ui $ sudo docker compose up
[+] Running 2/2
 ✔ Network zwavejs-ui_default  Created                                                                                                                                                                                                  0.5s
 ✔ Container zwave-js-ui       Created                                                                                                                                                                                                  0.3s
Attaching to zwave-js-ui
zwave-js-ui  | 2024-02-29 19:58:25.938 INFO APP: Version: 9.9.0.09b107a
zwave-js-ui  | 2024-02-29 19:58:25.968 INFO APP: Application path:/usr/src/app
zwave-js-ui  |   ______  __          __                      _  _____     _    _ _____
zwave-js-ui  |  |___  /  \ \        / /                     | |/ ____|   | |  | |_   _|
zwave-js-ui  |     / /____\ \  /\  / /_ ___   _____         | | (___     | |  | | | |
zwave-js-ui  |    / /______\ \/  \/ / _' \ \ / / _ \    _   | |\___ \    | |  | | | |
zwave-js-ui  |   / /__      \  /\  / (_| |\ V /  __/   | |__| |____) |   | |__| |_| |_
zwave-js-ui  |  /_____|      \/  \/ \__,_| \_/ \___|    \____/|_____/     \____/|_____|
zwave-js-ui  |
zwave-js-ui  | 2024-02-29 19:58:26.116 WARN STORE: scenes.json not found
zwave-js-ui  | Logging to file:
zwave-js-ui  |  /usr/src/app/store/logs/zwavejs_2024-02-29.log
zwave-js-ui  |
zwave-js-ui  |
zwave-js-ui  | #
zwave-js-ui  | # Fatal error in , line 0
zwave-js-ui  | # unreachable code
zwave-js-ui  | #
zwave-js-ui  | #
zwave-js-ui  | #
zwave-js-ui  | #FailureMessage Object: 0x75821764
zwave-js-ui exited with code 0
pi@raspberrypi:/opt/zwavejs-ui $

I've also attached some log files that might contain more details (I can't see big things go wrong but I'm not an expert).

[zwavejs-ui log2.txt](https://github.com/zwave-js/zwave-js-ui/files/14472734/zwavejs-ui.log2.txt)
[zwavejs-ui log1.txt](https://github.com/zwave-js/zwave-js-ui/files/14472735/zwavejs-ui.log1.txt)

Hope one of you can shed a light or point me in the right direction. Thanks in Advance!

Regards Henny

**Comment by hvoorend** [comment]
Thanks kpine. Tried the second option first as this is the least "disturbing" ;-). However installation failed. See logging below.
Hope you can help me out?

pi@raspberrypi:~ $ **sudo apt-key adv --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys 04EE7237B7D453EC 648ACFD622F3D138**
Executing: /tmp/apt-key-gpghome.8HhyQumQNe/gpg.1.sh --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
gpg: key DC30D7C23CBBABEE: public key "Debian Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" imported
gpg: key E0B11894F66AEC98: public key "Debian Archive Automatic Signing Key (9/stretch) <ftpmaster@debian.org>" imported
gpg: Total number processed: 2
gpg:               imported: 2
pi@raspberrypi:~ $ **echo "deb http://httpredir.debian.org/debian buster-backports main contrib non-free" | sudo tee -a "/etc/apt/sources.list.d/debian-backports.list"**
deb http://httpredir.debian.org/debian buster-backports main contrib non-free
pi@raspberrypi:~ $ **sudo apt update**
Get:1 http://httpredir.debian.org/debian buster-backports InRelease [51.4 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Get:3 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:4 https://download.docker.com/linux/raspbian buster InRelease [33.6 kB]
Get:5 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13.0 MB]
**Err:1 http://httpredir.debian.org/debian buster-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131**
Get:6 http://archive.raspberrypi.org/debian buster/main armhf Packages [400 kB]
Get:7 https://download.docker.com/linux/raspbian buster/stable armhf Packages [40.1 kB]
Reading package lists... Done
**W: GPG error: http://httpredir.debian.org/debian buster-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'http://httpredir.debian.org/debian buster-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.**

**Comment by robertsLando** [comment]
Try to: 

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6ED0E7B82643E131
```

**Comment by hvoorend** [comment]
Thank you so much kpine and robertsLando! 
Install of libseccomp2 now succeeded and the zwavejs-ui container keeps running now. My nodes are now in the process of being discoverd (60% already is). This one was giving me headaches and I'm so happy that you guys could help me out. THANKS!

**Comment by robertsLando** [comment]
You welcome @hvoorend
