### ISSUE TITLE
[mqtt] Zwave-Js-UI clears retained message even though retain is disabled

### ISSUE THREAD

**Issue by spacemanspiff2007** [zwave-js/zwave-js-ui#3633]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.9.0.09b107

### ZwaveJS version

12.4.4

### Describe the bug

Zwave-Js-UI clears retained message even though retain is disabled.

### To Reproduce

Disable retain

![grafik](https://github.com/zwave-js/zwave-js-ui/assets/10754716/7fe75c8c-9f33-4b5f-83fa-065dc69f9438)

Find node that uses a notification or a scene

![grafik](https://github.com/zwave-js/zwave-js-ui/assets/10754716/81314fe6-db0a-4569-b5a6-cf812a478849)

trigger scene, observe that the scene is reported.
Observe clearing of retained value by sending an empty payload

````
[2024-03-06 13:24:46] [INFO] Message arrived for broker with topic: "zwave/53/91/0/scene/002",  payload: "0"
[2024-03-06 13:24:47] [INFO] Message arrived for broker with topic: "zwave/53/lastActive", payload: "1709727886877"
[2024-03-06 13:24:47] [INFO] Message arrived for broker with topic: "zwave/53/91/0/scene/002", payload: ""
````

### Expected behavior

When retain is disabled the last message with empty payload should not be send

e.g. the above messages should look like this
````
[2024-03-06 13:24:46] [INFO] Message arrived for broker with topic: "zwave/53/91/0/scene/002",  payload: "0"
[2024-03-06 13:24:47] [INFO] Message arrived for broker with topic: "zwave/53/lastActive", payload: "1709727886877"
````

### Additional context

Since retain is disabled it's not necessary to clear the retained value since it will not be republished on connect.
It actually makes processing these messages much harder because one hast to actively filter out the messages with empty payload on the mqtt client side.

**Comment by robertsLando** [comment]
@spacemanspiff2007 That's not used to clear retain, that's just default behaviour of notificaitons. Notifications are not sent with retain flag neighter when retain flag is true
