### ISSUE TITLE
 The port (/dev/serial/by-id/usb-0658_0200-if00) disappears when you restart Z-Wave-JS UI on VM Synology

### ISSUE THREAD

**Issue by Warp95** [zwave-js/zwave-js-ui#3634]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Home Assistant Add-on

### Z-Wave JS UI version

9.9.0

### ZwaveJS version

0.4.5

### Describe the bug

Configuration:
- Synology, DSM 7.2.1 Update 4
- HA core 2024.3.0, under VM in Synology

Unable to configure the Z-Stick Gen5 key, under Z-Wave JS UI, the port (/dev/serial/by-id/usb-0658_0200-if00) disappears when you restart Z-Wave-JS UI.
With the use of Z-Wave JS, there is no problem, the port is present and remains present, even when restarting Z-Wave JS.

### To Reproduce

installer HA et Z-Wave JS UI, sous une VM Synology avec une clé Z-Stick Gen5

### Expected behavior

That the port /dev/serial/by-id/usb-0658_0200-if00 does not disappear when starting Z-Wave JS UI.

### Additional context

- Synology, DSM 7.2.1 Update 4
- HA core 2024.3.0, under VM in Synology

**Comment by robertsLando** [comment]
Hi @Warp95, sincerly I have no clue why that happens but this seems not an issue strictly related to Z-WaveJS UI but more likely to the VM configuration or else (maybe some udev rules?). Maybe @kpine has some hints about this

**Comment by Warp95** [comment]
Hi @robertsLando, I don't think it comes from the configuration of the VM under Synology, because as explained everything works very well with just Z-Wave JS installed -> the key and port are well recognized.

But when I switch to Z-Wave JS UI, as explained, the port disappears.

**Comment by robertsLando** [comment]
What is not clear to me is what you mean with "the port disappiars". Does it disappiar just from settings or from the machine too? I don't do anything that could cause both this behaviours as this would be blocking for everyone using this application this is why I have a feel this is not related to ZUI

**Comment by Warp95** [comment]
Here are the steps:

- installing Z-Wave JS UI
![image](https://github.com/zwave-js/zwave-js-ui/assets/13014428/828dfda2-5b1c-4438-88eb-c5e06844e8d0)

- Configuring the Z-Wave port (present at this time)
![image](https://github.com/zwave-js/zwave-js-ui/assets/13014428/4950817c-143d-47b9-95c0-85736f72616b)

- Once saved -> error in logs
![image](https://github.com/zwave-js/zwave-js-ui/assets/13014428/1343e117-17e3-4299-92ac-27079bf60040)

- Return to the configuration to notice the disappearance of the port /dev/serial/by-id/usb-0658_0200-if00
![image](https://github.com/zwave-js/zwave-js-ui/assets/13014428/d779c1cc-aa81-4c1a-ac13-b5a766dd45f5)

**Comment by robertsLando** [comment]
@Warp95 Try to disable soft reset in settings, that's not ideal but it's just to see if that's the root cause of your issues

**Comment by Warp95** [comment]
YES ! With the soft reset it works!

What is the impact of having disabled the soft reset?

**Comment by robertsLando** [comment]
> What is the impact of having disabled the soft reset?

The protocol requires it on startup but seems some sticks doesn't like that, for more detailed info check this: https://github.com/zwave-js/node-zwave-js/issues/6341

**Comment by Warp95** [comment]
@robertsLando, a big thank-you !!
I have one last question for a perfect installation of Z-Wave JS UI, you need:

1. Uninstall Z-Wave JS
Or
2. Disable Z-Wave JS
Or
3. Configure Z-Wave JS to server ws://a0d7b954-zwavejs2mqtt:3000

Thank you for your answer.

**Comment by robertsLando** [comment]
If you are talking about the Home Assistant Z-Wave JS integration you have to make it point to your Z-UI instance so the correct answer is 3: Configure Z-Wave JS to server ws://a0d7b954-zwavejs2mqtt:3000

**Comment by robertsLando** [comment]
See [here](https://zwave-js.github.io/zwave-js-ui/#/homeassistant/homeassistant-official) for more details
