### ISSUE TITLE
NVM Management Restore APi

### ISSUE THREAD

**Issue by Siburanjan** [zwave-js/zwave-js-ui#3637]
Hi,

I wanted to backup and restore NVM , The backup is happening properly when i hit the API "{ "api": "backupNVMRaw", "args": [] }" and stored in the path server/store/backup/nvm/ . but when i want to restore the NVM after reset i am unable to do it through api , but the restore is happening through ui. Can you please help me out with the api for restore and how to specify the file path for the nvm_file downloaded.

**Comment by robertsLando** [comment]
@Siburanjan check https://zwave-js.github.io/zwave-js-ui/#/guide/mqtt?id=restorenvm

Topic: `zwave/_CLIENTS/ZWAVE_GATEWAY-<mqtt_name>/api/restoreNVM/set`

Payload:

```
{
    "args": [
        data,
        false
    ]
}
```

The `data` payload should be a Buffer

**Comment by Siburanjan** [comment]
Yes, the issue is stable and working fine. Thanks for your timely support.

**Comment by Siburanjan** [comment]
I am closing this issue.
