### ISSUE TITLE
Docker version?

### ISSUE THREAD

**Issue by apella12** [zwave-js/zwave-js-ui#3657]
Noticed this during upgrade (using 3.7) like in the docs.
`WARN[0000] /home/zui/docker-compose.yml: `version` is obsolete`

**Comment by zackbcom** [comment]
remove the `versoin` key from your docker-compose.yml file.
It probably is the first thing in your file `versoin: 3.8` or something like that.

**Comment by apella12** [comment]
Thanks ! did not know that was no longer needed.
