### ISSUE TITLE
Smart Start Screen Data Inconsistencies 

### ISSUE THREAD

**Issue by zackbcom** [zwave-js/zwave-js-ui#3674]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.11.1.9e7d24e

### ZwaveJS version

12.5.5

### Describe the bug

edit2: view the below comment from @robertsLando on changes: https://github.com/zwave-js/zwave-js-ui/issues/3674#issuecomment-2068960023

edit: After looking at the code, I think this is the intended behavior. [disable check](https://github.com/zwave-js/zwave-js-ui/blob/9e7d24eef6afc5889f3f3729670349b8f205c2b0/src/views/SmartStart.vue#L30)

After upgrade from `9.9.1` to `9.11.1`, the smart start screen has an issue loading all of the edit buttons, check boxes, protocol toggles.

![image](https://github.com/zwave-js/zwave-js-ui/assets/1888323/2daff789-c047-49ca-9c12-54f9e5d04853)

### To Reproduce

Have smart start items.
Upgrade docker from `9.9.1` to `9.11.1`.
Unsure if it's some edge case from my personal Smart Start items.

### Expected behavior

Shows all edit buttons, able to check all boxes, able to toggle the protocols.

### Additional context

Looks like the items upgraded correctly with the recent updates
from
```json
{
"k": "controller.provisioningList",
    "v": [
        {
            //...
            "supportedProtocols": [
                0,
                1
            ],
            //...
        }
    ]
}
```
to
```json
{
"k": "controller.provisioningList",
    "v": [
        {
            //...
            "supportedProtocols": [
                "ZWave",
                "ZWaveLongRange"
            ],
            //...
        }
    ]
}

```

**Comment by zackbcom** [comment]
@AlCalzone I'm unsure if this is UI specific.

**Comment by AlCalzone** [comment]
The ones that are already included  (have a node id in the first column) cannot be edited anymore, since the edit will have no effect until it's excluded and included again.

**Comment by zackbcom** [comment]
Agree, I submitted this because I thought the editing ended at the 2nd checkbox (second arrow) like it had some parsing issue with the rest of the data. 

My use case for Smart Start screen is to keep a list of all my of my zwave devices and give them a name specific to the DSK.
For some devices I have to search using it's DSK to know what device it is and rename it. Like Water Sensors, door sensors, external plugs. I move these around some times and change all batteries or upgrade firmware with a [plug in battery for coin cell](https://www.amazon.com/Connect-CR2032-Converter-Counter-Display/dp/B097N7F2RR).

Having to locate DSK row, then locate node id, then go to control panel and rename is a bit longer. But probably less work than update both sections.

Maybe we can have a button to:
- navigate to the Control Panel and go the the specific node and open the node details.
- or pop up a modal for the linked node on the Smart Start Screen.

**Comment by zackbcom** [comment]
For the additional Info we could have a collapsible header above the table to give some more context around how the table manages it's data, and what the actions do, Zwave Button, Active, Check boxes, etc

maybe something like this, but a bit cleaner
![image](https://github.com/zwave-js/zwave-js-ui/assets/1888323/6854f3b6-fa25-4604-87a2-de98d94a2b05)
