### ISSUE TITLE
Smart Start Manufacture/Label/Description Blank for items attached to nodes

### ISSUE THREAD

**Issue by zackbcom** [zwave-js/zwave-js-ui#3677]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.11.1.9e7d24e

### ZwaveJS version

12.5.5

### Describe the bug

I am unable to see / update the Manufacture/Label/Description on smart start assets that are attached to a node. 

![image](https://github.com/zwave-js/zwave-js-ui/assets/1888323/b53c4e9b-5b97-444c-b31d-a587756483b7)

<img width="1360" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/1888323/e5783e9e-a652-49ee-862e-6c03c4a1a4e1">

### To Reproduce

Not sure if related to upgrade from 9.9.1, or what version of node-js the devices were added with.

### Expected behavior

Should show related information from node

**Comment by robertsLando** [comment]
@AlCalzone I'm wondering if this is a regression on driver side because I can see them on my end but I think this happens only for newly added Smart Start codes.

**Comment by AlCalzone** [comment]
The device manufacturer/label for SmartStart entries can (but doesn't have to) be included in the QR code. When it is, it is also included in the SmartStart provisioning entry that Z-Wave JS saves in its cache. This is what Z-Wave JS UI displays there AFAIK.

The information in the second screenshot comes from our device config files.

So they aren't related per se. I suppose it makes sense to display the information from the `Node` instance there if the provisioning entry doesn't have a manufacturer/label and the node is already included.

**Comment by robertsLando** [comment]
Oh ok I wasn't aware of this, I can look at that in #3674

**Comment by Botched1** [comment]
> Oh ok I wasn't aware of this, I can look at that in #3674

One thing I would add is that I think the "Protocol" field should also populate after a device has been paired, too.

See screenshot. The "Computer Room Door" SmartStart entry was manually added (not scanned from QR code). Long Range boot mode was selected, and the device successfully paired as LR (as noted by the device ID#), yet the Protocol is blank.

![image](https://github.com/zwave-js/zwave-js-ui/assets/19985320/20ff08c6-0014-45de-a884-e981946ebbee)

**Comment by robertsLando** [comment]
Ok follow updates on #3674
