### ISSUE TITLE
Diagnose / Health Check Lists Neighbors for Z-Wave LR Devices, when there obviously are not any (by definition)

### ISSUE THREAD

**Issue by Botched1** [zwave-js/zwave-js-ui#3680]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.11.1.9e7d24e

### ZwaveJS version

12.5.5

### Describe the bug

Health check on Z-Wave LR devices shows a neighbor count, even though Z-Wave LR devices do not have neighbors.

### To Reproduce

From Network Graph view and selecting a Z-Wavew LR end device then click the blue DIAGNOSE button.

Run a health check against the controller.

Note that the results show a neighbor count, even though Z-Wave LR devices do not have neighbors, and connect directly to the controller.

![image](https://github.com/zwave-js/zwave-js-ui/assets/19985320/8a036b72-f700-46df-962d-e50919ffa661)

### Expected behavior

It should not list neighbors for Z-Wave LR devices.

**Comment by AlCalzone** [comment]
related to https://github.com/zwave-js/node-zwave-js/issues/6627

**Comment by robertsLando** [comment]
@Botched1 Please follow updates on that issue

**Comment by AlCalzone** [comment]
@robertsLando You can start by hiding the neighbors display when doing health checks on a LR device
