### ISSUE TITLE
For Z-Wave LR Devices Diagnose / Health Check Should Not Allow Health Checks Against anything except the controller

### ISSUE THREAD

**Issue by Botched1** [zwave-js/zwave-js-ui#3681]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.11.1.9e7d24e

### ZwaveJS version

12.5.5

### Describe the bug

Health Check / Diagnose will allow you to attempt a health check between a Z-Wave LR device and other devices, even though Z-Wave LR devices can't talk directly to anything except the controller.

### To Reproduce

From Network Graph view and selecting a Z-Wavew LR end device then click the blue DIAGNOSE button.

Run a health check against any node, except the controller.

It will fail as Z-Wave LR devices can not communicate with other end devices, so should not be allowed at all.

### Expected behavior

You should not be able to health check a Z-Wave LRT end device against anything other than the controller.

**Comment by robertsLando** [comment]
Correct, will fix

**Comment by robertsLando** [comment]
> @robertsLando You can start by hiding the neighbors display when doing health checks on a LR device

cc @AlCalzone I will do it here
