### ISSUE TITLE
Cannot scroll down to channel values in the controller info panel on the map 

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js-ui#3685]
See video
[Screencast from 24.04.2024 12:23:22.webm](https://github.com/zwave-js/zwave-js-ui/assets/17641229/91803628-cf68-43f4-9a01-b60bee46ce20)

**Comment by robertsLando** [comment]
Hummmm interesting one, I should check if I can control someway the css of the legend as it seems everything is messed up when values are popolated

**Comment by AlCalzone** [comment]
I think it's the layout switch in the labels between selecting and deselecting a point.
