### ISSUE TITLE
Removed of failed nodes acts strangely

### ISSUE THREAD

**Issue by bronger** [zwave-js/zwave-js-ui#3693]
### Checklist

- [x]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.11.1.e327942

### ZwaveJS version

12.5.6

### Describe the bug

If I click on “remove” under “Failed nodes” in the “advanced” dialog of a dead node (red sad face), nothing happens. Really nothing, as if it was hanging (which it is not because I can cleanly close the “advanced” dialog).

I can, however, successfully remove the dead node by removing all currenlty dead nodes in the “advanced actions”. However, this opens a lot of red error messages (which I failed to preserve) for all the non-dead nodes.

### To Reproduce

See above.

### Expected behavior

For using the “remove” button for a single dead node, I expect it to remove the node, possibly after a confirmation dialog.

For using the removal of all currently dead nodes in the “advanced actions”, I got the expected behaviour except for the spurious error messages.

### Additional context

I restarted the zwave-JS UI container and retried.  I think this time, the symbol was not the red sad face but a grey disc (unknown status?). This was the situation when the ”advanced actions” – “removal of failed nodes” was successful. But I hadn’t tried that before the restart.

**Comment by bronger** [comment]
I experience the same dead buttons for “re-interview node” and “update values”.

**Comment by bronger** [comment]
I do not have this issue with version 9.11.1.9e7d24e.

**Comment by robertsLando** [comment]
Fixed on master now, thanks for spotting the error before the official release :)
