### ISSUE TITLE
[feat] Allow to change provisioning entries name/loc even when after they have a node binded

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js-ui#3699]
Ref: https://github.com/zwave-js/zwave-js-ui/discussions/3694#discussioncomment-9318701

**Comment by foxxcomm** [comment]
We are running into this. When we notice a typo or want to change the name or location of a SmartStart entry that is already assigned the edit button is not present. Implementing this would make it easy to update the name or location in Home Assistant by simply editing the SmartStart entry then excluding the device and SmartStart would then re-include the device using the updated name/location.

Thank You

**Comment by robertsLando** [comment]
@AlCalzone Should this be possible?

**Comment by AlCalzone** [comment]
I think it's fine. This info is just for the user anyways.

**Comment by foxxcomm** [comment]
@AlCalzone --

Just upgraded to v9.14.0 and tested this. Don't see the edit button active after upgrade on all our SmartStart entries which are already assigned to nodes. Have cleared our browser cache with same results. Should the edit button become active on in-use entries after this upgrade? Let me know if you need debug information and if so where to send it. Thanks!

**Comment by robertsLando** [comment]
I can see it, could you double check the version please?

![2024-06-18_08-43](https://github.com/zwave-js/zwave-js-ui/assets/11502495/7374cde9-aa11-4dbf-be51-c0d58b74be9a)

**Comment by robertsLando** [comment]
I can see it, could you double check the version please?

![2024-06-18_09-57](https://github.com/zwave-js/zwave-js-ui/assets/11502495/fcaf64dd-c2a7-4ca9-af5b-9b863ca053e2)

**Comment by robertsLando** [comment]
LOL sorry just saw that I pushed the commit after 9.14.0 release. Please wait for 9.14.1 or, if using docker, use `master` tag isntead
