### ISSUE TITLE
Fan Mode setting of MCO Home Thermostats are not available to Home assistant

### ISSUE THREAD

**Issue by richardstone** [zwave-js/zwave-js-ui#3700]
I'm using two types of MCO Home Thermostats. MH8-FC (0x015f-0x0802-0x5102) and MH5 (0x015f 0xf523-0x7101). 
(MH5 does not seem to have an official configuration in ZwaveJS yet too.)

I'm looking for the Fan State settings in Home Assinstant, but it looks like that it is not available. The setting is available within ZwaveJSUI.
<img width="444" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/22618286/c68ecb6b-b549-4be9-8b35-8c42fdd2b427">

**Comment by robertsLando** [comment]
@richardstone Are you using MQTT discovery or home assistant integration?

**Comment by richardstone** [comment]
I’m using MQTT discovery

**Comment by robertsLando** [comment]
Could I ask you why? The reccomended way to use zui with home assistant is by using the integration, check docs here: https://zwave-js.github.io/zwave-js-ui/#/homeassistant/homeassistant-official

**Comment by richardstone** [comment]
I'm using MQTT as I'm collecting many zwaveJS controllers in a single MQTT broker, and pass that single one to Home Assistant and it's simpler this way for me.

**Comment by robertsLando** [comment]
In order to add fan mode handling you should edit the discovery config. Here are the docs to help you doing that: https://zwave-js.github.io/zwave-js-ui/#/homeassistant/homeassistant-mqtt?id=custom-components
