### ISSUE TITLE
[feat] Zniffer

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js-ui#3703]
Z-Wave JS 12.6.0 introduces [Zniffer](https://zwave-js.github.io/node-zwave-js/#/api/zniffer) APIs.

This issue is used to discuss about how to integrate it on the UI

**Comment by robertsLando** [comment]
@AlCalzone

**Comment by zackbcom** [comment]
Added in [Release 9.13.0](https://github.com/zwave-js/zwave-js-ui/releases/tag/v9.13.0)
