### ISSUE TITLE
How to fetch the zwave controller sdk(chip binary) version in a separate nodejs application

### ISSUE THREAD

**Issue by hassan-xy** [zwave-js/zwave-js-ui#3718]
Hi guys,
I need to fetch the zwave controller sdk(chip binary) version in a separate nodejs application. I am not sure as to how I can fetch it. I tried but was unable to do so. Can you guys share an example of how I can fetch it. 
![image](https://github.com/zwave-js/zwave-js-ui/assets/125990448/113117e9-4ae9-4f74-a557-bd2be141b58b) 

Thanks

**Comment by robertsLando** [comment]
MQTT ? https://zwave-js.github.io/zwave-js-ui/#/guide/mqtt

**Comment by hassan-xy** [comment]
I mean not through MQTT but maybe like I hit an API and I receive the version number as response, kinda like this example:
{"api":"firmwareUpdateOTW","args":[{"name":"zwave_ncp_serial_api_controller_BRD4207A.gbl","data":{}}]}

Thanks

**Comment by robertsLando** [comment]
@hassan-xy there is no api for that, the alternative is to enable zwavejs server and connect using websockets like home hassistant does:

See docs here: https://github.com/zwave-js/zwave-js-server
