### ISSUE TITLE
Unable to change zwave config

### ISSUE THREAD

**Issue by zackbcom** [zwave-js/zwave-js-ui#3728]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.13.0

### ZwaveJS version

12.9.1

### Describe the bug

Unable to save config if zniffer is disabled.

prob needs another check in there for zwave enabled, zniffer disabled.

```js
		differentPorts() {
			return (
                                (this.newZwave.enabled &&
					!this.newZniffer.enabled ) ||
				(this.newZwave.enabled &&
					this.newZniffer.enabled &&
					this.newZwave.port !== this.newZniffer.port) ||
				'Zniffer and Z-Wave ports must be different.'
			)
		}
```

SOURCE - https://github.com/zwave-js/zwave-js-ui/blob/1c36405f0265a87acb5057ddef1782115570f66e/src/views/Settings.vue#L1976

### To Reproduce

have zwave enabled, have zniffer disabled. make change to zwave configs, save.

### Expected behavior

able to save zwave config.

### Additional context

<img width="492" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/1888323/78356c1f-dffb-43dd-8f4f-42fef83cd608">
<img width="205" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/1888323/91aaf05f-64b2-4855-8eac-50d50bb9d271">

**Comment by robertsLando** [comment]
@zackbcom Did you used the same port on zniffer? I mean if you enable it and clear the port and then disable it again does it works?

**Comment by robertsLando** [comment]
This is better:

```js
differentPorts() {
			return (
				!this.newZwave.enabled ||
				!this.newZniffer.enabled ||
				this.newZwave.port !== this.newZniffer.port ||
				'Zniffer and Z-Wave ports must be different.'
			)
		},
```

**Comment by zackbcom** [comment]
> @zackbcom Did you used the same port on zniffer? I mean if you enable it and clear the port and then disable it again does it works?

I tried both ways. wouldn't save with same port though. 

New updates fixes it. thanks! Currently testing the zniffer, so far it's awesome.

**Comment by robertsLando** [comment]
@zackbcom Thanks for your feedback 🙏🏼
