### ISSUE TITLE
zniffer: Ability to reference keys from zwave config

### ISSUE THREAD

**Issue by zackbcom** [zwave-js/zwave-js-ui#3731]
**Is your feature request related to a problem? Please describe.**
I would like the ability to use the keys defined in zwave config for zniffer without needing to copy paste.

**Describe the solution you'd like**
Different ideas:
1. Button at the headers (Security Keys , Security Keys (Long Range)) to copy all keys from zwave config into zniffer.
2. If zniffer keys empty use keys from zwave config
3. checkbox next to zniffer key to use zwave keys, disable key text input

**Comment by robertsLando** [comment]
Yeah we already plan to improve things here, the idea is also to remove keys from settings and/or allow to change them on runtime from zniffer page, also allowing to add more set of keys in case there are multiple networks to sniff

cc @AlCalzone

**Comment by AlCalzone** [comment]
I think making it easier to reuse the same keys from the driver is still worth it. Like a button to copy then over or a checkbox, even if it is just temporary.
