### ISSUE TITLE
Zniffer: Enhance column widths

### ISSUE THREAD

**Issue by zackbcom** [zwave-js/zwave-js-ui#3732]
**Is your feature request related to a problem? Please describe.**
Update column widths to have tighter data.

**Describe the solution you'd like**
Update the TH in the table to remove with in `px` to use `ch`
example:
add the following to each th: `white-space: nowrap;`
Column: `#`, css: `width: 10ch;`
Column: `Timestamp`, css: `width: 12ch;`
Column: `Delta [ms]`, css: `width: 4ch;`
Column: `Protocol Data Rate`, css: `width: 20ch;`
Column: `RSSI`, css: `width: 4ch;`
Column: `Ch`, css: `width: 4ch;`
Column: `Home Id`, css: `width: 8ch;`
Column: `Route`, css: `width: ??ch;`
Column: `Type`, css: `width: ??ch;`
Column: `Payload`, css: `width: ??ch;`

Additional Changes:
Move Routes to end as it expands quite large
Prefer static / semi static width columns on the left with known max ch defined. (RSSI, Ch, Home Id, Rate)

Examples:
<img width="1329" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/1888323/d8bf3238-789c-4a32-af52-2d7cc0f82094">
<img width="1329" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/1888323/e815ec84-37a6-49a2-b3ea-4fc00e8e428f">
<img width="1329" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/1888323/aef92885-ae33-4e15-9aaf-b68c65cafb23">

Before Changes:
<img width="1329" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/1888323/7d453975-223f-45c1-bd76-5ab192c598c9">
<img width="1329" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/1888323/809d0038-ab33-4a9a-aeda-e8433c7fffc5">

**Comment by robertsLando** [comment]
Thanks for the suggestion! 🙏🏼
