### ISSUE TITLE
Complains about a settings error which is not configured at all (Zniffer) 

### ISSUE THREAD

**Issue by mmattel** [zwave-js/zwave-js-ui#3736]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.13.0

### ZwaveJS version

12.9.1

### Describe the bug

When trying to save the current settings, I get the following complaints:
- `Your configuration contains errors, fix it`
- `Zniffer and Z-Wave ports must be different.`

Note that Zniffer is **NOT** configured nore enabled.

![image](https://github.com/zwave-js/zwave-js-ui/assets/3321281/dfdc0805-415b-420f-8a28-be963ba9a828)
![image](https://github.com/zwave-js/zwave-js-ui/assets/3321281/f6bfc342-f91d-4b4b-81b0-7ddde6b077cf)

### To Reproduce

Have
- Zwave enabled and configured and
- Zniffer disabled and unconfigured (as not used)

--> Try to click `SAVE`

### Expected behavior

Save the settings must be possible when Zniffer is disabled and unconfigured.

**Comment by zackbcom** [comment]
Fixed in 9.13.1

**Comment by robertsLando** [comment]
Use latest 9.13.1/2 version

**Comment by mmattel** [comment]
Installed, works 👍
