### ISSUE TITLE
login UX is blank starting in 9.13.2

### ISSUE THREAD

**Issue by abscondment** [zwave-js/zwave-js-ui#3737]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.13.2.632ca88

### ZwaveJS version

12.9.1

### Describe the bug

When logged out, I am presented with a blank screen. I cannot log in.

![Screenshot from 2024-05-31 18-26-42](https://github.com/zwave-js/zwave-js-ui/assets/36872/8377a6b3-f497-40c3-9772-1d93082d8ce7)
![Screenshot from 2024-05-31 18-26-54](https://github.com/zwave-js/zwave-js-ui/assets/36872/bceef2ea-9932-48fa-8b09-9ce62a57a822)

 The console has a JavaScript error:
```
Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://rosebud:8091/') with script ('https://rosebud:8091/sw.js'): An SSL certificate error occurred when fetching the script.
```

However, I can access the script from my browser without error.

### To Reproduce

1. Use SSL
2. Upgrade to v9.13.2
3. Log out

### Expected behavior

Z-Wave JS UI is configured to serve traffic over HTTPS with a self-signed certificate.

Occasionally, I will need to tell my browser (Brave `Version 1.66.118 Chromium: 125.0.6422.147 (Official Build) (64-bit)`) to accept this self-signed certificate as valid in order load the page. This is normal, and expected. 

When _logged out_, I expect to see the login prompt and be able to log in with my username and password.

### Additional context

If I revert to `v9.13.1` and refresh, I can log in again.

If I upgrade to `v9.13.2` while already logged in, I can access the site and it seems to function without issue. If I log out and refresh, it reverts to the broken behavior.

**Comment by abscondment** [comment]
@kpine I would assume you're correct. It serves the same certificate either way.

The other interesting part: I get the same ServiceWorker SSL error with both the functioning login screen (9.13.1) and with the broken one (9.13.2).

**Comment by robertsLando** [comment]
Yeah that error on console happens when the swrvice worker isn't loaded. I would like to ask you to try pressing Ctrl+F5 to try a refresh pf the page without cache. Let me know if that fixes the issue

**Comment by abscondment** [comment]
>  I would like to ask you to try pressing Ctrl+F5 to try a refresh pf the page without cache. Let me know if that fixes the issue

Yeah: same results with Ctrl+F5, with loading in Incognito, with disabling the cache in DevTools. I get a Loading spinner, and then a blank page with just the footer.

**Comment by Razor648** [comment]
i have the same issue with the latest build 9.13.2. Docker version.

**Comment by IetIesAai** [comment]
same here - starts working when i change to "authEnabled":false in the settings.json...

**Comment by robertsLando** [comment]
Sorry guys, I added some skeleton loaders on pages and seems that broke the login (the only page I didn't tested). Fixed on master now. You can re-enable auth then.

**Comment by IetIesAai** [comment]
thanks for the quick fix - just pulled the update and re-enabled auth, all good!
