### ISSUE TITLE
MQTT status topic not published, discovered nodes remain unavailable

### ISSUE THREAD

**Issue by Call-Me-G-Now** [zwave-js/zwave-js-ui#3742]
Before submitting a bug please read: <https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/bug_report>

If you are using the Home Assistant Z-Wave JS integration, please add a full dump:

Home Assistant --> settings --> Integrations --> Z-Wave JS --> Configure --> Create dump --> zip the json file and post it here.

### Version

Build/Run method:

[X ] Docker

Z-Wave JS UI version: DOCKER 3.19.2 amd64 - not shown anywhere in webui nor the logs!
Z-Wave JS version: 12.9.1 from the logs

### Describe the bug

No `status` topic created at `/zwave/<nodename>/status`

The HA discovery pushes this topic for availability:
```JSON
{
  "command_topic": "zwave/FDIM/38/1/targetValue/set",
  "state_topic": "zwave/FDIM/38/1/currentValue",
  "state_value_template": "{{ \"OFF\" if value_json.value == 0 else \"ON\" }}",
  "brightness_command_topic": "zwave/FDIM/38/1/targetValue/set",
  "brightness_scale": 99,
  "brightness_state_topic": "zwave/FDIM/38/1/currentValue",
  "brightness_value_template": "{{ value_json.value }}",
  "on_command_type": "brightness",
  "availability": [
    {
      "payload_available": "true",
      "payload_not_available": "false",
      "topic": "zwave/FDIM/status",
      "value_template": "{{'true' if value_json.value else 'false'}}"
    },
```

see screenshot of discovery msg sent + topics available:

![img](https://github.com/zwave-js/zwave-js-ui/assets/125204742/e19ef92b-c16d-43be-8c3a-819ee837935e)

**To reproduce:
- Download docker img 3.19.2
- start clean docker, no nodes.json / settings.json
- go to settings, add mqtt server url, click save
- log mqtt topics
- - confirm HA discovery is send with a reference to `zwave/<nodename>/status` as the availability topic
- - confirm `zwave/<nodename>/status` does not exist
- experiencing this with Fibaro Zwave Dimmers, relay's and wall plugs (that's all i own, so this happens for every node in my network)

**Expected Behavior:
- HA discovery to be working out of the box
- in this case, `zwave/<nodename>/status` to exist with the expected `true` or `false` value

**Comment by robertsLando** [comment]
@Call-Me-G-Now Check you mqtt settings on ui and ensure you don't have enabled the `ignore status` setting:

![2024-06-03_10-44](https://github.com/zwave-js/zwave-js-ui/assets/11502495/10cb9790-0254-40a1-be70-544e974eb9c1)
