### ISSUE TITLE
No device properties shown after update to 9.13.3

### ISSUE THREAD

**Issue by Mclupo** [zwave-js/zwave-js-ui#3749]
Zwave-js-ui in docker on raspi 4 , 8gb
Aeotec stick 7
After the update no datas of the zwave devices are shown. The page is just blank

**Comment by robertsLando** [comment]
12.9.1 isn't a valid zui version, are you on 9.13.2? If not update pleae

**Comment by Mclupo** [comment]
Sorry you are right. It's 9.13.3

**Comment by Mclupo** [comment]
Just to get me right, zwave is proper working ,and all devices are there. 
It's like you see at pos 003, no properties are shown, just the up arrow.

![Screenshot 2024-06-05 at 13-16-29 Z-Wave JS UI](https://github.com/zwave-js/zwave-js-ui/assets/53428233/eb70d9f3-3df4-4ff6-8036-ae3a36c90f54)

log file is on the way

**Comment by Mclupo** [comment]
[z-ui_2024-06-05.log](https://github.com/user-attachments/files/15586081/z-ui_2024-06-05.log)

**Comment by robertsLando** [comment]
@Mclupo Oh thanks for the clarification, it wasn't clear to me you meant that.

Does that happens sporadically or always? Could you try with a different browser? I tried on my end and I can see all them. Also would be helpful to see chrome console, maybe there is an error there that could help me debug the issue

**Comment by Mclupo** [comment]
I got the fault. it was the time zone. I had ZZ = /Europe/Berlin instead of Europe/Berlin. the first slash was wrong. 
Everything working fine now. thanks for your help

**Comment by robertsLando** [comment]
@Mclupo Glad you fixed it, I found a bug that was not setting timezone correctly in previous version this is why you saw that after the upgrade, the timezone was simply not picked up before so you didn't saw the error :)
