### ISSUE TITLE
Heatit TF016 / TF021 - Basic report

### ISSUE THREAD

**Issue by kjetilsn** [zwave-js/zwave-js-ui#3773]
Before submitting a bug please read: <https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/bug_report>

If you are using the Home Assistant Z-Wave JS integration, please add a full dump:

Home Assistant --> settings --> Integrations --> Z-Wave JS --> Configure --> Create dump --> zip the json file and post it here.
[zwave_js-a52298b972a36aa7260d504c814976b8-Bad-b2e9f709f4337079d6f4bd0988ee018c.json](https://github.com/user-attachments/files/15866410/zwave_js-a52298b972a36aa7260d504c814976b8-Bad-b2e9f709f4337079d6f4bd0988ee018c.json)

### Version

Build/Run method:

[ x ] Docker
[ ] Git Clone + npm install + npm run build + npm start
[ ] Pkg

Z-Wave JS UI version: 9.13.4.e803879
Z-Wave JS version: 12.10.0

### Describe the bug

This relates to older Heatit thermostats TF016 / TF021 which does not report power usage or relay state. In order to calculate power usage we have used the On/Off control group association back to the gateway to get the state. I will admit that I don't know if the "bug" (i guess it is not really a bug) is in Z-wave JS, or in home assistant.
In the past a number entity has been available in home assistant for basic report from the zwave device for knowing the state of the relay. This worked when the on/off association were established between the node and gateway. A while ago this was replaced by a light entity, I suspect this was not intentional, but it worked. However, now there are no entities available for this information, nor is it available as i.e zwave_js.value_updated in the events listener I home assistant. Z-wave JS logs the information, so the node does send it:
`` 
2024-06-14T07:22:23.727Z CNTRLR   [Node 005] [~] [Basic] currentValue: 99 => 99                     [Endpoint 0]
2024-06-14T07:22:23.733Z DRIVER « [Node 005] [REQ] [ApplicationCommand]
                                  └─[BasicCCReport]
                                      current value: 99
2024-06-14T07:22:23.734Z CNTRLR   [Node 005] [~] [Basic] currentValue: 99 => 99 
``

**Comment by robertsLando** [comment]
This issue is releated to the underlying [Z-Wave JS Driver](https://github.com/zwave-js/node-zwave-js), please report it [here](https://github.com/zwave-js/node-zwave-js/discussions/new?category=request-support-investigate-issue)
