### ISSUE TITLE
Zniffer: Routed acks / errors should be shown in the frame list, not only the details

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js-ui#3775]
These are frames with `routedError: true`:
![grafik](https://github.com/zwave-js/zwave-js-ui/assets/17641229/248548f4-e10c-4db8-9beb-9fbb52403f0c)

We should show that those are routed errors and color them red in this view.

Likewise those are frames with `routedAck: true`:
![grafik](https://github.com/zwave-js/zwave-js-ui/assets/17641229/c5cea532-6e1c-4c50-9f6c-76eb58184d65)

We should highlight them like ACKs and show in the payload that they are routed acks.

**Comment by robertsLando** [comment]
> We should show that those are routed errors and color them red in this view.

 row color you mean?

> We should highlight them like ACKs and show in the payload that they are routed acks.

Should I use `ZWaveFrameType.AckDirect` color so for the row? And in the payload column write somethinf like `ROUTED ACK` ?
