### ISSUE TITLE
Fibaro Door sensor - lost the Temp sensor when included as S0 (instead of no security) - what am I doing wrong?

### ISSUE THREAD

**Issue by larhedse** [zwave-js/zwave-js-ui#3779]
So I have two Fibaro Door Window sensors (FGD002). If I include one of them without security I get a tempsensor. If I include one of them with S0 security (no it does not support S2....) I lose my temp sensor in that device. What am I doing wrong here?

Included the debug files, one with S0 and one without any security, if it is any help?
[FibaroDoorSensor_NoSecurity_and_TempSensor.txt](https://github.com/user-attachments/files/15912231/FibaroDoorSensor_NoSecurity_and_TempSensor.txt)
[FibaroDoorSensor_S0_Security_and_NO_TempSensor.txt](https://github.com/user-attachments/files/15912232/FibaroDoorSensor_S0_Security_and_NO_TempSensor.txt)

**Comment by larhedse** [comment]
Never mind, after I wrote the above the temp sensor turned up - I think I need to wait extra long for sensors to turn up after inclusion? Sorry.

**Comment by robertsLando** [comment]
> I think I need to wait extra long for sensors to turn up after inclusion? Sorry.

It depends based on the connection quality and the sensor but yeah could take some minutes, maybe try to manually wake up it if it's battery powered

**Comment by larhedse** [comment]
Well, about 15 minutes I say.

Now I have a kind of different problem though: One of two sensors, both are now included with S0 security, does have a temp sensor, however it is never updated and the creation value is 0 degres. On top of all, it does not accept any parameter changes at all - it is like it does not even like to be "wake up" mode. However it has no problem reporting door open/closed - so something works, it is just temp sensor that well is there but not activ...?

**Comment by larhedse** [comment]
I am sorry but i have to re-open this...

I have, 8 times, tried to re-include this door sensor. Now the first Fibaro FGDW002 Door/Windows sensor did eventually just turn up a working temp sensor in S0 security. Without any security that one was included with a working temp sensor immediately - not so for the 2nd FGDW002.

Out of 8 attempts, three on NO Security worked every time with a temp sensor immediately. 

Five of the attempts on S0 security, the temp sensor never was there from the beginning. The first and last S0 security attempt eventually turned up a temp sensor that only showed zero degrees. However there is just nu updates on the temp sensor. Not can I - for some reason unknown to me - update parameters. Nothing happens.

Currently in S0 Security - with re-interviewed node information. 

Wake up the device well it works - but nothing seems to be happening.

Yes the door sensor, open/closed, works - but that is about all.

I must be doing something wrong here - the 1st worked, not the 2nd - the are the same model and firmware, and yet behaves completely different... I am a bit lost for solution for the moment...

**Comment by robertsLando** [comment]
Hi @larhedse, this issue is releated to the underlying [Z-Wave JS Driver](https://github.com/zwave-js/node-zwave-js), please report it [here](https://github.com/zwave-js/node-zwave-js/discussions/new?category=request-support-investigate-issue)

Also remember to attach Driver logs so @AlCalzone can helps you.

> Question if possible: where do I change parameters? In the Integration for Z-Wave or in Z-Wave JS UI add-on?

I may have missed this, anyway you can do from both AFAIK but generally I suggest to do it from ZUI interface
