### ISSUE TITLE
Fibargroup | Roller Shutter | FGRM222 no entity for up down stop and percentage

### ISSUE THREAD

**Issue by Fireblade900rr** [zwave-js/zwave-js-ui#3780]
Hi, i dont know if its an Z-Wave JS/UI Issue

I own many FGRM222 (V1) and 3x FGR222 (V2) Roller Shutter by Fibaro.

All FGR222 are working fine with entity for up/stop/down but this is missing for the FGRM222.
Sometimes theres an Entitiy for up down, but it gets diabled and doesn't work at all, sometimes there's just the switch.

Different v1 devices

![image](https://github.com/zwave-js/zwave-js-ui/assets/56742771/8918f347-48c7-4fc3-afda-0948f8741605)

The working v2

![image](https://github.com/zwave-js/zwave-js-ui/assets/56742771/db765338-a1e8-4f28-aec5-aa7a7b238d36)

Also theres a "Manufacturer Proprietary v1 which would report the opening grade in perscent, This is missing on both versions.

![image](https://github.com/zwave-js/zwave-js-ui/assets/56742771/996b357f-92ce-43b8-8e24-7ce10fa81968)

I already tried reinterview but had no luck for fixing this.

[Debug_v1.txt](https://github.com/user-attachments/files/15928246/Debug_v1.txt)
[Debug_v2.txt](https://github.com/user-attachments/files/15928247/Debug_v2.txt)

Im new this this integration, so if you need further infos please give me a step by step manual for this.

**Comment by wigster** [comment]
I was about to report this also: 

zwave-js-ui: 9.14.1
zwave-js: 12.11.1
home id: 3245779512
home hex: 0xc176aa38

FGRM222 (0x010f 0x0301-0x1001) used to be identified correctly as a cover entity in HA, together with full tilt support and workign correctly. I re-interviewed it last week for the first time in probably a year and now it is identified as a switch. The switch does lift the shader properly, but does not deal with the tilt of the slats. The configuration options for the device are correct, but the control entities are not anymore.

I have multiple such devices and the interviews complete for all of them with this result.

**Comment by Fireblade900rr** [comment]
Also FGD212 Dimmer ist not working, cause theres no way to set the brightness, no slider oder anything else. Just on / off.

**Comment by robertsLando** [comment]
Sorry I may have missed this.

Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

cc @AlCalzone

**Comment by AlCalzone** [comment]
> Also FGD212 Dimmer ist not working, cause theres no way to set the brightness, no slider oder anything else. Just on / off.

Working fine here:
![grafik](https://github.com/zwave-js/zwave-js-ui/assets/17641229/78942666-7819-424b-a85c-1df0e2dcfe88)

![grafik](https://github.com/zwave-js/zwave-js-ui/assets/17641229/ad2e88db-7d21-4ecd-8c83-67176e515454)

**Comment by Fireblade900rr** [comment]
Heres the log of reinterview in debug mode 10:04 o'clock Roller Shutter, and 10:09 o'clock Dimmer
[z-ui_2024-06-26.log](https://github.com/user-attachments/files/15984572/z-ui_2024-06-26.log)

**Comment by AlCalzone** [comment]
Did you forget to upload the file?

**Comment by Fireblade900rr** [comment]
Here it is, sorry

**Comment by AlCalzone** [comment]
That's not a driver log. Please read [the link](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs) again.

**Comment by Fireblade900rr** [comment]
Sorry, here they are, 13:08 o'clock
[zwave-js-ui-store.zip](https://github.com/user-attachments/files/15987035/zwave-js-ui-store.zip)

**Comment by AlCalzone** [comment]
From that log it looks like everything should work fine in Z-Wave JS UI. The corresponding values are there:
```
2024-06-26T11:09:00.208Z CNTRLR   [Node 016] [Manufacturer Proprietary] fibaro[venetianBlindsPositi [Endpoint 0]
                                  on]: metadata updated
2024-06-26T11:09:00.209Z CNTRLR   [Node 016] [+] [Manufacturer Proprietary] fibaro[venetianBlindsPo [Endpoint 0]
                                  sition]: 66
```
Do you see them in the UI? If so, this is a bug in Home Assistant.

**Comment by Fireblade900rr** [comment]
Yes i can this value in JS UI -> Manufacturer Proprietary v1
[16-145-0-fibaro-venetianBlindsPosition] Venetian blinds position

I can also set a new value there, submit it and its working.

I still cant use the up down buttons 
![image](https://github.com/zwave-js/zwave-js-ui/assets/56742771/5a033a70-34b2-4072-adda-452b11895b22)
![image](https://github.com/zwave-js/zwave-js-ui/assets/56742771/9fd8842e-7454-49e7-b25f-660ed9f65e1c)

Theres no option for setting this parameter in HA

![image](https://github.com/zwave-js/zwave-js-ui/assets/56742771/6c6f26f1-e757-41d3-8728-6ea6371b6ade)


Maybe you can tell me what i have to set in "Set a Z-Wave value" as property, nothing i tried is working.
I just want to use this in scripts, so i wouldn't need it in HA UI itself.

![image](https://github.com/zwave-js/zwave-js-ui/assets/56742771/151c46ce-0ad6-4111-a643-b5a70746b5c1)

**Comment by Fireblade900rr** [comment]
I am really annoyed of the roller shutters. Even FGR-222 isnt working as expected. There are no sensors for the state of opening, exactly  [9-145-0-fibaro-venetianBlindsPosition] Venetian blinds position

Wheres the error for this missing sensor ? How can i achieve to get this value shown in HA ?

**Comment by AlCalzone** [comment]
> Yes i can this value in JS UI -> Manufacturer Proprietary v1 [16-145-0-fibaro-venetianBlindsPosition] Venetian blinds position
> 
> I can also set a new value there, submit it and its working.

So this is a bug in Home Assistant, not Z-Wave JS (UI). See also https://github.com/home-assistant/core/issues/115632
Apparently, HA has no discovery scheme for this device and expects it to use Multilevel Switch like almost all other devices of this kind.
