### ISSUE TITLE
Controller Becomes Unresponsive After Setting New Config Value For Battery Device

### ISSUE THREAD

**Issue by ADHDSquir** [zwave-js/zwave-js-ui#3781]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.14.1

### ZwaveJS version

12.11.1

### Describe the bug

When setting a new configuration value for a battery-powered device, the value is not set and the controller becomes unresponsive to any other commands for any other devices. 

### To Reproduce

In Z-Wave JS UI, select a battery powered device, change a Configuration value and click the send arrow, the spinning circle says to "wake up your device in order to send commands" but waking the device doesn't cause the commands to send. Further, no command can be sent to any other device on the network until Z-Wave JS is restarted.

### Expected behavior

The network should continue to function while waiting for a battery powered device to wake up.

### Additional context

This is occurring with a Zooz ZSE11 Q Sensor and happen with both secure and insecure inclusion. I have tested two different ZSE11 devices and have the same experience with both.

**Comment by robertsLando** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

**Comment by robertsLando** [comment]
This issue is releated to the underlying [Z-Wave JS Driver](https://github.com/zwave-js/node-zwave-js), please report it [here](https://github.com/zwave-js/node-zwave-js/discussions/new?category=request-support-investigate-issue)
