### ISSUE TITLE
Loading animation (load bar and spinning circle) stay infinitely on

### ISSUE THREAD

**Issue by jfhautenauven** [zwave-js/zwave-js-ui#3791]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Z-Wave JS UI version

9.14.4

### ZwaveJS version

12.12.1

### Describe the bug

I noticed since a few days that the load animation on ZW JS UI stays there indefinitely and doesnt go away anymore.

![image](https://github.com/zwave-js/zwave-js-ui/assets/83645528/caa37928-92b4-4faf-b4c6-1fe4cad9d6a4)

It is not a blocking issue but I'm pretty sure it's a regression.

### To Reproduce

Have ZW JS UI run a couple of hours.
Use Chrome navigator
Navigate to ZW JS UI
The loading is done. The load animation goes away for one second, then comes back until the end of times :) 

### Expected behavior

The load animation goes away when the page is loaded

**Comment by robertsLando** [comment]
@jfhautenauven Could you show me what's on chrome network tab? Just to understand what's the outgoing request that causes that

**Comment by goofball222** [comment]
Also seeing this behavior. Nothing going as far as active connections in the Chrome dev tools network tab after the initial page load.

**Comment by robertsLando** [comment]
Do you have an easy way to reproduce this apart from having the tab inactive for a couple ho hours?

**Comment by rcode6** [comment]
Also having this happen in Firefox.  Nothing noteworthy in the network requests (nothing hanging or errored).

This happens every page load for me.  I don't even need to wait.

**Comment by robertsLando** [comment]
Do you guys have authentication enabled or not?

**Comment by rcode6** [comment]
No authentication for me.  Using a reverse proxy, https to nginx, then http to zwave-js-ui.

**Comment by rcode6** [comment]
Tested a couple more scenarios.

Firefox Windows, Firefox IOS, Safari IOS all give me the infinite loading circle right on page load, but only if I access it through my reverse proxy (https to nginx, http to zwave js ui).  If I skip the reverse proxy and go to zwave-js-ui via http to the IP, then the issue goes away.

Microsoft Edge is fine, with or without the reverse proxy.

**Comment by robertsLando** [comment]
this could explain why I'm not able to reproduce this, I'm not running it behind a proxy. I will try to find out why this happens.

If others having this bug confirms me they are using a proxy too would be helpful

**Comment by robertsLando** [comment]
I have been able to reproduce this only on firefox behind a reverse proxy with auth disabled. Seems that for some reason (axios or browser bug?) I get an axios event that tells me there is a download progress AFTER the request is done. This so spawns a new progress that remains there indeterminately.

Fixed on master now

**Comment by rcode6** [comment]
Updated to 9.16.2, issue is fixed for me.  Thanks!

**Comment by robertsLando** [comment]
Thanks to you for providing me the informations to reproduce the issue :)
