### ISSUE TITLE
FGRM222 issue on multilevel switch

### ISSUE THREAD

**Issue by Patator33** [zwave-js/zwave-js-ui#3794]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - npm run build - npm install

### Z-Wave JS UI version

9.14.4

### ZwaveJS version

12.12.1

### Describe the bug

Since 9.14.4, the FGRM222 (v22.22) have no multilevel switch. So i can just open and close witch binary switch.
When i use the wall switch manually, a multlilevel Switch v0 appear with just a current value.
With a  FGR222, i have a multilevel switch v3 with possible action like target value.

### To Reproduce

re-interview node wiil do nothing but the multilevel swtch v0 desappear.

### Expected behavior

have a complete multilevel swtich with positionning

**Comment by robertsLando** [comment]
This issue is releated to the underlying [Z-Wave JS Driver](https://github.com/zwave-js/node-zwave-js), please report it [here](https://github.com/zwave-js/node-zwave-js/discussions/new?category=request-support-investigate-issue)
