### ISSUE TITLE
No arm64 release?

### ISSUE THREAD

**Issue by uronito** [zwave-js/zwave-js-ui#3795]
No arm64 release?

**Comment by robertsLando** [comment]
@uronito arm64 release seems broken. I already opened #3790 and https://github.com/uraimo/run-on-arch-action/issues/150 hope to fix it soon

**Comment by uronito** [comment]
Thanks!!!!

**Comment by uronito** [comment]
we have it @robertsLando !!!!!!!!

**Comment by robertsLando** [comment]
Yeah! thanks again for pointing me to the fix! So weird how things get broken without touching enything because of underlying issues 😆

**Comment by robertsLando** [comment]
Arm64 latest: https://github.com/zwave-js/zwave-js-ui/actions/runs/9854680856
Armv7 latest: https://github.com/zwave-js/zwave-js-ui/actions/runs/9854876403

**Comment by robertsLando** [comment]
Starting from next release you will also see armv7 and arm64 in release, for now download them from  links above as I just did a release

**Comment by uronito** [comment]
Thanks!!!!!!!!

Works like a charm!!!!!!!!

You 're a crack!!!!!
