### ISSUE TITLE
GE Fan Controller TargetValue not getting updated by MQTT

### ISSUE THREAD

**Issue by i8beef** [zwave-js/zwave-js-ui#3798]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.14.4.40080a1

### ZwaveJS version

12.12.1

### Describe the bug

Upgraded and found that my GE 300S Fan switch stopped responding to MQTT requests for the "TargetValue" (32-0-targetValue) setting. Polling and "CurrentValue" publishing still looks to work correctly, and I can update any of it from the zwave-js-ui interface fine. 

### To Reproduce

Publish to previous working MQTT targetValue topic is no longer responding. Confirmed that MQTT topic is configured in zwave-js-ui and msg is being sent correctly (confirmed with another listener).

### Expected behavior

Should respond to targetValue/set MQTT topic as it did before upgrade

### Additional context

When I go to Settings, General, and look at the value I have setup for the targetValue (I am manually configuring MQTT mappings here), the MQTT topic's "Value" field is empty which looks wrong. I can select "Target Value" here and update, and it does save, but it doesn't make it work, and a few minutes later it will empty out again.

**Comment by robertsLando** [comment]
@i8beef do you see the message is received on zui logs? Could you show me the topic your are publishing to when writing to target value? Are you adding `/set` suffix when writing to that topic? Did it used to work with prev version? If yes could you tell me which is the latest working version?

**Comment by i8beef** [comment]
1. It DID work in previous version I was running, yes, no other change besides upgrading the container.
2. My system is set to use `zwave/<room>/<device>/<zwaveValue>/set` for command topics, ie I am publishing to `zwave/masterBedroom/masterBedroomFan/targetValue/set`
3. I had to play around with the log settings to get it to write anything out for it, but I get this in the log:

```
2024-07-08 17:41:17.558 INFO MQTT: Message received on zwave/masterBedroom/masterBedroomFan/targetValue/set: '33'
2024-07-08 17:41:17.559 DEBUG GATEWAY: No writeable valueId found for masterBedroom/masterBedroomFan/targetValue
```

I'm assuming that tracks with my statement that the UI isn't showing a bound "value" for this topic like it used to...

**Comment by i8beef** [comment]
Ok hold on: something changed. I went back in and set the valueId to "Target Value" again manually, but this time it took. Now it IS accepting changes again. It seems to have survived a container restart too...

Really weird, but appears to be working again... if you change the Value Id on a topic in the Settings screen, do you then have to also still click "save" at the bottom of the settings screen? Its possible that its the combination of me trying to manually fix that before but not clicking that save button, but when I had to ALSO modify the logging settings at the same time (thus making me click that save button at the bottom) it actually persisted correctly?

Still not sure why it would have lost that value id in the first place on a simple upgrade, but possibly user error here?

**Comment by robertsLando** [comment]
@i8beef You must click `SAVE` button every time you change a setting, I think the issue was this as it explains all your problems above

**Comment by i8beef** [comment]
Just pointing out, it doesn't explain why it LOST the target value id when I upgraded... so still might be a bug somewhere there or something weird. But good to close this out for now.

**Comment by robertsLando** [comment]
@i8beef If the target value has been lost it means that the device didn't reported it during interview so it could be both an issue with driver or most lickely with the device itself. In this cases BTW a re-interview of the device usually fixes everything
