### ISSUE TITLE
GET https://api.github.com 403 (Forbidden)

### ISSUE THREAD

**Issue by duylong** [zwave-js/zwave-js-ui#3805]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.14.5.a2817c3

### ZwaveJS version

12.12.3

### Describe the bug

Not a big problem but sometimes I have this problem:

```
# index-BzRFGSh0.js:123
GET https://api.github.com/repos/zwave-js/zwave-js-ui/releases/latest 403 (Forbidden)
```

### To Reproduce

I feel like this happens a lot in the evening, I forgot to copy the URL content but it indicated an access limit exceeded.

### Expected behavior

Nothing blocking, just an error in the browser web console.

**Comment by robertsLando** [comment]
@duylong That's an api that I call in order to check if there are new releases and also get changelog, ignore it, maybe I can simply skip showing the error on the UI
