### ISSUE TITLE
If setting the powerlevel or region fails, the controller UI is out of sync

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js-ui#3809]
Here I'm setting a value that the stick does not accept:
![grafik](https://github.com/user-attachments/assets/e34b78f4-c801-4a3d-95ac-d6adfaff0b58)
It looks like it was successful though.

Looking at the logs, it can be seen that the change was not accepted and the actual powerlevel is requested:
```
11:19:54.663 DRIVER « [RES] [SerialAPISetup]
                        command:               GetPowerlevel16Bit
                        normal powerlevel:     1.0 dBm
                        output power at 0 dBm: 0.0 dBm
2024-07-12 11:19:54.664 INFO Z-WAVE: Success zwave api call setPowerlevel false
```

The UI does not update however and still shows the 20 I tried to set.

If I then try to set 20 again, the API is actually called with 1, although the UI shows 20:
```
2024-07-12 11:21:40.019 INFO Z-WAVE: Calling api setPowerlevel with args: [ 1, 0, [length]: 2 ]
11:21:40.020 DRIVER   all queues busy
11:21:40.021 SERIAL » 0x0108000b12000a0000e4                                              (10 bytes)
11:21:40.022 DRIVER » [REQ] [SerialAPISetup]
                        command:               SetPowerlevel16Bit
                        normal powerlevel:     1.0 dBm
                        output power at 0 dBm: 0.0 dBm
```

The same happens with the region.

**Comment by robertsLando** [comment]
It should be handled by the call to `updateControllerNodeProps` that should send back previous values: https://github.com/zwave-js/zwave-js-ui/blob/c30493ca58d765bc8ca672fd3c6d42bb93d98ad2/api/lib/ZwaveClient.ts#L3075

Can the call to setRFRegion throw?

**Comment by AlCalzone** [comment]
Dunno then. When I tested, it did not update the UI.
