### ISSUE TITLE
Zniffer Config for Default Frequency shows the drop down for RF Region

### ISSUE THREAD

**Issue by zackbcom** [zwave-js/zwave-js-ui#3820]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.16.1.438e38e

### ZwaveJS version

13.0.1

### Describe the bug

Zniffer Config for Default Frequency shows the drop down for RF Region

<img width="553" alt="image" src="https://github.com/user-attachments/assets/3c91b9b3-8f9d-418c-8325-ceb2b2824a3c">

### To Reproduce

view config click dropdown

### Expected behavior

show correct config options

**Comment by robertsLando** [comment]
That's correct, what's the problem?

**Comment by zackbcom** [comment]
Ah maybe I was confused as the zwave drop down had different verbiage. I was reading frequency as if it was some sort of time based option. 

I get it now, although a bit confusing.
