### ISSUE TITLE
Association dialog "add" button is disabled even with no errors

### ISSUE THREAD

**Issue by mckochan** [zwave-js/zwave-js-ui#3822]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Home Assistant Add-on

### Z-Wave JS UI version

v9.16.1

### ZwaveJS version

v13.0.1

### Describe the bug
Introduced by this change: https://github.com/zwave-js/zwave-js-ui/pull/3804

The "add" button in the add group dialog box is disabled even though the group association is supported.
![image](https://github.com/user-attachments/assets/5d4c839f-0460-4d55-8380-d06c70489b03)

### To Reproduce

Try to add a group association.

### Expected behavior

The "add" button should be enabled if there is no error shown.

### Additional context

I have double checked this association is supported and tried other known-working associations. When an invalid association is attempted, an error message appears as it should.

**Comment by Pentelfrost** [comment]
I ran into this issue too. I rolled back my docker container to zwave-js-ui: 9.13.1.73e6713 and the association worked just fine.

**Comment by gshlomi** [comment]
Had my container on Latest, rolled back to 9.15.0 and set the associations successfully...

**Comment by robertsLando** [comment]
Please be patient the issue is fixed I just have to release a new patch
