### ISSUE TITLE
Log nodes only supports nodes 1-232 even though Long Range Nodes start at 256

### ISSUE THREAD

**Issue by Scoop2389** [zwave-js/zwave-js-ui#3827]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Home Assistant Add-on

### Z-Wave JS UI version

9.16.2

### ZwaveJS version

13.0.2

### Describe the bug

Settings -> Z-wave -> Log nodes only supports nodes 1-232 even though higher node numbers are possible due to Z-Wave Long Range. This means you cannot restrict logging to long range nodes.

### To Reproduce

0. Have a Z-wave stick/dongle/whatever that allows for Long Range Devices and connect at least one
1. Go to Settings
2. Z-wave Dropdown
3. "Log nodes" Setting
4. Type in the ID of any Z-wave Long Range Node
5. Gives error "Nodes must be between 1-232", attempting to save gives error "Your configuration contains errors, fix it"

### Expected behavior

0. Have a Z-wave stick/dongle/whatever that allows for Long Range Devices and connect at least one
1. Go to Settings
2. Z-wave Dropdown
3. "Log nodes" Setting
4. Type in the ID of any Z-wave Long Range Node
5. No error, saving works

### Additional context

I am using Home Assistant *bum bum bum*. However, this is most probably likely not a Home Assistant issue. If this is a Home Assistant issue, feel free to let me know and I will happily move it to another repository.

**Comment by robertsLando** [comment]
@AlCalzone Should I change the check so?
