### ISSUE TITLE
Hank Zwave Motion Sensor Assosiation Timeout

### ISSUE THREAD

**Issue by Siburanjan** [zwave-js/zwave-js-ui#3829]
I am facing an issue with the association of Hank Zwave Motion Sensor. Can you please guide me in the possible way to make the association possible or any other clarity related to the same

**Comment by robertsLando** [comment]
This issue is releated to the underlying [Z-Wave JS Driver](https://github.com/zwave-js/node-zwave-js), please report it [here](https://github.com/zwave-js/node-zwave-js/discussions/new?category=request-support-investigate-issue)
