### ISSUE TITLE
Schlage lock management; slots disappear from UI and unclear whether usercode exists

### ISSUE THREAD

**Issue by phagerman** [zwave-js/zwave-js-ui#3845]
I'm using zwave-js-ui version:
zwave-js-ui: 9.16.2
zwave-js: 13.0.2

I'm using Home Assistant 2024.7.4
I have 18 devices and I think a pretty solid zwave network.
The problem devices are Schlage BE469ZP door locks

Occasionally when I try to add a pin code (usercode), whether through the Home Assistant Developer Tools or through the zwave-js-ui user interface, I receive a confirmation that it was added (either green checkmark or dialog box) and then the slot literally disappears from the UI (see attached image for UserID 17). More often than not I think the pin code actually gets entered in the lock but I don't know of a way to confirm.

If I'm missing any information that would help troubleshoot please let me know. And if there is a way to confirm that the pin code is actually in the lock that would be great. I'd prefer to do this programmatically rather than the UI anyway.

![Screenshot 2024-08-12 at 9 38 00 AM](https://github.com/user-attachments/assets/7bedfc74-3f1d-455d-9a6a-bf0e15f9e45d)

**Comment by robertsLando** [comment]
Please make a [application log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=application-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

Also please attach a node json dump (just click on node `Advanced` button and then `Export JSON` with UI format). And also check if there are issues on chrome console.

The logs should contain a try when you set the userCode, does refreshing UI make the userId 17 appear again?
