### ISSUE TITLE
Ping Button in Network Graph Obstructed by Bottom Banner

### ISSUE THREAD

**Issue by The00Dustin** [zwave-js/zwave-js-ui#3890]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Home Assistant Add-on

### Z-Wave JS UI version

9.18.1

### ZwaveJS version

13.2.0

### Describe the bug

The ping button (and possibly others) are obstructed by the bottom banner when a desktop browser is sized small enough to cause the node properties section to be narrow enough for the buttons to wrap.  Here is a screenshot:
![Screenshot](https://github.com/user-attachments/assets/2eea2b2e-a66c-44d8-8b77-c68c1622b33b)

### To Reproduce

Reduce the size of your desktop browser enough to move the ping button to a separate row from other buttons.

### Expected behavior

The bottom of the node properties section should sit above the banner so that everything contained within it can be seen..

**Comment by The00Dustin** [comment]
To elaborate a bit in case this isn't as easily reproducible as I expect it to be:  The browser in this screenshot is Safari on macOS.  Also, ssince the scrollbar isn't visible, I did confirm the part of the page with the legend and graph was scrolled all the way down for the included screenshot..

**Comment by The00Dustin** [comment]
Sure enough.  I'm not sure how that would be made obvious, I guess if the mouse cursor could be changed that might be obvious enough, but it still seems odd to have any part of it behind anything by default when that can be avoided (the whole thing will fit when I move it).

**Comment by robertsLando** [comment]
@The00Dustin Could we agree to change the cursor as a fix?

**Comment by The00Dustin** [comment]
I just tried on mobile, and I don't think this would happen on mobile (at least not with the HAOS add-on), so yes, I think that's a fair fix.

**Comment by robertsLando** [comment]
I also added a method to position the view in the best place based on window dimensions so you should not move it anymore :)
