### ISSUE TITLE
Controller status is "Unknown state".

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js-ui#3891]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.18.1.fe0ba05

### ZwaveJS version

13.2.0

### Describe the bug

The controller state is shown as "Unknown state".

![image](https://github.com/user-attachments/assets/452316c3-ec95-4393-899f-fb9bda602e29)

### To Reproduce

No steps.

### Expected behavior

Correct state is shown.

### Additional context

Driver itself gives an inclusion state, so it must be down to how ZUI is calculating it.

```javascript
const { logger, zwaveClient, require } = this
logger.info(`Controller inclusion state: ${driver.controller.inclusionState}`);
```

Output at time of UI  "Unknown state" is:

```text
Sep 13 10:25:04 zui[302191]: 2024-09-13 10:25:04.325 INFO Z-WAVE: Calling api driverFunction with args: [
Sep 13 10:25:04 zui[302191]:   'const { logger, zwaveClient, require } = this\n' +
Sep 13 10:25:04 zui[302191]:     'logger.info(`Controller inclusion state: ${driver.controller.inclusionState}`);',
Sep 13 10:25:04 zui[302191]:   [length]: 1
Sep 13 10:25:04 zui[302191]: ]
Sep 13 10:25:04 zui[302191]: 2024-09-13 10:25:04.328 INFO Z-WAVE: Controller inclusion state: 0
Sep 13 10:25:04 zui[302191]: 2024-09-13 10:25:04.329 INFO Z-WAVE: Success zwave api call driverFunction undefined
```

`0` is `InclusionState.Idle`.

**Comment by robertsLando** [comment]
I think this is due to the change with controller events, I forgot to init the value as before the only way I had to get updates of the inclusion state was to use an interval. Fixing it asap
