### ISSUE TITLE
What's the difference between Rebuild Routes and Rebuild Routes?

### ISSUE THREAD

**Issue by TheKorn2** [zwave-js/zwave-js-ui#3898]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Z-Wave JS UI version

9.18.1

### ZwaveJS version

13.2.0

### Describe the bug

<img width="599" alt="rebuild_routes" src="https://github.com/user-attachments/assets/a12cf384-6338-4ff1-864f-8ed23d87be81">

What's the difference between Rebuild Routes and...  Rebuild Routes in the advanced actions menu?

### To Reproduce

* Open Zwave-js-ui
* Open the lower right hamburger menu
* See rebuild routes and rebuild routes in the list of things you can do

### Expected behavior

Rebuild routes and...  **Mega awesome super extreme Liquid Death** rebuild routes? Compu Hyper Mega Global Rebuild Routes? 

If these really are just a "regular" and "super" of the same thing, shouldn't they be one item and an optional checkbox?  ("hardcore mode" checkbox, or something similar?)

**Comment by robertsLando** [comment]
@TheKorn2 the first on top right does the rebuild for ALL nodes, the second just to a single node (if you trigger it will ask you the node id)

Reason is that a while ago the first was called "heal nodes" so when refactoring all method names I didn't notice them are equals now 😆 let me make it more clear
