### ISSUE TITLE
Add Destination Selection when Uploading Files to Store

### ISSUE THREAD

**Issue by The00Dustin** [zwave-js/zwave-js-ui#3903]
**Is your feature request related to a problem? Please describe.**
Currently, the upload function for the store only puts files in the root of the store, this means that users must use other methods to get files into subfolders such as config.

**Describe the solution you'd like**
I would like to be able to choose a destination subfolder before or after clicking the upload button when I am adding files to the store.

**Describe alternatives you've considered**
Alternatives aka workarounds include manually creating files and pasting their contents or using other out of band methods such as SCP or SMB

**Additional context**
This feature request is being created per the Discord conversation ending [here](https://discord.com/channels/1111193770935996459/1111193771820974112/1286246561692778528).

**Comment by robertsLando** [comment]
Fixed by #3915
