### ISSUE TITLE
Soft reset troubleshooting

### ISSUE THREAD

**Issue by jbob762** [zwave-js/zwave-js-ui#3919]
I appreciate you creating and continuing work on zwave-js-ui. It and zwave2mqtt have been valuable, reliable bridges between my zwave devices and my mqtt broker. Thanks! Hopefully if someone else runs into something similar they can troubleshoot it easily.

The configuration - zwave-js-ui is running in a Debian VM on a Proxmox host with a Zooz ZST10 zwave stick forwarded to the VM. It normally shows up as /dev/ttyACM0 in the VM. zwave-js-ui is installed using NPM and PM2.

Initially on start zwave-js-ui is able to query the zwave stick until zwave-js-ui attempts a soft reset. The zwave stick gets kicked to /dev/ttyACM1 and zwave-js-ui repeatedly fails to connect to it on /dev/ttyACM0. The web UI shows a red bar with an error about the driver not being ready. After poking between the settings in the web UI and the logs I eventually put together to turn off the soft reset - things start working, devices start showing up, and I get "driver ready" in the UI.

Some verbiage added to the "troubleshooting" section of the website RE the soft reset and common failures if the stick doesn't support would have made troubleshooting my issue easier. Either that or in the description of the soft reset maybe some added verbiage about the kinds of failures to expect if the stick doesn't support that.

Some troubleshooting verbiage along the lines of:
If there is an error with the driver not being ready after startup, check the logs and look for failures after "Soft reset." If there are errors after a soft reset, try turning it off.

[zwavejs_2024-09-28_excerpt.log](https://github.com/user-attachments/files/17179876/zwavejs_2024-09-28_excerpt.log)

**Comment by robertsLando** [comment]
@jbob762 Try to disable soft reset on zwave settings

**Comment by jbob762** [comment]
Yes, that’s what fixed it. I was suggesting adding something to the troubleshooting section of the website to make it easier to understand what’s happening.

**Comment by robertsLando** [comment]
@jbob762 Generally soft-reset shouldn't be disabled, that's an old issue related to old controllers, what you should do is to update your stick firmware to latest. See https://github.com/zwave-js/node-zwave-js/issues/6341
