### ISSUE TITLE
NVM Restore to SmartStick G8 800 Series not successful

### ISSUE THREAD

**Issue by Josef69** [zwave-js/zwave-js-ui#3938]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Home Assistant Add-on

### Z-Wave JS UI version

zwave-js-ui: 9.21.1

### ZwaveJS version

zwave-js: 13.4.0

### Describe the bug

I tried to integrate my new G8 stick into Home Assistant and transfer the old configuration via NVM Restore. Unfortunately, the restore is aborted with the error “error while calling restore VM: The NVM File ID must be set before serializing”. 

### To Reproduce

trying another restore prozess

### Expected behavior

Is there a solution for that error? And then yes, what is the solution for that?

**Comment by Josef69** [comment]
![Screenshot 2024-10-10 181727](https://github.com/user-attachments/assets/fb71adca-ffa1-494e-b9c2-00fa19c604a0)

**Comment by robertsLando** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

cc @AlCalzone

**Comment by AlCalzone** [comment]
Update to the latest version.

**Comment by stephanseitz** [comment]
I also have the same problem. If I have understood correctly, this should be fixed in https://github.com/zwave-js/node-zwave-js/issues/7219.  When is the next release planned?

**Comment by robertsLando** [comment]
It's out now

**Comment by stephanseitz** [comment]
The restore has now worked perfectly, thank you very much for the quick fix!

**Comment by Josef69** [comment]
I can also confirm that it is now working. Thank you very much for the quick implementation.
