### ISSUE TITLE
Node getting not optimal route. Able to fixate connection to another node?

### ISSUE THREAD

**Issue by Tom-ahawk** [zwave-js/zwave-js-ui#3942]
One of my nodes is almost always getting a red Edges line (9.6 kbit/s). Occasionally I see it gets a yellow (40 kbit/s), only ones I have seen it getting a green (100 kbit/s), - connected to different nodes.

Is it possible to peg a node to another (best) node?
If yes, how, if not, is it a possible functionality?

Thanks for this realy nice integration!

Cheers.

**Comment by robertsLando** [comment]
yes you can do this from mesh graph, just select a node and setup a priority route by selecting the node to use as repeater (if any)
