### ISSUE TITLE
Missing status when Home Assistant restart then device are unavailable

### ISSUE THREAD

**Issue by Turbox35** [zwave-js/zwave-js-ui#3952]
Before submitting a bug please read: <https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/bug_report>

If you are using the Home Assistant Z-Wave JS integration, please add a full dump:

Home Assistant --> settings --> Integrations --> Z-Wave JS --> Configure --> Create dump --> zip the json file and post it here.

### Version

Build/Run method:

[X] Docker
[ ] Git Clone + npm install + npm run build + npm start
[ ] Pkg

Z-Wave JS UI version: **9.23.0**
Z-Wave JS version: **13.9.0**

### Describe the bug

My issue discussed here [https://github.com/zwave-js/zwave-js-ui/issues/3642](https://github.com/zwave-js/zwave-js-ui/issues/3642) is still present but I have investigate a little.
The problem: each time Home Assistant restart, some devices comes unavailable until I change something into Zwave JS UI setting.
Indeed if I check or uncheck the "notify new versions" as an exemple, my devices come available.

I have checked and when Home Assistant restart the message offline/online message is well published and the a rediscovery of all my device is well published on MQTT but the status informations of devices is not published.

I understand now why some devices have this issue and others not, it's because the working device don't have the "availability" configuration message into their discovery payload (probably old devices).

"Ignore status update" is well uncheck, so I don't understand why it's not published. Do you have an idea? What's could be wrong in my configuration (docker or Zwave JS UI)?

**Comment by robertsLando** [comment]
With "status" updates you refer to MQTT messages published on `<node-prefix>/status` ?

**Comment by Turbox35** [comment]
Hello,

Exactly. Like this :
![image](https://github.com/user-attachments/assets/0b6162b3-3ec6-494b-a166-8a7de006cada)

**Comment by robertsLando** [comment]
> The problem: each time Home Assistant restart, some devices comes unavailable until I change something into Zwave JS UI setting.

Yep because when you press save you restart the gateway so everything is published again.

> but the status informations of devices is not published.

Do you have retain flag set to true on mqtt settings? Pay attention to don't confuse it with retained discovery, that's another setting that should be kept off

**Comment by Turbox35** [comment]
Oh no it's set to false.
![image](https://github.com/user-attachments/assets/84674bed-6c60-47db-9a75-86b1b7164181)
I don't really understand, If I set it to True all MQTT message sent by Zwave JS UI will be retained (like temperature, power... value) including availability informations? If yes I understand why retain availability data but not why for the sensor data values.

**Comment by robertsLando** [comment]
> I don't really understand, If I set it to True all MQTT message sent by Zwave JS UI will be retained (like temperature, power... value) including availability informations? If yes I understand why retain availability data but not why for the sensor data values.

Sensor values may change, the status changes only when node status changes. BTW that should fix your issue

**Comment by Turbox35** [comment]
I confirm it works. Thanks a lot for your help.
Regarding devices which don't have the availability option , should I rediscover node or rediscover each line?

![image](https://github.com/user-attachments/assets/5c73de93-25b1-4347-a040-a6f07626b698)

**Comment by robertsLando** [comment]
@Turbox35 Do you have `Persistent` to true on those devices in table? Anyway try using rediscover node

**Comment by Turbox35** [comment]
Hello @robertsLando , sorry I miss your answer. Yes, it's linked to Persistence option which was set, so, all is normal.
Again thanks all works fine now.
