### ISSUE TITLE
Snapcraft package release is not updating with the latest versions

### ISSUE THREAD

**Issue by jfhautenauven** [zwave-js/zwave-js-ui#3971]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Z-Wave JS UI version

Not relevant

### ZwaveJS version

Not relevant

### Describe the bug

Hello, seems that the snapcraft repo is not updating with the latest versions of the package. Currently still on version 9.23 where the current code version is 9.26

### To Reproduce

Snap refresh, no new package found

### Expected behavior

Package is published correctly to Snapcraft and I can update to the latest available version

**Comment by robertsLando** [comment]
Please open the issue in the repository linked by @kpine, I will check it

**Comment by jfhautenauven** [comment]
https://github.com/giaever-online-iot/zwave-js-ui/issues/26
