### ISSUE TITLE
On update to 9.27.1, all devices show unknown manufacturer, product, product code

### ISSUE THREAD

**Issue by luckyjay** [zwave-js/zwave-js-ui#4003]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

PKG executable

### Z-Wave JS UI version

9.27.1

### ZwaveJS version

14.3.2

### Describe the bug

I hope I didn't do something stupid, but after upgrading from 9.26.0 to 9.27.1, all my zwave devices are listed in the UI with unknown manufacturer, product, product code
![image](https://github.com/user-attachments/assets/a19bf6a0-eb3b-4666-998f-c368b02c3b33)
 

### To Reproduce

Update from 9.26.0 to 9.27.1.

### Expected behavior

No unknowns in manufacturer, product, product code columns

### Additional context

Falling back to 9.26.0 no longer shows unknowns.

Re-interviewing on 9.27.1 will complete, but does not correct the unknowns even after restarting the service.

Environment is Ubuntu 24 LTS x64 VM, fully patched/updated running on Proxmox.

**Comment by luckyjay** [comment]
Note: I was running the 9.27.1 executable from https://github.com/zwave-js/zwave-js-ui/releases/download/v9.27.1/zwave-js-ui-v9.27.1-linux.zip

**Comment by zmcnaney** [comment]
Same issue here - simply updated it in place using:

`RELEASE=$(curl -s https://api.github.com/repos/zwave-js/zwave-js-ui/releases/latest | grep "tag_name" | awk '{print substr($2, 2, length($2)-3) }')
  systemctl stop zwave-js-ui.service
  wget https://github.com/zwave-js/zwave-js-ui/releases/download/${RELEASE}/zwave-js-ui-${RELEASE}-linux.zip &>/dev/null
  unzip zwave-js-ui-${RELEASE}-linux.zip &>/dev/null
  \cp -R zwave-js-ui-linux /opt/zwave-js-ui
  service_path="/etc/systemd/system/zwave-js-ui.service"
  echo "[Unit]
  Description=zwave-js-ui
  Wants=network-online.target
  After=network-online.target
  [Service]
  User=root
  WorkingDirectory=/opt/zwave-js-ui
  ExecStart=/opt/zwave-js-ui/zwave-js-ui-linux
  [Install]
  WantedBy=multi-user.target" >$service_path
systemctl enable --now zwave-js-ui.service`

**Comment by luckyjay** [comment]
> Are you setting environment variables `STORE_DIR` and `ZWAVEJS_EXTERNAL_CONFIG`?

I don't believe so. I can try if there's some guidance on what to set them to. I assume STORE_DIR is the path to the storage directory. But not sure about the external config.

Looking at logs, I saw this in the zwavejs log for 9.27.1 (not happening in 9.26.0)

![image](https://github.com/user-attachments/assets/5de701cf-2b63-4585-be38-11c845dfc651)

**Comment by luckyjay** [comment]
I've been using the linux executable in the releases at https://github.com/zwave-js/zwave-js-ui/releases/, with no special env vars set in the past. Willing to try something but not sure what to set ZWAVEJS_EXTERNAL_CONFIG to.

**Comment by luckyjay** [comment]
Okay, sorry for being a bonehead on that - I thought the env var was looking for a path to an existing file :(

I set the env var and I don't have unknowns now, when running from command line.

Now just need to incorporate that to apply when running as a service.

**Comment by luckyjay** [comment]
Okay, looks like adding Environment to the systemd service definition works. But something automagic would be nice :)
![image](https://github.com/user-attachments/assets/cd139409-9c2c-4ad5-a301-27430480bdd1)

**Comment by luckyjay** [comment]
> @robertsLando I'd suggest some documentation updates to indicate that `ZWAVEJS_EXTERNAL_CONFIG` is required for all installations now, or you could add a UI setting that allows configuration of driver option `deviceConfigExternalDir`, and pre-configures a sensible default in the store directory, much like the `deviceConfigPriorityDir` option does.

+1 for sensible default

**Comment by robertsLando** [comment]
@kpine not sure if latest driver version changed something but I'm wondering why it wasn't needed before 🤔

I'm wondering if it could make sense to set default store folder and external db to `homedir()/.zwave-js-ui`. @AlCalzone thoughts? Of course this only when there are no env vars set

**Comment by AlCalzone** [comment]
https://zwave-js.github.io/node-zwave-js/#/getting-started/migrating/v14?id=changed-some-default-paths is the correct section, but yes.

The cache files were previously located in the subdirectory `cache` of the directory where the `package.json` of `zwave-js` resides, so at the mercy of the used package manager. And now they are in the subdirectory `cache` of the current process' `cwd`.

**Comment by AlCalzone** [comment]
Hmmm... At least the embedded config should get loaded, so I think this is still a bug in the bundling process.

**Comment by robertsLando** [comment]
> Hmmm... At least the embedded config should get loaded, so I think this is still a bug in the bundling process.

Yeah this is what I mean, if this issue never happened before it means this is related to something else

**Comment by AlCalzone** [comment]
I've narrowed it down to zwave-js not being able to find the bundled config files in the executable created by `pkg`

**Comment by robertsLando** [comment]
Wow it's not driver or zui issue, the issue is in pkg: https://github.com/yao-pkg/pkg/pull/124

**Comment by robertsLando** [comment]
Starting from next minor version setting `ZWAVEJS_EXTERNAL_CONFIG` env var will not be needed anymore: https://github.com/zwave-js/zwave-js-ui/pull/4055. It will be set to `<store_dir>/.config-db` dir by default
