### ISSUE TITLE
Is anyone having problems with dimmers?

### ISSUE THREAD

**Issue by webmogul1** [zwave-js/zwave-js-ui#4008]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

PKG executable

### Z-Wave JS UI version

9.27.2

### ZwaveJS version

14.3.2

### Describe the bug

It is happening with dimmers from different brands.
Controls do not work. 

If if start a Level up nothing happens.

`11/13/2024,` 7:32:34 PM - value updated
Arg 0:
└─commandClassName: Multilevel Switch
└─commandClass: 38
└─endpoint: 0
└─property: Down
└─newValue: true
└─prevValue: true
└─propertyName: Down
11/13/2024, 7:32:20 PM - value updated
Arg 0:
└─commandClassName: Multilevel Switch
└─commandClass: 38
└─property: targetValue
└─endpoint: 0
└─newValue: 0
└─prevValue: 0
└─propertyName: targetValue
11/13/2024, 7:32:20 PM - value updated
Arg 0:
└─commandClassName: Multilevel Switch
└─commandClass: 38
└─property: currentValue
└─endpoint: 0
└─newValue: 0
└─prevValue: 0
└─propertyName: currentValue
11/13/2024, 7:32:20 PM - value updated
Arg 0:
└─commandClassName: Multilevel Switch
└─commandClass: 38
└─property: duration
└─endpoint: 0
└─newValue
└──value: 0
└──unit: seconds
└─prevValue
└──value: 0
└──unit: seconds
└─propertyName: duration
11/13/2024, 7:30:20 PM - value updated
Arg 0:
└─commandClassName: Multilevel Switch
└─commandClass: 38
└─property: duration
└─endpoint: 0
└─newValue
└──value: 0
└──unit: seconds
└─prevValue
└──value: 0
└──unit: seconds
└─propertyName: duration
11/13/2024, 7:30:20 PM - value updated
Arg 0:
└─commandClassName: Multilevel Switch
└─commandClass: 38
└─property: targetValue
└─endpoint: 0
└─newValue: 0
└─prevValue: 0
└─propertyName: targetValue
11/13/2024, 7:30:20 PM - value updated
Arg 0:
└─commandClassName: Multilevel Switch
└─commandClass: 38
└─property: currentValue
└─endpoint: 0
└─newValue: 0
└─prevValue: 0
└─propertyName: currentValue
11/13/2024, 7:30:20 PM - value updated
Arg 0:
└─commandClassName: Multilevel Switch
└─commandClass: 38
└─endpoint: 0
└─property: Down
└─newValue: true
└─prevValue: true
└─propertyName: Down
11/13/2024, 7:29:30 PM - ready
11/13/2024, 7:29:30 PM - alive
Arg 0:
0`

### To Reproduce

Just try to turn on the light.

### Expected behavior

Dimmer should work

**Comment by zmcnaney** [comment]
It's directly related to the issue with transistionDuration.   AlCazone is looking into it: https://github.com/zwave-js/zwave-js-ui/issues/4006

Debugging happened in the discord earlier today - it's related to the parsing of the transistionDuration into a "duration" object, and it's not playing nice.

See here:  https://discord.com/channels/1111193770935996459/1111206982779686972/1306312224360632474

**Comment by robertsLando** [comment]
A fix has been merged, wait for next patch release
