### ISSUE TITLE
Vertical scroll bars missing 

### ISSUE THREAD

**Issue by austinmroczek** [zwave-js/zwave-js-ui#4014]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Home Assistant Add-on

### Z-Wave JS UI version

9.26.0

### ZwaveJS version

13.10.3

### Describe the bug

Vertical scroll bars are missing in the Control Panel.  This prevents me from accessing all of the nodes (I have a few dozen) or the full configuration options for nodes with many configuration options.

### To Reproduce

Access Z-Wave JS UI Home Assistant add-on via Safari (18.1) on Mac (MacOS 15.1), or using Home Assistant Companion App (2024.9.2) on same Mac. 

### Expected behavior

Vertical scroll bars allow me to scroll down to see more nodes, or see more configuration options for nodes, etc.

### Additional context

Scroll bars are visible and working on Firefox (132.0.2) on same Mac.

Scroll bars are visible (though not needed with touch swipe ability) on Home Assistant Companion App (2024.9.4) on iOS (18.1), and Safari.

**Comment by duylong** [comment]
I have also noticed this issue. Visible only with Mozilla Firefox, no visible with Microsoft Edge and Google Chrome.
