### ISSUE TITLE
Dimmers (multiple brands) not functional in 9.27.2

### ISSUE THREAD

**Issue by curt7000** [zwave-js/zwave-js-ui#4021]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

PKG executable

### Z-Wave JS UI version

9.27.2

### ZwaveJS version

14.3.2

### Describe the bug

Dimmers (all brands) are no longer functional in Home Assistant 2024.11.2 (Python VENV 3.12.2).  State is reported correctly when adjusting on/off/level from ZWaveJSUI, but Home Assistant is unable to set On/Off or set level.  Rolling back to version 9.26.0 corrects issue.  Present on 9.27.0/1/2.

### To Reproduce

Updated to 9.27.2 from 9.26.0

### Expected behavior

Commands sent by Home Assistant are to correctly set On/Off/Level.

### Additional context

I attempted to pull DUMP, but there is no option in CONFIGURE menu to download DUMP.

**Comment by zmcnaney** [comment]
https://github.com/zwave-js/zwave-js-ui/issues/4008#issuecomment-2476283593

**Comment by robertsLando** [comment]
9.22.3 is out
