### ISSUE TITLE
9.27.8 / 14.3.7 - crashed after working for some hours after update

### ISSUE THREAD

**Issue by kpanchen** [zwave-js/zwave-js-ui#4053]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

PKG executable

### Z-Wave JS UI version

9.27.8

### ZwaveJS version

14.3.7

### Describe the bug

After update from 9.27.7 worked for some hours and stopped responding. UI is not responding, MQTT seems publishing but not responding to updates. Restart won't fix and issue. Reverting back to 9.27.7 works fine.

In the log just see the line:
`2024-12-05T15:40:29.423Z DRIVER   Dropping message because the driver is not ready to handle it yet.`

Line repeats from time to time.

Logs attached. Note: that log includes both failure and working normally after reverting back.
Let me know if more information required.

### To Reproduce

Update to a new version.

### Expected behavior

Operate normally

[zwavejs_current.zip](https://github.com/user-attachments/files/18029933/zwavejs_current.zip)
[z-ui_current.zip](https://github.com/user-attachments/files/18029935/z-ui_current.zip)

### Additional context

Not sure about this error:
`2024-12-05T15:40:36.525Z CONFIG   Writing the device index to disk failed: ENOENT: no such file or directory, op
                                  en '/snapshot/build/node_modules/@zwave-js/config/config/devices/index.json'`

**Comment by robertsLando** [comment]
You should set the env var `ZWAVEJS_EXTERNAL_CONFIG=./store/.config-db` fix this command in order to customize the destination folder

**Comment by robertsLando** [comment]
Starting from next minor version setting that env var will not be needed anymore: https://github.com/zwave-js/zwave-js-ui/pull/4055

**Comment by kpanchen** [comment]
Thanks!! Had to do a bit of googling but understand the issue now, guess I'll wait for a fix on your side, prev version just works fine! Thanks a lot for the answer!!!
