### ISSUE TITLE
Heatit Z-TRM2fx climate component shows always heating

### ISSUE THREAD

**Issue by JariInc** [zwave-js/zwave-js-ui#4063]
If you are using the Home Assistant Z-Wave JS integration, please add a full dump:

Home Assistant --> settings --> Integrations --> Z-Wave JS --> Configure --> Create dump --> zip the json file and post it here.

[config_entry-zwave_js-1a2137c20ea7b4688890b939c75cecbd.zip](https://github.com/user-attachments/files/18147875/config_entry-zwave_js-1a2137c20ea7b4688890b939c75cecbd.zip)

### Version

Build/Run method:

[X] Docker
[ ] Git Clone + npm install + npm run build + npm start
[ ] Pkg

Z-Wave JS UI version: 9.28.0.e336517
Z-Wave JS version: 14.3.7

### Describe the bug

Climate component in Home Assistant shows that it's always heating, when in reality it is not. However there is a switch that shows correctly when heating is on.

#### Climate component
![Screenshot_20241216_113321](https://github.com/user-attachments/assets/ed972d77-a047-4553-ad34-c4a27fb0b835)

#### Switch:
![Screenshot_20241216_113352](https://github.com/user-attachments/assets/ac0b38aa-f3ce-42a7-b68b-f593d337848c)

**Comment by robertsLando** [comment]
I think you should open this issue on HA core as I don't think the issue is on UI side.

**Comment by JariInc** [comment]
> I think you should open this issue on HA core as I don't think the issue is on UI side.

Thanks, I will do that.
