### ISSUE TITLE
feat: update alpine base image version

### ISSUE THREAD

**Issue by karmingc** [zwave-js/zwave-js-ui#4064]
**Is your feature request related to a problem? Please describe.**
The latest version seems to 3.21.0, it would nice to have this updated as the current one is 3.18.4.

**Comment by robertsLando** [comment]
I remember we were stick to 3.18.4 as latest was causing problems with serial port module, I can try to check if the problem is still there or not 👍🏼

**Comment by robertsLando** [comment]
Tried this but seems it gets stuck with arm v6/7 build: https://github.com/zwave-js/zwave-js-ui/actions/runs/12396734017/job/34605445567

**Comment by robertsLando** [comment]
@karmingc FYI next release will use alpine 3.21 as they fixed the issue that caused the stuck builds
